### ISSUE TITLE
Python bindings failed to load

### ISSUE THREAD

**Issue by thiteixeira** [coreemu/core#104]
Hi,

I am running core-gui on a Ubuntu 16.04 machine and installed EMANE following the GitHub instructions (https://github.com/adjacentlink/emane/wiki/Build#Ubuntu%2014.04/16.04%20LTS).

Then, I open sample1.imn scenario on CORE, enable EMANE (IEEE 802.11), and execute. The check Emulation Light comes up with the following messages:
`error starting emane: Command '['emane', '-d', '--logl', '3', '-f', '/tmp/pycore.38396/emane.log', '-r', '/tmp/pycore.38396/platform.xml']' returned non-zero exit status 1 `
and
`exception: wlan10 (10) unable to publish EMANE events because the eventservice Python bindings failed to load`

I tried to look for solutions online, but the mailing list seems to be down. Could you assist me with this issue, please?

Thank you,
Thiago

**Comment by xiaoxiaopingzi** [comment]
I have also encountered the same problem with you，and  I am running core on a CentOS 7 machine,for the first message:

> error starting emane: Command '['emane', '-d', '--logl', '3', '-f', '/tmp/pycore.38396/emane.log', '-r', '/tmp/pycore.38396/platform.xml']' returned non-zero exit status 1

when i modify the  platform.dtd file in /usr/share/emane/dtd/  directory,The first message no longer appears,
>           <!ATTLIST platform 
>                   name CDATA #IMPLIED
>                   id CDATA #REQUIRED  >      ----> This is the line I  added

but the second error message 
> unable to publish EMANE events because the eventservice Python bindings failed to load

I  do not know how to slove it, you slove it ?
