### ISSUE TITLE
How to use RJ45 connection in python API?

### ISSUE THREAD

**Issue by jtremback** [coreemu/core#111]
I'm using the RJ45 connector along with a dummy interface to connect a remote debugger in one of my CORE nodes to the host system. I've been able to make it happen in the graphical interface, but it's unclear how to do it with the python API.

**Comment by Shatnerz** [comment]
I've stopped using CORE, but I have done this in the past. I believe you just need to create an RJ45 node and set the name to the correct interface, likely "dummy0" in this instance.

**Comment by jtremback** [comment]
Doesn't work. I'm also having issues sending packets in the python api, with scripts that work in the visual interface. It's probably the same root cause. Feel free to close this, I'll reopen it if I find out more about what's going wrong.
