### ISSUE TITLE
Node on two wlans with auto-mobilities works with only one wlan

### ISSUE THREAD

**Issue by shanv82** [coreemu/core#116]
Scenario: 
3 nodes present in emulation
* Nodes <n2,n1> in wlan "right", Nodes <n3,n1> in wlan "left"
* Both left and right wlans configured with default values in basic wireless range model. 
* Nodes n3 and n2 make simple horizontal motion to make and break connection. ns-2 mobility script configured for the same, to autostart and loop.

Problem: Node n1 (connected to both left and right wlans) establishes connection with only one network's nodes (either n3/n2). This can be verified using ping

Additional information: When automatic mobility is not configured, and the nodes are manually moved towards and away from each other, node n1 is able to ping n2 and n3 as per the configured range.

Software Versions;
CORE: 4.8
Linux kernel version: 3.13.0-31 on i686, also verified with higher version of kernel running on amd64 arch.
TCL/TK: Version 8.6.1

Attached files: The imn file used for the experiment, and the ns-2 mobility script for the left and right wlans.
NOTE: Attached imn and scen files are saved as txt in order to upload them here.

[simple_2wan_net.imn.txt](https://github.com/coreemu/core/files/908446/simple_2wan_net.imn.txt)

[left.scen.txt](https://github.com/coreemu/core/files/908448/left.scen.txt)
[right.scen.txt](https://github.com/coreemu/core/files/908449/right.scen.txt)

**Comment by bharnden** [comment]
Got around to playing with this and determined an issue, I assume it is what you were running into, albeit 4.8 was some time ago.

The fix is on the development branch. Thanks for letting us know.
