### ISSUE TITLE
CORE definitely removed from Debian

### ISSUE THREAD

**Issue by eribertomota** [coreemu/core#117]
NEWS: CORE will be permanently removed from Debian soon. Please, see the following link:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860516

Consequently, CORE will also be dropped from Ubuntu and several distros based in Debian.

This bug is related to #75 

Regards,

Eriberto

**Comment by gh0st42** [comment]
That's too bad as CORE is a real useful tool for researchers. Maybe someone can setup a PPA or provide a snap package for ubuntu/debian. Ubuntu seems to be the most common distribution used by the students at our university. I saw you already provide some debian packages outside of the official debian repos which is great!

This would also open the opportunity to deliver bug fixes and new versions faster without forcing people to build CORE from source (which is actually quite easy :)).

**Comment by eribertomota** [comment]
Hi @gh0st42 

Yes, I am maintaining CORE outside of Debian at http://eriberto.pro.br/core/

You can use the .deb from my repo in Ubuntu, considering that Ubuntu catch its packages directly from Debian.

Cheers,

Eriberto

**Comment by siliconja** [comment]
While the root/user separation issue is important for general-use Ubuntu deb packaging, and shared systems like in academics, this traditionally has NOT been a priority for those developing CORE -- e.g. DoD mobile networking researchers -- where they've dedicated one (or e.g. 50) machines to emulation, and the emulator can be freely given root access.

Good point about the PPA. We'll try and do that for future releases.

**Comment by eribertomota** [comment]
A bit more... As an example, I did a test now and CORE for Jessie (from my repo) works fine over Ubuntu 17.04. I can do all needed tests and create a compatibility list.

Cheers,

Eriberto

**Comment by siliconja** [comment]
Thanks for the data point.

Any automated tests?

Some people are looking into making some automated tests for CORE. This would greatly reduce the burden of various pull requests --> we could be more responsive to community developments.

**Comment by eribertomota** [comment]
"Any automated tests?"

No. I need to install some versions (three last versions, I think) and test. :-) I will can do it in next week. However, if anyone could test it, I could publish the results.

I will publish about 17.04 in my site now.
