### ISSUE TITLE
Core-Users mailing list is down?

### ISSUE THREAD

**Issue by isapir** [coreemu/core#118]
I get a connection timeout when trying to visit https://pf.itd.nrl.navy.mil/mailman/listinfo/core-users and can't find another way to view archives or join the list.

**Comment by siliconja** [comment]
It appears up for me now. You do have to use https (like you've written above) and not http.

April archives: https://pf.itd.nrl.navy.mil/pipermail/core-users/2017-April/thread.html

**Comment by isapir** [comment]
I clicked the link from README.md so it had the correct protocol.  I see the issue though:

Chrome 57 on Windows 10 reported an issue with the SSL certificate and allowed me to add an exception and allow to connect.  Chromium 57 on Fedora 25 just gives an error message (screenshot below).

![screenshot from 2017-04-23 14-40-43](https://cloud.githubusercontent.com/assets/885907/25317717/de6a1f5e-2832-11e7-8e5f-4991bfd3dde5.png)

**Comment by isapir** [comment]
Here is what I get on Windows 10 with Chrome 57.  Notice that I do have an option to proceed here:

![image](https://cloud.githubusercontent.com/assets/885907/25317760/22f10916-2834-11e7-81ba-ec1158daeb4d.png)

**Comment by isapir** [comment]
Firefox gives a better error message:  

```
https://pf.itd.nrl.navy.mil/mailman/listinfo/core-users

Peer’s Certificate issuer is not recognized.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIEvDCCA6SgAwIBAgIDAKvOMA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNVBAYTAlVT
MRgwFgYDVQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UE
CxMDUEtJMRgwFgYDVQQDEw9ET0QgSUQgU1cgQ0EtMzcwHhcNMTYwOTIyMjAzMDQ5
WhcNMTkwOTIzMjAzMDQ5WjBvMQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBH
b3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsTA1BLSTEMMAoGA1UECxMD
VVNOMRwwGgYDVQQDExNwZi5pdGQubnJsLm5hdnkubWlsMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAwWTpyZofOTwgsTkBd6ctQjwA6vT7pPOCFkxdv7qJ
iPNpTr2gtCA8rCdfhloAKopak4nLMNKwm0SqGEQKwwOOMnu4z4knEJehIj4Iq6K1
RjYCZeiJr/Y26QKaDWPMIP6fNAdoPRa7yIAyRW8H+sWOvcPF4Opky7Xv1NFRESGm
zWo9Nn2panSyamMfZdcxYL/cy5R8G/hYVIuILjRtIUOMyr6GT7KIQD5Y+1g+FRcg
MWeI4xMWsLQJYGm66KQAhobsHKbErt+LlsbIizdAOKxikRpqlOl64ZChJjW0+7pS
zHwqTLjgQFRFZt6y1BeFpcEjp/Xot9nA7YAqZaD7C+QEYwIDAQABo4IBcTCCAW0w
HwYDVR0jBBgwFoAUFiR+9y3B75I/vkTnVF7p/he686EwHQYDVR0OBBYEFNEopmfr
s+Gy4iWuOS4Tc5NQzw6KMGcGCCsGAQUFBwEBBFswWTA1BggrBgEFBQcwAoYpaHR0
cDovL2NybC5kaXNhLm1pbC9zaWduL0RPRElEU1dDQV8zNy5jZXIwIAYIKwYBBQUH
MAGGFGh0dHA6Ly9vY3NwLmRpc2EubWlsMA4GA1UdDwEB/wQEAwIFoDA5BgNVHR8E
MjAwMC6gLKAqhihodHRwOi8vY3JsLmRpc2EubWlsL2NybC9ET0RJRFNXQ0FfMzcu
Y3JsMDYGA1UdEQQvMC2CE3BmLml0ZC5ucmwubmF2eS5taWyCFmZvcmdlLml0ZC5u
cmwubmF2eS5taWwwFgYDVR0gBA8wDTALBglghkgBZQIBCycwJwYDVR0lBCAwHgYI
KwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQgCAjANBgkqhkiG9w0BAQsFAAOCAQEA
VlBzeL8C+uTxbJu7eC0Xt3Tap5MCtLx2sVvRn6LwsbClPOooSQKQjeiA1wwBkBvP
ld4danN7Hdrui3jHepcqFRxUtZRgmUEDcEIWipnHYagv3KYJmQhTrkPu2Pfd7XEx
3YYpTwFwru9X16T9GguVDQrZ6gru6Bv7d/2I2xv/P/R//StOFRlTO5N6LqYBTdp2
LIgXtABd2Eheg+ga1u1GU0FeLtQpG4QuXOS4wKaQ9ynoMvKbvWBjLqAtNM1lrdsy
XJeiFJB/U39vqmVgqWEb4Ibju1ImpbwGPhjNSaN54kKGQ5CXTNp600bOXcbYtBnv
wteeeu/FhDf43tovr4nTPA==
-----END CERTIFICATE-----

```

![screenshot from 2017-04-23 15-00-37](https://cloud.githubusercontent.com/assets/885907/25317829/b2243742-2835-11e7-9efa-d877e45e0a63.png)

**Comment by isapir** [comment]
Not sure if you want to keep this ticket open or not.  Closing for now.
