### ISSUE TITLE
Add new service in nodes

### ISSUE THREAD

**Issue by exceed1007** [coreemu/core#121]
I'm trying to add a new service of network measurement into CORE, but I find the steps in manual are not very clear, and the sample doesn't exist in the myservices/ directory. So could you give me a template and the specific steps?

**Comment by bharnden** [comment]
[Example Service](https://github.com/coreemu/core/blob/master/daemon/examples/myservices/sample.py)

There is this for now, in the near future services may be refactored and at that time a more fleshed out example will be put into the online documentation.
