### ISSUE TITLE
Not able to run executable in run tool command prompt

### ISSUE THREAD

**Issue by Arjun666** [coreemu/core#123]
Hi,

I need to run sub agent executable in all my virtual nodes. It is very difficult to open individual terminal and run the command. So i have used run tool option(we can find in left side of core-gui) where i am able to execute unix commands(ls, ps etc) for selected devices at a time. But my requirement is run executable in all my virtual devices. Here i am facing issue, executable is running only in the first selected device and then run tool is stuck. Even i have tried running my executable with background process execution option(&)

Please find attached screenshot for clear idea.

![issue](https://user-images.githubusercontent.com/29732351/27590287-d49b518e-5b6b-11e7-8f67-8e93dedad247.PNG)

./mysubagent -f -Lo -x  tcp:localhost:1705 &

Please suggest me how can i run  executable in selected virtual devices without opening terminal.Because if i have 500 devices i cant log into all devices and run executable.

**Comment by cspiker7** [comment]
Hi Argun666,
Try creating a runtime hook script to start your process (Session, Hooks). Something like this:

#!/bin/sh
# session hook script; write commands here to execute on the host at the
# specified state
sleep 1
for dir in *.conf
do
                subdir=$(basename "$dir" )
                node="${subdir%.*}"
                nodenum="${node#?}"

                # Start your process

                vcmd -c /tmp/pycore.*/$node -- ./mysubagent -f -Lo -x tcp:localhost:1705 > /tmp/ mysubagent_n${nodenum}.log 2>&1 &

                sleep 0.5


done

Hope that is helpful!

Thanks,
Carrie

**Comment by Arjun666** [comment]
Thanks for your quick response and support

Should i run this script from my machine ?not from my virtual device terminal.

Can you please give me more info for my below queries
 subdir=$(basename "$dir" )  => Here subdir is name of every device confi file(am i right?)
 node="${subdir%.*}"   =>  ???
 nodenum="${node#?}" =>????

Please find attached pycore session file screenshot and need to run my executable in all switches.
![issue2](https://user-images.githubusercontent.com/29732351/27597059-e58e3fac-5b7e-11e7-850e-ef45b482e1d7.PNG)

**Comment by cspiker7** [comment]
In the CORE GUI, go to Session, Hooks, New, and paste whatever script you need there. CORE will automatically run the script when you press “play”.
I showed you an example of a for loop that will run a command on each virtual node in your scenario by looping through the virtual node directories, but the hook script actually runs on the host. You can modify it to meet your needs. Check /var/log/core-daemon.log for errors.
