### ISSUE TITLE
Getting error when trying to open core-gui

### ISSUE THREAD

**Issue by Netsim1234** [coreemu/core#124]
Hi,

I am new to CORE network simulator and tried to configure CORE setup in my linux machine using steps given in https://downloads.pf.itd.nrl.navy.mil/docs/core/core-html/install.html

When i am trying to open core-gui I am getting below error.
Please help me.
![c
ore-gui](https://user-images.githubusercontent.com/29755485/27641823-a07f7e8c-5c3a-11e7-827c-b46fc17c9cff.PNG)

**Comment by bharnden** [comment]
if this is still a problem with the latest packages, let us know
