### ISSUE TITLE
Node Positions Not Set When Using "--batch" Option 

### ISSUE THREAD

**Issue by trentbottin** [coreemu/core#126]
Setup:
Ubuntu: 14.04
core-gui: version 4.8 (20170509)
emane: v1.0.1
scenario: 2 nodes (rfpipe)

I am writing a test script using "core-gui --batch 2node_rfpipe.imn" to launch a CORE session.  When reviewing my data, I noticed my nodes were able to communicate when their positions (too far apart) should have precluded connectivity.  When I ran the scenario using the --start option, I did not have an issue.  Looking at the EMANE log, I noticed the nodes' positions where not being set when using the "--batch" option (see log excerpts below).    During trouble shooting, I attempted to use coresendmsg to update the nodes' positions with negative results.

emane1.log entry using core-gui --start 2node_rfpipe.imn
15:54:14.180385 DEBUG PHYI 001 FrameworkPHY::processEvent event id: 100
15:54:14.180641 DEBUG PHYI 001 FrameworkPHY::processEvent location event:  nem: 1 position: lat: 47.576474 lon: -122.128517 alt: 2.000000 orientation: none velocity: none 

emane1.log entry using core-gui --batch 2node_rfpipe.imn
16:02:11.153825 DEBUG PHYI 001 FrameworkPHY::processEvent event id: 100
16:02:11.154074 DEBUG PHYI 001 FrameworkPHY::processEvent location event:  nem: 1 position: lat: -0.000018 lon: 0.000010 alt: 0.000000 orientation: none velocity: none

**Comment by bharnden** [comment]
batch removed for now
