### ISSUE TITLE
Two-Node Tool does not take Zoom into account

### ISSUE THREAD

**Issue by isapir** [coreemu/core#130]
When the canvas is Zoomed, the Two-Node tool does not scale the coordinates accordingly so the "circles" that mark the nodes are "off".

See screenshot showing pc15 (green) and host11 (red)

![screenshot from 2017-09-17 23-04-27](https://user-images.githubusercontent.com/885907/30530582-ae9498de-9bfc-11e7-8088-936f15efa8b9.png)

**Comment by bharnden** [comment]
Current GUI cannot be supported currently, looking to support and resolve issues in a new GUI moving forward.
