### ISSUE TITLE
No longer able to build RPM package

### ISSUE THREAD

**Issue by gsomlo** [coreemu/core#134]
I'm trying to package the current 5.0 (rc? -- as of commit 06d4c46) for Fedora, and things look pretty grim.

I have worked around several missing dependencies and a PYTHONPATH error with the attached patch, 
[fedbuild.patch.txt](https://github.com/coreemu/core/files/1379445/fedbuild.patch.txt) but I've finally got stuck on the new 'logzero' dependency introduced by commit e4b2801 -- there's no Fedora package for that module, and therefore no way to build a working package of the CORE project.

Am I missing anything ? Is there a way around this?

Thanks,
--Gabriel

...
Installed /builddir/build/BUILDROOT/core-5.0-1.20171011git06d4c46.fc26.x86_64/usr/lib/python2.7/site-packages/core_python-5.0-py2.7.egg
Processing dependencies for core-python==5.0
Searching for logzero
Reading https://pypi.python.org/simple/logzero/
Download error on https://pypi.python.org/simple/logzero/: [Errno -2] Name or service not known -- Some packages may not be found!
Scanning index of all packages (this may take a while)
Couldn't find index page for 'logzero' (maybe misspelled?)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for logzero
error: Could not find suitable distribution for Requirement.parse('logzero')
make[4]: Leaving directory '/builddir/build/BUILD/core-5.0.20171011git06d4c46/daemon'
...

**Comment by bharnden** [comment]
> Name or service not known -- Some packages may not be found!

It appears you do not have an internet connection or are behind a proxy and it is not configured appropriately. Since you are unable to reach PyPi.

**Comment by gsomlo** [comment]
On Fri, Oct 20, 2017 at 04:13:11PM +0000, bharnden wrote:
> > Name or service not known -- Some packages may not be found!
> 
> It appears you do not have an internet connection or are behind a
> proxy and it is not configured appropriately. Since you are unable
> to reach PyPi.

The problem is there is no "logzero" (or, more likely, "python-logzero")
package in any of the Fedora repositories.

A proper RPM package has to account for all prerequisites via RPM
dependencies. Using PyPi to pull in Python packages as part of the
build process effectively counts as "side-loading" them from RPM's
point of view... Works great if building on the machine one plans
to run the software (i.e. a "one-off"), not so much for building a
portable package that can be installed elsewhere later on.

**Comment by gsomlo** [comment]
After building my own "python-logzero" RPM (I plan on trying to push
that into the fedora repositories if everything else works out in the
end), I ran into a fresh snag trying to make a CORE rpm:

Once the %install part of the RPM build process completes, the list of
files in $RPM_BUILD_ROOT does not match the list of files expected by
"%files daemon", in particular anything under %{python_sitearch} and
%{python_sitelib}.

None of the %{python_sitearch} are there (no .so files at the end of
"make install"), and the %{python_sitelib} (i.e.
".../usr/lib/python2.7/site-packages/...") files are not where they
should be.

There's a "core_python-5.0-py2.7.egg" directory containing the "core"
directory which USED to go directly under %{python_sitelib}. The
corens3 folder isn't even there at all, there's only
"corens3_python-5.0-py2.7.egg", which if unzipped MANUALLY will yield
the expected corens3 folder.

As far as I can tell, the new "install" target in the main Makefile
seems to be broken.

Am I missing anything ?

For the record, I create a .src.rpm file:

	rpmbuild -bs core.spec

which I then build using

	mock -r fedora-26-x86_64 core*.src.rpm

which is the standard way to build clean, portable Fedora/RHEL/CentOS
packages that are independent of the local idiosyncrasies of the
machine doing the build.

For the (small) differences between my spec file and what's currently
in the CORE git repo, see http://www.contrib.andrew.cmu.edu/~somlo/CORE/

The plan is, once we figure out how to create a sane, repeatable RPM
build process, I will try to push python-logzero upstream and also
submit a patch against the current .spec file to include my fixes.

All I need is a little help figuring out why immediately following a
"make install" most of core-daemon's python files are not where one
would expect them to be... :)

Thanks,
--Gabriel

**Comment by gsomlo** [comment]
I submitted https://github.com/coreemu/core/pull/139 which should fix all these issues, please consider pulling.
