### ISSUE TITLE
[v5.0] sphinx-apidoc: command not found

### ISSUE THREAD

**Issue by eribertomota** [coreemu/core#136]
Hi,

The configure script should check if the command 'sphinx-apidoc' exist.

$ make
[...]
sphinx-apidoc -o . ../core
/bin/bash: sphinx-apidoc: command not found

Thanks in advance.

Regards,

Eriberto

**Comment by eribertomota** [comment]
For mail message: sorry. Not '$ ./configure'. Use '$ make'.

**Comment by bharnden** [comment]
should be fixed on rel/5.1 branch
