### ISSUE TITLE
[v5.0] 'make' command fails when using distclean

### ISSUE THREAD

**Issue by eribertomota** [coreemu/core#137]
Hi,

When packaging version 5.0 for Debian, I discovered that the source code do not build twice. It is a problem, because is not possible test the final package several times. The problem is when running 'make distclean'. It is a issue for other distros too.

How to reproduce:

./bootstrap.sh
./configure
make
make distclean
[...]
Making distclean in daemon/doc
make[1]: Entering directory '/PKGS/core/core-release-5.0/daemon/doc'
make[1]: *** No rule to make target 'distclean'.  Pare.
make[1]: Leaving directory '/PKGS/core/core-release-5.0/daemon/doc'
Makefile:462: recipe for target 'distclean-recursive' failed
make: *** [distclean-recursive] Error 1

There are other little issues but I need wait for a fix for this bug to make new tests and send a new report.

Thanks a lot in advance.

Regards,

Eriberto

**Comment by bharnden** [comment]
should be fixed in rel/5.1 branch.
