### ISSUE TITLE
[v5.0] What version of EMANE is supported?

### ISSUE THREAD

**Issue by apwiggins** [coreemu/core#140]
What version of EMANE is supported?  The release notes are silent on this item.  We have custom extensions to EMANE, so it's important to know which version of EMANE to target when migrating to CORE v5.0.  Please update the changelog.
https://github.com/coreemu/core/releases

Previously, CORE 4.8 changelog:
EMANE:
    - support for EMANE 0.9.2
    - run emane in each container when using EMANE 0.9.2
    - support using separate control networks for EMANE OTA and event traffic

CORE 4.7 changelog:
EMANE:
    - support for EMANE 0.9.1
    - fix error when using Comm Effect model with loss/duplicate string values
    - enable flow control in virtual transport if enabled in the MAC model
    - fix bug #150 where EMANE event service/address port were not used

UPDATE: in core-daemon startup log, this appears:
[E 171121 12:42:58 commeffect:<module>:14] error importing emaneeventservice and emaneeventcommeffect
[E 171121 12:42:58 tdma:EmaneTdmaModel:20] EMANE TDMA requires EMANE 1.0.1 or greater

**Comment by bharnden** [comment]
For 5.1 we will probably plan to target and only support 1.2.1. The current 5.0 release should work with 1.0.1.

**Comment by bharnden** [comment]
Updates have been made to the rel/5.1 branch, it should support 1.0.1 and 1.2.1 now. Need to test how far back it will work. Trying to make use of emane's python binding to dynamically generate some of the configuration options for emane models and as long as an older version conforms to what the code base uses it should still work.
