### ISSUE TITLE
Problem with IPv6 address when using commands in vtysh or ifconfig

### ISSUE THREAD

**Issue by edusachs** [coreemu/core#141]
Hi folks, how are you?

I found a bug in the Core Emulator, I'm going to report to the group.

I used the Virtual Machine below, and I also updated Core Emulator to version 4.8, and the bug has been confirmed.

- https://downloads.pf.itd.nrl.navy.mil/core/vmware-image/vcore-4.7.zip

I built a very simple topology to explain the bug (is documented in the image1.jpg and topology-bug.imn in this issue).

In the interfaces of the routers there is the IPv6 address configuration.

When I use the option "Shell Window" to open "vtysh" in order to disable (down) the network interface using the "shutdown" command and after that the "no shutdown" command to enable (up) the interface, the IPv6 address is LOST, and IPv4 addressing is configured correctly.

The same problem occurs when I use the command "ifconfig eth0 down" and "ifconfig eth0 up".

I use the default configuration of addressign IPv6 in the Zebra, look at this:

interface eth0
	ipv6 address 2001::1/64

Therefore, I can not use the "shutdown" and "no shutdown" command when I use the network interface with the address IPv6 configuration.

So... the bug is only related to IPv6.

Follows an image (file ifconfig-1.png) before the command "shutdown", and another image (file ifconfig-2.png) after the command "no shutdown".

Would you have any more questions about this bug?

Did you reproduce or understand the case?

All files listed are attached in this issue.

Thanks.

![ifconfig-1](https://user-images.githubusercontent.com/34560360/34038168-8e887324-e172-11e7-84ba-7a9ca2730256.png)
![ifconfig-2](https://user-images.githubusercontent.com/34560360/34038169-8ea3aaf4-e172-11e7-8a41-36d158757093.png)
![image1](https://user-images.githubusercontent.com/34560360/34038170-8ec1c494-e172-11e7-94ac-571d4b92a9b8.jpg)

**Comment by Kevlar** [comment]
Hi, could you verify that this is still an issue on CORE 5.2 or newer?

**Comment by bharnden** [comment]
this is the equivalent of bringing down and up the interface, which would cause additional addresses to be lost in the process, since they are temporary.

since this is being done outside of CORE's knowledge, one would need to save/restore addresses that may be lost.

One way of achieving something along those lines could be the following.
```shell
ip address save dev eth0 > eth0.config

ip address restore < eth0.config
````
