### ISSUE TITLE
SDN service in Core

### ISSUE THREAD

**Issue by SHZ18** [coreemu/core#146]
Hi,
Could you please add an example to show how to use the new SDN service in Core? 

Thank you

**Comment by andreas-ibm** [comment]
Do my comments in #150 make it easier?

I've created a few different SDN solutions with the new services... Do you have a particular goal in mind?

**Comment by issam565** [comment]
Hi,

I'm struggling the understand how can I create 2 OVS swicthes controlled by an external RYU controller. By external, I mean having 3 nodes on my CORE topology: 2 ovs nodes connected to one router or host node with ryu service. How can I manage to reach from both ovs nodes that external IP representing the ryu node?
