### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by HansieB12** [coreemu/core#147]
Dear member,
`make -j4` delivers a lot of problems.

`sudo core-daemon` : sudo: core-daemon: command not found
(There is no core-daemon in /usr/local/sbin/)

`core-gui` : error: missing built-in node type 'OVS'!
move your ~/.core/nodes.conf file to re-create the defaults

What's the problem?

Regards.

HansieB12

**Comment by bharnden** [comment]
Which version are you trying this on? Which Linux distribution?

**Comment by HansieB12** [comment]
Dear bharnden,
Thank you for your respose.

Ubuntu 16.04. All latest versions, up to date.

Regards.

HansieB12

**Comment by bharnden** [comment]
Sorry, I should have been more specific. Which version of CORE are you trying this on, is what I meant. There are efforts to improve the build process in general, which the latest in on branch rel/5.1.

- What problems are you getting with the make command? I have just been using make alone, with no options.
- I am not sure how you attempted to install CORE as far as your missing core-daemon

The ~/.core/nodes.conf is a more nuanced thing to explain, since the intent was people could customize files within. So the gui will only create this directory for you with the latest defaults when it doesn't exist. So it does not override your own files. You can move the directory temporarily to have it be generated then move desired files back in place.

```bash
mv ~/.core ~/.core.tmp
core-gui
# ~/.core is generated
```

**Comment by HansieB12** [comment]
Dear,
I try to work according to the "Wiki" page: [https://github.com/coreemu/core/wiki](https://github.com/coreemu/core/wiki)
The attemp to install CORE :-1: 

Build and install

git clone https://github.com/coreemu/core.git
cd core
./bootstrap.sh
./configure
make -j4

### 
this puts the GUI under /usr/local/lib/core
Python module under /usr/local/lib/python2.7/dist-packages/
binaries under /usr/local/sbin/core-daemon,vnoded,vcmd and /usr/local/bin/core-gui

sudo make install

Problems with the make command ?: 

`make -j4
..........
make[3]: Entering directory '/home/hans/core/scripts/perf'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/hans/core/scripts/perf'
make[3]: Entering directory '/home/hans/core/scripts'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/hans/core/scripts'
make[2]: Leaving directory '/home/hans/core/scripts'
Making all in daemon
make[2]: Entering directory '/home/hans/core/daemon'
Making all in src
make[3]: Entering directory '/home/hans/core/daemon/src'
SBINDIR=/usr/local/sbin LDFLAGS=" -lev" CFLAGS="-O3 -Werror -Wall -Wno-int-in-bool-context -D_GNU_SOURCE " /usr/bin/python setup.py build
gcc -DHAVE_CONFIG_H -I. -I../..    -Wall -fno-strict-aliasing -O3 -g  -O3 -Werror -Wall -Wno-int-in-bool-context -D_GNU_SOURCE -MT vnode_io.o -MD -MP -MF .deps/vnode_io.Tpo -c -o vnode_io.o vnode_io.c
gcc -DHAVE_CONFIG_H -I. -I../..    -Wall -fno-strict-aliasing -O3 -g  -O3 -Werror -Wall -Wno-int-in-bool-context -D_GNU_SOURCE -MT vnoded_main.o -MD -MP -MF .deps/vnoded_main.Tpo -c -o vnoded_main.o vnoded_main.c
gcc -DHAVE_CONFIG_H -I. -I../..    -Wall -fno-strict-aliasing -O3 -g  -O3 -Werror -Wall -Wno-int-in-bool-context -D_GNU_SOURCE -MT vnode_server.o -MD -MP -MF .deps/vnode_server.Tpo -c -o vnode_server.o vnode_server.c
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, Extension
ImportError: No module named setuptools
Makefile:700: recipe for target 'libnetns.a' failed
make[3]: *** [libnetns.a] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/vnoded_main.Tpo .deps/vnoded_main.Po
mv -f .deps/vnode_io.Tpo .deps/vnode_io.Po
mv -f .deps/vnode_server.Tpo .deps/vnode_server.Po
make[3]: Leaving directory '/home/hans/core/daemon/src'
Makefile:640: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/hans/core/daemon'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hans/core'
Makefile:390: recipe for target 'all' failed
make: *** [all] Error 2'

Regards.

HansieB12

**Comment by HansieB12** [comment]
`mv ~/.core ~/.core.tmp

core-gui` 

resulted as expected.

**Comment by bharnden** [comment]
You are missing the package python-setuptools. The documentation needs a solid pass, over the whole thing, once the dust settles.

**Comment by HansieB12** [comment]
Dear bharnden,
It works all very well now.
Thank you for your consideration.
Regards.
HansieB12
