### ISSUE TITLE
CORE Application in cyber security

### ISSUE THREAD

**Issue by HansieB12** [coreemu/core#148]
"CORE (Common Open Research Emulator) is a tool for emulating networks using a GUI or Python scripts."

Dear Member,
Could I use CORE in case for emulation for cyber-security purposes?

In many cases (ethical) hacking it is forbidden by law. But I could use CORE as an emulator?

Best Regards.

HansieB12

**Comment by siliconja** [comment]
Invalid issue. Use the mailing list to ask questions.
