### ISSUE TITLE
services parent classes appearing in services menu

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#153]
There are several helper classes which are "parent" classes of particular service groups, that should not appear in the services menu, as they do not do anything (they are helpers only.)

Examples of these services include: UtilService, XorpService, QuaggaService, NrlService, BirdService.

This can be fixed using the following code change -- skip auto-loading a service if its name is empty. (Also, for the above mentioned parent classes, need to set `_name = ""`.)

```
diff --git a/daemon/core/service.py b/daemon/core/service.py
index 47e6eb9..ba32a5a 100644
--- a/daemon/core/service.py
+++ b/daemon/core/service.py
@@ -72,6 +72,8 @@ class ServiceManager(object):
         """
         services = utils.load_classes(path, CoreService)
         for service in services:
+            if len(service._name) == 0:
+                continue
             service.on_load()
             cls.add(service)
 
```

**Comment by bharnden** [comment]
Thanks, updated rel/5.1 to avoid these classes.
