### ISSUE TITLE
Wrong variable name in /etc/init.d/core-daemon

### ISSUE THREAD

**Issue by dw19375** [coreemu/core#154]
When installing CORE 5.1 beta-3 using `make install`, python site-packages are in `/usr/local/lib`, however the init script for core-daemon (/etc/init.d/core-daemon, line 23) sets the environment variable `PYTHON_PATH`, but it should be `PYTHONPATH`.  Removing the underscore allows the service to load correctly.

**Comment by bharnden** [comment]
good catch, will update it.

**Comment by bharnden** [comment]
Updated this in rel/5.1, will need to update the pre-built packages, but fixed in source.
