### ISSUE TITLE
Tools/Mac_Addresses works *only* for the first interface of entire emulation

### ISSUE THREAD

**Issue by TinCanTech** [coreemu/core#157]
All other MAC Addresses fall back to default value "00:00:00:aa:nn:nn"

**Comment by bharnden** [comment]
What is your example of what's going wrong? I just ran a quick test using code based on 5.1 Beta 4, it worked as described in the dialog box for the GUI.

MAC address where generated starting with the new value placed in the dialog. In my test I provided "5" and got 3 MAC addresses as expected (00:00:00:aa:00:05, 00:00:00:aa:00:06, 00:00:00:aa:00:07).

**Comment by TinCanTech** [comment]
I appear to be using the field incorrectly.  In order to understand the problem I observe, use 16777214 as your MAC seed.  The first eth0 MAC is 00:aa:00:ff:ff:fe (correct) but the next (ie. the other end of the first link) is 00:00:00:aa:01:00 .. and subsequent MAC addresses follow on from aa:01:00
I don't know the code involved but perhaps a more robust use of the seed field so that it wraps at a much higher value (if that is possible); or a more clear description of the field or even constrain the field input value to your expected range.

**Comment by Kevlar** [comment]
This code currently resides in the TCL/TK GUI, which we are moving away from.  We will look towards using this MAC scheme in our new GUI candidate.

**Comment by bharnden** [comment]
As noted above this will stay the way it is in the current GUI can look to document this better. The new GUI can try to take a more ideal approach eventually.
