### ISSUE TITLE
core-gui: CONFDIR hardcoded to build user's home directory

### ISSUE THREAD

**Issue by gsomlo** [coreemu/core#160]
gui/core-gui.in contains (currently on line 63), the following construct:

... `eval "echo @CORE_GUI_CONF_DIR@"` ...

As of the latest update to v 5.1 (git commit b5df7a8), the build process ends up hardcoding that as the home directory of the user performing the build. If I build manually on my workstation, the resulting gui/core-gui script has:

... `eval "echo /home/somlo/.core"` ...

Similarly, if I build an RPM using mock, I get:

... `eval "echo /build/.core"` ...

and so on. After running ./bootstrap.sh and ./configure, the resulting Makefile has, among others,

...
CORE_GUI_CONF_DIR = ${HOME}/.core
...

However, when sed replaces "@CORE_GUI_CONF_DIR@" with the *value* of $CORE_GUI_CONF_DIR, we end up evaluating *too far*. Not sure how that was handled before 5.1, and I don't know enough about automake to come up with what I presume should be a one-liner patch...

TIA for looking into it,
--Gabriel

**Comment by bharnden** [comment]
Good catch, I updated master with a quick fix, since it now has the 5.1 changes. I could potentially use "~/.core" instead as well.
