### ISSUE TITLE
5.1 core-daemon binaries installed under /bin (instead of /sbin)

### ISSUE THREAD

**Issue by gsomlo** [coreemu/core#161]
I also noticed that in the latest version everything (core-gui, as well as core-daemon + friends) gets installed into /usr/bin; Before, only core-gui used to go there, everything else (packaged under core-daemon) used to be placed under /usr/sbin.

I'm getting ready to send a pull request to update 'packaging/rpm/core.spec.in' to work against 5.1, and if you intended for everything -daemon to still go into /usr/sbin, then I'd rather wait for the commit addressing that.

If, OTOH, having everything go into /usr/bin/ is intentional, then please disregard and just close this issue.

Thanks,
--Gabe

**Comment by bharnden** [comment]
It's intentional, the old packaging is no longer used and there were changes to leverage [FPM](https://github.com/jordansissel/fpm) to help build the different packages and maintain that in an easier way.
