### ISSUE TITLE
SDN Service naming

### ISSUE THREAD

**Issue by andreas-ibm** [coreemu/core#169]
Tiny "Issue"; the services in the SDN category are "OvsService" and "ryuService", can we drop the "Service" part and name them like other services, i.e. "OpenvSwitch"/"OvS" and "Ryu"?

Thought it would be good to get this resolved quickly before too many people have imn files with the current names!

**Comment by andreas-ibm** [comment]
*cough* @bharnden

**Comment by andreas-ibm** [comment]
Actually, I think "OpenvSwitch" is probably more in line with the naming of other services?

**Comment by bharnden** [comment]
The issue  with this at the moment is that these names are treated as unique IDs for saving to IMN/XML and referenced within scripts.

Ideally we could split that up and have one name for display and one for identification, which would allow for flexibility in changing how things are displayed without impacting anything else. 

With the current GUI being stuck on leveraging IDs alone, that causes issue as well, until we can get a more maintainable GUI in place or spend some serious time learning the old one. I am hoping to get to a more manageable one going forward that would be easier to change/update.

I would need to check how strongly people would not like names being changed and having to go update all their files/scripts/etc to reflect the new names, to change them now considering everything else.

**Comment by andreas-ibm** [comment]
Indeed, I was hoping this would be early enough to be able to change them without much disruption, but I hear you!
As for GUI, my vote is discard the Tk one and build a new one using a web frontend. Have you ever used Node-RED and it's associated Worldmap?
