### ISSUE TITLE
CORE virtual interface and multicast traffic

### ISSUE THREAD

**Issue by fenwick0neil** [coreemu/core#174]
Have been developing a host network connected to the router / radio, where user traffic (MGEN) is generated from the host network.

<host>----core ethernet------<radio tech>----------< ---EMANE

We were able to identify that the UDP check sum on generated packets were bad.  Since the UDP check sum is bad the Linux kernel is dropping the multicast streams.  Using a ethtool command we are able to over come this issue; however it it feels like a brute force method way of fixing the issue.

Below is an example of ethtool on a CORE Ethernet interface and EMANE interface and the ethtool command to fix the check sum.

[HOST]# ethtool -k lan0 | grep check
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: on
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: on

[Radio]# ethtool -k wifi | grep check
rx-checksumming: off [fixed]
tx-checksumming: off
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: off [requested on]
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]

By running:

ethtool -K lan0 tx off
Actual changes:
tx-checksumming: off
	tx-checksum-ip-generic: off
	tx-checksum-sctp: off
tcp-segmentation-offload: off
	tx-tcp-segmentation: off [requested on]
	tx-tcp-ecn-segmentation: off [requested on]
	tx-tcp-mangleid-segmentation: off [requested on]
	tx-tcp6-segmentation: off [requested on]
udp-fragmentation-offload: off [requested on]

**Comment by wiinguyen** [comment]
Hi, I'm still experiencing this issue on ubuntu 18.04 with CORE (latest codes built from sources). Is there any other workaround?

**Comment by bharnden** [comment]
@wiinguyen what is your specific use case where this causes an issue? Please provide all details, commands used, etc

**Comment by Kevlar** [comment]
We'll look to disabled checksums in a near release.

**Comment by bharnden** [comment]
updated on develop
