### ISSUE TITLE
All nodes get the same service config - OvsService

### ISSUE THREAD

**Issue by andreas-ibm** [coreemu/core#177]
This is on rel/5.2

I have three nodes with a customised OvsService config:
```bash
#!/bin/sh
# auto-generated by OvsService (OvsService.py)
## First make sure that the ovs services are up and running
/etc/init.d/openvswitch-switch start < /dev/null

## create the switch itself, set the fail mode to secure, 
## this stops it from routing traffic without defined flows.
## remove the -- and everything after if you want it to act as a regular switch
ovs-vsctl add-br ovsbr0 # -- set Bridge ovsbr0 fail-mode=secure

DPID=0003000100aa0003
ovs-vsctl set Bridge ovsbr0 other_config:datapath-id=$DPID

ip addr add 172.16.2.3/24 dev ovsbr0
ip link set dev ovsbr0 up

## Now add all our interfaces as ports to the switch
## Add the CORE interface to the switch
ovs-vsctl add-port ovsbr0 eth0 -- set Interface eth0 ofport_request=1
## start them up so we can send/receive data
ovs-ofctl mod-port ovsbr0 eth0 up
## Add the CORE interface to the switch
ovs-vsctl add-port ovsbr0 eth1 -- set Interface eth1 ofport_request=2
## start them up so we can send/receive data
ovs-ofctl mod-port ovsbr0 eth1 up
## Add the CORE interface to the switch
ovs-vsctl add-port ovsbr0 eth2 -- set Interface eth2 ofport_request=3
## start them up so we can send/receive data
ovs-ofctl mod-port ovsbr0 eth2 up
## Add the CORE interface to the switch
ovs-vsctl add-port ovsbr0 eth3 -- set Interface eth3 ofport_request=4
## start them up so we can send/receive data
ovs-ofctl mod-port ovsbr0 eth3 up

## We assume there will be an SDN controller on the other end of this, 
## but it will still function if there's not
ovs-vsctl set-controller ovsbr0 tcp:172.16.2.1:6653
```
Where the DPID and IP address are different for each node.

At runtime, they all get the same content (i.e. they all run with n3's configuration)

**Comment by andreas-ibm** [comment]
In even more weirdness, I decided to start a with a blank sheet since the .imn file I was using was from pre-5.2, so i created a new emulation , added 3 ovs switches and 6 pcs, wired them all together and then looked at the services. The "default" OvsService.sh configuration for my new node was the old custom n3 configuration shown above!

In the previous example, the contents when looking at them through the configuration dialog was "correct", it was only at runtime the weirdness occurred, but with a new emulation the weirdness has crept into even the config dialogs!

Ah-hah, issuing a restart of the core-daemon gets the proper default config back again.

Re-loading the previous config re-surfaces the issue

Restarting core-daemon and starting with a clean sheet still has the runtime problem though, when I set custom config files for OvsService they all get the same config at runtime.

It's not just OvsService, applies to UserDefined service too, if i define a custom file with different content, they all get the same content at runtime.

**Comment by TinCanTech** [comment]
Andreas, I have seen very similar behaviour with rel/5.1 -- Some weird config options seem to linger even after full uninstall/reinstall .. I have had to fall back to using only rel/5.0
I realise this does not help you but I wanted to confirm that you are not going mad .. 
rel/5.1 (and I guess 5.2) is too much a _work in progress_ to be able to rely on CORE to function _as expected_ at this time, in my experience.

**Comment by bharnden** [comment]
@TinCanTech your issue, was caught and fixed in 5.2, I believe.

@andreas-ibm I caught this one internally and have a fix locally, I will include it in the next beta, thanks for posting your issue

**Comment by TinCanTech** [comment]
@bharnden -- I'll take your word for now as no time to test thoroughly.
I believe the main reason I had _issues_ with 5.1/2 was due to opening .imn files created with 5.0 and there being some inconsistencies between versions and saved files (I think .. could not prove it).  As for the _issue_ you believe I had, there was more than one but I could not give any more time to it so decided to wait until those release get a little more stable.

**Comment by andreas-ibm** [comment]
is it possible this issue also resides in 5.1? Just seeing the same symptoms...

**Comment by bharnden** [comment]
Yes, separate issue, but similar effect as I noted above, things should be better with the 5.2 Beta 2 release yesterday. If not, let me know.

**Comment by andreas-ibm** [comment]
Can confirm, 5.2-beta-2 works way better, having to reconvert all my services back to 5.2 format :-)
