### ISSUE TITLE
Can We trunk VLANS in Core using the RJ45 connector or tunnel to an external server -- Feature Enhancement

### ISSUE THREAD

**Issue by adityasriv22** [coreemu/core#180]
Also How can we Make VLANS on switches in CORE?

**Comment by Kevlar** [comment]
CORE doesn't currently have any specific functionality to support VLAN.  You should be able to use the ip command within a core node to set VLAN interfaces up.  We would welcome contributions to aid in their creation.

**Comment by bharnden** [comment]
This section in the docs speaks to this question for VLAN'ing multiple RJ45s to the same interface, but requires outside effort.

Will note down the idea for VLANs on switches, but no current plans for native support.
