### ISSUE TITLE
Missing global variable 'coreemu'

### ISSUE THREAD

**Issue by adur1990** [coreemu/core#182]
Hi,

I try to connect a Python script to the core-daemon like so:

```
coreemu = globals().get("coreemu", CoreEmu())
session = coreemu.create_session()
```

Unfortunately, the variable `coreemu` is not available. I installed CORE using [your guide](http://coreemu.github.io/core/install.html#installing-from-packages-on-ubuntu) to install CORE via the provided `*.deb` packages. Nothing else was done so far, I just followed these steps. Am I missing something?

Thank you,
Artur

**Comment by bharnden** [comment]
That variable would only exist when running the script from within GUI.

```
File -> Execute XML or Python script...
````

The above example would fall back to a new instance of CoreEmu() when running it standalone.

Unless you did run it from the GUI and something else is going on?

**Comment by adur1990** [comment]
Oh, okay. Didn't know that. Is there any way to attach the GUI to a running script? My plan was to be able to start a simulation using Python and have the ability to see "what happens" periodically (for debugging and so on).

**Comment by bharnden** [comment]
That is what the above option in the GUI tries to provide. You may need to switch sessions after, but that is the intent.

So the GUI runs the script, which provides the global variable "coreemu" to leverage and hook into the GUI.

**Comment by adur1990** [comment]
Hmm... okay. But there is no way to attach the GUI to a session created from CLI? We use an automation script to execute a massive number of experiments using CORE as the emulation environment. If this is not possible, than please close this issue :)
