### ISSUE TITLE
Viewing BW on only wireless topologies

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#189]
While I am using wireless connections through quagga-mr, I am unable to look at the bandwidths on the links through the gui. I tried selecting a link with the bandwidth view tool but its not creating the bandwidth chart it normally does with wired links.

**Comment by emirljuca** [comment]
I am currently using Ubuntu 18.04 through a VM

**Comment by bharnden** [comment]
Will need to check if this is expected or not for basic WLAN, maybe @siliconja remembers? Thanks for the input.

**Comment by emirljuca** [comment]
No problem, I thought I remembered it working in CORE 4.8 when I clicked the antenna. This doesn't seem to be the case with this version. I am not sure if this was removed

**Comment by bharnden** [comment]
Also which tool are you referring to specifically? Like "Widgets -> Throughput", or if it's something different.

**Comment by emirljuca** [comment]
Hey is this still being looked at?

**Comment by bharnden** [comment]
I have never seen that used myself since starting to help out with CORE, was hoping to get @siliconja input. I tried using it and didn't see anything, but I am not sure what it is supposed to do.

**Comment by siliconja** [comment]
- the Throughput Widget will show the throughput of wireless nodes, if they're using basic range (but not EMANE)
- if bandwidth exceeds the threshold, the node is circled using the configured color
- with the bandwidth graph tool selected, you normally click on a link to bring up its graph
- wireless "links" connecting the node to the wlan are hidden, so you can't really click on them; however, you can use the debugger and/or imn hacks to bring up a plot

choose Tools -> Debugger...

invoke the **thruPlot** Tcl/Tk function:
`thruPlot c link x y height width isresize`

example:
`thruPlot .c l1 100 100 250 250 0`

to see a list of possible links, view the imn file, or use `puts $link_list` into the debugger, and `puts $l1` to view an individual link's variables

once you configure a plot to your liking, you can save it with the imn file

attached is an example imn file having a wireless plot
[wireless-plot.imn.txt](https://github.com/coreemu/core/files/2425850/wireless-plot.imn.txt)

**Comment by emirljuca** [comment]
Thanks for your detailed response, I can use the debug tool for future projects. However I think I found what I was looking for through the gui. It seems if I click on the ip interface it brings up the graph for the wireless links, showing me the throughput for that interface.
