### ISSUE TITLE
Unable to connect nodes connected wirelessly with EMANE 802.11

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#190]
I have a network of mdr-routers all connected to a single WLAN that is running the emane 802.11abg model. When I start the CORE emulator, the nodes stay with a red box around them and they aren't able to ping each other.

**Comment by bharnden** [comment]
Which version of CORE are you using? EMANE requires a separate installation process, I assume that was done as well? 
[CORE EMANE Documentation](http://coreemu.github.io/core/emane.html)

There are also some Ubuntu 18.04 specific packages here that may help.
[EMANE Installation](https://github.com/adjacentlink/emane/wiki/Install#ubuntu-1804-lts-amd64)

You can set logging to DEBUG under /etc/core/logging.conf and run the daemon from command line yourself to help provide better context for any issues you may be having. Or look at the existing service log files.

```bash
sudo core-daemon
```

**Comment by emirljuca** [comment]
I used the install instruction on the https://github.com/adjacentlink/emane/blob/master/INSTALL with not much success, I will try the instructions you listed and will provide an update. Thanks for the help!

**Comment by emirljuca** [comment]
I have it working now, thanks for the help! I had CORE version 5.2 BTW.

**Comment by emirljuca** [comment]
However, I am not seeing the links in the CORE gui, is this a known bug?

**Comment by bharnden** [comment]
We do not currently get information from EMANE to determine if the link is up or not yet, but it is something we hope to add in.
