### ISSUE TITLE
core/examples/netns/emane80211.py example does not start all services on nodes

### ISSUE THREAD

**Issue by limonoah** [coreemu/core#191]
Working with example emane80211.py, executing it from command line creates 5 nodes 
in the session with `session.services.addservicestonode(tmp, "", services_str)` and `services_str = "zebra|OSPFv3MDR|IPForward"` 
but a `ps aux` in the n1 console shows **only** emane running.

The Python output log shows:
```
[I 180921 09:23:54 vnode:startup:106] setting hostname: n1
[I 180921 09:23:54 vnode:mount:243] mounting /tmp/pycore.1/n1.conf/var.run at /var/run
[I 180921 09:23:54 vnode:mount:243] mounting /tmp/pycore.1/n1.conf/var.log at /var/log
[I 180921 09:23:54 service:addservicestonode:296] setting node specific services: zebra|OSPFv3MDR|IPForward
[W 180921 09:23:54 service:addservicestonode:301] configured service zebra for node n1 is unknown
[W 180921 09:23:54 service:addservicestonode:301] configured service OSPFv3MDR for node n1 is unknown
[W 180921 09:23:54 service:addservicestonode:301] configured service IPForward for node n1 is unknown
```

Any idea why those services are showing as unknown?
Thanks!

**Comment by bharnden** [comment]
It appears you are using an older version of CORE, I would recommend trying the latest first. The method in the log no longer exists and the example is now in a different directory.

Your example would now live at:
https://github.com/coreemu/core/tree/master/daemon/examples/api

**Comment by limonoah** [comment]
Confirmed that upgrading CORE solved the issue. Thanks!
