### ISSUE TITLE
Opening node terminal appends terminal to core-gui runner

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#192]
I am not sure if this is intended but, when opening up a core node terminal within the gui, core attached the terminal to the terminal running core-gui. My current system setup is CORE 5.2 and Ubuntu 18.04 using GNOME version 3.28.2. Previously, I did something similar with an older version of CORE (4.8) and a different version of Ubuntu (16.04) and it would open the terminals into different instances. Changing this is not very necessary but if there is a way to change this to how it worked in my previous setup, that would be awesome.

![before](https://user-images.githubusercontent.com/43454326/45959843-d4e69800-bfe8-11e8-9c2c-11cf39fd5661.PNG)
![after](https://user-images.githubusercontent.com/43454326/45959846-d748f200-bfe8-11e8-9ef8-4504ab3caac1.PNG)

**Comment by siliconja** [comment]
I agree this is an annoying artifact of installing on Ubuntu 18.04.

You can set CORE to open new windows by default going to _Edit_ -> _Preferences_ -> _Terminal program:_, and enter the following:
`gnome-terminal --window --`

I like to create a separate profile for my CORE terminals, to differentiate them from normal host terminals (e.g. change the background color), so I use the following:
`gnome-terminal --window --profile=gray --`

A possible improvement to CORE would be to detect Ubuntu and/or this newer version of gnome-terminal and use a sane default.

**Comment by bharnden** [comment]
Quick test under Ubuntu 16.04 shows what you provided above working the same way, so maybe defaulting to this would be better for now, even if it potentially is a bad default for even older systems. Would be the easiest for 16/18 support.

```
gnome-terminal --window --
```

**Comment by siliconja** [comment]
yes, supporting the latest two Ubuntu LTS releases (16.04 and 18.04) seems sufficient

**Comment by emirljuca** [comment]
Awesome, this worked great for me thanks!
