### ISSUE TITLE
Using "sudo service core-daemon start" does not seem to work with core-gui

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#194]
I am getting the following errors when I run core-gui after trying to start the core-daemon using "sudo service core-daemon start". I am using CORE 5.2 and Ubuntu 18.04. I don't believe I had this problem with CORE 4.8 and I am not sure if this is intended behavior.

```
dev@ubuntu:~$ core-gui
Connecting to "core-daemon" (127.0.0.1:4038)...
This feature requires a connection to the CORE daemon.

Failed to connect to 127.0.0.1:4038!

Have you started the CORE daemon with '/etc/init.d/core-daemon start'?
  (Error: couldn't open socket: connection refused)
dev@ubuntu:~$ sudo service core-daemon start
[sudo] password for dev: 
dev@ubuntu:~$ core-gui
Connecting to "core-daemon" (127.0.0.1:4038)...
This feature requires a connection to the CORE daemon.

Failed to connect to 127.0.0.1:4038!

Have you started the CORE daemon with '/etc/init.d/core-daemon start'?
  (Error: couldn't open socket: connection refused)
dev@ubuntu:~$ sudo /etc/init.d/core-daemon start
[sudo] password for dev: 
core-daemon already started
unable to start core-daemon, see /var/log/core-daemon.log
dev@ubuntu:~$ sudo /etc/init.d/core-daemon restart
core-daemon not running
starting core-daemon
dev@ubuntu:~$ core-gui
Connecting to "core-daemon" (127.0.0.1:4038)...connected.
```
Works from here on.

**Comment by bharnden** [comment]
It's hard to say without seeing more or playing with what you have. It is also possible you have old 4.8 leftovers causing issues.

Beyond that it appears you tried to start the GUI, but the daemon was not up.  Starting the daemon checked for a leftover PID file, which it claimed to exist, but maybe the daemon had crashed it was not cleaned up? Then you ran restart, which actually started it up and you connected.

**Comment by emirljuca** [comment]
I think it may be the old core 4.8 causing these problems. I believe I have tried it before with `sudo service core-daemon restart` with it still not working. If you would like confirmation I can run that. Also I can provide any logs you might think would help debug. Is there a way this can be fixed with somehow removing the files needed and reinstalling CORE 5.2?

**Comment by bharnden** [comment]
Did you install using a package or make install? Uninstall the current build, however you went about installing it.

Check if you can still import core within python or if any scripts still exist related to core and wipe those.

Look for leftover files and remove them:
```shell
# can be /usr or /usr/local depending on what was done
PREFIX=/usr
# be aware that not all of these files below may be related to core
ls -al $PREFIX/bin/core*
ls -al /etc/core
ls -al $PREFIX/share/core
ls -al $PREFIX/lib/python*/dist-packages/core*
ls -al $PREFIX/lib/core
```
Then attempt a fresh install, see if you still have issues.

**Comment by siliconja** [comment]
don't forget about the old version of CORE using `$PREFIX/sbin/core*`  (sbin versus bin)

that has caused me trouble in the past

(if installing from source, you can always check out the old 4.8 version, and use `sudo make uninstall`)

**Comment by emirljuca** [comment]
Hey sorry about the late response but this seemed to have worked. I did both of the suggestions and I think it was a problem with the old version of CORE. Thanks so much for your help!

**Comment by martin20082018** [comment]
@siliconja 
sorry guys - I'm quite new on github.
I have the same problem now with Core-Gui 5.3.1.

> sudo service core-daemon restart
> core-gui
Connecting to "core-daemon" (127.0.0.1:4038)...
This feature requires a connection to the CORE daemon.
Failed to connect to 127.0.0.1:4038!
Have you started the CORE daemon with '/etc/init.d/core-daemon start'?
  (Error: couldn't open socket: connection refused)
...

I used to work on my **ubuntu 18.04 machine the core 5.2.2**
with **python 2.7.15**...  --> this works quite well
But when I tried to use EMANE the links between wireless nodes are not shown anymore....

Then I tried first the **new version 5.3.1** first on a virtual machine to test it if this works in this respect.
And I got the above described message.
Can you help me with this?
best regards, 
Martin

**Comment by martin20082018** [comment]
here is an update after I closed the core.gui and entered >**sudo service core-daemon status**

Sep 13 12:00:12 martin-VirtualBox systemd[1]: Started Common Open Research Emulator Service.
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]: Traceback (most recent call last):
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]:   File "/usr/bin/core-daemon", line 18, in <module>
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]:     from core.api.grpc.server import CoreGrpcServer
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]:   File "/usr/lib/python3/dist-packages/core/api/grpc/server.py", line 8, in <mod
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]:     import grpc
Sep 13 12:00:12 martin-VirtualBox core-daemon[5735]: ModuleNotFoundError: No module named 'grpc'
Sep 13 12:00:12 martin-VirtualBox systemd[1]: core-daemon.service: Main process exited, code=exited, status=1/FAILURE
Sep 13 12:00:12 martin-VirtualBox systemd[1]: core-daemon.service: Failed with result 'exit-code'.

**Comment by bharnden** [comment]
EMANE has never shown links between nodes. When you disable EMANE, which would use the default WLAN basic range model, that does show links.

Your issue is related to missing the python grpc dependency, that should be resolved by installing the python requirements.txt file.

[requirements.txt](https://github.com/coreemu/core/blob/develop/daemon/requirements.txt)
```shell
pip install -r requirements.txt
```

**Comment by martin20082018** [comment]
I try to use the method displaying links with emane with the paper written by Jeff Ahrenholz and Rommie L Hardy **"Drawing One-Hop Links Using the Common Open Research Emulator (CORE) Service"**

**My setup:
-  ubuntu 18.04 machine 
-  core 5.2.2
-  python 2.7.15**

Here I have also encountered the problem that the 
"coresendmsg" command doesn't work!
If I try to at least move on node a little bit with:
**coresendmsg node number=3 xpos=125 ypos=525**

==> I get the following error message:
...
Unknown message type requested: node
Usage: coresendmsg [-h|-H] [options] [message-type] [flags=flags] [message-TLVs]
Supported message types:
  ['NODE', 'LINK', 'EXECUTE', 'REGISTER', 'CONFIG', 'FILE', 'INTERFACE', 'EVENT', 'SESSION', 'EXCEPTION']
...

I configured the control network to : 172.16.0.0/24
I can ping from the node to 172.16.0.254
And from the host machine into the core network to a particuliar node e.g. 10.0.0.3...

I really would appreciate your help!

**Comment by bharnden** [comment]
I would use the latest CORE in general, which would also help in catching any other issues etc moving forward.

But beyond that, the paper you pointed out it based on a very old version of CORE and will not directly translate due to code changes etc. Things like coresendmsg have also changed slightly as well. You could run the command with a "-h" to see the options etc.

There is hope as we move forward and after getting some other aspects of the code in order we could work to have some form of native link drawing for EMANE incorporated, but that probably wont be for a while.

**Comment by salmanshokha** [comment]
Just for future references, I had a similar problem. I noticed the default version of Python was 2.7. Switching `Python 3.6.9` as default Python version worked like a charm.
