### ISSUE TITLE
Python API: Distance in BasicRangeModel 

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#197]
I tried to setup a core session with three wifi nodes, basically modelling the hidden node problem.
Therefore, I wrote the following python script to setup everything.

```
#!/usr/bin/python

from core.emulator.coreemu import CoreEmu
from core.emulator.emudata import IpPrefixes
from core.enumerations import NodeTypes, EventTypes
from core.mobility import BasicRangeModel
from core.emulator.emudata import NodeOptions
import time
import signal
import sys

def signal_handler(sig, frame):
        print('You pressed Ctrl+C!')
        # shutdown session
        coreemu.shutdown()
        sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

coreemu = CoreEmu()

prefixes = IpPrefixes("10.0.0.0/24")

session = coreemu.create_session()

session.set_state(EventTypes.CONFIGURATION_STATE)
wlan = session.add_node(_type=NodeTypes.WIRELESS_LAN, _id=255)
session.mobility.set_model(wlan, BasicRangeModel)

# create nodes
wireless_nodes = []
for i in xrange(3):
    opts = NodeOptions(name="n"+str(i+1),model = "PC")
    opts.set_position(50+275*i, 100)
    opts.services = []
    node = session.add_node(node_options=opts)
    interface = prefixes.create_interface(node)
    session.add_link(node.objid, wlan.objid, interface_one=interface)
    wireless_nodes.append(node)

session.wireless_link_all(wlan, wireless_nodes)

session.instantiate()

for i in wireless_nodes:
    print(i.getposition())

print("Simulation running, press CTRL+C to shutdown!")
while True:
    time.sleep(1)
```

The x positions each lie 275 (pixel?) apart which should be the default range of the BasicRangeModel. Printing the positions of all three nodes during runtime confirms the set positions.
When I starting pinging from `n1`I can reach both nodes even though at least `n3` should be far out of range.
If I interactively setup up the exact same scenario in core-gui it works as intended. So this is either a bug, something undocumented or I did some stupid mistake :)

Btw: All tests were performed on the latest core 5.2 release on ubuntu 18.04

**Comment by bharnden** [comment]
I think an idea got left in place, that shouldn't have been. Looks like removing one line will solve your problem with some local checking.

Just remove this and leave the rest the same. This will need to be cleared out from code and examples as well.
```python
session.wireless_link_all(wlan, wireless_nodes)
```

**Comment by gh0st42** [comment]
That fixed it and yes most of the code is directly from the official example :)
Thanks for the quick response!

Though, it is kind of confusing since in UI you have to link all nodes to one WiFi network.

**Comment by bharnden** [comment]
The link all just shouldn't be there, but you are linking it to the WLAN already in code.

```python
session.add_link(node.objid, wlan.objid, interface_one=interface)
```

In the UI you can link individual nodes as well as the convenience context menu to link all.
