### ISSUE TITLE
GUI Requirements

### ISSUE THREAD

**Issue by bharnden** [coreemu/core#207]
Determine what functionality is needed for replacing the existing GUI. Ideally aiming for a functional 80% solution that can provide basic functionality.

It will also allow us to easily change/add/update/fix functionality within the GUI that is not really possible today.

A GUI is being played with on the branch [develop](/coreemu/core/tree/develop).

* [x] core daemon
  * [x]  reconnect / change server dialog
  * [x]  gui configuration files save / load
* [x]  session
  * [x]  start / stop
  * [x]  options
* [x]  nodes
  * [x]  creation
  * [x]  deletion
  * [x]  linking
  * [x]  default nodes types
  * [x]  custom node types
  * [x]  move nodes and update positions
  * [x]  terminals
  * [x]  terminal options / custom terminals
* [x]  services
  * [x]  selection
  * [x]  configuration
* [x]  emane
  * [x]  very simple antennae graphics
  * [x]  get configuration
  * [x]  set configuration
* [x]  wlan (non-emane)
  * [x] get configuration
  * [x] set configuration
* [ ] mobility
  * [x] emane nodes
  * [x] wlan nodes
  * [ ] limited to one at a time
* [x]  xml
  * [x]  save
  * [x]  load
  * [x] validate save can only occur while running
* [x]  rest api
* [x]  grpc streaming
  * [x]  events
  * [x]  links
  * [x]  nodes
  * [x]  files
  * [x]  config
  * [x]  exception
* [x]  alpha ip/subnet generation
* [x]  hooks
  * [x]  get hooks
  * [x]  create hook

**Comment by gh0st42** [comment]
Support for mobility models is missing (config, start, stop, pause)
