### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by bharnden** [coreemu/core#208]
Determine what API calls are needed/wanted for various purposes moving forward. Feel free to add any input on what is desired/needed.

- [x] emane
  - [x] set general emane configuration
  - [x] get general emane configuration
  - [x] set general emane model configuration
  - [x] get general emane model configuration
  - [x] get emane models
- [x] hooks
  - [x] add hook
  - [ ] delete hook
  - [x] get hooks
- [x] links
  - [x] add link
  - [x] edit link
  - [x] delete link
- [x] mobility
  - [x] set mobility config
  - [x] get mobility config
  - [x] mobility action start/stop/pause
- [x] nodes
  - [x] add node
  - [x] edit node
    - [ ] update icon
    - [ ] update location
  - [x] delete node
  - [x] get node links
    - [x] link options (bandwidth, loss, etc)
  - [x] get node info
  - [x] get node terminal command string
- [x] services
  - [x] get services
  - [x] get node services
  - [x] set node services
  - [x] get node service file
  - [x] set node service file
- [x] sessions
  - [x] get sessions
  - [x] add session
  - [x] delete session
  - [x] get session options
  - [x] set session options
  - [x] set session location
  - [x] get session location
  - [x] get session info
  - [x] set session state
- [x] wlans
  - [x] get wlan config
  - [x] set wlan config
- [x] xml
  - [x] save xml
  - [x] load xml
- [x] events
  - [x] file events
  - [x] exception events
  - [x] link events
  - [x] config events
  - [x] event events
  - [x] node events

**Comment by rodsantiago** [comment]
move node to new location
change node icon
