### ISSUE TITLE
can core  simulate a mix network include of  traditional netwrok and sdn network ?

### ISSUE THREAD

**Issue by hugo921** [coreemu/core#212]
i wanna to simulate a network consist of  traditional router and switch running ospf or isis .this network still include some sdn switches and a sdn controller .
can  the above scence be supported ?

**Comment by cspiker7** [comment]
Yes, CORE will support that network. Just add routers that run services configured for what you want (ospf or isis) and then add ovs switches (make sure they are running the ovs service configured as you need). Then you can add another node to run the sdn controller service or run it on one of your existing router or switch nodes. We’ve used both Ryu and ODL as controllers, but you can experiment with others.

Carrie

**Comment by hugo921** [comment]
thanks for your reply，is there a deadline for  this function,expect  it  available  as soon!  the  5.2 version  support the  services  more fewer。

**Comment by bharnden** [comment]
@hugo921 most services did not work out of the box due to needing extra software to run, they are now "hidden", we are working to define documentation about what is needed and how to use them moving forward.

Please open an issue if you have any other questions.
