### ISSUE TITLE
CORE cannot run on CentOS. Right click menu cannot pop-up cmd window as it does in Ubuntu.

### ISSUE THREAD

**Issue by combat-networks** [coreemu/core#214]
![qq 20181029232136](https://user-images.githubusercontent.com/10898900/47660369-ce43d580-dbd1-11e8-9e4d-137ac1aafdad.jpg)
CORE cannot run on CentOS. Right click menu cannot pop-up cmd window as it does in Ubuntu.

**Comment by Kevlar** [comment]
The red boxes around your nodes mean something has not yet started properly.  Can you check the contents of "/var/log/core-daemon.log" for any errors and share them here?

**Comment by bharnden** [comment]
What @Kevlar said would be the best place to start.

Beyond that the commands ran from the "Shell window" context menu option are commands defined by what shell terminal command exists in "Edit -> Preferences..." under "Programs -> Terminal program". If there is an error launching that shell, it would be displayed as output in the terminal running the GUI.

It appears as though things are not starting to begin with. Likely missing a system dependency.

**Comment by combat-networks** [comment]
Thanks a lot for your help dear Kevlar and bharnden. We are working at it following your sugguestions. If there is any progress, we will post here.
