### ISSUE TITLE
Help! Anyone run CORE successfully on CentOS 7?

### ISSUE THREAD

**Issue by combat-networks** [coreemu/core#215]
Help! Anyone run CORE successfully on CentOS 7?

**Comment by Kevlar** [comment]
What seems to be the issue?  I (and others I know) have CORE running on CentOS 7.

If are building from source, I recommend trying to build from packages.  See the following link for details:
http://coreemu.github.io/core/install.html#build-packages

**Comment by bharnden** [comment]
Is this related to the same case in your other issue? Or do you have anything new to provide?

**Comment by combat-networks** [comment]
thanks very much. we are working.
