### ISSUE TITLE
Default bandwidth of BasicRangeModel off by factor 1000

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#216]
In `core-gui` the default bandwidth is 54mbit/s like in an 802.11g network. When using the python api the default bandwidth of the basic range model is 54000bps, this should probably by 54000000 like in the gui version.

https://github.com/coreemu/core/blob/4e6ec1a47489ca4efc01a7c348e78b69db7c6759/daemon/core/mobility.py#L320

**Comment by bharnden** [comment]
Updated
