### ISSUE TITLE
Changing mount path

### ISSUE THREAD

**Issue by preetham94** [coreemu/core#219]
I am trying to create multiple nodes and run an application the those nodes. But as the file system for each node is mounted on tmp directory, the logs created gets flushed after the session ends. Is it possible to create the node data static or is it possible the mount  point in CORE

**Comment by bharnden** [comment]
You can avoid deletion of directories for the session by using "Session -> Preserve session dir" and setting that to "On".

If the data is being written by your own service or from a node terminal, you can also write it out to anywhere you want. You are not truly locked within that nodes directory it just serves as a starting point at the moment.
