### ISSUE TITLE
Session hooks

### ISSUE THREAD

**Issue by preetham94** [coreemu/core#222]
I want to run a application in multiple nodes and found that session hooks option will serve my purpose. Can someone help me by providing some sample session hook scripts so that I can create my own script to run my application

**Comment by preetham94** [comment]
I have found how to write the script but after running the script, I am unable to open the node terminals. Is there a way out for this issue ?

**Comment by bharnden** [comment]
Would need more information on exactly what you are doing if this is still an issue
