### ISSUE TITLE
RJ45 does not get saved correctly in XML

### ISSUE THREAD

**Issue by ptesavol** [coreemu/core#223]
The "rj45 physical interface tool" does not get saved correctly in XML format.

Simplest possible replication:

- Open new canvas, and add a "rj45 physical interface tool" on it
- Save as XML
- Open the saved XML -> the rj45 is no longer there 

There is no problem if using the .imn format.

**Comment by ptesavol** [comment]
If I start the session, then save as xml, stop the session, and load the xml, the RJ45 appears as a router on the canvas.

**Comment by bharnden** [comment]
Fixed in latest commit, thanks for your help
