### ISSUE TITLE
Slow route propagation with default settings

### ISSUE THREAD

**Issue by ptesavol** [coreemu/core#225]
I have created a simple chain topology of 3 routers with default settings depicted below. 

 Router A                  Router B              Router C  
(10.0.1.1) ---  (10.0.1.2  10.0.2.1) --- (10.0.2.2)

However, i have observed it takes around 50 seconds after the session has switched to RUNTIME_STATE before ping starts going through from Router A to Router C. Since ping starts going through from Router A to Router B immediately after the session has gone to RUNTIME_STATE, I assume the long delay is caused by route propagation delay. 

Is this kind of  50s delay of delay normal? Is there something I can do to make it shorter?

**Comment by siliconja** [comment]
See this PR which addresses the convergence time issue: https://github.com/coreemu/core/pull/202

In the PR comments you'll find links to past mailing list discussions on this topic.

**Comment by ptesavol** [comment]
Thank you! Merging this pull request brought the time for the first end-to-end ping to go through down to 12s. The 12s delay stays about constant for chains of 3 to 64 routers. However, after the chain length gets over 64 routers, the end-to-end ping stops going through no matter how long I wait. Is there some other Quagga setting that could help getting past the 64 routers limit?

**Comment by siliconja** [comment]
Default ping TTL (time-to-live) is 64 (on Ubuntu at least); maybe your IP TTL is expiring? You can try `ping -t 255 10.0.80.1` (replace with your target IP).

**Comment by bharnden** [comment]
Potentially we could offer this option through a second service with fast convergence, or eventually with configuration support in services, this could be supported by a single service.

**Comment by bharnden** [comment]
Seems resolved, will discuss options for moving forward with new/configurable services.
