### ISSUE TITLE
During session start->clicked on host or PC or Router..Giving  error

### ISSUE THREAD

**Issue by nileshpatil38** [coreemu/core#226]
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0:
Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached

**Comment by bharnden** [comment]
Would need more information on what distribution you are using to try and help. I haven't seen anyone have this. You can change the terminal command used, which may alleviate the issue in this particular case.
