### ISSUE TITLE
Mobility not reproducable

### ISSUE THREAD

**Issue by adur1990** [coreemu/core#227]
Hi,

today, I stumbled across a problem regarding the mobility in CORE. I use CORE version 5.2 on a Ubuntu machine with 80 cores and 256 GB RAM to emulate 100 nodes in a Wi-Fi scenario.

The nodes shall move according to the SLAW mobility model generated with BonnMotion.

I tried two runs with the exact same parameters, but noticed, that nodes are not moving the same across the runs. They are generally following the same paths, but in different speeds.

My first guess was that 100 nodes maybe a little much, so I reduced to 10, but with the same results.

Maybe it's an issue with the refresh speed of 50 ms? In a third experiment, I reduced the refresh speed to 1000 ms, but with the same result.

`htop` also indicates, that the machine is more or less idling, so I think it's an issue with CORE.

I [attached everything](https://github.com/coreemu/core/files/2778125/mobility_issue.zip) to reproduce this issue. First, there is the `quick_test.py` script I use (please change the xml file name accordingly). Second, there are three xml scenario files, which point to the corresponding `ns_movement` files. Finally, I also attached the traces of node 2 in every run. It is our own logging format, which logs the position of every node every 10 seconds and dumps them to a trace file per node.

**Comment by bharnden** [comment]
Thanks for the information and data, I can bring this up with some others that might have better knowledge specific to this issue and see if it makes any sense to them.

Maybe @siliconja would have an idea?

**Comment by bharnden** [comment]
If you are sampling positions periodically using threads, you are not guaranteed you are logging at the exact same point in time. I would never expect to see the same exact values.

**Comment by bharnden** [comment]
Please reopen if my remarks were not clear, thanks for your input.
