### ISSUE TITLE
questions about ryu and ovs

### ISSUE THREAD

**Issue by lixiajun** [coreemu/core#229]
My  environment  are  core 5.2,  ryu==4.5, ovs==2.9.0 ,centos7.5,my questions  are:
1.the core project cant auto start ovs  and ryu, but i find that code file  sdn.py  support start
2. in  sdn.py  40 lines:
    cfg += "/etc/init.d/openvswitch-switch start < /dev/null\n"
   it didnt match my environment,. Do the core project have  ovs  version limit

**Comment by bharnden** [comment]
The existing service, is likely defined in a static way. You could easily copy that file and modify it to your needs as a custom service. Which should solve your problem.

**Comment by lixiajun** [comment]
Thanks.
I   start  ovs  and ryu  by  command. Then  I  create  ovs  switch  ,  the  switch  can start,but  it  has no ip and   i find that the  etc.openvswitch  directory and var.log.openvswitch  is none.  
can  you  help me?

**Comment by lixiajun** [comment]
> The existing service, is likely defined in a static way. You could easily copy that file and modify it to your needs as a custom service. Which should solve your problem.

Thanks.
I start ovs and ryu by command. Then I create ovs switch , the switch can start,but it has no ip and i find that the etc.openvswitch directory and var.log.openvswitch is none.
can you help me?

**Comment by bharnden** [comment]
It's hard to say without knowing everything you are trying out specifically. Ryu and OVS specifics would be best to read their documentation.

**Comment by bharnden** [comment]
I would refer to OVS documentation https://docs.openvswitch.org/en/latest/, it's a bit out of scope for CORE specifically.
