### ISSUE TITLE
Issue with emulating layer 2 traffic

### ISSUE THREAD

**Issue by suhrm** [coreemu/core#231]
Hi,

I am trying to recreate a network using CORE. In this network the LLDP information is needed from each of the devices. However the links do not forward this information (I can see them it from the host itself)

Regards.

Rasmus Suhr Mogensen

**Comment by cspiker7** [comment]
Here is a sample script you can run to test if enabling LLDP does what you want.

#/bin/bash
#This script that goes through all bridges set up by CORE and enables LLDP forwarding on them.
#It needs to be run with sudo on the host after starting the CORE scenario, so it can find the bridges.

for f in `ls -d /sys/class/net/b.*`
do
  filename=$f/bridge/group_fwd_mask
  echo 16384 > $filename
done

As a more persistent alternative for CORE, you can modify vnet.py to add the following to startup():
            # turn on LLDP forwarding (disabled by default in linux)
            lldpfile = "/sys/class/net/%s/bridge/group_fwd_mask" % self.brname
            if os.path.exists(lldpfile):
                open(lldpfile, "w").write('0x4000')

And then rebuild and reinstall CORE with this little hack. There might be a more elegant way…. But that will work.

Carrie

**Comment by suhrm** [comment]
Thanks. That resolved the issue.

Regards.

Rasmus Suhr Mogensen
