### ISSUE TITLE
Core service full ifname

### ISSUE THREAD

**Issue by carelphillipkruger** [coreemu/core#232]
Hi all,

I am trying to write my own service to launch a RiotOS native instance for simulating a WSN as shown below.

cfg += "riot %s -i %s -d\n" % (node.ifname(0),node.name)

The node.ifname(0) command returns "eth0" and not the full "eth0@if8" interface name as shown by ip a command when in the node terminal. The RiotOS instance thus fails because it can`t bind to the eth0 interface.  When executing manually with eth0@if8 in the terminal the RiotOS instance works.

How would I go about getting the full interface name as shown by the ip a command  ?

[RiotOSService.txt](https://github.com/coreemu/core/files/2939932/RiotOSService.txt)

**Comment by bharnden** [comment]
You would need to parse it yourself, since CORE does not natively have the "if#" name saved.

Snippet to achieve what you desire, based on the output I see for the command below in my current environment:
```python
output = node.check_cmd("ip -o link show %s" % netif.name)
desired_name = output.split(":")[1].strip()
```

**Comment by carelphillipkruger** [comment]
Hi bharnden.

Thank-you for the fast reply.Your advice to parse the IF# name works well.
