### ISSUE TITLE
Question on python 3 plans

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#233]
Is there any plans for the CORE API to move to python 3? Python 2 will be at end-of-life some time soon and I was hoping there might be a timeline you all as developers might have to update the CORE API.

**Comment by bharnden** [comment]
My initial hope would be to support python2/python3 to allow a period for transitioning. I can modify the python code itself to conform, but currently have issue with getting the netns c extension to compile under 3. If we were able to get someone to help on that part alone, it would go a long way.

**Comment by emirljuca** [comment]
Did you guys make the c extension? If so, where is it in the repository?

**Comment by siliconja** [comment]
Yes, @tomgoff authored them, under `core/netns/`.

**Comment by emirljuca** [comment]
I suppose you guys would want it to compile for both python2 and python3?

**Comment by bharnden** [comment]
Yes, if the netns module alone could be built in such a way, we would eventually be able to convert the standard python code

**Comment by bharnden** [comment]
Current plan is to bypass the need of extensions at all and issue commands using vcmd directly through subprocess, which avoid the need to compile the extension for python. Have a mostly working usage of it now for supporting 2/3 on a branch that will go to develop in near future.

**Comment by bharnden** [comment]
Is now on develop, if you want to play with it or try, there are some different requirements for getting operational, which we need to document.
