### ISSUE TITLE
coresendmsg problems

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#235]
Hello, I get the following error whenever I try to do a coresendmsg on an xml topology running in the core-gui. I remember this working fairly recently however, I am not sure what I did to break it.
```
user@ubuntu:~/user-repo/user/test$ coresendmsg --help
Traceback (most recent call last):
  File "/usr/local/sbin/coresendmsg", line 336, in <module>
    main()
  File "/usr/local/sbin/coresendmsg", line 219, in main
    types = map(msgtypenum_to_str, coreapi.message_types.keys()[:-1])
AttributeError: 'module' object has no attribute 'message_types'
```

**Comment by bharnden** [comment]
Not sure which version you are attempting to run, but if it's a more recent one, you are likely using an older version of the coresendmsg script that wasn't removed when updating code.

That line doesn't exist in the latest code:
https://github.com/coreemu/core/blob/master/daemon/scripts/coresendmsg

Which explains why you are getting and error about the module not having the attribute.

**Comment by emirljuca** [comment]
I built from source since I had the most success with this, but I am under this branch and commit...
```
commit 9b1141a135a1e36e41ba8bad0c3031ebf89723b9 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by bharnden** [comment]
Your installation was on a machine that never had CORE before?

For the file and commit you just referenced, that line you are getting an error on does not exist:
https://github.com/coreemu/core/blob/9b1141a135a1e36e41ba8bad0c3031ebf89723b9/daemon/scripts/coresendmsg#L219

This tells me there must be an older/prior file lingering around.

**Comment by emirljuca** [comment]
Ahh I probably do, I switched branches around a couple times to see the older versions of CORE, do you know how to delete these older files? Can I run some cleanup script?

**Comment by bharnden** [comment]
Depends how the different versions were installed during the process.

Beyond that, you can run:
```shell
which coresendmsg
```

To find out where the one you are running is currently living and remove it. Potentially other core files hiding in that same directory.

**Comment by emirljuca** [comment]
Ahhh okay, I checked and it put it in the following location...
```
/usr/local/sbin
```
I would guess that it needs to be here?
```
/usr/local/bin
```

**Comment by emirljuca** [comment]
Its seems to have worked, I am able to do the help command now. Could this be included in the make file?

**Comment by bharnden** [comment]
What do you mean by "included in the make file"?

**Comment by emirljuca** [comment]
Something like what is put in this post from [StackOverflow](https://stackoverflow.com/questions/33581943/how-to-write-a-makefile-rule-to-remove-files-clean-only-if-the-files-are-prese?rq=1) where a clean script was used.

**Comment by bharnden** [comment]
There is the following which should remove and uninstall the files, if we are missing any then we can update this. A problem can occur if installation files change and the prior version was not uninstalled before dealing with a newer version, since the new version doesn't know about the prior files.

```shell
make uninstall
```
