### ISSUE TITLE
EMANE and CORE Integration problem

### ISSUE THREAD

**Issue by enoorani** [coreemu/core#238]
I originally posted this in emane project but i was told the issue is irrelevant to the exclusion of python3-emane.
https://github.com/adjacentlink/emane/issues/96#issuecomment-480331166

I was wondering what is causing this problem. 

I skipped python3-emane package and it ran smoothly 
![image](https://user-images.githubusercontent.com/22139887/55640388-79684480-5799-11e9-92ab-f2ae8280fa27.png)
when im trying to use emane in core and run it
![image](https://user-images.githubusercontent.com/22139887/55640492-b7656880-5799-11e9-8376-13fd189f98c6.png)

I get this error
![image](https://user-images.githubusercontent.com/22139887/55640534-d2d07380-5799-11e9-9cdd-5d748790845d.png)

The system is using python2.

![image](https://user-images.githubusercontent.com/22139887/55640783-4b373480-579a-11e9-9d63-1b666f84a31c.png)

also i did "sudo ln -s /usr/local/share/emane /usr/share/emane" based on what has been suggested on the CORE installation guide.

**Comment by bharnden** [comment]
1) Can you post the contents of the log file referenced?
2) If the log file doesn't exist, when you start the session, can you try running the same command from the nodes terminal yourself. That should help make what's going wrong obvious.

**Comment by enoorani** [comment]
@bharnden I get the error as soon as I start the emulation! Core is runnning fine when "none" is selected as the EMANE module option, but if I change it to any other option I get the error.

![image](https://user-images.githubusercontent.com/22139887/55670843-22c14000-5857-11e9-96e7-755156481930.png)

![image](https://user-images.githubusercontent.com/22139887/55670805-bba38b80-5856-11e9-82b6-3d8f8150aa60.png)

![image](https://user-images.githubusercontent.com/22139887/55670794-a3cc0780-5856-11e9-8aa9-bb3f3ab9f515.png)


The node log file says this( note that this one picture is from a different session but everything is the same except the number 4038 which is 41381 in the rest of the snapshots)

![image](https://user-images.githubusercontent.com/22139887/55670913-d9bdbb80-5857-11e9-9b78-41d51c3c4203.png)


As you mentioned  /tmp/pycore.?????/emane.log doesn't exist, and I didn't try any commands when I ran it...just changed the MAC PHY EMANE module from none to 802.11 in the configuration of wlan! what command do you think I need to run on the nodes so it would give you more info.

![image](https://user-images.githubusercontent.com/22139887/55671034-72a10680-5859-11e9-861b-ac220f7a7e18.png)


I've attached the core-daemon.log here.  
[core-daemon.log](https://github.com/coreemu/core/files/3050566/core-daemon.log)

**Comment by bharnden** [comment]
So in the CEL window, we can see the exact command that was executed as an attempt to run EMANE for that node. Running this by hand on the nodes in a broken state would give us good feedback about why it failed.

I took out the daemon and log file options, since I think we would be ok to just let output go to console as we observe what goes wrong.

It may be the emane is not on path within the nodes and that explains why there is no log to begin with.

```shell
emane --logl 3 -r /tmp/pycore.41381/platform.xml
```

**Comment by enoorani** [comment]
@bharnden running your suggested command on a node in the broken state yields
![image](https://user-images.githubusercontent.com/22139887/55671755-530ddc00-5861-11e9-875e-01a48d8ba8f4.png)

I took a look at the dtd folder as well
![image](https://user-images.githubusercontent.com/22139887/55671790-a97b1a80-5861-11e9-84b2-3e0d4d4ae752.png)

and the platform.dtd file contains
![image](https://user-images.githubusercontent.com/22139887/55671833-1989a080-5862-11e9-8573-34d4c738242a.png)

**Comment by bharnden** [comment]
It appears to be an issue with not matching the emane schema. Is this the latest emane? Potentially they changed the schema. The latest I recall seeing work is 1.2.3. Thank for bringing this to my attention, if the newest one has changed.

**Comment by bharnden** [comment]
You can also try xmllint as recommended, feeding the schema and the platform.xml, see if it gives a better error message.

**Comment by bharnden** [comment]
Now that I ran something here to check at some level, what version of CORE are you running? If you got CORE from the NRL site, that version is very out of date and doesn't support newer versions of EMANE.

A generated platform.xml from CORE normally has the ID of the node appended on the name of the file.

```shell
platform2.xml
```

Also there is no id attribute that I see in your file, that appears in mine.

Yours:
```xml
<platform id="1" name="Platform 1">
```

Mine:
```xml
<platform>
```

**Comment by enoorani** [comment]
Yes, you're right! this is the version of the core that I have, 4.8!
![image](https://user-images.githubusercontent.com/22139887/55679117-bafd0a80-58d3-11e9-9514-f12e98718dfe.png)

and yes, I followed the instructions on nrl website...What would be the latest version of CORE, 5.2.1? and what version of emane dose it fully support?

Thanks a lot for the suggestions...

**Comment by bharnden** [comment]
Here on GitHub is the latest code and documentation. The latest is 5.2.1 and I tested with EMANE 1.2.4 today, which I had to build from source, but I usually use their pre-built packages for Ubuntu.

**Comment by enoorani** [comment]
@bharnden I installed the version on github by following http://coreemu.github.io/core/install.html . I got it running on an Ubuntu 16.04 lxc container. But When I run the emulation it doesn't work! I don't get the green links indicating the connectivity. Also double clicking on the nodes doesn't open the terminal. I was wondering if you could help me out here.
I've also attached the core-daemon log-file.
![image](https://user-images.githubusercontent.com/22139887/55680168-04555600-58e4-11e9-86fc-bd556465d233.png)

[core-daemon.log](https://github.com/coreemu/core/files/3051292/core-daemon.log)

**Comment by bharnden** [comment]
CORE is creating containers itself. You can't run CORE from within one, like lxc. You can run on bare metal or from within a VM.

**Comment by enoorani** [comment]
@bharnden Thanks for the help. Core 4.8 runs fine within the container. any idea why?

**Comment by bharnden** [comment]
Not offhand, I have only come on recently. There may have been changes at some point in how CORE's containers are created.

Creating containers within containers doesn't sound like a good idea. There had been thoughts of wanting to run CORE within a Docker container to help setup an environment in some cases, but what I had read seemed like it would cause issue. I hadn't got a chance to dive into trying.

This part is your specific error, which is failing on mounting "/", which as far as I can tell is the same method called on the 4.8 branch on GitHub:
```shell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 490, in handle_message
    replies = message_handler(message)
  File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 668, in handle_node_message
    node = self.session.add_node(node_type, node_id, node_options)
  File "/usr/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 496, in add_node
    node = self.add_object(cls=node_class, objid=_id, name=name, start=start)
  File "/usr/lib/python2.7/dist-packages/core/session.py", line 486, in add_object
    obj = cls(self, *clsargs, **clskwds)
  File "/usr/lib/python2.7/dist-packages/core/netns/vnode.py", line 506, in __init__
    self.startup()
  File "/usr/lib/python2.7/dist-packages/core/netns/vnode.py", line 516, in startup
    super(LxcNode, self).startup()
  File "/usr/lib/python2.7/dist-packages/core/netns/vnode.py", line 104, in startup
    self.pid = int(output)
ValueError: invalid literal for int() with base 10: '4273\nvnoded[1]: 06:22:53.555407 nssetup[netns.c:46]: mounting / failed: Permission denied'
```

It is also possible that 4.8 on GitHub is different than NRL's 4.8. I would be curious if the 4.8 here would give you the same issue. But, that wouldn't really help you now. I haven't known anyone running CORE within another container, so this is the first I have seen anyone trying.

**Comment by enoorani** [comment]
@bharnden Thanks! I purged 4.8 and installed 5.2.1 but when I'm trying to run the emulation it's unable to connect to the core daemon.
![image](https://user-images.githubusercontent.com/22139887/55687152-abafa880-5937-11e9-8b05-cd7645d37797.png)

**Comment by bharnden** [comment]
This is all being ran from the same environment? How did you end up installing things? Are you certain the core-daemon is running?

I will usually just run it by hand myself as opposed to using the system service.

```shell
sudo core-daemon
```

Otherwise you can see if the process is running or check service status:
```shell
# sysv
sudo service core-daemon status
# systemd
sudo systemctl status core-daemon
```

**Comment by enoorani** [comment]
@bharnden For installing core 5.2.1, I followed "installing from packages on Ubuntu" on http://coreemu.github.io/core/install.html#ubuntu-1604-requirements. 
![image](https://user-images.githubusercontent.com/22139887/55689263-69469580-5950-11e9-906c-6253fba363cf.png)
![image](https://user-images.githubusercontent.com/22139887/55689292-b6c30280-5950-11e9-8be8-5b18e578a3ef.png)
![image](https://user-images.githubusercontent.com/22139887/55689300-cf331d00-5950-11e9-8016-8ecc915e5cdc.png)
![image](https://user-images.githubusercontent.com/22139887/55689306-dfe39300-5950-11e9-824f-8e4ef4aece75.png)

No, the core-daemon is not running and I can't get it to run...it throws this error
![image](https://user-images.githubusercontent.com/22139887/55689208-c857da80-594f-11e9-9a58-853466bb807f.png)

**Comment by bharnden** [comment]
That's related to a protobuf message by the emane library that CORE is using. Something is not installed appropriately for emane it appears. You can see in the stack trace it is occurring on line 9 in emane.events.event_pb2 which is a protobuf file.

How was emane installed?
