### ISSUE TITLE
Could not communicate core emulator system to outside real system using RJ45

### ISSUE THREAD

**Issue by nileshpatil38** [coreemu/core#242]
My use case like 
Core emulator installed in Ubuntu 18.04( no VM used)
Host/PC ==> Router ==> RJ45 physical interface tool. 
And like to ping another real computer with IP address (172.16.15.87). But could not ping that real host from core emulator.

Please suggest!! New to core emulator environment. 

Thanks is advance.

**Comment by bharnden** [comment]
This speaks about using RJ45, if it helps: http://coreemu.github.io/core/usage.html#rj45-tool

Otherwise a CORE node would need to be linked to the RJ45 and configured to be on the same subnet with a route to reach out to the real computer.

**Comment by nileshpatil38** [comment]
Thank you for the help!!. I tried but could not connect with physical network. 
I have reconfigure topology in CORE emulator, according to our physical network configuration.
My topology (on Core emulator installed in Ubuntu 18.04( no VM used)):

**Host/PC (172.16.12.20/22) =>   (172.16.12.1/22)Router(172.16.13.1/22) =>  RJ45 Physical Interface (enp2s0).**

Real system Ip address is: => 172.16.15.87

Our subnet is like => 172.16.12.*/22  (255.255.252.0).

When ping from core host(ping 172.16.15.87)=> getting messages=>
PING 172.16.15.8 (172.16.15.87) 56 (84) bytes of data.
From 172.16.12.20 icmp_seq=1 Destination host Unreachable.
....
After Control+C
6 packet transmitted, 0 received, +3 errors, 100 % packet loss, time 51113ms pipe 4.

**Comment by nileshpatil38** [comment]
@bharnden actually its work (ping from both side) when I directly connect my core emulator host to RJ45 physical interface. 

Reconfigured ..
Host/PC (172.16.15.10/24) => RJ45 Physical Interface (enp2s0).

Real system IP address is: => 172.16.15.87
Our subnet is like => 172.16.15.*/22 (255.255.255.0).
This configuration works, but I want to put many host, that should communicate with real system.

**Comment by nileshpatil38** [comment]
@bharnden, thank you for help. Its work, instead of router, I used Ethernet switch and its working fine. Really thank you so much. Because of your help, I get idea to configure correctly.
