### ISSUE TITLE
[BUG] Problem with tunnel tool

### ISSUE THREAD

**Issue by asabolansky** [coreemu/core#246]
[untitled.imn.gz](https://github.com/coreemu/core/files/3179775/untitled.imn.gz)
The topology don't start in batch mode when you have a topology that has connected a GRE Tunnel  tool to a switch and the switch connected to a router.

OS: Ubuntu 18.04
CORE: 5.2.1

**Comment by bharnden** [comment]
Thanks for the input, some changes to help fix these issues are on develop.

**Comment by bharnden** [comment]
Should be fixed on develop, will be in next release
