### ISSUE TITLE
Hosts on different routers only find eachother after ping between the routers

### ISSUE THREAD

**Issue by Quixus** [coreemu/core#247]
I built the attached basic topology (it is an .imn file renamed to .txt) and tried pinging n4 from n1. It did not work. But after pinging one router from the other, pinging betwen the hosts works. OSPF 2 and 3 are enabled on both routers. Is this a bug or a feature? If it isn't a bug, how do I enable automatic network discovery?

[edit]Despite the GUI showing highlighted routes, the terminal window also shows the following errors:

```Couldn't highlight next hop: 10.0.0.1
Couldn't highlight next hop: 10.0.0.10
Couldn't highlight next hop: 10.0.1.1
Couldn't highlight next hop: 10.0.1.2
Couldn't highlight next hop: 10.0.0.10
Couldn't highlight next hop: 10.0.2.10
`````
[/edit]
Thanks in advance for your answer.
[Basic routing.txt](https://github.com/coreemu/core/files/3186215/Basic.routing.txt)

**Comment by bharnden** [comment]
Please reopen if there are any other problems.
