### ISSUE TITLE
wlan configuration can't be changed at runtime

### ISSUE THREAD

**Issue by Kevlar** [coreemu/core#252]
Using coresendmsg to change wlan configuration no longer works during runtime

Create a core scenario with the basic wlan and attempt to use coresndmsg to change the parameters of the wlan configuration.  It doesn't affect the state of the wlan

The wlan configuration should change.

Configuration
 - OS: Ubuntu 18.04
 - Latest CORE  (works in CORE 4.8 on Ubuntu 16)

**Comment by bharnden** [comment]
fixed on develop
