### ISSUE TITLE
[FEATURE] Could CORE support LXD/LXC instead of the older form of LXC

### ISSUE THREAD

**Issue by bmullan** [coreemu/core#257]
**Is your feature request related to a problem? Please describe.**
LXD is the "hypervisor" for the newer version & API of LXC.   I'd like to see CORE support LXD/LXC instead of the older LXC without LXD daemon.

**Describe the solution you'd like**
I'd like to see CORE support LXD/LXC instead of the older LXC without LXD daemon.
https://linuxcontainers.org/lxd/introduction/

**Describe alternatives you've considered**

**Additional context**
LXD is supported by both OpenStack and OpenNebula v5.8 and later.   LXD has many advanced container capabilities some of which Docker does not yet implement or have.

**Comment by bharnden** [comment]
CORE currently doesn't support or use LXC or LXD. CORE uses its own small C binary to create its version of name spaced nodes. This does not cover the file system aspect, like LXC and Docker.

In the future there may be a Docker or LXC like node that can be connected to the existing node types, but that may still be a while.

**Comment by bmullan** [comment]
ok thanks...

**Comment by bharnden** [comment]
Did you have a specific need from LXC/LXD? Just curious as that can help potentially shape future decisions.

**Comment by bmullan** [comment]
My reason for asking was part my background and part how CORE might be used for a dual purpose.

I may not explain this well but I'll start by saying I recently retired from 20 years at Cisco Systems.  

A good Network Simulator  to me, is not just about connectivity, the routing protocols used etc but also could/should include an ability for the user to setup traffic loads based on the same applications or application use-cases they implement in their existing enterprise Servers/VMs.    

Of course simulating traffic is possible but then its difficult to duplicate the affects real customer server applications could impact the network with or the load (cpu, disk etc) of those applications on the "nodes".

Many simulators are looking to Docker containers as "nodes" but I just have doubts how realistically a Docker "application" container can implement the above in representative of an Enterprise's Servers.

LXD/LXC are "system" containers and can be of just about any Linux Distro and end-user might want to be represented (fedora, centos, debian, ubuntu, oracle, alpine, manjaro, etc)

As "system" containers an end user could setup a duplication of their actual Server configured workloads used in their enterprise.

As to how CORE might use LXD containers and implement a "dual" purpose..  After a practitioner using CORE tests out their topology/loads etc...  after the testing, the remaining LXD containers could actually become development/test/production "servers" already configured with their existing server applications.   Using LXD's ability to copy/clone LXC containers to/from remote LXD/LXC containers on other "hosts" those Simulator nodes could actually be utilized.    The CORE graphical representations captured could become documentation etc.

Anyway, maybe this doesn't make sense as i may not be explaining the thoughts well.

Attached is a long list of currently implemented & available LXD/LXC Linux "system" images.   Each is basically a full OS except they share the Kernel of the "Host".

[lxd-images.txt](https://github.com/coreemu/core/files/3283497/lxd-images.txt)

**Comment by bharnden** [comment]
Thanks for the input, that makes perfect sense and when we get there maybe a reason to try out Lxc first. Ideally maybe even support both for whatever people would like.

**Comment by Echirivella** [comment]
Any update in this feature?

**Comment by bharnden** [comment]
Docker and LXC (by way of LXD) are supported now and have been for a while. I forgot this existed to update. The integration is fairly minimal at the moment though and assumes you have the images you need for the nodes cached locally.

They can be used directly through python/gRPC or the new python based GUI.

**Comment by bmullan** [comment]
@bharnden   (re LXD) ... Great thanks... I'll try to take a look.
