### ISSUE TITLE
[BUG] 5.3 shows 5.2 as version on help

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#265]
**Describe the bug**
Possibly small bug, help still shows 5.2

**To Reproduce**
After uninstalling 5.2 from source and then installing 5.3, the help menu still showed 5.2 as the version.
1. Have 5.2 from source
2. Uninstall 5.2
```
cd ./core
sudo make uninstall
```
3. Change to 5.3
```
git checkout rel/5.3
```
4. Regular install
5. Check help <-- issue

**Screenshots**
![image](https://user-images.githubusercontent.com/43454326/60517100-0e9dab00-9cad-11e9-8997-b81ab85291c2.png)

**Desktop (please complete the following information):**
 - OS: 18.04
 - CORE Version 5.3

**Comment by bharnden** [comment]
I can double check this, assuming this isn't related to an older instance of the GUI sticking around under a different path possibly.

**Comment by bharnden** [comment]
I just checked both current deb packages and both had 5.3 GUIs, I can only assume something was left behind, due to the previous uninstall as noted in the issue.

You can verify this at some level by uninstall your 5.3 and seeing if you can still run core-gui
