### ISSUE TITLE
[BUG] Problem with running wlan.py example in GUI

### ISSUE THREAD

**Issue by chorig9** [coreemu/core#270]
**Describe the bug**

Problem with running wlan.py example from daemon/examples/api in GUI.

**To Reproduce**
1. in core-gui, click  File -> Excuting XML or Python script.py and provide wlan.py
2. See error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/core/utils.py", line 39, in execute_file
    exec(data, exec_globals, exec_locals)
  File "/home/igor/Projects/core-release-5.3.1/daemon/examples/api/wlan.py", line 72, in <module>
    main()
  File "/home/igor/Projects/core-release-5.3.1/daemon/examples/api/wlan.py", line 63, in main
    options = parser.parse_options("wlan")
AttributeError: module 'parser' has no attribute 'parse_options'
```

**Expected behavior**
Working session in core-gui?

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - CORE Version  5.3.1
 - EMANE Version [e.g. 1.2.4]

**Additional context**
This looked like some problem with finding parser.py module so trying to fix it I copied content of parser.py to the wlan.py but the I got:

```
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/core/utils.py", line 39, in execute_file
    exec(data, exec_globals, exec_locals)
  File "/home/igor/Projects/dtn/core/daemon/examples/api/wlan.py", line 115, in <module>
    main()
  File "/home/igor/Projects/dtn/core/daemon/examples/api/wlan.py", line 110, in main
    example(options)
  File "/home/igor/Projects/dtn/core/daemon/examples/api/wlan.py", line 70, in example
    session = coreemu.create_session()
  File "/usr/lib/python3/dist-packages/core/emulator/coreemu.py", line 118, in create_session
    session = Session(_id, config=self.config)
  File "/usr/lib/python3/dist-packages/core/emulator/session.py", line 67, in __init__
    os.mkdir(self.session_dir)
FileExistsError: [Errno 17] File exists: '/tmp/pycore.1'
```

**Comment by chorig9** [comment]
I don't seem to be able to run any example in the GUI (by clicking Execute XML or Python script), am I doing something wrong?

**Comment by bharnden** [comment]
That script is intended to be ran standalone outside the usage of the daemon/GUI. There is one that speaks to being executed here https://github.com/coreemu/core/blob/master/daemon/examples/api/switch_inject.py. That one potentially hasn't been checked lately, but hopefully should work.

Most of the script examples lean towards standalone scripts to drive CORE as opposed to using the GUI.

**Comment by chorig9** [comment]
Thanks, switch_inject.py works great with the GUI.

**Comment by gdalya** [comment]
I am having this same problem.  I can't find switch_inject.py in the repo.  Is it still there?  I'm new to github.

**Comment by bharnden** [comment]
> I am having this same problem. I can't find switch_inject.py in the repo. Is it still there? I'm new to github.

I am not sure what you are talking about, maybe you can be more specific and I can try to help.

**Comment by gdalya** [comment]
Thanks, @bharnden.

I am trying to write a script to modify the parameters of a node after the core.start_session() call that comes at the end the examples that I've looked at and after I've started core-gui and attached to the session.  For example, for a wlan node, to change the bandwidth value.

You wrote above that [switch_inject.py](https://github.com/coreemu/core/blob/master/daemon/examples/api/switch_inject.py) is such an example, but the link currently gives a 404 error.

I've figured out how to connect to find running sessions and how to connect to them using the CoreGrpcClient.get_session method.  I can also change a node value and then print the node fields and see the change in the parameter, but the value in core-gui doesn't update.

Also, all of this is from executing python scripts from the command line.  When I run from File>Execute Core Script in core-gui, I'm not sure it works.  print() commands don't *seem* to do anything, but I'm not sure to what window they would print.

**Comment by bharnden** [comment]
Where are you finding reference to switch_inject.py? That's what I would like to know.

I would probably never use `File->Execute` it is more of a legacy aspect lingering around and requires nuanced usage.

gRPC would be the better approach for what it sounds like you want to do (https://coreemu.github.io/core/grpc.html).

**Comment by gdalya** [comment]
Thank, @bharnden.

I am okay using scripts from the command line, and not from inside core-gui, and I've already had some success using the grpc model.

My question at this point is that I have

1. created a core session using the wireless.py script
2. started core-gui and connects to that running session
3. write a second script that also connects to the session using the connect() method
4. modified a node's parameters using that second script

But, when I look inside core-gui, the node is unchanged.

How do I get core-gui to realize the changes that I made in an external script?

Or maybe I didn't make the changes that I thought I made?

Here's my code for the second script:
`# required imports
`
`from core.api.grpc import client
`from core.api.grpc.wrappers import NodeType, Position
`
`# interface helper
`iface_helper = client.InterfaceHelper(ip4_prefix="10.0.0.0/24", ip6_prefix="2001::/64")
`
`# create grpc client and connect
`core = client.CoreGrpcClient()
`core.connect()
`
`# get session
`    
`sessions = core.get_sessions()
`
`# print(sessions)
`
`session = core.get_session(sessions[-1].id);
`
`np = wrappers.Position(360, 360)
`session.move_node(5, 1, position=np)
`
`print(session)
`print()
`print(session.nodes[1])
`print()
`print(session.nodes[1]).name='Joe Flebeats'
`print(session.nodes[1])
`print()
`
`print(session.nodes[1].wlan_config)
`print()
`print(session.nodes[1].wlan_config['bandwidth'])
`print()
`
`session.nodes[1].wlan_config['bandwidth'] = '10000000';
`print(session.nodes[1].wlan_config['bandwidth'])
`print()

**Comment by bharnden** [comment]
Yes, you are not setting it correctly.

This would be the call to set it, while running:
```python
wlan_node_id = 1
core.set_wlan_config(session.id, wlan_node_id, dict(bandwidth="10000000"))
```

This will also not currently update within the GUI in that moment, if you really want to see that within the GUI, you would have to rejoin the session.

**Comment by gdalya** [comment]
Thankyou @bharnden -- this has been very helpful.
