### ISSUE TITLE
[BUG] error installing python package futures==3.2.0

### ISSUE THREAD

**Issue by Mordecai71** [coreemu/core#272]
**error installing python package futures==3.2.0**

$ sudo python3 -m pip install -r requirements.txt
Collecting futures==3.2.0 (from -r req.txt (line 4)) Could not find a version that satisfies the requirement futures==3.2.0 (from -r req.txt (line 5)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r req.txt (line 5)) 

Sames error with futures=3.3.0 (the last one https://pypi.org/project/futures/#history)

All other python packages installed ok.

 - OS: Ubuntu 18.04.3 LTS (clean fresh install with all updates)
 - CORE Version 5.3.1

Thanks for any help
--
Marcius

**Comment by Brianhedgecock** [comment]
On Aug 27, 2019 7:13 PM, Marcius Dias <notifications@github.com> wrote:

error installing python package futures==3.2.0

$ sudo python3 -m pip install -r requirements.txt
Collecting futures==3.2.0 (from -r req.txt (line 4)) Could not find a version that satisfies the requirement futures==3.2.0 (from -r req.txt (line 5)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r req.txt (line 5))

Sames error with futures=3.3.0 (the last one https://pypi.org/project/futures/#history<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpypi.org%2Fproject%2Ffutures%2F%23history&data=02%7C01%7C%7Ca37539bff4b04e9626ad08d72b5d41f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637025551839141097&sdata=%2FAoqPpBJ0fmIZvRlm9EKD8YlkOUIPCblfQ1TFHOPZkk%3D&reserved=0>)

All other python packages installed ok.

  *   OS: Ubuntu 18.04.3 LTS (clean fresh install with all updates)
  *   CORE Version 5.3.1

Thanks for any help

Marcius

**Comment by bharnden** [comment]
futures is a python 2 specific requirement, there should be an update to resolve this issue. If you are planning to use python 3, you can remove the line for "futures" and try again.

Thanks for pointing this out.

**Comment by Mordecai71** [comment]
Thank you very much. I this point, I've already moved on with python 2.x, I will try this later.

**Comment by bharnden** [comment]
requirements.txt fixed on develop, thanks for the input
