### ISSUE TITLE
error when I make core 5.3.1

### ISSUE THREAD

**Issue by lirivernick** [coreemu/core#274]
I don't know how to solve it ,My OS is ubuntu 12.04
root@rfcontroller:/home/yy/core-master# make
make all-recursive
make[1]: Entering directory /home/yy/core-master' Making all in gui make[2]: Entering directory /home/yy/core-master/gui'
Making all in icons
make[3]: Entering directory /home/yy/core-master/gui/icons' make[3]: Nothing to be done for all'.
make[3]: Leaving directory /home/yy/core-master/gui/icons' make[3]: Entering directory /home/yy/core-master/gui'
make[3]: *** No rule to make target core-gui', needed by all-am'. Stop.
make[3]: Leaving directory /home/yy/core-master/gui' make[2]: *** [all-recursive] Error 1 make[2]: Leaving directory /home/yy/core-master/gui'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/yy/core-master'
make: *** [all] Error 2

**Comment by lirivernick** [comment]
I don't know how to solve it ,My OS is ubuntu 12.04
root@rfcontroller:/home/yy/core-master# make
make  all-recursive
make[1]: Entering directory `/home/yy/core-master'
Making all in gui
make[2]: Entering directory `/home/yy/core-master/gui'
Making all in icons
make[3]: Entering directory `/home/yy/core-master/gui/icons'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/yy/core-master/gui/icons'
make[3]: Entering directory `/home/yy/core-master/gui'
make[3]: *** No rule to make target `core-gui', needed by `all-am'.  Stop.
make[3]: Leaving directory `/home/yy/core-master/gui'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/yy/core-master/gui'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/yy/core-master'
make: *** [all] Error 2

**Comment by lirivernick** [comment]
and my configure result:
root@rfcontroller:/home/yy/core-master# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for a sed that does not truncate output... /bin/sed
checking for NgMkSockNode in -lnetgraph... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for int32_t... no
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint32_t... no
checking for uint8_t... no
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... no
checking for vfork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for atexit... yes
checking for dup2... yes
checking for gettimeofday... yes
checking for memset... no
checking for socket... yes
checking for strerror... yes
checking for uname... yes
checking for a Python interpreter with version >= 2.7... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for brctl... /sbin
checking for sysctl... /sbin
checking for ebtables... /sbin
checking for ip... /sbin
checking for tc... /sbin
checking for mount... /bin
checking for umount... /bin
checking for convert... yes
checking for ovs-vsctl... /usr/bin
checking for ovs-ofctl... /usr/bin
checking Python.h usability... yes
checking Python.h presence... yes
checking for Python.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libev... no
did not find libev using pkconfig...
checking for ev_set_allocator in -lev... yes
found libev OK
using startup option initd
configure: creating ./config.status
config.status: creating Makefile
config.status: creating gui/version.tcl
config.status: creating gui/Makefile
config.status: creating gui/icons/Makefile
config.status: creating scripts/Makefile
config.status: creating scripts/perf/Makefile
config.status: creating man/Makefile
config.status: creating docs/Makefile
config.status: creating daemon/Makefile
config.status: creating daemon/doc/Makefile
config.status: creating daemon/doc/conf.py
config.status: creating daemon/proto/Makefile
config.status: creating netns/Makefile
config.status: creating netns/version.h
config.status: creating ns3/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
------------------------------------------------------------------------
core 5.3.1 Configuration:

Build:
  Host System Type:           
  C Compiler and flags:       gcc  -O3 -Werror -Wall -D_GNU_SOURCE
  Prefix:                     /usr/local
  Exec Prefix:                ${prefix}

GUI:
  GUI path:                   ${prefix}/lib/core
  GUI config:                 $${HOME}/.core

Daemon:
  Daemon path:                ${exec_prefix}/bin
  Daemon config:              /etc/core
  Python:                     /usr/bin/python
  Logs:                       /var/log

Startup:                      initd

Features to build:
  Build GUI:                  yes
  Build Daemon:               yes
  Documentation:              no

------------------------------------------------------------------------
On this platform you should run core-gui as a normal user.
------------------------------------------------------------------------

**Comment by bharnden** [comment]
I don't see anything specific in terms what the error is in what you pasted, but at the same time Ubuntu 12 is rather old and I would strongly suggest moving to 16/18.

**Comment by lirivernick** [comment]
> I don't see anything specific in terms what the error is in what you pasted, but at the same time Ubuntu 12 is rather old and I would strongly suggest moving to 16/18.
> 
> I would go so far as to say we wouldn't expect it to work in 12, but it might be possible with pain.

OK，thanks，I decided to update my os。
