### ISSUE TITLE
Replacing Quagga with FRR and/or OLSR

### ISSUE THREAD

**Issue by Kevlar** [coreemu/core#283]
We're in discussion about replacing Quagga with FRR and/or OLSR as the default routing options for routers and mdr routers and are interested in the opinions of the community.   Please respond to this issue, or reach out on discord if this topic interests you.

**Comment by apwiggins** [comment]
We're squarely in the FRR camp as we are migrating away from Quagga.  FRR has a broad set of protocols, so should be preferable to a wide audience.

If OLSR, would you be looking at version 2?

**Comment by bharnden** [comment]
@apwiggins I think the biggest thing we would like to be able to achieve is a reasonably good solution that eventually could get to a simple package installation alone. Something that would allow things to work out of the box more or less and require less work to install all the various parts. Not that someone couldn't do that for other cases, but at least making the default easier to use. If that makes sense.

olsr seems to be available for Ubuntu, but not CentOS. FRR is available as a snap package from what I can see, but I cannot make it a deb/rpm package requirement.

**Comment by apwiggins** [comment]
@bharnden  Ubuntu 19.10 has FRR6.02-2build2 as an installable deb package.  19.10 will be released in the next couple of weeks.
![image](https://user-images.githubusercontent.com/7106951/66238351-ce93fd00-e6cd-11e9-9bed-ce8339f3404c.png)

**Comment by bharnden** [comment]
@apwiggins Thanks! That is good to know. There are other dependencies we need that are in 19 as well. I think we would at least plan to see if we can get something configured for out of the box on Ubuntu 20 since it is an LTS release, but maybe earlier if we finish playing with other ideas.

**Comment by apwiggins** [comment]
@bharnden Glad to help out.  Also, Fedora30 has FRR7.1-2.fc30 so some minor differences to take into account.
![image](https://user-images.githubusercontent.com/7106951/66240221-67c51280-e6d2-11e9-97cc-bafd3dcd88be.png)

**Comment by bharnden** [comment]
Taking the path of looking at helping automate more parts of the installation, hurdles like installing OSPF MDR are not as big of a concern.

The hope was there would be a solution that could provide a simple install path with out of the box functionality for typical CORE nodes. But, there does not seem to be a good answer at the moment for replacing OSPF MDR and leaving this as if may be the right choice for now.
