### ISSUE TITLE
[BUG] Wrong configparser version specified in requirements.txt for 5.4.0

### ISSUE THREAD

**Issue by hofbi** [coreemu/core#288]
**Describe the bug**

Installation of Pre-Req Python Requirements fails due to not existing version of `configparser==4.0.1`

**To Reproduce**
1. Download https://github.com/coreemu/core/releases/download/release-5.4.0/requirements.txt
2. Run `sudo python3 -m pip install -r requirements.txt`
3. Installation fails due to not existing version of config parser

**Expected behavior**
Installation should succeed

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CORE Version [e.g. 5.4.0]

**Additional context**
If you check the available configparser versions on [PyPI](https://pypi.org/project/configparser/#history) you will find that there is just a version 4.0.2. So changing from 4.0.1 to 4.0.2 will fix this issue.

**Comment by bharnden** [comment]
Ya, the devs for configparser pulled that version after it was released and we forgot to catch this here and update it. Will bump it, thanks for the feedback.

**Comment by bharnden** [comment]
Fixed on develop, will update the release file as well, if anyone is using that.
