### ISSUE TITLE
[BUG] docker install

### ISSUE THREAD

**Issue by J4ckt0rr4nc3** [coreemu/core#309]
i have followed the tutorial about install docker service in nodes in this Github. my core emulator version is 4.8 (20150605) and my ubuntu is 16.04 64bit but when i do the steps in the mentioned tutorial and after restart the core service and run the core-gui again and run a sample topology in core emulator i got this error "can not find channel named -1" or sometime i got this one "can not find channel named sock+number" how can i solve it??

**Comment by bharnden** [comment]
I assume you are referring to this? http://coreemu.github.io/core/services.html#docker

The documentation would be based on using the latest release, 4.8 is very old at this point. The docker service has been experimental as far as I am aware. The newest release has more native integration with docker based nodes, but can only be driven from scripts currently. When we eventually release a redo of the current GUI, we will have them added in.
