### ISSUE TITLE
NS2 setdest command not moving in x direction

### ISSUE THREAD

**Issue by carelphillipkruger** [coreemu/core#314]
When running an NS2 movement script the _setdest_ command only moves the node along the y-axis and ignores the x axis for movement.

1. Open a new canvas
2. Place a node
3. Create a wireless cloud and add the NS2 mobility script below

$node_(1) set X_ 40.00
$node_(1) set Y_ 500.00
$ns_ at 1 "$node_(1) setdest 500 200 0.62"
$node_(2) set X_ 60.00
$node_(2) set Y_ 500.00
$ns_ at 1 "$node_(1) setdest 500 200 0.62"

4. Link node to cloud and simulate

**Expected behavior**
The node only moves along the y-axis and ignores the x-axis

 Ubuntu 18.04
 CORE Version 5.3.1
 EMANE Version 1.2.3

**Comment by bharnden** [comment]
Thanks, found the issue, will look to have a fix in the next release

**Comment by bharnden** [comment]
should be fixed on latest release on master
