### ISSUE TITLE
[BUG] reopen terminal bug

### ISSUE THREAD

**Issue by NatanielAfonso** [coreemu/core#317]
Hello!

I received your response on the previous issue, but was unavailable at the moment.

I still have the terminal problem on the nodes and as said before, I had already changed the terminal to "lxterminal" but the error continues.

follows the image of the "env" command on one of the nodes.

NOTE: I am using Lubuntu 19.04 and Ubuntu 18.04

![image](https://user-images.githubusercontent.com/56442173/69236992-6e6cf380-0b73-11ea-826c-d35c01e1d851.png)

**Comment by bharnden** [comment]
I believe I noted in the other case, this is likely due to the fact that the inherited environment for nodes does not have a TERM variable set. There are ways to add/modify the global environment for nodes though. You can place a file /etc/core/environment with values you would like.

```shell
TERM=whatever-i-want
```

**Comment by NatanielAfonso** [comment]
bharnden,

Thank you!

I solved my problem according to the tip you gave me, thank you very much!


![image](https://user-images.githubusercontent.com/56442173/69686776-8545a580-109f-11ea-9019-c225651cbdba.png)
