### ISSUE TITLE
Using EMANE Raw Transport in CORE

### ISSUE THREAD

**Issue by Lindo-Elec** [coreemu/core#318]
Hi

I'm currently emulating a network in CORE using the Bypass EMANE model. When setting up the EMANE model in CORE it automatically creates a transvirtual XML file. Is there a way to change this in CORE such that the EMANE model uses Raw Transport instead? Your help is much appreciated.

**Comment by bharnden** [comment]
From what I can see the only things related to raw are when an EMANE cloud is linked to an RJ45 node.

What is your use case? If it is lacking and something we can look to support it would be worth noting. Thanks!

**Comment by Lindo-Elec** [comment]
You'll have to forgive me. I'm an electrical engineer so my knowledge about networks is quite limited. I hope I'm able to explain this comprehensively...

I'm currently working on a wireless network of smart sensors that will be taking measurements at different locations and transmitting them through the network. The sensors used will be operated by low powered devices (e.g. Arduino) which will be running RIOT OS. In order to emulate this use case as close to reality as possible (using CORE and EMANE), I'm running RIOT OS on the 'host' nodes in a CORE session. RIOT has its own network architecture which uses its own tap devices, while EMANE creates a network using tap devices of its own. I've been trying to interface these two "networks" with no success. I was told by my supervisor that I need to be running the emulation with EMANE's Raw transport library instead of Transvirtual transport. While this seems possible using EMANE alone, I can't seem to find a way to do so with CORE.

If you can explain how I can do this, or give me an alternative approach that would be helpful. Thanks

**Comment by bharnden** [comment]
I'll mention this topic in an upcoming meeting. From what I can see I do not think what you want is a current out of the box solution. Maybe there is something I am missing and will find out. Otherwise you would have to try and go down the path of writing custom services to create the tuntap devices needed, run emane as desired, and your virtualized riot os processes.

**Comment by bharnden** [comment]
The person I hoped would have any idea, did not. I am pretty sure what I said stands. There is not currently out of the box support for using raw mode, unless its through an RJ45 node.

It is possible, what you need is not raw and that you need EMANE to leverage the tap interface these riot OS processes are using, that can likely be achieved through a custom service, but you would need to write all the logic to create the tap, start your RIOT process and then create/start EMANE with that interface. This is my quick take from glancing over the RIO website.

In the future maybe we can support settings a custom interface for a node connected to EMANE to use, which would at least remove the need to setup/run EMANE on your own.

**Comment by Lindo-Elec** [comment]
Okay, I'll try that. Thanks for the assist

**Comment by bharnden** [comment]
Will note this down as future task to consider, hope things worked out for you.
