### ISSUE TITLE
Packet level data payload modification at source

### ISSUE THREAD

**Issue by szl0144** [coreemu/core#320]
Hi,
I plan to assign some user defined data to packet data payload at Application layer, can you tell me whether it is available by changing CORE source code? And where can I change them in CORE.

Thank you very much.
Shaoyi

**Comment by bharnden** [comment]
All data sent within a core session is generated by the applications and services that you run. So it can be whatever you want. There is no need to modify source to achieve that. I may be misunderstanding your question, but CORE does not generate any traffic itself.

**Comment by szl0144** [comment]
I see, I think you explanation is for my doubts. So CORE doesn't generate any packets, it just receives traffic from other applications. 

Can I use MGEN which is a default traffic generator for EMANE as the applications and services? Because I don't know whether there is any default packets generator for CORE in current program. 
I think there must be an interface for CORE to receive outside traffic from other applications if it doesn't generate any packets.

**Comment by bharnden** [comment]
CORE creates containers on your system, within those containers you can run and use any tool installed on the system, like MGEN.

In a simple case, you can create and link 2 nodes, then click on each node and start MGEN receiving on one node and a sender on the other. To have traffic move through the network. But you could also run any program you like.
