### ISSUE TITLE
Install core python modules in dist-packages

### ISSUE THREAD

**Issue by VincentEmond** [coreemu/core#321]
Hi,

I'm new to autotools, python and open source development in general so you'll have to forgive me if my question seem obvious to you.

I looked at how to install core from source and I noticed that if I configure the PYTHON variable to point to my system interpreter `/usr/bin/python3` then the core python modules will be installed in `/usr/local/lib/python3.6/site-packages/core` 

The problem is that this path is not searched by the python system interpreter installed from the Ubuntu 18.04 repo with apt.

```
$ python3 -m site
sys.path = [
    '/home/analyst',
    '/usr/lib/python36.zip',
    '/usr/lib/python3.6',
    '/usr/lib/python3.6/lib-dynload',
    '/home/analyst/.local/lib/python3.6/site-packages',
    '/usr/local/lib/python3.6/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/analyst/.local' (exists)
USER_SITE: '/home/analyst/.local/lib/python3.6/site-packages' (exists)
ENABLE_USER_SITE: True
```
I also followed the instruction to build a .deb package with fpm and I get something like this
(installed in site-packages)
```
-rw-r--r-- 0/0            3124 2019-11-04 15:50 ./usr/local/lib/python3.6/site-packages/core/emulator/sessionconfig.py
-rw-r--r-- 0/0           65159 2019-11-06 14:48 ./usr/local/lib/python3.6/site-packages/core/emulator/session.py
-rw-r--r-- 0/0            5372 2019-11-06 14:48 ./usr/local/lib/python3.6/site-packages/core/emulator/enumerations.py
-rw-r--r-- 0/0            2612 2019-11-06 14:48 ./usr/local/lib/python3.6/site-packages/core/emulator/data.py
-rw-r--r-- 0/0            7881 2019-11-06 14:48 ./usr/local/lib/python3.6/site-packages/core/emulator/distributed.py
-rw-r--r-- 0/0            3624 2019-11-04 15:50 ./usr/local/lib/python3.6/site-packages/core/emulator/coreemu.py
```
however if I inspect the packages you provide on the release page I see that its installed in dist-packages:

```
-rw-r--r-- 0/0            3624 2019-10-17 22:13 ./usr/lib/python3.6/dist-packages/core/emulator/coreemu.py
-rw-r--r-- 0/0            3124 2019-10-17 22:13 ./usr/lib/python3.6/dist-packages/core/emulator/sessionconfig.py
-rw-r--r-- 0/0             704 2019-10-21 23:41 ./usr/lib/python3.6/dist-packages/core/constants.py
```
One of the workaround I found is to compile a python interpreter from source and use that interpreter in the `./configure` script. An interpreter built from source includes **site-packages** in its default search path.

Is there a way to configure the makefile to install the core python modules into **dist-package** so that I can use my system interpreter, that way I don't have to compile python from source or mess with the default PYTHONPATH?

I am guessing it has something to do with **AM_PATH_PYTHON(3.6)** in **configure.ac** but I don't know much about automake and autoconf.

**Comment by bharnden** [comment]
I believe this will be alleviated with the next release. You can update the global python path, which should hopefully work for you. There is some nuance to different Linux distros and which paths they have by default.

```shell
echo ../site-packages > /usr/local/lib/python3.6/dist-packages/site-packages.pth
```

**Comment by bharnden** [comment]
should be fixed in latest release on master
