### ISSUE TITLE
Unable to get Docker service running

### ISSUE THREAD

**Issue by shivani-1521** [coreemu/core#322]
Hello,
I am able to add Docker as a service with the help of "http://coreemu.github.io/core/services.html#docker". But I get the error "Cannot connect to the docker daemon at unix: ///var/run/docker.sock. Is the docker daemon running" with commands like docker images, on the node terminal. I would be grateful to know if I'm missing a step somewhere or whether the Docker service only works with certain versions.
Core version : 5.5.2
Docker version : 19.03.5
Ubuntu 18.04
As I'm new to CORE, I'd be very grateful for help. Thanks!

**Comment by bharnden** [comment]
The Docker service as it exists is still more or less experimental and an older way of trying to integrate it. This being to try and run Docker inside a CORE container.

There is an updated path that is implemented and being improved where Docker containers can be created in a more natural way and linked to existing nodes. This can currently only be achieved through scripts on master branch but will be available in the new GUI when released.

Here is some notes on using this path in scripts, maybe you solved your problems and are closing the issue, sorry I didn't get back sooner.

https://github.com/coreemu/core/tree/master/daemon/examples/docker

**Comment by shivani-1521** [comment]
Thank you for your reply. Earlier Docker started on boot on my computer. So the Docker daemon on the CORE node was unable to bind to Unix socket. Hence, the error was fixed with sudo service docker stop.  
https://docs.docker.com/install/linux/linux-postinstall/

And thank you for sharing the link, I'll explore the Docker nodes in CORE.

**Comment by devannair777** [comment]
Hello Shivani,
I am running into a similar issue when trying to setup docker container on CORE..Can you explain what you did to get docker service running.  I tried running service docker start inside bash of one of the nodes where I wanted to run docker service and it says 'Cannot create directory cpuset ' ??
