### ISSUE TITLE
Error: couldn't open socket: connection refused

### ISSUE THREAD

**Issue by Martinjgge** [coreemu/core#324]
It is impossible for me to start the core daemon.

```
martin@frank:~$ core-gui
Connecting to "core-daemon" (127.0.0.1:4038)...
This feature requires a connection to the CORE daemon.

Failed to connect to 127.0.0.1:4038!

Have you started the CORE daemon with '/etc/init.d/core-daemon start'?
  (Error: couldn't open socket: connection refused)
```
Actually running /etc/init.d/core-daemon start tells me i have Permission denied, running 'sudo /etc/init.d/core-daemon start' gived me

```
martin@frank:~$ sudo /etc/init.d/core-daemon start
starting core-daemon
martin@frank:~$ Traceback (most recent call last):
  File "/usr/bin/core-daemon", line 16, in <module>
    from core import constants
  File "/usr/lib/python3.6/dist-packages/core/constants.py", line 1, in <module>
    from core.utils import which
  File "/usr/lib/python3.6/dist-packages/core/utils.py", line 17, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

The gui still works but when using something i need the daemon for a popup comes up informing me of this. Sometimes when clicking "start deamon" the popup is blank (sometimes grey, sometimes black), sometimes it just gives me the 'Error: couldn't...'

**Desktop:**
 - OS: Ubuntu 18.04.4
 - CORE Version python3_5.5.2
 - EMANE Version [i don't have a clue what this is but i don't have it i think]

**Comment by bharnden** [comment]
It looks like you are missing python dependencies, did you install them as noted in the instructions?

http://coreemu.github.io/core/install.html#pre-req-python-requirements

```shell
sudo python3 -m pip install -r requirements.txt
```

**Comment by Martinjgge** [comment]
It does now appear to work! i have to do it via console, the button in the gui does nothing. And yes, I actually did forget to get the dependencies, thank you!
