### ISSUE TITLE
core-daemon service not running.

### ISSUE THREAD

**Issue by hirocsingh** [coreemu/core#325]
The service is not running on ubuntu 19.10 even after installing every package correctly following the Installation document.
 Getting following error:

`Traceback (most recent call last):
  File "/usr/bin/core-daemon", line 16, in <module>
    from core import constants
ModuleNotFoundError: No module named 'core'
`

**Comment by bharnden** [comment]
This will be alleviated with the next release. I believe your problem is the global python path. Hopefully the below will fix your problem, change python version if needed.

```shell
echo ../site-packages > /usr/local/lib/python3.6/dist-packages/site-packages.pth
```

**Comment by bharnden** [comment]
Noting this as the same issue as #321 hope this helped you.
