### ISSUE TITLE
[BUG] core-daemon start fails to find vnoded

### ISSUE THREAD

**Issue by pgfaller** [coreemu/core#327]
**Describe the bug**
Default installation of core-6.0.0 on CentOS 7 can not find 'vnoded' executable

**To Reproduce**
1. Install as follows:
`    pip3 install grpcio protobuf lxml fabric
    yum -y update
    yum -y install kernel-modules-extra quagga xorg-x11-xauth gnome-terminal
    yum -y install /vagrant/core-6.0.0/core_6.0.0_x86_64.rpm
`
2. Execute:
`
$ sudo /etc/init.d/core-daemon start
`
3. See error
`
[vagrant@coreemu ~]$ Traceback (most recent call last):
  File "/usr/local/bin/core-daemon", line 16, in <module>
    from core import constants
  File "/usr/local/lib/python3.6/site-packages/core/constants.py", line 9, in <module>
    VNODED_BIN = which("vnoded", required=True)
  File "/usr/local/lib/python3.6/site-packages/core/utils.py", line 141, in which
    raise ValueError(f"failed to find required executable({command}) in path")
ValueError: failed to find required executable(vnoded) in path
`

**Expected behavior**
The start script /etc/init.d/core-daemon should have set the PATH to include /usr/local/bin

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos 7]
 - CORE Version [e.g. 6.0.0]

**Additional context**

Workaround:
`
                echo "starting $NAME"
                PATH=$PATH:/usr/local/bin $CMD 2>&1 >> "$LOG" & 
                # $CMD 2>&1 >> "$LOG" &
`

**Comment by bharnden** [comment]
You could also run configure with a prefix that would be on the path of the distribution as another options.

```shell
./configure --prefix=/usr
```

or alternatively update the PATH for the system itself to be valid.

Thanks for pointing this out, will discuss.

**Comment by bharnden** [comment]
For now things will stay as is, depending on the distribution building from source and accounting for the system pathing would need to be accounted for.

Will be looking into higher level ways of packaging to potentially avoid pathing issues altogether, but may not be likely.
