### ISSUE TITLE
Change Control Network but failed

### ISSUE THREAD

**Issue by ChengDaHaI** [coreemu/core#335]
Hi,
I followed ["Activating the Primary Control Network" ](http://coreemu.github.io/core/ctrlnet.html) to change the control network but it failed. 

In fact, when the controlnet line in  /etc/core/core.conf is uncommented, i still have the control net bridge(172.16.0.254). At the same time, nothing is in Session->Options. So, if there another file specify the contronet in CORE? 

Any hint or advice is appreciated. Thank you.

Best,
Hai

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.2.3]

**Comment by bharnden** [comment]
So you have the following in core.conf?

```shell
controlnet = 172.16.0.0/24
```

Then you see nothing in Session -> Options at all?

I see that value in the "Control Network" option when I do the above.

Do you get control networks setup on the nodes too? Or are you just not seeing this in the GUI?

What version of CORE are you using?

**Comment by ChengDaHaI** [comment]
> So you have the following in core.conf?
> 
> ```shell
> controlnet = 172.16.0.0/24
> ```
> 
> Then you see nothing in Session -> Options at all?
> 
> I see that value in the "Control Network" option when I do the above.
> 
> Do you get control networks setup on the nodes too? Or are you just not seeing this in the GUI?
> 
> What version of CORE are you using?

Hi

Thanks for your reply. The key problem i don't mentioned is i use python script to emulate a network, instead of core-gui. The script is "emane80211.py" in example folder.

1. When the "controlnet = 172.16.0.0/24" line in core.conf is commented, i see the controlnet bridge ip is 172.16.0.254. When i uncomment it, i still have the same bridge. Right now, i change it to "10.99.0.0/24", i see "10.99.0.0/24" in the controlnet blank in Options. 

However, in the script case, but the bridge is still 172.16.0.254. The related loggins is:

> INFO:root:controlnet prefix: <class 'str'> - 172.16.0.0/24
> INFO:root:added control network bridge: b.ctrl0net.1 172.16.0.0/24
> INFO:root:address 172.16.0.254

2. It works in core-gui but not in script case. In script case, I run ifconfig in each node and there is a controlnet ip (172.16.0.XX). Also, in my host(my desktop), there is a controlnet bridge 172.16.0.254. CORE vrsion 5.5.2（20191021）

Best,
Hai

**Comment by bharnden** [comment]
I see, EMANE by default requires and uses a control network. The core.conf file is only used by the core-daemon.

If you are running a script directly, you would need to configure the setting yourself. Potentially there could be improvements to add a convenience for reading and loading that file, but it is not there today.

You would need to do something like the following.

```python
coreemu = CoreEmu(config={"controlnet": "10.99.0.0/24"})
session = coreemu.create_session()
```
