### ISSUE TITLE
gRCP created routing not functioning

### ISSUE THREAD

**Issue by devdkerr** [coreemu/core#353]
Creating a network solely from gRPC which consists of a two hosts and two routers connected as follows (h1 <-> r1 <-> r2 <-> h2), creates a network that seems to share routes appropriately, but does not transit traffic accordingly. Ping's from h1 to h2 result in a "Destination Host Unreachable" which is not consistent as the same network created from the GUI.

In both cases I am using the standard services and service configuration defaults. I have been able to validate these via both the GUI interface and gRPC configuration retrievals.

See the code below to reproduce the observed unexpected behavior.

```python
import time
from core.api.grpc import client, core_pb2

core = client.CoreGrpcClient('<daemon>')

with core.context_connect():
    # create session
    session_id = core.create_session().session_id
    core.set_session_state(session_id,
        core_pb2.SessionState.CONFIGURATION)

    # create nodes    
    h1_id = core.add_node(session_id, core_pb2.Node(
        name='h1', model='host', type='DEFAULT')).node_id
    r1_id = core.add_node(session_id, core_pb2.Node(
        name='r1', model='router', type='DEFAULT')).node_id
    r2_id = core.add_node(session_id, core_pb2.Node(
        name='r2', model='router', type='DEFAULT')).node_id
    h2_id = core.add_node(session_id, core_pb2.Node(
        name='h2', model='host', type='DEFAULT')).node_id

    # create links
    net1 = client.InterfaceHelper(ip4_prefix='10.10.0.0/16')
    core.add_link(session_id, h1_id, r1_id,
                  net1.create_interface(h1_id, 0),
                  net1.create_interface(r1_id, 0))
    net2 = client.InterfaceHelper(ip4_prefix='20.20.0.0/16')
    core.add_link(session_id, r1_id, r2_id,
                  net2.create_interface(r1_id, 1),
                  net2.create_interface(r2_id, 1))
    net3 = client.InterfaceHelper(ip4_prefix='30.30.0.0/16')
    core.add_link(session_id, r2_id, h2_id,
                  net3.create_interface(r2_id, 0),
                  net3.create_interface(h2_id, 0))

    # instantiate session
    core.set_session_state(session_id,
        core_pb2.SessionState.INSTANTIATION)
    time.sleep(120)

    print (r1_id, core.node_command(session_id, r1_id,
        'ip route show').output, '\n')
    print (r2_id, core.node_command(session_id, r2_id,
        'ip route show').output, '\n')

    h2_eth0 = core.node_command(session_id, h2_id,
        'ifdata -pa eth0').output
    print (h1_id, core.node_command(session_id, r1_id,
        'ping -c 3 {0}'.format(h2_eth0)).output, '\n')
    print (h1_id, core.node_command(session_id, r1_id,
        'traceroute {0}'.format(h2_eth0)).output, '\n')

    # delete session
    core.delete_session(session_id)
```

I would expect the ping and traceroute commands from h1 to work sucessfully and return valid ICMP responses for the ping and TTL exceed pings from traceroute.

My testing is run using the `devdkerr/core` container, and the comparison was done with a GUI initiated session in the same running instance (just different session).

**Comment by devdkerr** [comment]
The specific version of CORE daemon is v.6.0.0

**Comment by bharnden** [comment]
The Host service, which adds a default route to nodes, uses a ".1" address for the default routes. Which is not the address of the router nodes connected to these hosts, and this is the issue here.

When connected out in the GUI, you will see that the links would have a ".1" on the router side.

You can either change the router nodes to use a ".1" or would need to save a changed service configuration for both host nodes to have different default route values.

**Comment by devdkerr** [comment]
@bharnden that was it exactly. I did a direct compare of the node configurations and missed the fact that the default route IP didn't match the first hop routers. That fixed it.

It may be good to build into `InterfaceHelper` similar behavior as the GUI's default assignment of a `.1` address on nodes with model `router`.

Thanks for your help.
