### ISSUE TITLE
Can we create containers using vnoded without sudo priviliege ?

### ISSUE THREAD

**Issue by ChengDaHaI** [coreemu/core#362]
As descriped in title, is it possible to create containers/network namespaces without sudo priviliege?

**Comment by bharnden** [comment]
No, you cannot.

**Comment by ChengDaHaI** [comment]
> No, you cannot.

Hi,
 i found a similar problem in docker community:
` we can run docker command without sudo if we (have root privileges) add the users  to docker group. `

So, if it's possible to create a vnoded(or something) group and add other uses to this group to avoid sudo privileges?

Thanks

**Comment by bharnden** [comment]
Docker does things differently for various reasons and its containers are very different than CORE specific ones. So there isn't a current way to achieve what is noted.

In your example as noted in the Docker manual
> Giving non-root access
> 
> The docker daemon always runs as the root user, and since Docker version 0.5.2, the docker daemon binds to a Unix socket instead of a TCP port. By default that Unix socket is owned by the user root, and so, by default, you can access it with sudo.
> 
> Starting in version 0.5.3, if you (or your Docker installer) create a Unix group called docker and add users to it, then the docker daemon will make the ownership of the Unix socket read/writable by the docker group when the daemon starts. The docker daemon must always run as the root user, but if you run the docker client as a user in the docker group then you don't need to add sudo to all the client commands. As of 0.9.0, you can specify that a group other than docker should own the Unix socket with the -G option.

You are still indirectly using root privileges. I am not sure what your exact concern is with this.

**Comment by ChengDaHaI** [comment]
My concern is can i installed CORE in a high performance cluster such that common users can  use CORE without sudo in the cluster. 

As discussed in docker community, common users in clusters can be added to docker group to user docker without sudo. So, is it possible to do this with CORE(vnode)? such as replace vnode with docer or LXC.

**Comment by bharnden** [comment]
Using the gRPC API can be a means to achieve things without needing sudo technically, although if you are concerned with bad things these users can do, there are security risks. If I recall the same risks for users, when placing them into the docker group as well, if that matters.

There is no current way to setup some group in the same way as you asked currently.

**Comment by ChengDaHaI** [comment]
Thank you!
