### ISSUE TITLE
[BUG] FileExistsError: [Errno 17] File exists: '/tmp/pycore.1'

### ISSUE THREAD

**Issue by DejavuCarpediem** [coreemu/core#363]
**Describe the bug**
When I run the wlan.py (with one minor modification), there is an error: `stderr: b"vnoded[51]: 16:11:46.978050 forkexec[vnode_cmd.c:417]: execvp() failed for 'iperf': No such file or directory\n"`. Thus, I press "ctrl+c" to close the core GUI in terminal. Afterwards, when I run the first python script example in documentation [here](http://coreemu.github.io/core/scripting.html), the **FileExistsError: [Errno 17] File exists: '/tmp/pycore.1'** keeps showing. The whole error message can be found in "screenshots" section. I try to modify the session.py by replacing `os.mkdir(self.session_dir)` with `osmakedirs(self.session_dir, exist_ok= True)`, but to no avail. I have seen a similar bug issue #270, but the answer right there cannot solve my problem. 

**To Reproduce**
1. After the installation of core, start core GUI.
2. Files menu -> execute XML or Python Script -> choose the wlan.py file located in core/daemon/examples/python.
3. When there is an error, type "ctrl+c" to terminate.
4. run the first python script example in "Python scripting" documentation using again the GUI as describe in step 2, there goes the error. 

**Expected behavior**
I do not know the the behavior of the example script because I have not run it successfully. 

**Screenshots**
![1](https://user-images.githubusercontent.com/55478215/73639157-ca411600-46a6-11ea-84a8-b033ea346fe0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version:  6.0.0
 - EMANE Version: I built core from source. I don't know how to check this one. 

**Additional context**
The one minor modification I add to wlan.py is as follows: there is a built-in module named parser. Whenever I run this file, I got the error that "parser" module does not have the "parse" method. The imported file should be the parser.py instead of the built-in module. Thus I import the parser.py by adding the following codes into the original wlan.py.
```
import imp
parser = imp.load_source('parser', '/home/username/core/daemon/examples/python/parser.py')
```

**Comment by bharnden** [comment]
Can rename parser to avoid the conflict. Can also remove the usage of iperf as it is just an example.

You can run "core-cleanup" when you have a failure like you did to delete nodes, bridges, and directories that may have been leftover from a bad run.

**Comment by siliconja** [comment]
Formerly, CORE session numbers were randomly assigned, with collisions far less likely. Was there a reason to start numbering the sessions 1, 2, 3, etc.?

Could have get_unique_session_number() that picks randomly and checks for existing.

**Comment by bharnden** [comment]
The fact those files exist are due to an error, leaving a lingering problem doesn't seem ideal. We could check for existing folders and skip until a clean number exists, avoiding any conflict, but I still don't like the idea of ignoring accidental leftover directories.

Create session will take an ID if I recall, so there is always room to avoid it, if desired.

**Comment by DejavuCarpediem** [comment]
@bharnden  `core-cleanup` is exactly what I need, thank you for the answer. Where can I  find these `core-***` commands, like `core-gui` and `core-cleanup`? Before I opened this issue, I have been searching for something like the command `core-cleanup` for a while without success.

**Comment by bharnden** [comment]
These are the scripts that will be installed with the latest release:
https://github.com/coreemu/core/tree/master/daemon/scripts

They will usually either be in /usr/bin or /usr/local/bin depending on how things were installed.
