### ISSUE TITLE
[BUG] Creating Custom Services Using Python Script 

### ISSUE THREAD

**Issue by DejavuCarpediem** [coreemu/core#369]
**Describe the bug**
The "Configuring Services" section in the documentation [CORE Python Scripting](http://coreemu.github.io/core/scripting.html#configuring-services) should be updated. Because there is no longer a "services" package under the "session". There four key methods there `set_service`, `get_service`, `set_service_file` and `add_services` are now defined in the class "core.services.coreservices.Coreservices". But the key question I want to ask is that **_How to execute a shell script on nodes when the session starts using python script?_** For example, I would like the PC node to execute the following simple one-line script `sudo mkdir xxx` when the simulation session starts using python script. I can type the that command in the "UserDefined" options in CORE GUI, but in terms of python scripting, I don't even know how to create the "service_name" that can be used in `set_service(self, node_id, service_name)`. I have tried everything I can think of for "service_name", but alway got an error: `TypeError: 'NoneType' object is not callable` Are there any minimal working examples concerning how to execute a shell script on nodes using python scripts?  

**To Reproduce**
1. Go to [here](http://coreemu.github.io/core/scripting.html#configuring-services)
2. Copy the codes in "Configuring Services" and paste it to .py file.
3. Execute the python file using "sudo python3" in the terminal
4. See errors

**Expected behavior**
I expect the custom services to execute the shell script I defined using python script.

**Screenshots**
![error](https://user-images.githubusercontent.com/55478215/74334311-9cf61580-4dd4-11ea-9965-32a3bd427e43.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.0.0
 - EMANE Version: I don't know

**Additional context**
I have to admit that I don't understand the usage even after I read the docstring shown by help commands in interactive Python shell. Only until I read issue #268 did I know exactly how to use CoreService. By the way, another question is that how to create a host using python script? I don't see this in `core.emulator.enumerations.NodeTypes`.

**Comment by bharnden** [comment]
> The "Configuring Services" section in the documentation CORE Python Scripting should be updated. Because there is no longer a "services" package under the "session". There four key methods there set_service, get_service, set_service_file and add_services are now defined in the class "core.services.coreservices.Coreservices".

Those are not examples using the python module as reference, but a Session class instance, which does have a **services** member.

**Comment by DejavuCarpediem** [comment]
@bharnden 
My apologies. When I opened the sources file `/usr/local/lib/python3.6/dist-packages/core/emulator/session.py`  I saw that **services** member. Before, I just used `help(core.emulator.session)` in the interactive Python shell to check the methods defined.
 
If I have a multiple-line script, do I just concatenate those commands using Python string type and put that Python string in the `node.cmd("multiple_line_command")`? or should I execute the "script.sh" other ways?

**Comment by bharnden** [comment]
You could iterate over a list of commands running them one of a time, but it would probably be easier to execute some designed script as you noted

**Comment by DejavuCarpediem** [comment]
If I understand correctly, `node.cmd("sh script.sh")` would server my purpose here?

In case you didn't see the question in "additional context", how can I add a host node instead of a PC node using python script? I didn't see the "host" type in `NodeTypes` or there aren't any differences between these two and they are just represented with different icons in CORE GUI?

Sorry to bother you with so many rudimentary questions.

**Comment by bharnden** [comment]
You would need to use the NodeOptions class

```python
from core.emulator.emudata import NodeOptions

options = NodeOptions(model="PC")
session.add_node(options=options)
```

**Comment by DejavuCarpediem** [comment]
I have tried to create nodes both with `session.add_node()` and with the code you provided (using `NodeOptions` with model=PC). However, they all visualized in CORE GUI in the same icons. As shown by the following figure, although corenode3 ~ corenode6 are created with `session.add_node()` and corenode7 is created using `NodeOptions` with model=PC, they are the same in terms of type and the icon. What I desire is the node named "host" on the right side of this figure which I created using GUI.  
![image](https://user-images.githubusercontent.com/55478215/74410373-e0ec2780-4e73-11ea-81b2-deaff77dc31e.png)

**Comment by bharnden** [comment]
You want model="host" then

**Comment by DejavuCarpediem** [comment]
I just tried changing the model="PC" to model="host" with all other parts of Python script being the same, I got an error and thus cannot be visualized in CORE GUI.
![image](https://user-images.githubusercontent.com/55478215/74450466-10715300-4eb9-11ea-8b33-69841851462f.png)
 
Hence, I try model="Host". It works and the type is "host" but with a router icon in CORE GUI as shown in the following figure. As long as the functionalities are the same as the host, the icon doesn't matter to me. I'm okay with it. Thank you for your answer. By the way, are there differences between model="host" and model="Host"?
![image](https://user-images.githubusercontent.com/55478215/74449734-f3885000-4eb7-11ea-9e3c-5366b086dfcc.png)

**Comment by bharnden** [comment]
Some services require external software to be installed. Like the SSH service for Hosts above. If you use the GUI you can create custom nodes with different sets of services for whatever you need, with whatever icon you like. In case you are looking for a custom look and feel to what you are doing.

**Comment by DejavuCarpediem** [comment]
After I installed and started the ssh service, adding the host node using model="host" worked perfectly. There is no such constraint to create a host node in GUI and therefore I didn't realize ssh service is the problem although the error message shows exactly the ssh service isn't available. The reason I would like to create network topology using Python script is the scalability. It's not practical to create, for example,  1000 nodes in GUI and make these nodes execute scripts.  

I encountered another problem when executing the code `node.cmd("sh ~/hostattack.sh")` which I executed without any errors in the terminal opened by double-clicking the host node created using Python script. The error message I got is `Can't open ~/hostattack.sh\n"`. I tried `sudo sh hostattack.sh` as well, but this doesn't help.
![sherror](https://user-images.githubusercontent.com/55478215/74503470-f02eac00-4f2b-11ea-8357-0b494f0cefb2.png)

**Comment by bharnden** [comment]
~/ is relative to the root users home and not your normal user, potentially the assumption about how this path is resolving is incorrect. Make your path absolute and you will likely avoid this problem.

**Comment by DejavuCarpediem** [comment]
Yes, the absolute path solved that problem. It works great now. Thank you very much for your patience and quick reply. 

The following question is uncorrelated to this issue. If you think opening a new issue is better, please let me know. 

I want to ask if I can adjust how many cpu resources the host can use? For example, I would like to run an application on the host node, can I configure how many cpu resources used to run that application by adjusting maybe some parameters I don't know now? Even if the total resources owned by the host are fixed, as long as I can decide how many portions of the total cpu resources to run that application, this would serve my purpose.

**Comment by bharnden** [comment]
There is a Discord channel for conversation like this, so it doesn't have to be a formal issue etc.
https://discord.gg/AKd7kmP

Otherwise, no, there is no parameters to try and configure or constrain system resources.

**Comment by DejavuCarpediem** [comment]
I should have asked first if there are some places to ask questions like the Discord channel instead of opening a formal issue. Thanks for the link! It will definitely help me out if I have other problems.
