### ISSUE TITLE
[BUG] core does not execute ns2-mobility-scripts correctly

### ISSUE THREAD

**Issue by CryptoCopter** [coreemu/core#372]
**Describe the bug**
Version 5.3 seems to have introduced a regression that prevents core from correctly executing ns2 movement scripts.

I built a sample configuration with a movement script generated with bonnmotion using the RandomWaypoint model and tested it with all core versions since 5.2.0. 
Until version 5.2.2 the behaviour was as expected in that all the nodes moved as specified in the movement script.
Starting with version 5.3.1 (since 5.3.0 didn't seem to work at all), when executing a simulation with that same movement model, only a single node will move while all others remain static.

**To Reproduce**
1. Import sample config https://gist.github.com/CryptoCopter/e0c909640af91077c82b10e61d3abfdf
2. Fix path to ns2-script (because absolute paths...)
3. Run simulation

**Expected behavior**
Excpected behaviour (pre version 5.3): All nodes move
Broken behaviour (since version 5.3): Only a single node moves

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 Docker container on Arch Linux host
 - CORE Version 5.2 - 6.0

**Comment by bharnden** [comment]
Thanks, will look into this.

**Comment by bharnden** [comment]
Was able to find the issue and fix this one develop, thanks for your thorough input on this matter.

**Comment by CryptoCopter** [comment]
thanks for the quick fix!

Do you happen to have an ETA for a point-release containing this fix?

**Comment by bharnden** [comment]
I was hoping to make one soon, I would say by this weekend to be safe, but maybe earlier.

**Comment by CryptoCopter** [comment]
That would be great, thanks!
