### ISSUE TITLE
Can we use any python scripts(like corelocation.py, mobility.py) to move the nodes in real time in core-GUI? 

### ISSUE THREAD

**Issue by ChengDaHaI** [coreemu/core#376]
As stated in the title, can we run python scripts to simulate a wireless network and show the movement of nodes in core-gui?

Thanke you

**Comment by bharnden** [comment]
This section of the documentation speaks to your question:
http://coreemu.github.io/core/usage.html#mobility-scripting

There is also gRPC, similar to the TLV API, but that isn't documented heavily yet.

**Comment by mzy2240** [comment]
One thing may relate to this issue, when using python to create a session and instantiate it, how can I enable the grpc service? Or is it enabled by default? @bharnden

**Comment by bharnden** [comment]
You would need to start the CoreGrpcServer class, then you could use it. It is not a part of CoreEmu itself.

https://github.com/coreemu/core/blob/master/daemon/core/api/grpc/server.py

**Comment by mzy2240** [comment]
Thanks! I guess the GUI is communicating with the backend CoreEmu service via grpc, does that mean when I start the core-daemon service in the prompt, the grpc is enabled by default? Otherwise how does the GUI track the change of the emulation?

**Comment by bharnden** [comment]
That is correct.

The old GUI however uses an older formatted API based on TLV data.

The new python GUI in BETA uses gRPC.
