### ISSUE TITLE
core-daemon - failed to start

### ISSUE THREAD

**Issue by jakubkameleon** [coreemu/core#382]
Could I ask for help? I have installed core_6.1.0_amd64.deb on my Debian 10, Gui works fine but I have problem with start daemon.

`root@ThinkPad:~# service core-daemon status 
● core-daemon.service - Common Open Research Emulator Service
   Loaded: loaded (/lib/systemd/system/core-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-02-28 13:38:10 CET; 1s ago
  Process: 6822 ExecStart=/usr/local/bin/core-daemon (code=exited, status=1/FAILURE)
 Main PID: 6822 (code=exited, status=1/FAILURE)

Feb 28 13:38:10 ThinkPad systemd[1]: Started Common Open Research Emulator Service.
Feb 28 13:38:10 ThinkPad core-daemon[6822]: Traceback (most recent call last):
Feb 28 13:38:10 ThinkPad core-daemon[6822]:   File "/usr/local/bin/core-daemon", line 16, in <module>
Feb 28 13:38:10 ThinkPad core-daemon[6822]:     from core import constants
Feb 28 13:38:10 ThinkPad core-daemon[6822]: ModuleNotFoundError: No module named 'core'
Feb 28 13:38:10 ThinkPad systemd[1]: core-daemon.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 13:38:10 ThinkPad systemd[1]: core-daemon.service: Failed with result 'exit-code'.
`

**Comment by siliconja** [comment]
According to  `dpkg -c core_6.1.0_amd64.deb` we have Python 3 libraries installed to `/usr/local/lib/python3.6/dist-packages/core/.`

On Debian 10 if you enter `python3`, `import sys`, `print(sys.path)` you get  `/usr/local/lib/python3.7/dist-packages` etc.

So a quick fix for you would be (noting that `/home/user1/.local/lib/python3.7/site-packages` is in the PYTHONPATH) going to `~/.local/lib/python3.7` and move away `site-packages` and symlink it to the `/usr/local/lib/python3.6/dist-packages` dir.

Another option would be to export a new PYTHONPATH including that python3.6 path (even though you have python3.7) and run core-daemon from the terminal.

**Comment by jakubkameleon** [comment]
Hi thanks for your repaly, I move site-packages (directory) and created symlink  at the same name `/home/pretender/.local/lib/python3.7/site-packages` to `/usr/local/lib/python3.6/dist-packages ` but nothing happend :(. Should I change something else to force debian use python3.6? 

About second option how to export new PYTHONPATH and run core-daemon with this path?

**Comment by siliconja** [comment]
OK, to get this core_6.1.0_amd64.deb working under Debian 10, I had to do the following steps:
```
sudo -s
export PYTHONPATH="/usr/local/lib/python3.6/dist-packages`python3 -c 'import sys;print(":".join(sys.path))'`"
apt install python3-netaddr
pip3 install fabric
core-daemon
```
At this point I could run `core-gui` from a non-root terminal OK.

Now to get `coretk-gui` working... I tried `sudo apt install python3-pil.imagetk`, adjusting the PYTHONPATH as above, and then running `coretk-gui`. Under Edit > Preferences you are going to want to change your terminal. I tried gnome-terminal but that wasn't working for some reason (but cut-n-paste command from error message was working.)

**Comment by jakubkameleon** [comment]
Thank you for your time, I have followed your steps on my Debian 10 and Ubuntu 18.04(virtualbox) and the result is the same, still can't run core-daemon :(. I wonder if I forget something or what???

**Comment by siliconja** [comment]
OK so now we can see it is finding the CORE Python 3 modules but missing some dependencies. You can install these dependencies by downloading this requirements.txt file: https://github.com/coreemu/core/blob/master/daemon/requirements.txt

```sudo pip3 install -r requirements.txt```

(That is probably why my Debian 10 worked and yours did not, because I had previously issued the pip3 commands for building from source.)

**Comment by jakubkameleon** [comment]
Great now it works :) Thank you!!!

**Comment by siliconja** [comment]
Even though this is closed, we should document concisely the steps needed to install the 6.1.0 release on Debian 10.x
