### ISSUE TITLE
[BUG] can't launch gnome-terminal from coretk-gui

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#387]
**Describe the bug**
Install of CORE 6.1.0 under Ubuntu 18.04. Running coretk-gui. Double-click a node, and the default terminal setting of $TERM resolves to xterm-256color, which is not a valid command.

Change terminal preference to the gnome-terminal setting.

Double-click a node, and a new gnome-terminal pops up with an error: "There was an error creating the child process for this terminal" 'Failed to execute child process "/usr/local/bin/vcmd -c /tmp/pycore.1/n1 -- /bin/bash" (No such file or directory)'

Workaround: change to xterm.

**To Reproduce**
See description.

**Expected behavior**
gnome-terminal should launch with a node shell.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
I'm submitting a PR to fix this. It is a quoting issue.

**Comment by bharnden** [comment]
The new core gui will search for terminals we know about and use the first one found.

Fixed on develop.
