### ISSUE TITLE
[BUG] restart of core-daemon not handled well by coretk-gui

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#389]
**Describe the bug**
coretk-gui should reconnect to the core-daemon as needed, and handle the case where the connection gets interrupted.

**To Reproduce**
1. sudo core-daemon
2. coretk-gui
3. draw some nodes
4. stop core-daemon (CTRL+C), then start it again
5. from GUI, File > Save. You get an error dialog "GRPC Not Found" "session 1 not found"
6. click Session > Sessions > Connect to connect to daemon. Your scenario is now erased! No saving for you.

**Expected behavior**
coretk-gui should silently reconnect to a restart core-daemon, and proceed as if nothing happened. The old core-gui would reconnect.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
some changes to help support dealing with this on develop
