### ISSUE TITLE
[BUG] coretk-gui changing IP address from node configuration dialog does nothing

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#391]
**Describe the bug**
Can't change the IP address of a node.

**To Reproduce**
1. start coretk-gui
2. place PC and switch nodes, and link them together
3. double-click on PC to configure it
4. change the IPv4 address and click "Apply"
5. nothing changes in GUI, and when you re-enter the configuration dialog, old value still exists

**Expected behavior**
Should be able to change IP addresses of nodes.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
should be fixed on develop
