### ISSUE TITLE
[BUG] setting no IP address for an interface causes floating "/0" labels on link

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#392]
**Describe the bug**
The coretk-gui erroneously shows "/0" labels above a link if you delete the IP addresses.

**To Reproduce**
1. coretk-gui: draw a link between two routers
2. delete the IP addresses from one of the router interfaces 

Note: due to bug #391 you'll need to edit the XML scenario. Save the XML scenario file edit open with text editor.

Change:
`      <interface_one id="0" name="eth0" ip4="10.0.0.1" ip4_mask="24" ip6="2001::1" ip6_mask="64"/>
`
to this:
`      <interface_one id="0" name="eth0"/>
`

3. open the updated XML from coretk-gui
4. note the two floating "/0" labels above the link

**Expected behavior**
No numbers should be displayed if an interface has no IP addresses.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
Just to check, there is a desire to have no ip4/ip6 settings? Changes for allowing modifying addresses now expect them to exist, I would have to look at tweaking that a bit, if so.

**Comment by siliconja** [comment]
Correct. Sometimes you want no IPv4 address(es). Sometimes no IPv6. Sometimes neither statically assigned (e.g. using DHCP client service).

Additionally, the old GUI has a feature to quickly remove all: "Tools" > "IP addresses..." > "Remove IPv6":"all" button (or remove from "selected" group of nodes).

**Comment by bharnden** [comment]
Alright thanks, will look to clear that up then.

**Comment by bharnden** [comment]
should be fixed on develop as well as the display related issues.
