### ISSUE TITLE
[BUG] marker annotations persist between sessions

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#393]
**Describe the bug**
When drawing annotations, marks drawn by the marker tool persist across sessions. Oval/square/text are cleared when starting a new canvas, but not markings.

**To Reproduce**
1. start new scenario in coretk-gui
2. draw something using the marker tool
3. choose File > New Session
4. markings persist on new canvas; all other annotations (and nodes, links, etc.) are cleared

**Expected behavior**
Marker markings should be removed with File > New Session. And when opening new file, etc.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
fixed on develop
