### ISSUE TITLE
[BUG] clicking on toolbar rapidly sometimes causes entire coretk-gui to freeze

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#394]
**Describe the bug**
The coretk-gui tends to freeze for longish periods of time

**To Reproduce**
1. start a scenario
2. interact with the toolbar
3. clicking rapidly between buttons while it is communicating with core-daemon seems to trigger this

coretk-gui terminal has exceptions like this:
```2020-03-03 08:40:18,026 - INFO - coreclient:set_metadata - set session metadata {'canvas': '{"wallpaper": null, "wallpaper-style": 1, "gridlines": true, "fit_image": false, "dimensions": [1000, 750]}', 'shapes': '[]'}, result: result: true

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/usr/local/lib/python3.6/dist-packages/core/gui/toolbar.py", line 257, in start_callback
    total = time.perf_counter() - self.time
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Expected behavior**
No GUI lock-ups.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
May be worth revisiting if this is still an issue or we see similar exception in the recent develop branch code.

**Comment by bharnden** [comment]
Will close for now, can reopen and revisit if it shows itself again and hopefully we can catch any exceptions or errors related to this.
