### ISSUE TITLE
[FEATURE] have Save and Save As  menu items like other programs

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#395]
**Is your feature request related to a problem? Please describe.**
When you click "Save" it invokes a "Save As" dialog. But not all the time -- sometimes it just saves over the existing file (<-- actually this appears to be a BUG not RFE; if you open a file, the filename sticks and you can't save as something else). This is confusing for new users. Then there are extra steps if you want to save minor changes to a file (having to click the same name again, then yes to the overwrite prompt.)

**Describe the solution you'd like**
Have separate "Save" and "Save As..." menu items.

If they MUST be combined as one item (current situation), the item should at least be named "Save As...".

**Describe alternatives you've considered**
(see above)

**Additional context**
Save behavior seems to be broken. Try loading, changing, saving versus starting new session, changing, saving...

**Comment by bharnden** [comment]
Will work to get this to Save/Save As

**Comment by bharnden** [comment]
fixed on develop
