### ISSUE TITLE
[BUG] coretk-gui docker node type cannot be saved

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#396]
**Describe the bug**
Any changes to a docker node are not saved. The node re-appears as a custom node, without any settings.

**To Reproduce**
1. place a docker node
2. save the scenario
3. open the scenario
4. docker node icon transforms to a custom node type, and all settings are lost

**Expected behavior**
Correct save/load of docker nodes.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.1.0
 - EMANE Version N/A

**Additional context**
(none)

**Comment by bharnden** [comment]
fixed on develop
