### ISSUE TITLE
[BUG] WLAN bridge ebtable policy initialization

### ISSUE THREAD

**Issue by bharnden** [coreemu/core#406]
wlans started with connected nodes who are not connected to each other will not properly initiate the default drop route for the bridge, allowing communication to still work.

**Comment by bharnden** [comment]
@siliconja this appears to be related to the changes made to account for your multiple sessions at once.

I could add an ebtable change call in the WLAN startup method, which resolves this issue. Not sure if that will still cause issues for what you were experiencing. But, this is currently a problem.

**Comment by bharnden** [comment]
I looked at the history and it is definitely related to those changes.

**Comment by siliconja** [comment]
Can you post the error or exception?

Without the ebtables-for-WLAN-only, you get ebtables for ALL bridges (hub, switch), and then you can run into serious problems.

**Comment by bharnden** [comment]
It is not an error or exception. It is the fact that the bridge chain with a DROP policy does not get created for the bridge representing the WLAN.

To repeat, create a session with 2 MDR nodes connected to a WLAN, but place them at a distance that would not be connected, then start the session.

You will be able to ping between the nodes, etc, since chain representing the bridge is not added with a default policy of DROP.

**Comment by bharnden** [comment]
I will add a ebtables change event in wlan startup, which resolves this problem. This should hopefully avoid issues you were running into before when it tried to execute the ebtable commands directly.

**Comment by bharnden** [comment]
Fixed on develop
