### ISSUE TITLE
[FEATURE] Load an Scenario XML and run via CLI or API

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#412]
**Is your feature request related to a problem? Please describe.**

I am currently using the CORE GUI to create a simulation. Once I create it on the GUI, I am "Saving as XML" with the intent to reload the XML and start the simulation again.

What I need to do is take that exported XML and reload it into CORE, but via CLI or an API only. Then, via CLI/API, start the session as well (green run button). 

**Describe the solution you'd like**
If this feature is already available, could you direct me to it?

- Load an XML scenario via API/CLI
- Start session via API/CLI

**Describe alternatives you've considered**
I have tried digging around the documentation, but couldn't find what I was looking for when searching for "run", "xml", "session", etc. I figured I'd ask here since it is unknown to me if this is an actual feature or not.

If this is not a feature, perhaps I could program it in? If so, where in the code base should I extend a load and start session feature?

**Additional context**

**Comment by bharnden** [comment]
This would be one way, leveraging the gRPC API.

This would allow you to switch to the created session within the "core-gui" if that is desired.
```python
from core.api.grpc import client


def main():
    core = client.CoreGrpcClient()
    with core.context_connect():
        core.open_xml("/path/to/file/file.xml", start=True)


if __name__ == "__main__":
    main()
```

If you wanted to do it directly in code, this would pause the xml file running, when the program exits auto shutdown will occur, you will not be able to view this in the GUI, but could poke around using vcmd.
```python
from core.emulator.coreemu import CoreEmu


def main():
    coreemu = CoreEmu()
    session = coreemu.create_session()
    session.open_xml("/path/to/file/file.xml", start=True)
    input("press enter to auto shutdown")


if __name__ == "__main__":
    main()
```

**Comment by bharnden** [comment]
let me know if more is needed
