### ISSUE TITLE
[BUG] OSPF Link State Observer widget not working for FRR

### ISSUE THREAD

**Issue by smvoigt** [coreemu/core#413]
**Describe the bug**
When using FRR OSPFv2 instead of quagga OSPFv2 the Widgets|Adjency|OSPFv2 link state observer does not work. It works when Quagga OSPFv2 is used.

**To Reproduce**
1. Enable and configure **FRRzebra** and **FRROSPFv2** services on routers in a topology
2. Enable the Widgets|Adjacency|OSPFv2 widget
3. Start the emulation
4. Note that OSPFv2 states are not drawn on the topology

**Expected behavior**
The OSPFv2 states should appear the same as for the case where the quagga **zebra** and **OSPFv2** services are used

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - CORE Version 6.2
 
**Additional context**
The FRR and Quagga OSPF commands produce identical output from "show ip ospf neighbors" so it is not that.

**Comment by bharnden** [comment]
fixed on develop
