### ISSUE TITLE
New Core/Emane interface

### ISSUE THREAD

**Issue by jmk479** [coreemu/core#417]
We are trying to update our CORE/EMANE to the latest version for our project.  We are using CORE to model a communication network in a resource sharing environment.  We had it working with a previous version of core/emane.  However, during the upgrade to the latest version, I keep getting this error message:

Connecting to ANVEL
Traceback (most recent call last):
  File "syncANVEL_EMANE3.6.py < Caution-http://syncANVEL_EMANE3.6.py > ", line 165, in <module>
    main()
  File "syncANVEL_EMANE3.6.py < Caution-http://syncANVEL_EMANE3.6.py > ", line 111, in main
    mySession.instantiate()
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/session.py", line 1448, in instantiate
    if self.emane.startup() == self.emane.NOT_READY:
  File "/usr/local/lib/python3.6/dist-packages/core/emane/emanemanager.py", line 316, in startup
    r = self.setup()
  File "/usr/local/lib/python3.6/dist-packages/core/emane/emanemanager.py", line 275, in setup
    netidx = self.session.get_control_net_index(otadev)
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/session.py", line 1641, in get_control_net_index
    if dev[0:4] == "ctrl" and int(dev[4]) in [0, 1, 2, 3]:
TypeError: 'NoneType' object is not subscriptable

I have touched nothing in the emanemanemanger.py.  My code has not change drastically between the two versions.  The only changes I had to make where some updates to the API calls to reflect changes in the API of CORE.  I did notice a chance in the emanemanager.py around line 275.  That line was not there in the older version we are using which may be causing the issue.  Do I have to add something now to my session to properly get the ota device?  Is there a step I am missing here?

Is there  specific version of emane that I should be using with CORE?  

Any assistance you can provide would be greatly appreciated.

Thank you.

**Comment by bharnden** [comment]
This looks to be a common error message I have seem with the EMANE python bindings are not present. Potentially this shifted to python3 and you were on 2 before? Did you install the python3 emane bindings?

```shell
# open python3 interpreter
python3

# validate emane bindings
import emane
```

**Comment by jmk479** [comment]
Hi,

That seems to be my issue.  I am getting the module not found error.  What is the best way to set the bindings properly?  I have verified my install of emane.  

emane is installed in /usr/bin.  I did uninstall emane and reinstall it to verify the python3 .deb files were installed.  I have confirmed my default version of python is 3.6.3.   /usr/bin is within my PATH.  

Thank you.

**Comment by jmk479** [comment]
Nevermind, I figured it out.  It was my default python was anaconda python but the emane files were put the system python.  I needed to use /usr/bin/python3 then I was able to import emane just fine.

Now to get anaconda and emane to play nice together :)

Thank you.
