### ISSUE TITLE
[FEATURE]Support physical WIFI adaptor emulation

### ISSUE THREAD

**Issue by alexhuhaiping** [coreemu/core#419]
Core doesn't support emulating physical WIFI adaptor to connect to a real AP.
Do you have any plan to support it or any other suggestion?

**Comment by bharnden** [comment]
Are you thinking of something along the lines of Linux wireless drivers and the 80211_hwsim and using hostapd? Or did you have something else specifically in mind?

In general there has been some thought to look at trying to add something using the above, but nothing in the near term is likely.

**Comment by bharnden** [comment]
Will close for now without further feedback, feel free to comment and let me know otherwise, thanks.
