### ISSUE TITLE
[BUG] IPv6 Addresses disappear with FRR

### ISSUE THREAD

**Issue by smvoigt** [coreemu/core#421]
**Describe the bug**
When FRR is used the IPv6 addresses assigned to an interface disappear.

**To Reproduce**
1. Create a simple topology (which has IPv6 addresses on the interfaces)
2. Enable and configure FRRzebra, FRROSPFv2 and FRROSPFv3 services on routers in a topology
3. Start the emulation
4. Open a vtysh on a node and run "show interface eth0" and "show run"
```
n1# sh int eth0
Interface eth0 is up, line protocol is up
  Link ups:       1    last: 2020/04/06 16:43:08.47
  Link downs:     1    last: 2020/04/06 16:43:07.46
  vrf: Default-IP-Routing-Table
  index 838 metric 0 mtu 1500 speed 10000 
  flags: <UP,BROADCAST,RUNNING,MULTICAST>
  Type: Ethernet
  HWaddr: 00:00:00:aa:00:00
  inet 10.0.0.1/24
  inet6 fe80::200:ff:feaa:0/64
  Interface Type Other
  Link ifindex 839(Unknown)
n1# sh run
Building configuration ...

Current configuration:
!
frr version 6.0.2
frr defaults traditional
hostname n1
log syslog informational
service integrated-vtysh-config
!
interface eth0
 ip address 10.0.0.1/24
 ipv6 address 2001::1/64
!
```
5. Observe that the configured IPv6 address does not exist.
6. View the node log and observe the "ip address add {ipv6 address} dev eth0" command has been issued
7. Open a bash shell on the same node and run ifconfig eth0.
8. Observe that the configured ipv6 address does not exist.
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::200:ff:feaa:0  prefixlen 64  scopeid 0x20<link>
        ether 00:00:00:aa:00:00  txqueuelen 1000  (Ethernet)
        RX packets 354  bytes 37171 (37.1 KB)
        RX errors 0  dropped 34  overruns 0  frame 0
        TX packets 268  bytes 24420 (24.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
**Expected behavior**
The configured IPv6 should not disappear. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - CORE Version 6.2
 - EMANE Version 

**Additional context**
This IPv6 addresses disappear because the default behaviour for the kernel is to remove IPv6 addresses on if down. The frrboot.sh script runs:
``` bash
ip link set dev eth0 down
sleep 1
ip link set dev eth0 up
ip link set dev eth1 down
sleep 1
ip link set dev eth1 up
```
which removes the IPv6 addresses. 

There is a kernel setting which controls this behaviour:

keep_addr_on_down - INTEGER
	Keep all IPv6 addresses on an interface down event. If set static
	global addresses with no expiration time are not flushed.
	  >0 : enabled
	   0 : system default
	  <0 : disabled
Default: 0 (addresses are removed)

https://github.com/FRRouting/frr/blob/master/doc/user/Useful_Sysctl_Settings.md recommends setting this, but if it hasn't been applied it is hard to debug what is going on.

I propose using sysctl to set this when the interface is created:

e.g. 
``` python
self.run(f"{SYSCTL_BIN} -w net.ipv6.conf.{device}.keep_addr_on_down=1")
```

This would also resolve #141

**Comment by bharnden** [comment]
fixed on develop
