### ISSUE TITLE
[FEATURE] Add IS-IS to FRR service

### ISSUE THREAD

**Issue by smvoigt** [coreemu/core#423]
**Is your feature request related to a problem? Please describe.**
FRR supports IS-IS. It would be good to configure FRR IS-IS in CORE

**Describe the solution you'd like**
Similar config to the OSPFv2 and OSPFv3 configs. It should also generate a unique net id.

**Describe alternatives you've considered**
You can put IS-IS config directly in frr.conf, but you have to manually set unique IDs and manually start isisd.

**Additional context**

**Comment by bharnden** [comment]
added on develop
