### ISSUE TITLE
[BUG] Noticing python commands sent to nodes sometimes don't have output

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#434]
**Describe the bug**
I am noticing that in Python, some commands I am sending to nodes produce no output. However, when I am running Python in debug mode, there is output. 

**To Reproduce**
Set up core grpc api in python:
```
core = client.CoreGrpcClient()
with core.context_connect():
   core.open_xml(xml_network, start=True) #xml_network is attached at bottom
   ... find node 10.0.1.10 and call it node_id ...
   ... also run iperf -s -D on node 10.0.2.20 ...
   cmd = f"iperf3 -t 10 -c 10.0.2.20"
   out= core.node_command(session_id, node_id, cmd)
   logging.info("`%s` output:\n`%s`", cmd, out.output)
```

When running python in normal mode (i.e., not debug mode) I get this:
```
INFO:root:Running command `iperf3 -t 10 -c 10.0.2.20` on CVTSC-DDG1
INFO:root:`iperf3 -t 10 -c 10.0.2.20` output:
```

**Expected behavior**
When I run in debug mode and go through slower (or even when I manually shell into the node)

```
INFO:root:Running command `iperf3 -t 10 -c 10.0.2.20` on NODE_X
INFO:root:`iperf3 -t 10 -c 10.0.2.20` output:
`Connecting to host 10.0.2.20, port 5201
[  4] local 10.0.1.10 port 39528 connected to 10.0.2.20 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   181 MBytes  1.51 Gbits/sec  308   1.64 MBytes       
[  4]   1.00-2.00   sec   178 MBytes  1.49 Gbits/sec    0   1.64 MBytes       
[  4]   2.00-3.00   sec   181 MBytes  1.52 Gbits/sec    4   1.64 MBytes       
[  4]   3.00-4.00   sec   185 MBytes  1.55 Gbits/sec    0   1.64 MBytes       
[  4]   4.00-5.00   sec   180 MBytes  1.51 Gbits/sec   15   1.64 MBytes       
[  4]   5.00-6.01   sec   178 MBytes  1.48 Gbits/sec    3   1.64 MBytes       
[  4]   6.01-7.01   sec   180 MBytes  1.51 Gbits/sec    8   1.64 MBytes       
[  4]   7.01-8.01   sec   179 MBytes  1.50 Gbits/sec    9   1.64 MBytes       
[  4]   8.01-9.00   sec   180 MBytes  1.52 Gbits/sec    0   1.64 MBytes       
[  4]   9.00-10.00  sec   180 MBytes  1.51 Gbits/sec    8   1.64 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.76 GBytes  1.51 Gbits/sec  355             sender
[  4]   0.00-10.00  sec  1.76 GBytes  1.51 Gbits/sec                  receiver

iperf Done.`
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - CORE Version [e.g. 6.3.0]

**Additional context**

Instead of python piping back the stdout of the command from the node into a variable, I'd be fine if the command's stdout was dumped to a file. Not sure if there is a capability for that.

[UC3.xml.txt](https://github.com/coreemu/core/files/4513295/UC3.xml.txt)

**Comment by esend7881** [comment]
I found a way around this by re-trying the command until a response is had. This is a 10 second command and I notice it would break out within 1 second, which told me the command may be failing at some point, however after a few retries, the command successfully goes through.

**Comment by bharnden** [comment]
I would still lean on there being some other issue going on, until a specific error can be specified, will close for now.

In the future we could likely add the status code to the response to at least mark the command as failed specifically.

**Comment by lemon-lyman** [comment]
I'm having the same issue with the exact same command. However, retrying the command still doesn't seem to work.

Ubuntu 18.04
Core 6.5.0

**Comment by bharnden** [comment]
I would recommend trying the latest, just to be on the same page.

But in 6.5.0 there is a `return_code` field as well in the response, is that also coming back 0?

Potentially providing exactly what you are doing can help.

**Comment by lemon-lyman** [comment]
Thanks for the response.

Unfortunately, upgrading CORE might not be possible atm due to dependencies. However, I was able to get a little more info by changing the iperf command to f"iperf3 --logfile iperf_log.txt -t 10 -c {address}". This command still returned no useful output, but the log file shows: "iperf3: error - unable to connect to server: Network is unreachable". The full script is:

```
import time

from core.api.grpc import client
from core.api.grpc.core_pb2 import Node, NodeType, Position, SessionState


interface_helper = client.InterfaceHelper(ip4_prefix="10.83.0.0/24")

core = client.CoreGrpcClient()
with core.context_connect():

    response = core.create_session()
    session_id = response.session_id
    response = core.set_session_state(session_id, SessionState.CONFIGURATION)

    # Create Nodes
    position = Position(x=200, y=200)
    wlan = Node(type=NodeType.WIRELESS_LAN, position=position)
    response = core.add_node(session_id, wlan)
    wlan_id = response.node_id

    position = Position(x=100, y=100)
    node1 = Node(model="mdr", position=position)
    response = core.add_node(session_id, node1)
    node1.id = response.node_id
    interface = interface_helper.create_interface(node1.id, 0)
    response = core.add_link(session_id, node1.id, wlan_id, interface)

    position = Position(x=100, y=100)
    node2 = Node(model="mdr", position=position)
    response = core.add_node(session_id, node2)
    node2.id = response.node_id
    interface = interface_helper.create_interface(node2.id, 0)
    response = core.add_link(session_id, node2.id, wlan_id, interface)

    response = core.set_session_state(session_id, SessionState.INSTANTIATION)

    # Start iperf server
    server_resp = core.node_command(
        session_id, node1.id, f"iperf3 -s", wait=False)

    # Start iperf client
    address1 = interface_helper.create_interface(node1.id, 0)
    cmd = f"iperf3 --logfile iperf_log.txt -t 10 -c {10}"
    client_resp = core.node_command(session_id, 3, cmd)

    # Check iperf log
    cat = core.node_command(session_id, 3, f"cat iperf_log.txt")
    [print(line) for line in cat.output.split("\n")]

    core.delete_session(session_id)
```

**Comment by bharnden** [comment]
That sounds like the case of the following. The MDR nodes are using a routing protocol to discover each other so that they can talk.

My assumption is, that you are attempting to talk to a server that has not been formally discovered yet.

You could validate this, just to verify that the command can work, by creating a simple 2 node scenario with them connected by a direct link using nodes with `model="PC"`. These would not have that discovery delay and should hopefully show the command working.

I can only assume at the moment that potentially iperf3 may not return a non 0 exit status, which ideally should be shown in the command due to said logged failure. That would be something else to verify.

If you did not delete the session at the end, you could also manually run commands and verify the situation within the nodes, after your script completes.

The following would jump to the shell of a given node, then you could manully run commands and poke around to validate things.
```
vcmd -c /tmp/pycore.<session id>/<node name>
```

**Comment by bharnden** [comment]
Also making sure you have OSPF MDR installed for the case above you are trying to run, or they will not discover each other. That would probably end up with other errors I imagine, but just another thing to validate.

**Comment by bharnden** [comment]
I narrowed it down your script is not using an address to connect at all.

```python
address1 = interface_helper.create_interface(node1.id, 0)
cmd = f"iperf3 --logfile iperf_log.txt -t 10 -c {10}"
```

```python
address1 = interface_helper.create_interface(node1.id, 0)
cmd = f"iperf3 --logfile iperf_log.txt -t 10 -c {address1.ip4}"
```
The response of the command ran was showing a `return_code` of 1 for error as well

**Comment by lemon-lyman** [comment]
Oh wow, that's a silly mistake. Script works as expected now. Thanks for your help!
