### ISSUE TITLE
[BUG] Need to manually specify ip route in CentOS but not in Ubuntu

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#437]
**Describe the bug**
When running traffic in my network in CentOS, I notice nothing flows unless I manually issue a ```ip route add 10.0.1.0/24 via 10.0.2.1 dev eth0``` command to my node-1. If I don't do this, data does not flow.

In Ubuntu, this does not happen.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Run CORE on CentOS 7
3. Run CORE-GUI
4. Load the attached XML network
5. Start network
6. Establish traffic between "N2" and "WW-N3"
7. Notice nothing flows
8. Then add route manually by issuing this command into N2: ip route add 10.0.1.0/24 via 10.0.2.1 dev eth0`
9. Then notice traffic flow

- For Ubuntu, do all the same steps, except notice you do not need to run the `ip route add` command.

**Expected behavior**
Data should flow in CentOS without needing to run the `ip route add...` command.

**Screenshots**
No traffic flowing prior to manually setting up route:
![image](https://user-images.githubusercontent.com/5004148/80153779-09c72200-8573-11ea-82fc-9afb5e734384.png)

After manually adding route:
![image](https://user-images.githubusercontent.com/5004148/80154516-96beab00-8574-11ea-807b-b9d13aa7d762.png)

On Ubuntu, I don't need to change anything and data flows:
![image](https://user-images.githubusercontent.com/5004148/80155110-d33ed680-8575-11ea-9413-d4448127fa18.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - CORE Version 6.3.0

**Additional context**

**Comment by bharnden** [comment]
Are you 100% sure these are both using the same exact version of CORE?

Can you look at the generated "defaultroute.sh" file on that node, that would normally set that up?

It is likely related to an update was trying to change behavior in how default route was being configured. Seeing this scenario, it is potentially something to still look at what would be most ideal.

**Comment by bharnden** [comment]
There is a change in logic on the develop branch that would solve this issue from occurring. Although in your case your issues were likely due to version differences, with different behavior.
