### ISSUE TITLE
Installing CORE 4.8 with Python3.6

### ISSUE THREAD

**Issue by ChengDaHaI** [coreemu/core#438]
Hi,

Due to specific project requirements, i have to install CORE4.8 to test my code. I try to install core4.8 from source code with Python3.6 on Ubuntu16.04. I faces many errors related to python binding with C, like "netnsmodule.c:85:12: error: implicit declaration of function ‘PyInt_FromLong’".

So, i just wonder can CORE4.8 be installed with python3?

Thanks,

**Comment by bharnden** [comment]
I am sorry to hear 4.8 is a requirement, but 4.8 cannot be installed with python3, only python 2.
