### ISSUE TITLE
[BUG] DEB-Package broken

### ISSUE THREAD

**Issue by CryptoCopter** [coreemu/core#442]
**Describe the bug**
When installing CORE via the official DEB-package, it appears to not install the python library to the python path.

**To Reproduce**
1. Clean install of Ubuntu 20.04 (server)
2. Download `core_6.3.0_amd64.deb` from GitHub releases
3. Install via `apt install ./core_6.3.0_amd64.deb`
4. Run `core-daemon`
5. See error:
```
Traceback (most recent call last):
  File "/usr/local/bin/core-daemon", line 16, in <module>
    from core import constants
ModuleNotFoundError: No module named 'core'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (server)
 - CORE Version 6.3.0

**Comment by bharnden** [comment]
Potentially your distribution that supports deb packages does not have the path being used?

see where files go:
```shell
dpkg -c core.deb
```

see your python paths:
```shell
python3 -m site
```

**Comment by CryptoCopter** [comment]
okay, so as it turns out, the package installs the library to `/usr/local/lib/python3.6/`, so this package would only work with Python 3.6 and no other (minor) version, I guess.

Ubuntu 20.04 ships with Python 3.8 which by default has the following paths:

```
sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/python3.8/lib-dynload',
    '/usr/local/lib/python3.8/dist-packages',
    '/usr/lib/python3/dist-packages',
]
```

Would you consider maybe installing to `/usr/lib/python3`, since that would be independent of the exact python version?

**Comment by bharnden** [comment]
Seems like that could work for Ubuntu, checking CentOS they don't appear to use something like that.

Will take a look into this, alternatively installing from source can be done, albeit with a few more dependencies.

**Comment by CryptoCopter** [comment]
well, the current stable Debian uses Python 3.7, so as is you deb package probably won't work on any current debian derived system

**Comment by bharnden** [comment]
Sure, was only concerned with Ubuntu at the time and 20 had not dropped yet. For the next release we will look into leveraging python3 as you noted, assuming Debian has that as well, then it should help there too. Also modifying the prefix to not be /usr/local.

**Comment by CryptoCopter** [comment]
okay, thanks!

While we are at it: there are several dependencies which CORE needs to run but which are not declared by the package, so currently you need to try to stat the daemon, have it fail, find the correct python package & repeat.

These packages are:
```
python3-netaddr
python3-grpcio
python3-protobuf
python3-fabric
python3-decorator
python3-lxml
python3-pyproj
```

**Comment by bharnden** [comment]
True, these are noted in the requirements.txt file. A lot of distributions, including Ubuntu 18 do not have some of the packages available to depend on that. Also depending on the system packages can result in version issues. Moving to trying to package a venv could be a path to look at, but there are still issues in dealing with the python version being used, although it resolves the python dependencies and version problems.

The install.sh script in the root of the repo can also be used to help automate an installation, including OSPF-MDR, which is needed for routing nodes by default.

**Comment by bharnden** [comment]
Packages may go away as we look to resolve various complications from installation by way of #486
