### ISSUE TITLE
Python Scripting Routers

### ISSUE THREAD

**Issue by JoshuaSFryer** [coreemu/core#445]
Hello,
I am trying to implement a network identical to the one set up in this image:

![image](https://user-images.githubusercontent.com/22202445/81423951-2a6eaa80-9123-11ea-9be1-ea7ba736e662.png)
(image mirror: https://imgur.com/a/BuVVU0y)

Two subnets, isolated from each other, connected via wireless network. This is desired because I want to be able to tune the connection properties (latency, jitter, etc) to simulate two sites with a wireless connection between them.

This network works when implemented in the GUI, but I need to create it with the Python API, and none of the examples have included how to set up routers. I have poked around in the source and read the documentation there, but I still cannot seem to get this working and am at a loss as to how to do this correctly. Any help would be greatly appreciated.
Thank you

**Comment by bharnden** [comment]
Is your goal with scripting more to really need to create everything? or is the desire just to be able to script changing link values?

Just changing the link values may potentially be an easier thing alone, but both can be possible.

The other factor would be if you desire to use the GUI at all. Since if you leveraged the gRPC API, you could then join and see the session created in the GUI.

**Comment by JoshuaSFryer** [comment]
The aim is that CORE will be used to simulate poor network conditions, with message queues running on each machine, communicating with each other. The goal with scripting is to make it so that the whole application can be run on AWS servers instead of relying on a GUI to implement the setup.
So the need is to have the setup in a python script runnable from the CLI, and for the script to use cmd to initiate the message queue processes.

**Comment by bharnden** [comment]
This is a small example for creating an MDR node as seen in your picture. The top level nodes in the GUI are all of type NodeTypes.DEFAULT. These nodes are nodes that run services. The services they run are determined by their model, in this case MDR and the OSPF MDR associated services. So the model names just end up being mappings to sets of services to run.

COREs versions of containers do not have file separation, like Docker nodes, on the flip side they would typically be faster to create and get going, but they inherit the file system from your host. So any software you would need to run or execute would need to be installed on the host system.

Depending on the software needed to run, you may need to create a service for it, to mount directories etc, if needed. Which is one of the features a service can help with.

If there is anything else I can try and help expand on, let me know, I'll try my best to help.

```python
import logging

from core.emulator.coreemu import CoreEmu
from core.emulator.emudata import IpPrefixes, NodeOptions
from core.emulator.enumerations import EventTypes

NODES = 2


def main():
    # ip generator for example
    prefixes = IpPrefixes(ip4_prefix="10.83.0.0/16")

    # create emulator instance for creating sessions and utility methods
    coreemu = CoreEmu()
    session = coreemu.create_session()

    # must be in configuration state for nodes to start, when using "node_add" below
    session.set_state(EventTypes.CONFIGURATION_STATE)

    # create mdr node
    options = NodeOptions(model="mdr")
    mdr_node = session.add_node(options=options)

    # shutdown session
    coreemu.shutdown()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
```

**Comment by JoshuaSFryer** [comment]
Thank you for your assistance.
Most of my trouble is coming from creating links between the routers and the PC nodes. In the examples included in the repository, I couldn't find instances of connecting multiple PC nodes to routers and routers to routers; in those examples, such as when connecting directly to WAN, only one interface is provided to the method (that of the new node). However when I try to link up my components: 
* If I only provide the new node's interface, an null exception in thrown deeper in the code, where the method attempts to get the address of the non-supplied second interface
* If I provide both the new node's interface and the router's interface, it works for the first link, (i.e. PC 1 -- router) but upon repeated links (PC 2 -- router), there is an exception thrown because the deeper method calls create_interface on the router's interface, resulting in an error because this entry/'file already exists'.
* If I create a new interface each time, the network apparently builds without error, but when I attempt to run a ping between two PCs, even ones connected to the same router, it always fails with 'destination unreachable'

So in essence, I am having issues now correctly linking up the nodes into the configuration in the image posted above.
I thank you again for your continued effort and patience.

**Comment by bharnden** [comment]
I see, the issue is this, the IpPrefixes helper, attempts to help with creating interfaces, but in a very simple way. Most users are not scripting generally, but there could likely be improvements to helping in this regard in the future.

But from my understanding for your problem. You need to create a new interface pair for each set of nodes, the only way you get around this is when you link all the nodes to a hub/switch to avoid creating unique pairs of interfaces.

I don't think the IpPrefixes class is handling this well and it was a quick helper for the examples more than anything.

But the following should work, given unique data for each case. If there are other exceptions/issues feel free to paste them and I can look into it, when I get time.

```python
options = NodeOptions()
node_one = session.add_node(options=options)
node_two = session.add_node(options=options)

# create node interfaces and link
interface_one = prefixes.create_interface(node_one)
interface_two = prefixes.create_interface(node_two)
session.add_link(node_one.id, node_two.id, interface_one, interface_two)
```

With interfaces being the following data:

```
from core.emulator.emudata import InterfaceData
# unique id
# name opitional, should default to eth$id
# desired ip4/mask
# desired ip6/mask
# desired mac or blank for random, if I recall right
return InterfaceData(
            _id=inteface_id,
            name=name,
            ip4=ip4,
            ip4_mask=ip4_mask,
            ip6=ip6,
            ip6_mask=ip6_mask,
            mac=mac,
        )
```

**Comment by JoshuaSFryer** [comment]
After some experimentation, which is essentially method 3 in my bullet point list, I do get the network to ostensibly be linked, but unfortunately even a ping to nodes on the same router result in Destination Unreachable errors. My code is the following (note that while this code creates two subnets, results are identical to only creating the one):
`# create emulator instance for creating sessions and utility methods
    coreemu = CoreEmu()
    session = coreemu.create_session()

    # must be in configuration state for nodes to start, when using "node_add" below
    session.set_state(EventTypes.CONFIGURATION_STATE)

    # create wlan network node
    wlan = session.add_node(_type=NodeTypes.WIRELESS_LAN)
    wlan_config = {"jitter":"500", "delay": "500"}
    session.mobility.set_model(wlan, BasicRangeModel, wlan_config)

    # create two MDR routers
    router_options = NodeOptions(model="mdr")
    router_options.set_position(20, 20)
    options = NodeOptions()
    options.set_position(0, 0)

    router_1 = session.add_node(options=router_options)
    router_2 = session.add_node(options=router_options)

    # Connect routers to WLAN
    prefixes = IpPrefixes("10.0.0.20/16")
    r1_interface = prefixes.create_interface(router_1)
    r2_interface = prefixes.create_interface(router_2)


    session.add_link(router_1.id, wlan.id, interface_one=r1_interface)
    session.add_link(router_2.id, wlan.id, interface_one=r2_interface)

    i=1
    # Create first subnet
    for _ in range(subnet_1_nodes):
        pc = session.add_node(options=options)
        interface = prefixes.create_interface(pc)
        router_interface=prefixes.create_interface(router_1)
        # router_interface=prefixes.create_interface(router_1, name="r"+str(i))
        session.add_link(pc.id, router_1.id, interface_one=interface, interface_two=router_interface)
        
        print("Linked node " + prefixes.ip4_address(pc) + " to router at " + 
        prefixes.ip4_address(router_1))
        i += 1

    # Create second subnet
    for _ in range(subnet_2_nodes):
        pc = session.add_node(options=options)
        interface = prefixes.create_interface(pc)
        router_interface=prefixes.create_interface(router_2)
        # router_interface=prefixes.create_interface(router_2, name="r"+str(i))
        session.add_link(pc.id, router_2.id, interface_one=interface, interface_two=router_interface)
        
        print("Linked node " + prefixes.ip4_address(pc) + " to router at " + 
        prefixes.ip4_address(router_2))
        i += 1


    # instantiate session
    session.instantiate()

    # get nodes for example run
    first_node = session.get_node(4)
    # last_node  = session.get_node(subnet_1_nodes + subnet_2_nodes + 3)
    last_node = session.get_node(5)

    address = prefixes.ip4_address(last_node)
    #("node %s pinging %s", last_node.name, address)
    print("node " + prefixes.ip4_address(first_node) + " pinging " + address)
    output = first_node.cmd(f"ping -c {ping_count} {address}")
    #output = first_node.cmd(f"traceroute -n -t 0 {address}")
    print(output)

    # shutdown session
    coreemu.shutdown()
`

As a side note, I earlier tried a custom implementation of create_interface designed to avoid name collisions, but since the add_link method uses the native CORE's method to make a new interface, it would appear that I would need to modify CORE's methods for that to be useful.

**Comment by bharnden** [comment]
Your problem in this case is the following, which are some of the things the GUI accounts for when creating links etc.

When a PC node is created in your case, it uses the service DefaultRoute, to add a default route for traffic. But it sets that route to 10.0.0.1 in your example. Yet you have no node that would have that address. Also typically the PC nodes linked to each MDR node would be on a different subnet,

It would look something like this when created in the GUI and that would need to be replicated:

(PC) 10.0.0.20 <--> (MDR) 10.0.0.1 <- wireless link -> (MDR) 10.0.1.1 <-->(PC) 10.0.1.20

**Comment by JoshuaSFryer** [comment]
Thank you for your continued help,
Is there a place or file where I can find all the things that the GUI does account for when linking and doing other significant tasks?

Attached
[subnets-over-wan.txt](https://github.com/coreemu/core/files/4610852/subnets-over-wan.txt)
 is my entire current file; I have hardcoded IP addresses for testing purposes and used my custom interface-creation that allows specification of IP4 addresses and subnet masks so that I can comply with the necessary IP addressing scheme (i.e. the one that the GUI created in the image of the original post). It continues to be unable to find the destination host when pinging. Is my approach wrong; is there a means to arrange the IP addresses in the needed way with IpPrefixes?

**Comment by bharnden** [comment]
How the GUI operated is more tribal knowledge than anything, that I have had to figure out over time and with trial and error in the UI.

Assuming you can use the GUI, it may be easy enough to mock your scenario, take notes and then mimic that.

It may also be possible that saving a scenario created in the GUI to XML and then loading and running that from code may be another avenue to take. Just throwing it out there.

**Comment by YannicBreiting** [comment]
I am facing the same problem with communicating between subnets.
Does anyone have a solution for that problem?

**Comment by YannicBreiting** [comment]
This thread was closed without presenting a solution to the actual problem. 
That's why I wanted to ask if anyone has a solution for this, since it is also a rather trivial issue.

Is there a way to create a network as described above with the current implementation of the interface creation (without Gui or XML)?

Those configurations are created from the Gui.
As you can see the default route is set to its own interface rather then the routers one. 

![example](https://user-images.githubusercontent.com/63100391/157912990-a03c8124-3031-4f76-86e4-50e15aee72b0.png)

**Comment by bharnden** [comment]
Looks like you are associating the wring interface, with the wrong node.

sat = PC = 10.0.0.20
sat_mdr = mdr = 10.0.0.1

```python
session.add_link(sat.id, sat_mdr.id, sat_iface2, sat_iface1)
```

**Comment by YannicBreiting** [comment]
I'm sorry I got a little dizzy after several days of debugging.

But thanks for your answer at least I found my error now!

**Comment by YannicBreiting** [comment]
One more quick note

It feels odd that default route is set to X.X.X.1 although the connected devices do not have such IP. 

A hint in the documentation would have really helped a lot
![example](https://user-images.githubusercontent.com/63100391/157960616-a1cb7d08-2154-42ff-87f4-58e80fa11eb9.png)
