### ISSUE TITLE
[BUG] Docker Services fail to start in Core 6.3.0

### ISSUE THREAD

**Issue by devannair777** [coreemu/core#446]
I find that there are two different approaches mentioned in the documentation for getting docker services started in CORE . https://coreemu.github.io/core/services/docker.html  and  https://github.com/coreemu/core/tree/master/daemon/examples/docker . When I tried to get docker services established by following the second guide I got a Docker service listed under my node window ...However I could not get docker services to run ...It mentioned the following error.. When I tried to install docker-py as it is mentioned as the first doc's recommendation the services tab did not list docker...Although if I understand correctly I should have gotten all docker images on my host tagged with core to be listed under my docker services tab...Any help would be much appreciated

![docker-core](https://user-images.githubusercontent.com/44372574/81432981-231bc100-9164-11ea-9679-5e5a0ef85b00.jpg)

![docker-core2](https://user-images.githubusercontent.com/44372574/81456165-b15a6c00-9191-11ea-9ded-3d3cc2d5185d.jpg)

 - OS: [Ubuntu 18.04]
 - CORE Version [6.3.0]
 - python 3.6.9
 - Docker 19.03.8 build afacb8b7f0

**Additional context**

**Comment by bharnden** [comment]
The Docker service likely doesn't work and was a different approach to trying to tackle the problem, compared to the more recent efforts that you found examples for.

I will likely remove the existing Docker service as it probably serves to just cause problems.

The more recent efforts you noted here:
https://github.com/coreemu/core/tree/master/daemon/examples/docker

Is related to using the new **core-pygui** as it will be known in the next release, which is still considered BETA. It would allow you to drag and drop nodes that represent Docker containers and specify an image to run on them. Then they would be networked together with other Docker nodes or CORE nodes depending on the session.

You could also look at scripting it that way as well, as noted in those examples.

**Comment by devannair777** [comment]
I dont understand , can Docker services be run on CORE nodes, because fundamentally I am not able to get the nodes connected to docker daemon on the host ...Is there a solution for that ?

**Comment by bharnden** [comment]
No, the service won't work.

Leveraging Docker would require using the new BETA python based GUI. This approach is fundamentally different than the service that had worked at one point functioned.

It also requires leveraging the configuration file noted in the example documentation, at least for default setups.

**Comment by bharnden** [comment]
Closing for now as the Docker service is removed on develop for next release.

The only Docker support will be the one noted here for scripting and the new GUI:
https://github.com/coreemu/core/tree/master/daemon/examples/docker
