### ISSUE TITLE
[BUG] Creating two different types of hooks causes an exception

### ISSUE THREAD

**Issue by raistlinJ** [coreemu/core#448]
**Describe the bug**
When a scenario has more than one type of hook (e.g., instantiation hook and runtime hook), an core-daemon throws an exception. This causes some functionality (such as the creation of the sessions-deployed.xml file) to not work.

**To Reproduce**
1. Create a new scenario with a single node
2. Add an instantiation hook (it can be left empty)
3. Add a runtime hook (it can be left empty)
4. Press the play button on the GUI
5. Observe the core-daemon output log in the terminal and notice the thrown exception.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.3.0

**Additional context**

**Comment by bharnden** [comment]
will look into this, thanks

**Comment by raistlinJ** [comment]
Thanks, in case it helps; my workaround was to remove the call around the session hooks dictionary, but this is only because I'm not concerned with hook ordering (within hook type) at the moment. Line 316 in core/daemon/xml/corexml.py
![image](https://user-images.githubusercontent.com/20727667/81593214-589af700-937c-11ea-95bb-56c8e655e64f.png)

**Comment by bharnden** [comment]
Yes, that is exactly the spot. I don't think the order even matters technically, just the way it has been from legacy code, will fix for next release.

**Comment by bharnden** [comment]
fixed on develop for next release, thanks again
