### ISSUE TITLE
[BUG] installation error and workaround 

### ISSUE THREAD

**Issue by bwcc60** [coreemu/core#452]
I meet the installation error and applied the workaround. please make sure the workaround is good enough, because later on, when I use core to simulate, I got some error log from daemon log. Thanks 

when I got the latest code to install using install.sh with a normal user, I got error at the 

```
function install_python_depencencies() {
  **sudo python3 -m pip install -r daemon/requirements.txt**
}
```
I forget the error content, but I google it, and decide not to use sudo at the above line. based on (https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice/802594#802594 ) 

then installation is smooth and no error message. But when I want to run core, I got error message 
ssss@ubuntu:~/CORE/core$ sudo systemctl status core-daemon
[sudo] password for wben: 
● core-daemon.service - LSB: Start the core-daemon CORE daemon at boot time
   Loaded: loaded (/etc/init.d/core-daemon; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

May 18 08:30:47 ubuntu core-daemon[35346]:   File "/usr/local/bin/core-daemon", line 16, in <module>
May 18 08:30:47 ubuntu core-daemon[35346]:     from core import constants
May 18 08:30:47 ubuntu core-daemon[35346]:   File "/usr/local/lib/python3.6/dist-packages/core/constants.py", line 1, in <module>
May 18 08:30:47 ubuntu core-daemon[35346]:     from core.utils import which
May 18 08:30:47 ubuntu core-daemon[35346]:   File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 34, in <module>
May 18 08:30:47 ubuntu core-daemon[35346]:     import netaddr
**May 18 08:30:47 ubuntu core-daemon[35346]: ModuleNotFoundError: No module named 'netaddr'**
May 18 08:41:55 ubuntu systemd[1]: Stopping LSB: Start the core-daemon CORE daemon at boot time...
May 18 08:41:55 ubuntu core-daemon[35425]: core-daemon not running
May 18 08:41:55 ubuntu systemd[1]: Stopped LSB: Start the core-daemon CORE daemon at boot time.

then I manually run `python3 -m pip install netaddr` . after that I run the core daemon by  `sudo core-daemon`  the core works normally, at least no error message.

I don't know whether my change for installation influence the core normal working. 

OS: Ubuntu 18.04 VM created by vmware workstation player
$ core-gui --version
core-gui version 6.4.0 (20200518)

Context:
After I used this workaround, later when I use RJ45 at the core-gui, I got error message when I stop the running simulation. I am not sure this is a new error or related to installation. 

```
2020-05-20 11:45:10,817 - ERROR - physical:shutdown - error shutting down
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/physical.py", line 328, in shutdown
    self.net_client.delete_tc(self.localname)
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/netclient.py", line 147, in delete_tc
    self.run(f"{TC_BIN} qdisc delete dev {device} root")
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/base.py", line 118, in host_cmd
    return utils.cmd(args, env, cwd, wait, shell)
  File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 236, in cmd
    raise CoreCommandError(status, args, stdout, stderr)
core.errors.CoreCommandError: Command(['/sbin/tc', 'qdisc', 'delete', 'dev', 'ens33', 'root']), Status(2):
stdout: b''
stderr: b'Error: Cannot delete qdisc with handle of zero.\n'

```

**Comment by bharnden** [comment]
Thanks for the input.

Ideally there could be a one size fits all install that would solve all current needs, but I haven't ran across one just yet. Although there are some approaches being considered to try and avoid various problems.

I believe there may be some issues with using just the user installed libraries via pip with services. This also causes issues in other distributions, like CentOS, that don't have the same behavior.

In all reality we should be forcing a virtualenv install in some way and make use of that. Potentially we should be dropping some of the current means of operation to help simplify accepting that path.

Your final exception on Rj45 shutdown is an ignorable error and has been squelched on the develop branch.

**Comment by bharnden** [comment]
Will look to deal with  a better solution to resolving some of these types of problems by way of #486
