### ISSUE TITLE
[BUG] nsenter Docker Node error

### ISSUE THREAD

**Issue by ehrenb** [coreemu/core#454]
**Describe the bug**
I installed Core Emulator via the ./install.sh script on Ubuntu 18.04.  I already have Docker (Docker version 19.03.8, build afacb8b7f0) installed on the same host.  Upon creating a simple network using core-pygui with one Docker node connected to a switch, connected to one router, I receive the following error from core-daemon when starting the network:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 425, in threadpool
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/session.py", line 359, in add_link
    interface = create_interface(node_one, net_one, interface_one)
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/emudata.py", line 336, in create_interface
    ifname=interface_data.name,
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/base.py", line 874, in newnetif
    ifindex = self.newveth(ifindex, ifname)
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/base.py", line 727, in newveth
    flow_id = self.node_net_client.get_ifindex(veth.name)
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/netclient.py", line 97, in get_ifindex
    return self.run(f"cat /sys/class/net/{device}/ifindex")
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/docker.py", line 159, in nsenter_cmd
    return utils.cmd(args, wait=wait, shell=shell)
  File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 237, in cmd
    raise CoreCommandError(status, args, stdout, stderr)
core.errors.CoreCommandError: Command(['nsenter', '-t', '3156', '-u', '-i', '-p', '-n', 'cat', '/sys/class/net/eth0/ifindex']), Status(1):
stdout: b''
stderr: b'cat: /sys/class/net/eth0/ifindex: No such file or directory\n'
```

- I've read and followed the instructions here: https://github.com/coreemu/core/tree/master/daemon/examples/docker. 

- I've confirmed that I can create a non-docker node and connect to the switch as well without error.

**To Reproduce**
1. Open core-pygui
2. Create one Docker node, one switch, one router and connect them
3. Start the network

**Expected behavior**
Expected to network to start without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 6.4.0
 - EMANE Version N/A
 - Python version 3.6.9
 - Docker version 19.03.8

**Comment by bharnden** [comment]
thanks, will take a look

**Comment by siliconja** [comment]
just noting that I tried this today too and ran into the same issue (CORE 6.2.0 based).

**Comment by bharnden** [comment]
There were some command changes introduced that depended on accessing files on the system for network settings. Previously this was not the case and the existing form of using nsenter did not take on the mount namespace to allow leveraging system utilities for orchestration.

To account for this and the need to change files under /sys, I have updated nsenter to leverage all namespaces (at this point I can likely just use docker exec and will test) as well as running the containers in privileged mode.

Now with these changes you will have make sure networking tools core would use exist and the containers themselves.

```dockerfile
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y iproute2 ethtool
```

This is on develop now and should resolve the error you ran into, given the caveats noted above.

**Comment by ehrenb** [comment]
Confirmed working now - rebuilt from develop branch, created a new Docker image with the above dependencies and pointed the Docker node's image to that.  Thanks for the fast response!
