### ISSUE TITLE
Changing network interfaces on the gui using a python script

### ISSUE THREAD

**Issue by kittyCat100** [coreemu/core#455]
I have a simple network on the core-gui (such as a router connected to two servers with various switches connected to the router). I want to be able to write a python script that I can run in the "execute python script" menu of the gui that will then change the jitter, latency, etc of the interface between different nodes. How do you do this? I have had trouble finding a write up about this.

**Comment by bharnden** [comment]
There are different ways to approach this, depending on what may work for your needs.

* coresendmsg - command line tool that uses the old TLV API to send commands
* gRPC API - would allow you to write a script and interface more directly in an easier way

Are you launching the session from execute python script in the first place?

**Comment by kittyCat100** [comment]
I am using gRPC API and am looking to launch the session from the executed python script. I am trying to connect a router to two servers and change the jitter/latency throughout the run of the network

**Comment by bharnden** [comment]
The gRPC API would not work from that context. The gRPC API communicates remotely with a running daemon.

So you would start CORE (Terminal 1):
```shell
sudo core-daemon
```

Then run your script (Terminal 2):
```shell
python3 grpcscript.py
```

Then you can use the "edit_link" function to change those settings during runtime.

**Comment by kittyCat100** [comment]
Oh ok. Is there a way to execute a python script during runtime that edits links without having to interact with the gui?

**Comment by bharnden** [comment]
The gRPC API as noted previously does just that, unless for some reason you can't use that.

**Comment by kittyCat100** [comment]
How is the edit_link function formatted?

**Comment by bharnden** [comment]
The function is documented here:
https://github.com/coreemu/core/blob/cc7c1348ce1ccf3894ba9513bc4383d40aaa0d85/daemon/core/api/grpc/client.py#L663

The specifics for the options, which you care about are defined in the protobuf file:

**Comment by kittyCat100** [comment]
Thank you - is there a way to edit a link and have it hold that configuration for a certain amount of time before changing configurations again?

**Comment by bharnden** [comment]
That would be up to you to do in your code, since you would be driving the changes. There is nothing provided like that.

**Comment by kittyCat100** [comment]
Sounds good - thank you.
