### ISSUE TITLE
Question: Ping Example with Python Scripting

### ISSUE THREAD

**Issue by kittyCat100** [coreemu/core#456]
Hello - another question regarding the grpc api python scripting. I am looking to perform a ping request between the nodes in my network. I found an example here https://github.com/coreemu/core/blob/master/daemon/examples/python/emane80211.py. This example is documented not to interact with the gui however. I  attempted the following with node1/node2 being ints:
```python
address = interface_helper.ip4_address(node1)
output = core_pb2.NodeCommandRequest(session_id=session_id, node_id=node2, command='ping -c 3 {address}')
logging.info("ping event: %s", output)
```

Now when ran this on the gui, nothing happens. When ran this on the command line, it prints the following:
```shell
INFO:root:ping event: session_id: 121 node_id: 2 command: "ping -c 3 {address}"
```

But I am looking to have it print the results of the ping.

**Comment by bharnden** [comment]
If you run anything in the GUI, you won't really see anything happening. Again I would not recommend doing that.

Your command is attempting to use an f string, but is not actually an f string. So you print out the response and see the command you ran.

Likely you would see the result if it was fixed.

```python
# not an f string
'ping -c 3 {address}'

# f string
f'ping -c 3 {address}'
```

**Comment by kittyCat100** [comment]
I fixed what you mentioned to
output = core_pb2.NodeCommandRequest(session_id=session_id, node_id=node2, command='ping -c 3 {address}'); however, when I run sudo python3 script.py, it still gives the following:
`INFO:root:node 2 pinging 10.83.0.3
INFO:root:ping event: session_id: 137
node_id: 2
command: "ping -c 3 {address}"`
Is it appropriate to use `logging.info("ping event: %s", output)` to get the ping results?

**Comment by bharnden** [comment]
What you just pasted is the same thing. Not sure what you changed.

You can use logging or print, whatever you like. You can see that it is wrong by the printed out command having the word address in it and not the actual address to ping.

https://www.python.org/dev/peps/pep-0498/

**Comment by kittyCat100** [comment]
Gotcha - okay I added the f back and got this result:
`INFO:root:node 2 pinging 10.83.0.3
INFO:root:ping event: session_id: 139
node_id: 2
command: "ping -c 3 10.83.0.3"`
I am just printing the output but it still only shows the command and not the results

**Comment by bharnden** [comment]
If you gave me your whole example, I could give it a check to see what is going on.

**Comment by kittyCat100** [comment]
`# import necessary libraries for script
import logging
from core.api.grpc import client, core_pb2

# define number of nodes, delay information and GUI set/not for diagram purposes
NODES = 2
DELAY_START = 0
DELAY_INT = 25
DELAY_RANGE = 2
GUI = 0

# for printing log events
def log_event(event):
    logging.info("event: %s", event)

# ping event function
def ping_me(node3, node2, session_id, interface_helper):
    address = interface_helper.ip4_address(node3)
    output = core_pb2.NodeCommandRequest(session_id=session_id, node_id=node2, command=f'ping -c 3 {address}')
    logging.info("node %s pinging %s", node2, address)
    logging.info("ping event: %s", output)

# edit link with delay
def delay_me(delay, node1, node2, session_id, core):
     print("Edit Link: Delay Links between Nodes", node1,"and",node2,"to ", delay, " us")
     options = core_pb2.LinkOptions(delay=delay)
     edit_interface = core.edit_link(session_id, node1, node2, options)
     logging.info("edited link: %s", edit_interface)

# main function
def main():
    # initialize core grpc client
    core = client.CoreGrpcClient()

    # create empty matrices for holding interface and node information
    temp_interfaces = []
    temp_nodes = []

    with core.context_connect():
        # create session
        print("------------------------------------------------------------")
        print("SETTING UP NETWORK")
        response = core.create_session()
        session = response
        logging.info("created session: %s", response)

        # handle events session may broadcast
        session_id = response.session_id
        core.events(session_id, log_event)

        # change session state
        response = core.set_session_state(session_id, core_pb2.SessionState.CONFIGURATION)
        logging.info("set session state: %s", response)

        # create switch node
        position = core_pb2.Position(x = 200, y = 200)
        switch = core_pb2.Node(type=core_pb2.NodeType.SWITCH, position=position)
        response = core.add_node(session_id, switch)
        logging.info("created switch: %s", response)
        switch_id = response.node_id
		
		# helper to create interfaces
        prefixes = "10.83.0.0/16"
        interface_helper = client.InterfaceHelper(ip4_prefix=prefixes)

        for i in range(NODES):
            # create node
            x = 150
            position = core_pb2.Position(x=150 + (x * i), y=400)
            node = core_pb2.Node(position=position)
            response = core.add_node(session_id, node)
            logging.info("created node: %s", response)
            node_id = response.node_id
            temp_nodes.append(node_id)

            # create link
            interface_one = interface_helper.create_interface(node_id, 0)
            response = core.add_link(session_id, node_id, switch_id, interface_one)
            logging.info("created link: %s", response)
            interface_id = response.interface_one
            temp_interfaces.append(interface_id)
        print("------------------------------------------------------------")

        print("INSTANTIATION")
        # Node variables for tests
        node1 = switch_id
        node2 = temp_nodes[0]
        node3 = temp_nodes[1]

        # change session state
        response = core.set_session_state(session_id, core_pb2.SessionState.INSTANTIATION)
        logging.info("set session state: %s", response)
        print("------------------------------------------------------------")

        # change delay in interface
        print("DELAY LINKS")
        # edit_link() options are opaque str, jitter int64, key int32, mburst int32,
        # mer int32, per float, bandwidth int64, burst int32, delay int64
        # dup int32, unidirectional bool

        DELAY_END = DELAY_START + (DELAY_INT * DELAY_RANGE)
        delay = DELAY_START
        while delay < DELAY_END:
            delay_me(delay, node1, node2, session_id, core)
            delay_me(delay, node1, node3, session_id, core)
			
			 # ping example
            ping_me(node3, node2, session_id, interface_helper)
            delay = delay + DELAY_INT

        print("------------------------------------------------------------")

        # if using CLI not GUI
        if GUI == 0:
            # shutdown the network
            print("SHUTDOWN")
            response = core.set_session_state(session_id, core_pb2.SessionState.SHUTDOWN)
            logging.info("set session state: %s", response)
            print("------------------------------------------------------------")


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    main()`

**Comment by kittyCat100** [comment]
import logging

from core.api.grpc import client, core_pb2


def log_event(event):
    logging.info("event: %s", event)


def main():
    core = client.CoreGrpcClient()

    with core.context_connect():
        response = core.create_session()
        logging.info("created session: %s", response)

        session_id = response.session_id
        core.events(session_id, log_event)

        response = core.set_session_state(session_id, core_pb2.SessionState.CONFIGURATION)
        logging.info("set session state: %s", response)

        switch = core_pb2.Node(type=core_pb2.NodeType.SWITCH)
        response = core.add_node(session_id, switch)
        logging.info("created switch: %s", response)
        switch_id = response.node_id

        interface_helper = client.InterfaceHelper(ip4_prefix="10.83.0.0/16")

        for i in range(2):
            position = core_pb2.Position(x=50 + 50 * i, y=50)
            node = core_pb2.Node(position=position)
            response = core.add_node(session_id, node)
            logging.info("created node: %s", response)
            node_id = response.node_id

            interface_one = interface_helper.create_interface(node_id, 0)
            response = core.add_link(session_id, node_id, switch_id, interface_one)
            logging.info("created link: %s", response)

        response = core.set_session_state(session_id, core_pb2.SessionState.INSTANTIATION)
        logging.info("set session state: %s", response)
		
        address = interface_helper.ip4_address(3)
        output = core_pb2.NodeCommandRequest(session_id=session_id, node_id=2, command=f'ping -c 3 {address}')
        logging.info("node %s pinging %s", 2, address)
        logging.info("ping event: %s", output)


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    main()

**Comment by kittyCat100** [comment]
I apologize that is so ugly - I wasn't able to format it better or attach a file

**Comment by bharnden** [comment]
Here for formatting:
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by kittyCat100** [comment]
Thank you
```
import logging

from core.api.grpc import client, core_pb2


def log_event(event):
    logging.info("event: %s", event)


def main():
    core = client.CoreGrpcClient()

    with core.context_connect():
        response = core.create_session()
        logging.info("created session: %s", response)

        session_id = response.session_id
        core.events(session_id, log_event)

        response = core.set_session_state(session_id, core_pb2.SessionState.CONFIGURATION)
        logging.info("set session state: %s", response)

        switch = core_pb2.Node(type=core_pb2.NodeType.SWITCH)
        response = core.add_node(session_id, switch)
        logging.info("created switch: %s", response)
        switch_id = response.node_id

        interface_helper = client.InterfaceHelper(ip4_prefix="10.83.0.0/16")

        for i in range(2):
            position = core_pb2.Position(x=50 + 50 * i, y=50)
            node = core_pb2.Node(position=position)
            response = core.add_node(session_id, node)
            logging.info("created node: %s", response)
            node_id = response.node_id

            interface_one = interface_helper.create_interface(node_id, 0)
            response = core.add_link(session_id, node_id, switch_id, interface_one)
            logging.info("created link: %s", response)

        response = core.set_session_state(session_id, core_pb2.SessionState.INSTANTIATION)
        logging.info("set session state: %s", response)
		
        address = interface_helper.ip4_address(3)
        output = core_pb2.NodeCommandRequest(session_id=session_id, node_id=2, command=f'ping -c 3 {address}')
        logging.info("node %s pinging %s", 2, address)
        logging.info("ping event: %s", output)


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    main()
```

**Comment by bharnden** [comment]
Here is an example of how to use it, you were not actually making a call to grpc for running the command.

```python
address = interface_helper.ip4_address(3)
logging.info("node %s pinging %s", 2, address)
response = core.node_command(session_id, 2, f"ping -c 3 {address}")
logging.info("ping event: %s", response)
for line in response.output.split("\n"):
    print(line)
```

**Comment by kittyCat100** [comment]
Awesome! This works! Thank you so much for your time and effort over the last week with these questions - I really appreciated the help. Have a great rest of your week.
