### ISSUE TITLE
[BUG] unable to ping ipv4 between nodes

### ISSUE THREAD

**Issue by ehrenb** [coreemu/core#457]
**Describe the bug**
I specified a simple network containing: router n1 (10.0.0.1/2001::1) <--> switch <-->  node n3 (10.0.0.20/2001::14).  I cannot send or receive pings between n1 and n3 over ipv4.  However, I can ping6 between the two nodes just fine with their ipv6 addresses.

*  I reproduced this on a clean Ubuntu 18.04 VM, with only CORE and Docker installed (I am not using the Docker Node). 
*  I am working off of develop (commit: 8fed201fd8641202b85082c9645d6ed7d1574d46 ), but was able to run this just fine a week ago on another machine (also working off of develop with the Docker Node fixes ).  
*  Additionally, I don't see any exceptions, warnings, or errors in the core-daemon.log. 

Any idea what this issue could be? 

**To Reproduce**
1. set up a simple network containing a router 10.0.0.1 and node 10.0.0.20 separated by a switch
2. attempt to ping from 10.0.0.1 <-> 10.0.0.20
3. receive no responses

**Expected behavior**
Expect to be able to ping successfully between nodes 

**Screenshots**
![ping](https://user-images.githubusercontent.com/5570335/83081192-12b58280-a04e-11ea-9221-5cc1105053c2.png)
![nodes](https://user-images.githubusercontent.com/5570335/83081193-134e1900-a04e-11ea-975c-3f1faf67c857.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 
 - CORE commit 8fed201fd8641202b85082c9645d6ed7d1574d46
 - EMANE Version  N/A

**Comment by siliconja** [comment]
This happens to me too, because Docker changes the default iptables forwarding chain to drop packets. You can fix it with this:

```
#!/bin/bash
set -x
sudo iptables --policy FORWARD ACCEPT
sudo sysctl net.ipv4.conf.all.forwarding=1
```

**Comment by ehrenb** [comment]
Thanks! that seems to have fixed it.

**Comment by jananparimalone** [comment]
@siliconja solution worked for me as well, as someone who has just installed coreemu and docker and is beginning Tutorial 1. Thank you for the help.
