### ISSUE TITLE
[BUG]  Device "Rj45Node2" does not exist

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#461]
When try to create the RJ45 node in python script using this command ``node = session.add_node(_type=NodeTypes.RJ45)``, it fails with such an error "Device "Rj45Node2" does not exist". I am not sure whether it is a bug, or it is not the correct way to create the RJ45 node.

**Comment by bharnden** [comment]
Trying to script things, the Rj45 nodes goal is to associate itself with a real interface on your host. The current way this occurs is by way of the nodes name, the name needs to be the exact name of a host interface.

You would need to create and provide NodeOption for the node being added as well, with the correct name being set.

**Comment by mzy2240** [comment]
Yeah you are right. I just find that through the source code and verified it is working that way. Just happen to interrupt the interface that is used for SSH T.T
