### ISSUE TITLE
Creating a python script to interact with .imn file question

### ISSUE THREAD

**Issue by kittyCat100** [coreemu/core#464]
Is there a method to utilize the gcrp api python scripting to change link values for individual links between nodes in a already created .imn file? I was hoping to load the .imn file into the gui and then import the python script, or import the .imn file into the script and interact with the links through the command line.

**Comment by bharnden** [comment]
IMN files are specific to the older GUI. They will eventually someday be deprecated.

You can load and save a IMN file into an XML file. You can load and interact with an XML based session using gRPC.

If you still prefer to to load an IMN file and then interact with it using gRPC you would still do that the same way as you have before, but you would need to determine the "session_id" to use. That could either be by manually providing one, or assuming the only existing session is the one you want to work with.

**Comment by kittyCat100** [comment]
Do you have any examples for interacting with gRPC and an XML file?

**Comment by bharnden** [comment]
Not specifically. You can leverage the client call here.

https://github.com/coreemu/core/blob/cc7c1348ce1ccf3894ba9513bc4383d40aaa0d85/daemon/core/api/grpc/client.py#L1121

Passing start set to True, the response will have the sessions id.

https://github.com/coreemu/core/blob/cc7c1348ce1ccf3894ba9513bc4383d40aaa0d85/daemon/proto/core/api/grpc/core.proto#L533

**Comment by bharnden** [comment]
In this case you are trying to 2 very different things, one of which does not actually make the gRPC call but just creates a class.

Here you are creating the CORE gRPC python client class, which is a convenience wrapper around making actual gRPC calls.
```python
core = client.CoreGrpcClient()
```

Here you are just creating a OpenXmlRequest object, this in itself doesn't do anything, it would have to be leverage from a connected gRPC client to actually do anything.
```python
request = core_pb2.OpenXmlRequest(data=data, start=start, file=file_path)
session_id = core_pb2.OpenXmlResponse.session_id
```

The link I provided before would make that call for you, including opening and reading the file, all for convenience.

https://github.com/coreemu/core/blob/cc7c1348ce1ccf3894ba9513bc4383d40aaa0d85/daemon/core/api/grpc/client.py#L1121

```python
def main():
    core = client.CoreGrpcClient()
    file_path = "file.xml"
    start = True
    with core.context_connect():
        response = core.open_xml(file_path, start=True)
        session_id = response.session_id
        core.events(session_id, log_event)
```

**Comment by kittyCat100** [comment]
How do you interact with the network in the xml file? For example, if I want to ping nodes or change interfaces within the xml file. Is there a way to for-loop through all the interfaces?

**Comment by bharnden** [comment]
Once you have the sessions ID, you can then use all the other API calls to collect information about the session and interact with it.

Get the session data, which provides an overview of all nodes/links:
```python
response = core.get_session(session_id)
```

Get node information and interfaces:
```python
response = core.get_node(session_id, node_id)
```

Send a command:
```python
response = core.node_command(session_id, node_id, cmd)
```

You can look at the client.py to see basically all the calls, for the responses most are returned as the protobuf response messages themselves for now, which can be views in core.proto.

**Comment by bharnden** [comment]
The develop branch was updated to better link to some of these files and updated examples for a couple simple cases. Which likely wont resolve all possible desires, but may at least be better to find information.

https://github.com/coreemu/core/blob/develop/docs/grpc.md
