### ISSUE TITLE
[BUG] gRPC hangs on stop_session from remote python client

### ISSUE THREAD

**Issue by devdkerr** [coreemu/core#473]
I have a remote client attempting to stop an active session using the gRPC api `stop_session` method. When invoked, the session is stopped, but the client hangs and never receives a response.

```python
from core.api.grpc import client, core_pb2

core = client.CoreGrpcClient('<remote ip>:50051')
with core.context_connect():
    core.stop_session(<session id>)
```

All subsequent gRPC requests (of all kinds) fail with the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/core/api/grpc/client.py", line 276, in get_sessions
    return self.stub.GetSessions(core_pb2.GetSessionsRequest())
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1592452739.354572344","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3962,"referenced_errors":[{"created":"@1592452739.354566212","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>
```

I have instrumented the server.py StopSession method and can validate that it is executing fully and getting to the return. Once this occurs I have to restart cored completely for gRPC interfacing to work.

I have attempted this same code via gRPC locally with 127.0.0.1:50051 and do not see the same issue. I can validate that I do not have any network filters or blocks in place that would prevent this traffic. Several gRPC api calls work prior to this including `get_sessions()`.

 - Client OS: Mac
 - CORE Daemon OS: Ubuntu 18.04
 - CORE Version: 6.5

**Comment by bharnden** [comment]
considering it seems to be saying that grpc is unavailable, there is no daemon error being logged at all in relation to this?

grpc is though http2, so it is possible to run into proxy issue, but sounds like it was working. It is hard to say what's going on with that alone.

**Comment by devdkerr** [comment]
The initial ‘stop_session’ call results in a socket timeout with no error on the server. Subsequent api calls result in the unavailable error on the client with no logging at all the server.

The server stills shows that 50051 is bound to the cored process (via netstat). This is making me think that the server is holding the socket open without terminating the response so no additional api calls can be made.

**Comment by bharnden** [comment]
Maybe there is something in the session hanging during shutdown? Are you using custom services or anything that may possibly results in such a case?

You could try a very simple basic scenario with a singular PC node to validate that it works on its own and is not related to anything more involved in your given scenario.

**Comment by devdkerr** [comment]
My original network configuration had a host-router-router-host (four nodes in total). No custom services or divergences from default configuration except for the link bandwidth configured for the link between the two routers.

I took your suggestion and tried to narrow down simpler cases to isolate the fault. Doing this helped me to isolate that it only hangs when I create a link where either interface_one or interface_two (in the call to `add_link`) has a zero in the `id` property of the `Interface` object.

```protobuf
message Interface {
    int32 id = 1;              <= when this is 0
    string name = 2;
    string mac = 3;
    string ip4 = 4;
    int32 ip4mask = 5;
    string ip6 = 6;
    int32 ip6mask = 7;
    int32 netid = 8;
    int32 flowid = 9;
    int32 mtu = 10;
}
```

**Comment by bharnden** [comment]
I was under the impression you were starting the session in the GUI and then interfacing with it? Are you creating a session through gRPC too? Or trying to add a link during runtime? The complete picture will help out.

**Comment by devdkerr** [comment]
Sorry for any confusion. This is a fully gRPC created session and network. The link being added is being added with the add_link client api call.

**Comment by bharnden** [comment]
It seems very odd that it would be just an issue for being remote, unless there is some gRPC specific issue going on.

There could be something else going on and maybe has something to do with what is being created and how? If you can post the code that could help.

There are also a few cases, which I am forgetting offhand, while gRPC should work remotely some calls specifying files, assume they exist on the host the daemon is running on and not the host running the remote gRPC calls.

Are you also running the daemon manually? Which would help expose any uncaught errors or exceptions not getting logged and rule that out as a possibility.

**Comment by devdkerr** [comment]
Here is the code that seizes up on the shutdown:

```python
from core.api.grpc import client, core_pb2

core = client.CoreGrpcClient('<grpc ip address>:<grpc port>')

with core.context_connect():
    session_id = core.create_session().session_id
    core.set_session_state(session_id, core_pb2.SessionState.CONFIGURATION)

    host_node = core.add_node(session_id, core_pb2.Node(model='host')).node_id
    rtr_node = core.add_node(session_id, core_pb2.Node(model='rtr')).node_id
    core.add_link(
        session_id, host_node, rtr_node,
        core_pb2.Interface(id=0, ip4='10.10.10.10', ip4mask=24, ip6='2001:dead:beef::10:10', ip6mask=96),
        core_pb2.Interface(id=0, ip4='10.10.10.1', ip4mask=24, ip6='2001:dead:beef::10:1', ip6mask=96),
    )

    core.set_session_state(session_id, core_pb2.SessionState.INSTANTIATION)
print ('started')

import time
time.sleep(2)

with core.context_connect():
    core.stop_session(session_id)
    core.delete_session(session_id)
```

If you change the `id` in the two Interface parameters to `1` instead of `0` it does not hang. I have not done extensive testing in the UI to see if it is consistent.

**Comment by bharnden** [comment]
Unless "rtr" is a custom node type, it wouldn't do much, although that shouldn't cause problems. Have you tried this scenario without using 2 context connects and just 1? or just using the simple ".connect()"? See if those would  make any difference or have relation.

**Comment by devdkerr** [comment]
Sorry about the `rtr`, typo in simplifying my code down (fixed in comment).

I will need to do it in two context connects but tried it in one context connection with same result, i.e. hanging on the shutdown if the interface is `0`. I also tried without the context manager by just using `.connect()` and `.close()` respectively as a single connection (not the two separate connections) with the same results.

**Comment by bharnden** [comment]
And when this happens, if you run the daemon from terminal, there is no signs of any errors at all?

**Comment by devdkerr** [comment]
No signs of error on the daemon in all cases. The last output in the standard logging is shown below with no output to stderr. If it's possible to turn on more verbose logging, I'm happy to.

```
2020-06-22 21:13:05,976 - INFO - session:set_state - changing session(1) to state RUNTIME_STATE
2020-06-22 21:13:08,064 - INFO - session:set_state - changing session(1) to state DATACOLLECT_STATE
2020-06-22 21:13:08,257 - INFO - session:set_state - changing session(1) to state SHUTDOWN_STATE
```

**Comment by bharnden** [comment]
I'll have to see if I can get something similar to replicate, since none of this points to any obvious problems.

I don't see why 0 or 1 would be any different for linking the nodes either. Especially when you say as long as it is local, there is no issue. That's why I was thinking trying different ways to connect might be a difference, since it seems to speak to something specific to gRPC, but that is just an assumption.

You could try either upgrading pr downgrading the grpc python dependency and see if there is any impact. I am aslo assuming this is a fresh/clean install otherwise maybe you need to rebuild the generated protobuf files, if there is any relation to that being an issue.

**Comment by bharnden** [comment]
I was finally able to getting around to test this out using your script. I tested on latest develop, so I needed to make a small syntax correction. But I was able to run the script repeatedly without issue or hangup.

You could try the same and see if that makes any difference. Otherwise, I would only recommend making sure the environments are clear of any old CORE installations and having a clean install.

**Comment by bharnden** [comment]
I couldn't replicate on develop as noted, if that could be tried and checked it would be good to know and I am not seeing any other specific issues to point to as a problem and would be inclined to close this for now.
