### ISSUE TITLE
[BUG] Typo in the directory name "sercurityservices"

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#478]
**Describe the bug**

Typo in the directory name "sercurityservices"

 

**To Reproduce**

1. In the CORE emulator, go to the directory core/configservices
2. Note the subdirectory here called "sercurityservices"
3. There seems to be an extra "r" in "sercurityservices"

 

**Expected behavior**

There seems to be an extra "r" in "sercurityservices"

 

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04 or CentOS 7.7.1908

- CORE Version: 6.3.0

- EMANE Version: N/A

**Comment by bharnden** [comment]
definitely a mistake, fixed on develop
