### ISSUE TITLE
[BUG] Incomplete state update in session.py (function open_xml())

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#479]
**Describe the bug**

Incomplete state update in session.py (function open_xml())

 

**To Reproduce**

1. Open file core/session.py
2. Go to the end of function open_xml()
3. Should the code under `if start:` be as follows? Updates are indicated by "#_ADDITION"

_start session if needed_

```
if start:
    state = EventTypes.INSTANTIATION_STATE  #_ADDITION
    self.set_state(state) #_ADDITION    
    self.instantiate()

```
 

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04 or CentOS 7.7.1908

- CORE Version: 6.3.0

- EMANE Version: N/A

**Comment by bharnden** [comment]
I'll take a glance and compare with normal startup behavior.

**Comment by bharnden** [comment]
Odds are this would have no real impact, unless you were trying to use a hook script during this state, the only thing I can think of.

But, I updated this to be consistent with how sessions are started up in other cases.
