### ISSUE TITLE
[BUG] OVS remains disabled even if network config (XML file) is generated with "core-daemon --ovs"

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#480]
**Describe the bug**

OVS remains disabled even if network config (XML file) is generated with "core-daemon --ovs"

 

**To Reproduce**

1. Start CORE daemon with `--ov`s: EX:  `sudo core-daemon --ovs &`
2. Start CORE GUI:  `sudo core-gui &`
3. Create a sample network in CORE GUI
4. Save network config as XML file
5. Exit CORE GUI
6. Start CORE GUI and open network config (XML file) just created
7. Note that OVS is not enabled in this network
8. See “Additional context” for a solution
 

**Expected behavior**

OVS should be enabled when this network config (XML file) is opened again in CORE GUI.

 

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04 or CentOS 7.7.1908

- CORE Version: 6.3.0

- EMANE Version: N/A

 

**Additional context**

Workaround: OVS can be enabled by editing network config (XML file) as follows: 

- Add the following line in **<session_options>**

`
<configuration name="ovs" value="True"/>
`

**Comment by bharnden** [comment]
will take a look, thanks

**Comment by bharnden** [comment]
Updated this case to work, but does not end up with the same value as your workaround.

The OVS option will now be presented in the session options in the GUIs and saved/read from XML, it for now would be stored as "0" or "1" for off and on.
