### ISSUE TITLE
[BUG] core-pygui observer widget raises exception if mouse passes over switch nodes

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#485]
**Describe the bug**
If you have an Observer Widget active and move the mouse over a switch node, an exception dialog pops up "node class(SwitchNode) is not expected(CoreNode)".

**To Reproduce**
See description.

**Expected behavior**
Observer Widgets should not generate node commands for non-container nodes like switches, hubs, RJ45s, WLANs.

Nothing should happen when I mouse over these other node types.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version develop 2020-07-07

**Additional context**

**Comment by bharnden** [comment]
Thanks will check this out, probably applies to other nodes as well, will fix.

**Comment by bharnden** [comment]
fixed on develop
