### ISSUE TITLE
[BUG] manually set interface ip address does not work

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#487]
**Dumb Question Warning: This might be a dumb question.**

I have a very simple network that contains two routers and two subnets. Let's say the prefixes are 192.168.1.0/24 and 192.168.2.0/24 for each subnet. What I find is the ip for routers will be 192.168.1.1 and 192.168.2.2, and I want the both start from 1. So what I did is to manally set the interface ip address, somethings similar to below:
```
prefix = IpPrefixes(ip4_prefix="192.168.2.0/24")
interface = prefix.create_interface(router2)
interface.ip4 = "192.168.2.1"
switch_interface = prefix.create_interface(switch2)
session.add_link(router2.id, switch2.id,
                         interface_one=interface,
                         interface_two=switch_interface)
```
And then when the session is instantiated, I check the ip address for the router2 by running 
```
router2_node = session.get_node(router2.id, CoreNode)
router2_ip = prefix.ip4_address(router2_node.id)
```
and the ip for the router2 might be anything but the one I manually set.

**Comment by bharnden** [comment]
You would not use this code to get the ip address for the node:

```python
# IpPrefixes is purely a utility class to try and help with generating addresses, not what is on a node
router2_ip = prefix.ip4_address(router2_node.id)
```

You can iterate over the nodes interfaces and addresses like so, in the current version (this is very different on develop and will be in the next release FYI):

```python
router2_node = session.get_node(router2.id, CoreNode)
for iface in router2_node.netifs():
    for address in iface.addrlist:
        print(address)
```

Also, in your link example is says switch, you normally would not provide an interface when linking to a switch, if that is what you are doing.
