### ISSUE TITLE
After Installation from an rpm (ver. 6.4) - Issue when trying to start core-daemon

### ISSUE THREAD

**Issue by k6ctw** [coreemu/core#489]
File:  "/usr/local/bin/core-daemon", line 16, in <module>
   from core import constants
ModuleNotFoundError: No module named core

Where did the rpm installation via yum (Centos 7.8) put that file?

**Comment by bharnden** [comment]
To see the files in an rpm:
```
rpm -qlp ./path/to/test.rpm
```

Typical problem is that the python path is different on CentOS then Ubuntu and by default does not have /usr/loca/site-packages or dist-packages and the one that isn't needs to be added.

In the future the plan is to likely switch to a virtual environment installation and avoid packaging altogether, hopefully avoiding these nuanced problems.

**Comment by k6ctw** [comment]
OK - I'm trying to get it to all point correctly.  This really is a pain in the neck. Yes, the Ubuntu installation seems to go fine but the Centoc one is problematic in a number of ways.Too bad we have to use centos.  Oh well - back to the grind.-----Original Message-----

**Comment by bharnden** [comment]
You can install from source as well, beyond a few extra dependencies, I believe it helps avoid this issue.

**Comment by bharnden** [comment]
You can also use ".pth" files within a python path to add to the path. One solution is to create a "site-packages.pth" and place it within dist-packages and its contents would be.

```
../site-packages
```

Or vice versa, I forget CentOS's case offhand.

**Comment by k6ctw** [comment]
Well, as you can see from the other issue submitted, installation from source is not working either.-----Original Message-----

**Comment by bharnden** [comment]
problems like this are hopefully resolved by the installation switch on the develop branch now related to #486
