### ISSUE TITLE
[Question] Best option for moving nodes in real time

### ISSUE THREAD

**Issue by lemon-lyman** [coreemu/core#492]
This question is extremely similar to #376 

I would like to move nodes around within a session with new location info that is not known ahead of time. Looking over the mobility section ([link](https://github.com/coreemu/core/blob/master/docs/gui.md#mobility-scripting)) it seems like ns-2 scripting and EMANE events are not viable options since they rely on locations being compiled before runtime.

Expanding on #376:
1. Using the setposition() method of CoreNode, can I just move the nodes around within a while loop whenever new location info comes in? e.g.

```
# Setup session
node = session.add_node(CoreNode)
…

while True:
	if new_location_info:
	        node.setposition(x=new_x, y=new_y)
```

2. Has there been any update to the gRPC documentation, besides [link](https://github.com/coreemu/core/blob/master/docs/grpc.md)? gRPC seems to be the solution landed on in #376

**Comment by bharnden** [comment]
They are updated on develop branch now and yes  gRPC would likely be the best. The assumed behavior for relative links working, only works within the repo and when the documentation pages are generated it broke the links =(.

On develop I am making the links hard coded to master, for better or worse =(.

If you look at the doc file directly, they will work: https://github.com/coreemu/core/blob/master/docs/grpc.md

The specific method you likely care about is:
https://github.com/coreemu/core/blob/e0842197e389f3f14c73dc5db6cc26f78e665f62/daemon/core/api/grpc/client.py#L496-L504

Which is using the grpc call:
https://github.com/coreemu/core/blob/e0842197e389f3f14c73dc5db6cc26f78e665f62/daemon/proto/core/api/grpc/core.proto#L56-L57

**Comment by lemon-lyman** [comment]
Thanks for the response!

I tried verifying this approach by adding it to the wlan.py example found [here](https://github.com/coreemu/core/blob/master/daemon/examples/grpc/wlan.py). I simply appended this codeblock:

```
    logging.info("position: %s", node1.position)

    address = interface_helper.prefixes.ip4_address(node1_id)

    # Ping test before change
    response = core.node_command(session_id, node2_id, f"ping -c 3 {address}")
    for line in response.output.split("\n"):
        logging.info(line)

    # Attempt to move node1 out of range
    core.edit_node(session_id, node1_id, position=Position(x=20000, y=100))
    logging.info("position: %s", node1.position)

    # Ping test after change
    response = core.node_command(session_id, node2_id, f"ping -c 3 {address}")
    for line in response.output.split("\n"):
        logging.info(line)
```

I expected the second ping test to fail since I had edited the position of node1 and moved it to an absurdly far distance. However, both ping tests pass with similar results. The 'logging.info("position: %s", node1.position)' also prints out the same node1 position before and after the 'core.edit_node' call, suggesting that the position of node1 isn't changed.

Relevant section of the logging output:
```
...
INFO:root:position: x: 100.0
y: 100.0

INFO:root:PING 10.83.0.2 (10.83.0.2) 56(84) bytes of data.
INFO:root:64 bytes from 10.83.0.2: icmp_seq=1 ttl=64 time=24.0 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=2 ttl=64 time=10.4 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=3 ttl=64 time=10.4 ms
INFO:root:
INFO:root:--- 10.83.0.2 ping statistics ---
INFO:root:3 packets transmitted, 3 received, 0% packet loss, time 2003ms
INFO:root:rtt min/avg/max/mdev = 10.393/14.939/23.997/6.404 ms
INFO:root:event: node_event {
  node {
    id: 2
    name: "CoreNode2"
    position {
      x: 20000.0
      y: 100.0
    }
    geo {
    }
  }
}
session_id: 46

INFO:root:position: x: 100.0
y: 100.0

INFO:root:PING 10.83.0.2 (10.83.0.2) 56(84) bytes of data.
INFO:root:64 bytes from 10.83.0.2: icmp_seq=1 ttl=64 time=11.8 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=2 ttl=64 time=13.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=3 ttl=64 time=10.5 ms
INFO:root:
INFO:root:--- 10.83.0.2 ping statistics ---
INFO:root:3 packets transmitted, 3 received, 0% packet loss, time 2003ms
INFO:root:rtt min/avg/max/mdev = 10.452/11.820/13.205/1.123 ms
DEBUG:root:stream closed
```

Am I using this core.edit_node() method correctly? Should it change the position attribute of the node1 object?

**Comment by bharnden** [comment]
Using your example, I think your running into a case of things happening too fast.

As far as the node position goes, you gRPC is client/server, so you are changing the position remotely. You would need to query for the node information again to see the changes.

```python
response = core.get_node(session_id, node1_id)
logging.info("position: %s", response.node)
```

If you bump up the number of pings you should hopefully see them start dropping, as the connection loss is not instantaneous.

```python
# Ping test after change
response = core.node_command(session_id, node2_id, f"ping -c 10 {address}")
logging.info("ping response:")
for line in response.output.split("\n"):
    logging.info(line)
```

**Comment by lemon-lyman** [comment]
Thanks for the response.

I see what I was doing wrong with the position info now, thanks. Querying the session as you suggested gives me the updated position info.

However, I'm still unable to see any change a ping test after a node has been moved. I even added a pause of 60 seconds. Here is the new test:
```
    response = core.get_node(session_id, node1_id)
    logging.info("position: %s", response.node)

    address = interface_helper.prefixes.ip4_address(node1_id)

    # Ping test before change
    response = core.node_command(session_id, node2_id, f"ping -c 10 {address}")
    for line in response.output.split("\n"):
        logging.info(line)

    # Move node1
    core.edit_node(session_id, node1_id, position=Position(x=20000, y=100))
    response = core.get_node(session_id, node1_id)
    logging.info("position: %s", response.node)
    logging.info("sleeping")
    time.sleep(60)

    # Ping test after change
    response = core.node_command(session_id, node2_id, f"ping -c 10 {address}")
    for line in response.output.split("\n"):
        logging.info(line)
```

And the ping test results are still similar:
```
INFO:root:PING 10.83.0.2 (10.83.0.2) 56(84) bytes of data.
INFO:root:64 bytes from 10.83.0.2: icmp_seq=1 ttl=64 time=20.3 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=2 ttl=64 time=10.1 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=3 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=4 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=5 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=6 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=7 ttl=64 time=10.1 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=8 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=9 ttl=64 time=10.1 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=10 ttl=64 time=10.1 ms
INFO:root:
INFO:root:--- 10.83.0.2 ping statistics ---
INFO:root:10 packets transmitted, 10 received, 0% packet loss, time 9010ms
INFO:root:rtt min/avg/max/mdev = 10.104/11.182/20.336/3.051 ms
INFO:root:position: id: 2
name: "CoreNode2"
position {
  x: 20000.0
  y: 100.0
}
geo {
}
dir: "/tmp/pycore.57/CoreNode2.conf"
channel: "/tmp/pycore.57/CoreNode2"

INFO:root:sleeping
INFO:root:event: link_event {
  message_type: DELETE
  link {
    node_one_id: 2
    node_two_id: 3
    options {
    }
    network_id: 1
    color: "green"
  }
}
session_id: 57

INFO:root:event: node_event {
  node {
    id: 2
    name: "CoreNode2"
    position {
      x: 20000.0
      y: 100.0
    }
    geo {
    }
  }
}
session_id: 57

INFO:root:PING 10.83.0.2 (10.83.0.2) 56(84) bytes of data.
INFO:root:64 bytes from 10.83.0.2: icmp_seq=1 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=2 ttl=64 time=10.5 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=3 ttl=64 time=10.6 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=4 ttl=64 time=10.3 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=5 ttl=64 time=10.3 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=6 ttl=64 time=10.6 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=7 ttl=64 time=10.4 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=8 ttl=64 time=10.3 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=9 ttl=64 time=10.2 ms
INFO:root:64 bytes from 10.83.0.2: icmp_seq=10 ttl=64 time=10.5 ms
INFO:root:
INFO:root:--- 10.83.0.2 ping statistics ---
INFO:root:10 packets transmitted, 10 received, 0% packet loss, time 9015ms
INFO:root:rtt min/avg/max/mdev = 10.179/10.380/10.637/0.149 ms
DEBUG:root:stream closed
```

**Comment by bharnden** [comment]
Are you using Ubuntu 20 or CentOS 8? If not what?

**Comment by lemon-lyman** [comment]
Ubuntu 20

**Desktop**:
OS: Ubuntu 20.04 within a VirtualBox on Mac
CORE Version 6.5.0
EMANE Version 1.2.6
Python Version 3.8.2

I'm the same user from #491 and I've implemented your [suggested fix](https://github.com/coreemu/core/issues/491#issuecomment-659462014)

**Comment by bharnden** [comment]
You can try pasting the complete example, which I can run and verify locally. But, beyond that it would be hard to say what is going on, unless the core-daemon is showing any errors/exceptions? Or anything else of value that seems off?

**Comment by bharnden** [comment]
You can check/verify the rules within ebtables are getting created/modified potentially as something else.

Add a manual pause, check, move node, check again.

```python
# setup scenario, check rules
input("press enter to continue")
# move node and check again
```

check rules:
```shell
sudo ebtables -L
```

**Comment by bharnden** [comment]
I just did a clean setup on 20, from "master" compensating for the various Ubuntu 20 issues. But was able to run the script above and got expected behavior.

I did notice your session ID above is 57, potentially you need to run `core-cleanup` as you may have leftovers from previous failed runs impacting what is going on. I would try this first and then try your script again, before looking into any other possibilities.

Otherwise, run `core-daemon` manually, see if there are any error/exceptions in the output when you run your script.

I would also set the range to something much smaller, and still move your node out of range the same way, but a distance that would stay on the canvas in the GUI (2000 is too far out). Then you can run `core-gui` after running your script and join the session you created. Then you could also manually play with dragging it in and out and seeing it disconnect and the response. Looking at `ebtables -L` to see changes. Or opening one terminal ping the other node and set it to the side while dragging around.

**Comment by bharnden** [comment]
Any luck on this?

**Comment by lemon-lyman** [comment]
Apologies for the delay.

I just did a clean install of an Ubuntu 20.04 VM and CORE 7.0.1. After changing the InterfaceHelper.create_interface() method to .create_iface() to accommodate for 7.0.1, the above script worked as expected. Thanks for your help!
