### ISSUE TITLE
[FEATURE] Launch session from file

### ISSUE THREAD

**Issue by walterhil** [coreemu/core#495]
I know the functionality exists to start a simulation in the python GUI close the GUI and keep the simulation running. Is it possible to start a sim from the terminal without opening the GUI?

**Comment by bharnden** [comment]
There are several ways this can be achieved. There is a new path that will supported in the next release, that should be the one used moving forward, which can be tried on the develop branch.

> **NOTE:** IMN files are specifically tied to the legacy GUI and are planned to be deprecated eventually

Launch a legacy GUI IMN file:
```shell
core-gui -b /path/to/file.imn
```

Write a script that would load the file over gRPC:
```python
from core.api.grpc import client

def main():
    # create grpc client and start connection context, which auto closes connection
    core = client.CoreGrpcClient()
    with core.context_connect():
       response =  core.open_xml("/path/to/file.xml", start=True)
       print(response.session_id)

if __name__ == "__main__":
    main()
```

> **ON DEVELOP BRANCH**
Leverage core-cli, this is more or less running the above gRPC script above.
```shell
usage: core-cli xml [-h] -f FILE [-s]

optional arguments:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  xml file to open (default: None)
  -s, --start           start the session? (default: False)

# open file and start it
core-cli xml -s -f /path/to/file.xml
```

**Comment by walterhil** [comment]
Awesome, Thanks
