### ISSUE TITLE
Add real-time throughput to links and custom alert in pyGUI

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#496]
Howdy!

I just wonder is there a way to add the real-time throughput info to links that show up in the new pygui, by only using the python script? Also is it possible to send a custom message (from a grpc client to the pygui/or to the grpc server) to trigger an alert and show up in the alert dialog? 

Thanks in advance!

**Comment by mzy2240** [comment]
In other words, what APIs/functionalities does the PYGUI support, using the grpc client, without modifying the source code?

**Comment by bharnden** [comment]
The throughput option is specific to the GUI at this point.

There is not an alert option by way of gRPC at the moment, may be reasonable enough to add though for a future release.

Everything else is mostly specific to creating and configuring sessions that get rendered by the GUI, since the GUI is querying that information when joining session etc.

**Comment by mzy2240** [comment]
Thanks @bharnden 

What I am trying to do right now is associated with [this issue](https://github.com/coreemu/core/issues/482) . I somehow managed to create a session, associated it with a grpc server and then started a pygui instance connecting to it. Everything works really well, so I am thinking if I can utilize the alert dialog to show some inference results from our backend it will be even sweeter. That's the major reason why I want to have this custom alert functionality. 

Speaking of this, again, if it is possible for you to add an **optional** argument to the core-pygui command so that we can specify the session, this will make the demo process fully automatic.

**Comment by mzy2240** [comment]
> Everything else is mostly specific to creating and configuring sessions that get rendered by the GUI, since the GUI is querying that information when joining session etc.

If that is the case, how to update the GUI when the session is running? Like the change of topology or change of ip address?

**Comment by bharnden** [comment]
> If that is the case, how to update the GUI when the session is running? Like the change of topology or change of ip address?

That is a bit more nuanced, I believe link additions and nodes would appear now, with changes on the develop branch (maybe it is on master). Some editing would bubble up to the GUI for nodes. For ip address changing, that would rely more on having to delete/add a link, as there is not a specific edit to modify an existing links addresses.

But editing and adding links during runtime bring up a separate issue. Service that run on nodes may often generate files and run using information about the interfaces at the time of startup (traditionally, everything being setup and starting has been the expected case). Modifying things after the fact, node services do not have any way to account for this or try to restart/etc.

I can look into quickly adding the alert like api by way of grpc, although these are currently called "Exceptions" internally. Although there can be an INFO Exception, which is a bit odd naming and should likely be refactored to alerts formally.

I can also see how much trouble pushing an option for a session id on startup would be too. If trivial I can get into the next release which should be soon.

**Comment by bharnden** [comment]
added the grpc alert API and did a small sprucing up for the alert handling to denote a number for alerts and properly handle changing the color etc based on severity.

these are on develop
