### ISSUE TITLE
[BUG] Cyclic dependency check false positive

### ISSUE THREAD

**Issue by jonashoechst** [coreemu/core#506]
When implementing services in multiple layers of dependencies, the cyclic dependency yields false positives. 

Example (where `--->` equals "depends on"):
```
Service B ---> Service A
Service C ---> Service A
Service C ---> Service B
```

In the example an error is raised, even though there are no cyclic but only a hierarchic dependencies:
```
ValueError: cyclic dependency at service(updateNodeState): queryService
```

The implementation resides here and might need to be adapted:
https://github.com/coreemu/core/blob/eb7038623853a0ea13cc6a09ee77d2fbd82cce78/daemon/core/services/coreservices.py#L101-L116

**Comment by bharnden** [comment]
Thanks, appreciate the input and details, will take a look when I get a chance.

**Comment by bharnden** [comment]
Is this is the latest version? What is your exact setup. An initial quick replication of this case seems to pass, I'll check if ordering matters as well.

**Comment by bharnden** [comment]
fixed on develop, for next release
