### ISSUE TITLE
[BUG] TCL bug with core-gui on CentOS 8

### ISSUE THREAD

**Issue by TreadCastle** [coreemu/core#508]
Attempting to run core-gui on CentOS 8 is resulting in a TCL error:
```
Error in startup script: can't use empty string as operand of "*"
	While executing
"expr {$x + 2 * $ox + 17}"
	(procedure "switchCanvas" line 41)
	Invoked from within
"switchCanvas first"
	(file "/usr/lib/core/initfui.tcl" line 807)
	Invoked from within
"source "$LIBDIR/initgui.tcl""
	Invoked from within
"if {$execMode == "interactive"} {
	# GUI-related files
	Source "$LIBDIR/widget.tcl"
	Source "$LIBDIR/tooltips.tcl"
	Source "$LIBDIR/initgu..."
	(file "usr/lib/core/core.tcl" line 130)

```
Core version: 6.5.0
OS: CentOS 8.2.2004 Core 
TCL version: 8.6

**Comment by bharnden** [comment]
This is related to installation and the new installation path is 7.x helps resolve this. On the other hand there are other problems with CentOS 8 that currently don't make it an ideal distribution to use, falling back to 7.x will fix that though.

* tc netem is not enabled by default and requires extra setup (which the installation procedures tries to rectify)
* there is no ebtables legacy version available, making usage of WLAN nodes based on current logic broken

**Comment by bharnden** [comment]
Closing for now, let me know if there are any other issues, beyond what is described above
