### ISSUE TITLE
can't figure out how to install from source on Linux Mint 19

### ISSUE THREAD

**Issue by tomhenderson** [coreemu/core#511]
I used to be able to install with:

```
$ git clone https://github.com/coreemu/core.git
$ cd core
$ ./bootstrap.sh
$ ./configure
$ make
$ sudo make install
```

Trying it today, it builds the gui and puts it in /usr/local/bin/, but does not install core-daemon script  (used to be in /etc/init.d/) nor the python libraries.

I then tried to use the install.sh script to build a venv but it errored out with:
unsupported os(linuxmint) like(ubuntu) version(19

I can't tell from http://coreemu.github.io/core/install.html what I should try next.

**Comment by bharnden** [comment]
The supported and tested OSs are CentOS/Ubuntu at this point. So there may be other issues with mint, but a quick way to get it to attempt the debian like install would be to adjust the following line. I need to fix this for the next release, so it would at least attempt a default pass at installing.

Although now that I am looking your os-release file is saying the like is `ubuntu` and not `debian`.

What you could do to bypass the failure and make an attempt at install, in an ubuntu/debian like way would be to modify the file `/etc/os-release` to have the following lines:
```
ID=ubuntu
ID_LIKE=debian
```

You can revert it back after attempting to use `install.sh` again.

**Comment by bharnden** [comment]
Also if there ends up being any unique quirks needed for mint for some reason, we could look to take contributions or add what's needed to try and help other mint users and have it be formally supported.

**Comment by tomhenderson** [comment]
Thank you for the fast response.  I edited /etc/os-release as you suggested and it installed; Linux Mint 19 is a Ubuntu 18 derivative.

The install.sh left the following footprint on my system; is this expected?
- an ospf-mdr directory in $HOME
- a new /etc/core directory with two files
- approximately 240 files installed across /usr/local

Are there other implications that I missed?  I had the expectation that install.sh would not do a system install; the script is pretty opaque and it is hard to tell what it does.

Could you list on your installation page the manifest of files that will be installed and how to uninstall?

**Comment by bharnden** [comment]
This section covers more or less what is going on in some detail: http://coreemu.github.io/core/install.html#automated-installation

I can take another pass at making this a bit more explicit and layout out where the files are going, based on install parameters.

What did you expect a script named install to do, if to not do an install?

I think you have covered more or less what is installed, there is however the python virtual environment that is created and used for CORE by default, unless passing the install local flag.

You can view its location:
```
cd <REPO>/daemon
poetry env info
```

**Comment by tomhenderson** [comment]
> 
> What did you expect a script named install to do, if to not do an install?

I'm not familiar with poetry, but with virtualenv, so I thought it would limit installation to $HOME somewhere, and I also saw this note on the page that implied to me that it would not install onto the system:
```
NOTE: installing globally can have issues with dependency conflicts etc
```

**Comment by bharnden** [comment]
That's just saying, if you decided the use the local install (into the system python), it is possible to run into dependency conflicts from packages installed by way of the package manager vs what is wanted by CORE going through pip. Being that these two parts are managed independently and CORE having been traditionally installed into the system python, it was an issue others had run into.

**Comment by tomhenderson** [comment]
I did not realize that it would take all of the actions in 'tasks.py' (which I just read for the first time).  Perhaps inform newcomers that they should read tasks.py to see what will happen with install.sh?

Feel free to close this issue; I am just offering documentation suggestions at this point.

**Comment by bharnden** [comment]
It's always good to get thoughts on improvement to factor into what might be best.

install.sh does not do all the tasks of tasks.py. It sets up the environment so tasks.py can be used, by way of the python invoke package, which then runs the install task. After that, invoke can be leveraged for any of the others tasks, like uninstall, etc.

**Comment by bharnden** [comment]
Updated install scripts to be a bit more robust and added a way to attempt a forced install for redhat/debian like distros. Not guaranteed to solve all your problems, but may help.

If there are unique gotchas to mint, we can look to add more formal checks to do it right.

Also too a pass on updating the install docs to be more explicit and denote all the files and locations things may go into.
