### ISSUE TITLE
[QUESTION] How to set CPU affinity per emulated host

### ISSUE THREAD

**Issue by therealbstern** [coreemu/core#518]
Does the current version of CORE still support setting CPU affinity on a per-emulated-host basis?  An old version supported this (though only in non-distributed mode) via the GUI, but I need to do this via the CLI or API.

**Comment by bharnden** [comment]
Far as I am aware it has not ever done that. I can ask around to double check. The TCL based GUI has not changed for years, so if it existed there, it should still be there.

**Comment by therealbstern** [comment]
Weird, a quick grep via the GitHub search above had one code hit in a comment in nodeconfig.tcl but nothing else.

It sounds to me like this is no longer possible.

**Comment by bharnden** [comment]
Considering those seem to only exist as comments, it must have been something they had hoped to do, but was never implemented. Sorry this is not the answer you were hoping for =(.
