### ISSUE TITLE
Host node access to Internet

### ISSUE THREAD

**Issue by Binsoma** [coreemu/core#519]
Greetings,

Is it possible for emulated host node to connect to Internet and ping for example www.github.com? download and run software like normal PC?

**Comment by bharnden** [comment]
The emulated nodes have access to the same file system, so they can run all software available on the host pc. There are some quirks with that, that can be compensated for by using Core Services, in case you need isolated directories for unique configurations etc.

For connecting to the internet, I would assume you could by leveraging the controlnet configuration that provides a common network interface for the nodes and actual host to communicate on. If the system was configured to route traffic from the nodes properly, then it should likely work. I am just not familiar with the specifics offhand.

**Comment by Binsoma** [comment]
well, thank you!

**Comment by Binsoma** [comment]
I configured the host directories to be accessed by emulated PC node  but nothing inside the directory can be seen or accessed from emulated nodes. How can I access the files inside host directories?

**Comment by bharnden** [comment]
I am not sure what you mean. The emulated nodes are running as root and can access the entire file system. Maybe you can provide a concrete example?

**Comment by Binsoma** [comment]
Hi, I added some directories that I wanted to access through the service settings user defined but when I start terminal of the node I see the name of the directory but not the contents.
![CORE](https://user-images.githubusercontent.com/34573767/97725986-b0622180-1ac6-11eb-8e14-09af147ecf2a.JPG)

**Comment by bharnden** [comment]
Sorry, that is not how it works. What I am saying is the following. 

* Do not add directories using service configuration, you only need this if it specific to a service and there is a valid reason
* Otherwise from a node terminal you can look at all files of the entire system, these are exactly the same as any path on your host and are not unique to a given node, since they share the entire system

```shell
# list home directories for all users of the actual home system
ls /home
```

**Comment by Binsoma** [comment]
How do I access host directories from a node terminal? I cannot list anything via emulated node.

**Comment by bharnden** [comment]
You use commands like ls and you list the path that you want, please provide an actual example of what you cannot do, because this does not currently make any sense.

**Comment by Binsoma** [comment]
when I double click a node I get a terminal with "root@n7/tmp/pycore.37915/n7.conf" when I type cd to get to home it stays as it is. When I type ls nothing on that directory.

**Comment by bharnden** [comment]
Yes, but if you modified a service to mount home, you have replaced it, so your decision to do that is masking the real home. You would need to remove /home from your service change.

Try starting a clean scenario, with no modified services and see what happens.

**Comment by Binsoma** [comment]
A new instance with default settings and still I cannot list my host directories.
![CORE](https://user-images.githubusercontent.com/34573767/97731058-94617e80-1acc-11eb-9abd-04697dc33a21.JPG)

**Comment by bharnden** [comment]
`cd /home` then `ls`, that error is fairly clear.

**Comment by Binsoma** [comment]
It worked! much appreciation for your time and patience. Cheers.
