### ISSUE TITLE
[BUG] core-daemon failed to start

### ISSUE THREAD

**Issue by GregoireJFM** [coreemu/core#521]
Could I ask for help? I have installed core 7.1.0, Gui works fine but I have problem with start daemon. 
First, I  start core-daemon, then core-gui but it's then written that core-daemon is not started. Finally, when I want to see the status of core-gui, I have some error. I know that there are already 2 topics on this issue but all I tried does not work.

**HP-Pavilion-m6-Notebook-PC:~$** _sudo service core-daemon start_
Swipe your finger across the fingerprint scanner

**HP-Pavilion-m6-Notebook-PC:~$** _core-gui_
Connecting to "core-daemon" (127.0.0.1:4038)...
This feature requires a connection to the CORE daemon.

Failed to connect to 127.0.0.1:4038!

Have you started the CORE daemon with '/etc/init.d/core-daemon start'?
  (Error: couldn't open socket: connection refused)

**HP-Pavilion-m6-Notebook-PC:~$** _service core-daemon status_
● core-daemon.service - Common Open Research Emulator Service
     Loaded: loaded (/lib/systemd/system/core-daemon.service; disabled; vendor >
     Active: failed (Result: exit-code) since Tue 2020-11-10 17:15:03 CET; 37s >
    Process: 30848 ExecStart=/usr/local/bin/core-daemon (code=exited, status=1/>
   Main PID: 30848 (code=exited, status=1/FAILURE)

nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: Started Common Ope>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]: Traceback >
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]:   File "/u>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]:     from c>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]: ModuleNotF>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: core-daemon.servic>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: core-daemon.servic>
lines 1-13/13 (END)...skipping...
● core-daemon.service - Common Open Research Emulator Service
     Loaded: loaded (/lib/systemd/system/core-daemon.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-11-10 17:15:03 CET; 37s ago
    Process: 30848 ExecStart=/usr/local/bin/core-daemon (code=exited, status=1/FAILURE)
   Main PID: 30848 (code=exited, status=1/FAILURE)

nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: Started Common Open Research Emulator Service.
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]: Traceback (most recent call last):
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]:   File "/usr/local/bin/core-daemon", line 16, in <module>
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]:     from core import constants
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC core-daemon[30848]: ModuleNotFoundError: No module named 'core'
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: core-daemon.service: Main process exited, code=exited, status=1/FAILURE
nov. 10 17:15:03 HP-Pavilion-m6-Notebook-PC systemd[1]: core-daemon.service: Failed with result 'exit-code'.

Desktop : 
 - OS:  Ubuntu 20.04
 - CORE Version 7.1.0
- Anaconda 3 and python 3.7
 
Thank you in advance

**Comment by bharnden** [comment]
Was this a fresh install? It appears your python path is not picking up CORE.

You can try manually running things without the service:
```shell
sudo core-daemon
```

If that fails with the same error, then look at the core-daemon script itself, specifically the shebang line.
```shell
vi /usr/local/bin/core-daemon
```

With the default install, this should point to the virtual environment created for CORE, if this is not the case, potentially you have old leftover files?

Did you install this from the install.sh script? Is this a normal Ubuntu Desktop install? Potentially root is not picking up /usr/local paths for your system and you need to reinstall using `-p /usr` if so, or update root to pick up said paths.

**Comment by GregoireJFM** [comment]
When I try the fist command, I obtain

`Traceback (most recent call last):
  File "/usr/local/bin/core-daemon", line 16, in <module>
    from core import constants
ModuleNotFoundError: No module named 'core'
`

The shebang line of the file `/usr/local/bin/core-daemon` is the following : 
**#!/home/gregoire/.cache/pypoetry/virtualenvs/core-AM2hJUEa-py3.6/bin/python**
So point to the virtual environment created for CORE.

But if I go to **home/gregoire/.cache/pypoetry/virtualenvs/core-AM2hJUEa-py3.6/bin/** 
there are two different executable python and python3, should I remove python and replace it by python3 in the shebang line ?

I installed it when I was using Ubuntu 18.04 (with these instructions **http://coreemu.github.io/core/install.html**), then I upgraded Ubuntu and also installed Anaconda. Is it possible that the update change something ?

**Comment by bharnden** [comment]
Potentially, you may try reinstalling from the core repo again and see if that can help. The fact that it seems core is missing from the  virtual environment does seem odd.

```shell
cd <core repo>
inv uninstall
inv install
```

**Comment by GregoireJFM** [comment]
Thank a lot, it is working !!
