### ISSUE TITLE
Resource monitoring

### ISSUE THREAD

**Issue by Binsoma** [coreemu/core#522]
Is there a way to monitor resource usage of emulator nodes? i.e CPU, memory, power/energy drain?

**Comment by bharnden** [comment]
You can leverage tools like top/htop to monitor the processes running on the system, everything running in the nodes will be descendants of the vnoded processes to create the nodes.

**Comment by Binsoma** [comment]
Yes I agree with that approach, but I was thinking monitoring of the whole network topology as the whole for a period of time.

**Comment by bharnden** [comment]
I am sure a script or tool with some smarts could be built to scrape this information and collect it over time, but even then that information is all based on the system it is running on or other aspects, like if running from within a VM vs actual hardware etc.

There is no built in convenience for this, sorry.

**Comment by Binsoma** [comment]
Okay understood, thanks.
