### ISSUE TITLE
A error occurs when I try to start a session with multi-server

### ISSUE THREAD

**Issue by Revan-github** [coreemu/core#524]
![qxlarge-dsc-B404D6DA37A807580F56846099148225.jpg](https://user-images.githubusercontent.com/45191163/98824849-c41a6a00-246e-11eb-9194-5f1107897809.jpg)
I have configured the ssh login and I can log in on another server with root or normal users.
But when I try to run a session with these two server, a error occurs, shown as the figure above.

**Comment by bharnden** [comment]
It looks like you have a setting for a controlnet using a specific ip address. It should be in the format "192.168.189.0/24".

**Comment by Revan-github** [comment]
Thanks a lot, this problem has been solved. 
And I would like to know how the tunnel is built.
When I put nodes in the distributed server, there is no error reported and every node has its ip address. But I just can't get the network work, it seems that the tunnel went wrong and the link between nodes are broken.

**Comment by bharnden** [comment]
If you have Docker installed that is a common side effect due to the ip table rules that Docker sets up. You can follow the instructions [here](https://github.com/coreemu/core/tree/master/daemon/examples/docker) to disable the rules for Docker or uninstall it and restart your machine.

**Comment by Revan-github** [comment]
I didn't install docker as I konw. 
![image](https://user-images.githubusercontent.com/45191163/98893279-17c39c80-24dd-11eb-9cdc-8f8e51e87827.png)
And a strange phenomenon is that when I try to use a node on distributed server to ping 192.168.189.2 for the first time，it will receive reply once, and then all packets are lost.
The network won't work as long as there is node on distributed server, even all nodes are on distributed server. 
May be this will help: 
when I run core-gui, I can start the terminal of node on distributed server. 
But when it comes to core-pygui,  the terminal of node on distributed server can not be started.

**Comment by bharnden** [comment]
May take me a bit to double check things, as I do not have a distributed setup available offhand.

One thing you could try is to follow the traffic and see where it is getting lost or dropped.

* See ICMP packets leave a node
* See them traverse over any Linux Bridges along the path
* See them traverse over setup GRE tunnels to Distributed Servers, if this is a path being pinged etc

**Comment by Revan-github** [comment]
Do you have any progress on this problem?

**Comment by bharnden** [comment]
I have not had chance to try and replicate, but even then if it works for me that doesn't explain much.

You say a non distributed scenario works fine? Only when it is distributed  you have an issue?

I also don't know exactly what you are running or trying to do, but I would trace packets and inspect the environments of the nodes to validate what is going on.

**Comment by Revan-github** [comment]
In the document, it says that install core in master server, and core-distributed in all servers. 
I feel it is quite strange, should I install core in all servers?

**Comment by bharnden** [comment]
No, CORE in distributed mode is leveraging the python library fabric to run passwordless SSH commands, assuming you setup the machine as advised. So that means it only needs to executables and associated software tool dependencies to run commands and set things up, not the actual CORE python library.

**Comment by Revan-github** [comment]
I run tcpdump on my ubuntu machine and found out that there is only the packet asking who has the target ip address. 
And this is the route table after I run the emulation on my ubuntu,
![image](https://user-images.githubusercontent.com/45191163/99750403-4cf26f00-2b1b-11eb-83d4-6aedcf58428a.png)
Is this a problem of the tunnel built between servers?

**Comment by Revan-github** [comment]
By the way , I run all of this in VmWare WorkStation, could this be why I failed to connect node in different servers?

**Comment by bharnden** [comment]
Which machine is this from? The distributed one? It does look like conflicting routes potentially from preexisting setup.

I also assume you set the distributed address in `/etc/core/core.conf`?
```
distributed_address = 129.168.0.101
```

I'll try to run a basic example tomorrow, it would help to have an idea of what you are actually running/trying, simplify it to two nodes if needed.

**Comment by Revan-github** [comment]
Thank you so much for replying. 
This is the route table on master server. 
The right table should have some route rules about the gre tunnel, right?

yeah, I  set the distributed address in /etc/core/core.conf?
Here is my core.conf setting: 
![image](https://user-images.githubusercontent.com/45191163/99768379-9f458700-2b3f-11eb-9f3d-e3c4115883a7.png)
![image](https://user-images.githubusercontent.com/45191163/99768403-ab314900-2b3f-11eb-91b0-3bd7c6cd6b19.png)
![image](https://user-images.githubusercontent.com/45191163/99768450-bd12ec00-2b3f-11eb-8f13-1c8cc649874f.png)

Here is my virtual machine setting:
master server: IP:192.168.189.101
distributed server : IP:192.168.189.102
I configure their IP as a fixed IP address. 
 Is there any other information you'd like to know, please inform me. 
Again, thanks a lot for your answering. It's really timely, helpful and important.

**Comment by bharnden** [comment]
Based on your example the `distributed_address` should be 192.168.189.101. This setting should be the address all other distributed nodes can talk to.

That would be a start and maybe your issue.

**Comment by Revan-github** [comment]
Thanks, I can ping through node in different servers now.
