### ISSUE TITLE
host/PC wireless connection with WLAN node 

### ISSUE THREAD

**Issue by Binsoma** [coreemu/core#528]
How do I configure two hosts/PCs to connect wirelessly?

I set up a WLAN and mdr routers which they connect via wireless but I don't know how to add hosts/PC via wireless connection with the router.

Option two, I had hosts without routers connecting with WLAN but I cannot ping the two wireless nodes. How to make them see each other?

**Comment by bharnden** [comment]
Host/PC/MDR nodes are really just a collection of services. The MDR nodes work in wireless, since they run a routing protocol that has discovery to create routes to other nodes.

Connecting other node types will not run such software and they will not find each other as you found out.

**Comment by Binsoma** [comment]
ok, thx.
