### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bugman-creator** [coreemu/core#530]
**Describe the bug**

This is for a class project. This is a list of checked output from a Static Code Analysis tool

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

Please find attached the file containing the errors. This file includes the error type, as well as the files and lines where the errors occur

[coreSCAResults.txt](https://github.com/coreemu/core/files/5578591/coreSCAResults.txt)

**Comment by bharnden** [comment]
Will take into consideration, but nothing not expected at the moment. Thanks.
