### ISSUE TITLE
[BUG]Change the server in which the nodes are in pygui

### ISSUE THREAD

**Issue by Revan-github** [coreemu/core#531]
**Describe the bug**
In pygui, I can put some nodes on distributed server. 
But when I try to put them back to the master server, it doesn't work
**To Reproduce**
1. Start a session in core-pygui
2. put some nodes on distributed server
3. put those nodes back to local server

**Expected behavior**
the nodes can be put back to local server

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 7.2.1

**Comment by bharnden** [comment]
Are you saying this happens during runtime? or stopping a session, putting the nodes back to local and then running again?

Because during runtime is definitely not a supported concept. Just double checking.

**Comment by Revan-github** [comment]
No, it's not runtime

**Comment by bharnden** [comment]
So you with a session not running you do the above steps and see the error in console or a dialog box or what? what exactly do you see? If you can post the error etc, as much specifics as possible. That would help a lot.

**Comment by Revan-github** [comment]
Well, there is no dialogbox. 
The nodes are put in local server by default, right?
I can change the nodes' server to a distributed server. 
And the there distributed server's name will appear behind the node's name.
But when I try to change back to the local server, there nothing changed after my operation.

**Comment by bharnden** [comment]
So visually in the GUI it doesn't change back? If you ran it is there an issue? or just visually in the GUI?

**Comment by Revan-github** [comment]
It's that not only visually in the GUI it doesn't change back.
There is no error report when I run it. 
The node just stay in the distributed server.

**Comment by bharnden** [comment]
Good to know then, will take a look into it eventually and test this out.

**Comment by bharnden** [comment]
Thanks for pointing this out, fixed on develop for next release.
