### ISSUE TITLE
core grpc client in Windows

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#533]
Just a thought, is it possible to somehow using the CORE grpc client in Windows? The scenario is, we will be running the main emulation in a Linux system, but using a grpc client in Windows to connect to it. Thank you in advance!

**Comment by mzy2240** [comment]
Thank you for your quick answer. Does any grpc client could work with the core grpc server? If not, do you have any suggestions how I could compile the core grpc client in Windows? Thanks!

**Comment by bharnden** [comment]
This is the path to the protobuf file used for gRPC:
https://github.com/coreemu/core/blob/master/daemon/proto/core/api/grpc/core.proto

You could generate code for a supported language to build a client to interact with a running server, given the configuration I spoke to above.
https://grpc.io/

You could potentially even build a package using poetry from the repo and install that at a windows box to use one of the existing python clients, but that may be more complicated than generated your own code.
