### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by Binsoma** [coreemu/core#540]
Hi @bharnden, how to enable connections without restriction between emulated nodes? For example when I try to connect to a specific port using Curl I keep getting connection refused.

**Comment by bharnden** [comment]
To curl something there would need to be software running on the other node to curl. Are you running a web server?

If you are and are still having issue, it can be possible the environment is inheriting your global proxy settings and they are getting in the way.

**Comment by Binsoma** [comment]
yes I am running a web server, how do I edit global proxy settings?

**Comment by bharnden** [comment]
In the node you are running curl a quick test would be to do the following:

```shell
export http_proxy=
export https_proxy=
```

There are a variety of ways that proxy settings could be getting applied, so it is hard to say one specific answer.

You could modify your system settings if one is set, I assume you may actually need it, if it is though.

**Comment by Binsoma** [comment]
thanks, I solved the problem by clearly specifying the host IP as my server, it seems emulated nodes do not interlink localhost(127.0.0.1) and their IP address. If you have your server in localhost and when you curl with host IP it gives connection refused.

**Comment by bharnden** [comment]
Yes, that is how it normally works, servers listening on localhost/127.0.0.1 can only be reached by way of localhost.
