### ISSUE TITLE
[BUG] install fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by HaanJde** [coreemu/core#544]
**Describe the bug**
install.sh fails on Ubuntu 20.04.1 LTS

**To Reproduce**

1) clone from github
2) run install.sh

**Expected behavior**

Expected install.sh to succeed.

**Screenshots**

me@mylaptop:/home/me >lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
me@mylaptop:/home/me >uname -a
Linux mylaptop 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
me@mylaptop:/home/me >cd ~/dat/Projects
me@mylaptop:/home/me >mkdir 568_core-Common-Open-Research-Emulator
me@mylaptop:/home/me >cd 568_core-Common-Open-Research-Emulator
me@mylaptop:/home/me >git clone git@github.com:coreemu/core.git .

...

me@mylaptop:/home/me >./install.sh

...

installing systemd service ... done
installing ospf mdr ... \Encountered a bad command exit code!

Command: 'cd ../ospf-mdr && make -j$(nproc)'

Exit code: 2

Stdout:

mv -f .deps/ipforward_proc.Tpo .deps/ipforward_proc.Po
mv -f .deps/if_netlink.Tpo .deps/if_netlink.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -fPIE  -ggdb -pie  -o testzebra test_main.o zebra_rib.o interface.o connected.o debug.o zebra_vty.o kernel_null.o redistribute_null.o ioctl_null.o misc_null.o -lcap  ../lib/libzebra.la -lcrypt   -lrt
mv -f .deps/rtread_netlink.Tpo .deps/rtread_netlink.Po
libtool: link: gcc -fPIE -ggdb -pie -o .libs/testzebra test_main.o zebra_rib.o interface.o connected.o debug.o zebra_vty.o kernel_null.o redistribute_null.o ioctl_null.o misc_null.o  -lcap ../lib/.libs/libzebra.so -lcrypt -lrt
mv -f .deps/rt_netlink.Tpo .deps/rt_netlink.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -fPIE  -ggdb -pie  -o zebra zserv.o main.o interface.o connected.o zebra_rib.o zebra_routemap.o redistribute.o debug.o rtadv.o zebra_snmp.o zebra_vty.o irdp_main.o irdp_interface.o irdp_packet.o router-id.o zserv_linkmetrics.o linkmetrics_netlink.o ioctl.o ipforward_proc.o if_netlink.o  rt_netlink.o rtread_netlink.o   -lcap   ../lib/libzebra.la -lcrypt   -lrt
libtool: link: gcc -fPIE -ggdb -pie -o .libs/zebra zserv.o main.o interface.o connected.o zebra_rib.o zebra_routemap.o redistribute.o debug.o rtadv.o zebra_snmp.o zebra_vty.o irdp_main.o irdp_interface.o irdp_packet.o router-id.o zserv_linkmetrics.o linkmetrics_netlink.o ioctl.o ipforward_proc.o if_netlink.o rt_netlink.o rtread_netlink.o  -lcap ../lib/.libs/libzebra.so -lcrypt -lrt
make[2]: Leaving directory '/home/jandh/dat/Projects/ospf-mdr/zebra'
make[1]: Leaving directory '/home/jandh/dat/Projects/ospf-mdr'

Stderr:

/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_get_flag'
/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_set_proc'
/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_init'
/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_clear'
/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_free'
/usr/bin/ld: ../lib/.libs/libzebra.so: undefined reference to `cap_set_flag'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:559: zebra] Error 1
make[1]: *** [Makefile:468: all-recursive] Error 1
make: *** [Makefile:400: all] Error 2

me@mylaptop:/home/me/dat/Projects/568_core-Common-Open-Research-Emulator >

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CORE Version 7.3.0
 - EMANE Version ?

**Additional context**
-

**Comment by bharnden** [comment]
Is this the Desktop version of Ubuntu? It appears you are installing CORE itself fine, but OSPF MDR that it is trying to help with is having issue for some reason.

I do not run into this in my relatively clean Ubuntu 20 Desktop myself, but I may start 100% clean just to check.

A quick search around on the error says that this may help clear it up and you could try it out.

```shell
sudo apt install libcap-dev
```

**Comment by HaanJde** [comment]
![image](https://user-images.githubusercontent.com/6189537/102808114-1f217400-43c0-11eb-8bb9-944eec0b7b91.png)

libcap-dev was already installed. But running install.sh again. This is an uptodate Ubuntu 20 Xubuntu desktop.

reinstall failed with 'core scripts found, please remove old installation' Uninstall with make uninstall failed, sudo make uninstall succeeded. Running install.sh failed again but this time with 'core scripts found, please remove old installation' too.

**Comment by bharnden** [comment]
```shell
# uninstall at your point
cd <repo>
inv uninstall

# install again
inv install
```

**Comment by bharnden** [comment]
Did this get resolved? I'll close if you figured it out.
