### ISSUE TITLE
[BUG] core-pygui does not store user files for services

### ISSUE THREAD

**Issue by carlosaguilarmelchor** [coreemu/core#550]
**Describe the bug**
When a file is added to a service on core-pygui it is not stored in the associated xml file. Upon reopening the xml the file does not exist any more. If the files are added by editing the xml file, they are removed by core-pygui when the xml is saved again.

**To Reproduce**
1. Open core-pygui
2. Add a PC node
3. Right-click on it and click on services
4. Choose a service (e.g. UserDefined)
5. Click on configure
6. Fill a filename (optional: click on the newfile "whitepage button")
7. Fill some content (click on the save to disk button)
8. Click on apply
9. Click on save
10. Save the xml with Ctrl-s and choosing a location
11. Close py-gui
12. Open py-gui
13. Load the file
-> The PC node does not have the file any more.

**Expected behavior**
I expect the file to exist when I reopen the xml.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CORE Version 7.1.0

**Additional context**

**Comment by bharnden** [comment]
should be fixed on develop, thanks
