### ISSUE TITLE
[BUG]core-pygui cannot display on srceen normally

### ISSUE THREAD

**Issue by hugo921** [coreemu/core#552]
**Describe the bug**
when i start core-pygui in the terminal,the first time it looks like normal without any operation.when i drag some element,it show fuzzy ,it looks like unable to redraw.

**To Reproduce**
1. start core-daemon in the terminal
2. start core-pygui in the terminal
3. drag some elements or just click and drag some icon
5.restart core-pygui
6.see error again
**Screenshots**
screenshot was made on the bottom attach files

**Desktop (please complete the following information):**
 - OS: [e.g. centos 8 stream in the vmwa
![2021-02-16 16-49-49 的屏幕截图](https://user-images.githubusercontent.com/33097584/108040443-4327cb80-7078-11eb-9dd7-28923da417f7.png)
![2021-02-16 16-50-25 的屏幕截图](https://user-images.githubusercontent.com/33097584/108040448-458a2580-7078-11eb-94e4-af610480d45d.png)

re virtual machine]
 - CORE Version [7.4.0]

**Comment by bharnden** [comment]
I could only assume it may be related to a newer library in that distribution. I would personally fall back to CentOS 7, if you need to use CentOS. CentOS 8 Stream is not a path we plan to validate and test against in the future, due to the direction it has taken.

**Comment by hugo921** [comment]
thanks very much，i solved it by execute “yum update” command。
