### ISSUE TITLE
SDT3D output does not work with CORE 7.4.0

### ISSUE THREAD

**Issue by martin20082018** [coreemu/core#560]
**Describe the bug**
If I run sample1.imn (is part of the installation package) with the "normal" GUI (started with core-gui) and enable in the options - SDT3D output --> and run the model.
I see that the nodes move around in the Core-GUI, but NOT in the SDT3D application.
This feature works in my **old CORE version: 5.2.2**
but not with the new one: **CORE version 7.4.0**

**To Reproduce**
1. Load model sample1.imn
2. Click on Sessions and then on Options
3. Enable SDT3D output and check if port 50000 is used
4. go to view and start SDT3D or start the app from a terminal ...   ./sdt3d.sh  (it doesn't matter which way you start the script)
5. start the model
==> I see that the nodes move around in the Core-GUI, but **NOT** in the SDT3D application.
==> IF I manually move (drag) one node in the CORE-GUI around --> then I see the node moves also in the SDT3D GUI - but no movement when the mobility script moves the nodes around.

**Expected behavior**
Both CORE GUI and SDT3D nodes move according the mobility script...

**Screenshots**
you see that 

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - CORE Version: 7.4.0
 - EMANE Version 1.2.7

**Additional context**

best regards,
Martin

**Comment by bharnden** [comment]
What version of SDT are you using? and are you sure that you are starting SDT in a CORE compatible way? There is a CORE specific startup script in SDT, but it has not been maintained and will fail, if I recall. SDT needs to be told to listen for connection to allow CORE to connect.

**Comment by martin20082018** [comment]
Cloned and built the development branch yesterday. In the GUI there is already version 7.5.0...
I have the same issue.
My SDT3D version is the latest **2.1c from 2019**...

**OR do you suggest  that I clone the master branch and build SDT3D new?**

**I also logged all the messages sent by CORE to SDT3D...** it simply stops sending commands after everything is initialized... - NO movement seen on SDT3D... when mobility script is executed. The nodes move correctly in the CORE GUI.
**What do you suggest ? Could it be that the SDT3D release from 2019 is simply too old?**
BUT no message is sending when mobility script runs... this seems to me an issue on CORE side.

The **runtime-hook.sh** script I used in my older CORE release. It seems that this is not executed correctly... I investigate more into this today.

**Comment by bharnden** [comment]
Well the fixes were put in today, so yesterday would be too old, but not sure your time zone to related to.

Not enough information to know about your hook script and what's going on there. 

I imagine if you pull the latest from todays changes, mobility should work in SDT based on the sample1.imn scenario you gave.

**Comment by martin20082018** [comment]
I double checked the souces and I saw the modification you did in the files... But maybe something went wrong removing the old version 7.4.0 from the system and 

**REMOVE CORE from the system**
cd <CORE_REPO>
sudo make uninstall
make clean
./bootstrap.sh clean 

**I addtion I tried:**
sudo apt remove core

**Building & Installation of CORE:**
./bootstrap.sh
./configure
make
sudo make install

**Do you suggest a better way to ensure that the old version is removed and building CORE and install it in a correct way?**

I clone an build CORE again!

**Comment by bharnden** [comment]
The current installation is a bit different then those commands alone before and covered here: https://coreemu.github.io/core/install.html

This is likely related to your current problems.
