### ISSUE TITLE
Problems with core-daemon

### ISSUE THREAD

**Issue by Ivoo25** [coreemu/core#563]
Hello, Im having some issues that I think are all related.
My issue basically is that I cant launch the core-daemon service
>> sudo service core-daemon start

Returns...

--> Failed to start core-daemon.service: Unit core-daemon.service not found.

If I type: /etc/init.d/core-daemon start
I get: bash: /etc/init.d/core-daemon: No such file or directory

any help please?
![image](https://user-images.githubusercontent.com/25638033/112467562-f786d280-8d45-11eb-9b37-ab5a2f1a4ec1.png)

**Comment by bharnden** [comment]
Not sure what version you are trying, but there is no sysv service, so that sounds about right. What version are you using?

There is a systemd service, I believe this is right below
```shell
sudo systemctl enable core-daemon
sudo systemctl start core-daemon
```

**Comment by bharnden** [comment]
Hopefully you resolved your problem, will close if I don't hear any more.

**Comment by bharnden** [comment]
@harrycha thanks for input, I will note this on the installation page.

**Comment by bharnden** [comment]
added to documentation on develop for next release
