### ISSUE TITLE
[BUG]trying to turn on DHCP server on MDR Router with 2 interfaces

### ISSUE THREAD

**Issue by astaikos316** [coreemu/core#567]
**Describe the bug**
Using current build from master.  Have a simple network setup.  Two OSPFv3MDR routers with a wireless interface and an ethernet interface to connect to external physical machines.  When trying to configure a DHCP server on each router I get an error stating "IndexError: index out range for address range size!" and the DHCP server config file is blank.  

**To Reproduce**
1. Add two MRD routers
2. Add Wireless LAN and connect routers to it
3. Add rj45 Physical Interfaces
4. Connect rj45 physical Interface to each router
5. Try to configure DHCP server on each router and error shows in CEL as well as core-daemon console "IndexError: index out range for address range size!"

**Expected behavior**
Should be able to configure DHCP servers without errors and get proper config files

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version - currnet build from master
 - EMANE Version Not Installed

**Comment by bharnden** [comment]
Thanks, will take a look at this.

**Comment by bharnden** [comment]
Fixed on develop

**Comment by astaikos316** [comment]
@bharnden how can i fix it? can i fix it on my installation?

**Comment by bharnden** [comment]
You can either modify the files based on the commit fix on develop, or adjust the network prefix for the wireless link.

It was having issue with the `/32` on the wlan link, which would now be skipped.

**Comment by siliconja** [comment]
I ran into this yesterday on a normal/wired scenario default "/24" network.

I had to go customize the DHCP (server) service, modify the `/etc/dhcp/dhcpd.conf` file and change this:
`subnet 10.0.0.10 netmask 255.255.255.0 {`
to this:
`subnet 10.0.0.0 netmask 255.255.255.0 {`

**Comment by astaikos316** [comment]
Thank you.  Pulling the files from the develop branch worked for me.

**Comment by astaikos316** [comment]
@bharnden Is it normal though to not see the DHCP server process in the processes list when it is running (physical clients attached are getting expected IP addresses.

**Comment by siliconja** [comment]
double-click on the node, and `ps ax` there should list a `dhcpd` process

if it is not running, run it manually by just typing `dhcpd` and it will inform you of any config errors

**Comment by astaikos316** [comment]
Also the init.d script is not created when installing from source during install like it is when installing from a package.  is there a way to create it so the core-daemon starts when the system starts up?

**Comment by bharnden** [comment]
init.d and sysv are considered deprecated in the newer releases, but there is a systemd service installed and available.

**Comment by bharnden** [comment]
@siliconja can you provide an example that causes that issue? I can try to verify

**Comment by astaikos316** [comment]
I corrected the DHCP issue.  I also had to change the subnet in the config files.  I cannot find the systemd service you are referring to though @bharnden

**Comment by bharnden** [comment]
There should be a file here: `/lib/systemd/system/core-daemon.service`

I believe the following should enables it, then you can start/stop:
`sudo systemctl enable core-daemon`

**Comment by siliconja** [comment]
Here are example imn files of the original broken case (notes: was using Ubuntu 20.04 with `isc-dhcp-server` apt installed).

The only difference between the two is that I customized the dhcpd.conf and changed that subnet line from "10" to "0" (/24).

(GitHub makes me add a ".txt" extension.)

[dhcp-server-client-broken.imn.txt](https://github.com/coreemu/core/files/6367519/dhcp-server-client-broken.imn.txt)
[dhcp-server-client.imn.txt](https://github.com/coreemu/core/files/6367520/dhcp-server-client.imn.txt)

Node n4 has the DHCP client configured, so it gets its address automatically.

**Comment by bharnden** [comment]
Thanks @siliconja, I'll take a look, maybe it is just the address generated.

**Comment by bharnden** [comment]
@siliconja Thanks was able to fix that part of the issue as well.
