### ISSUE TITLE
can't open terminals for node on remote server

### ISSUE THREAD

**Issue by PengfeiM** [coreemu/core#568]
I can ssh root@remoteserver.ip without password after my configuration. 
But I can't open the terminal for node on remote server.
It shows that I use the username on main server to ssh the remote server and went wrong. 
Do I need to make all the username on all servers be the same?

**Comment by bharnden** [comment]
the remote terminal session is opened as the current user of the GUI, which typically is not root. So if you want that as well, you need to configure that user too. Unless you potentially ran the GUI as root, but that is up to you.

https://coreemu.github.io/core/distributed.html#remote-gui-terminals
