### ISSUE TITLE
Traffic not being sent outside of core

### ISSUE THREAD

**Issue by harrycha** [coreemu/core#569]
Hi all, 

Similar to issues ##242 and #187, I am trying to use RJ45 to connect to outside machines. I am trying to take 2 ports (ens192 and ens224) and connect them together via some routers as shown in the diagram. When I ping from the connected machines to their respective ports, I see the tcpdump shows requests **and replies** from CORE and the Ubuntu Linux vm it's on. However the machine that originally pinged it doesn't receive the reply. This leads me to believe that the response from CORE isn't leaving the vm. I have changed settings on my ESXi server to promiscuous mode as suggested in issue #187 but it hasn't changed anything. Should I be looking into the network controller options or what? Any help is appreciated!  

![image](https://user-images.githubusercontent.com/33790468/118571328-c924e280-b74b-11eb-8ffc-a67f9050569c.png)

**Comment by bharnden** [comment]
It's hard to say without knowing the complete setup and being able to see what is going on. Assuming the outside machines are addressed in a way to align with the network and can route to the nodes within CORE.

Sounds like you have tried the right settings at least for using the RJ45s typically within a VM.

**Comment by harrycha** [comment]
Yeah, I'm sure the outside machines are addressed correctly as they pinged back and forth. Only after confirming that did I move forward with CORE. I'm using CORE_VERSION 7.5.1 and Ubuntu 20.04.2 LTS, what more would you like to know about the set up? Are there any tutorials on generating traffic within CORE and sending that out through an RJ45 port? Is this even possible?

**Comment by bharnden** [comment]
I did not mean your addressing between the real nodes themselves, but how they are addressed to interact with what is setup in the CORE scenario.

The RJ45 interfaces traditionally take away all normal functionality from an interface and allows it to behave as a dumb pipe, so to speak. Usually the only caveat being if you are not running on bare metal and need to setup promiscuous mode in the context of a VM. Not sure what more you can really tell me as I don't have your exact setup to look at in this case.

**Comment by bharnden** [comment]
Maybe starting off with just a single node connected to an RJ45 in CORE, and being able to ping that node directly from the outside machine and vice versa would be an easier place to start and limit what you are looking at and dealing with.

**Comment by harrycha** [comment]
When you say that the RJ45 interface in CORE allows this "dumb pipe" behavior, it sounds like exactly what I am aiming for. Maybe I should have prefaced this by saying I am only allocating the IP addresses inside CORE. Meaning the Linux host isn't determining the addresses for the ports. When I allocated IP addresses to ports using Linux, the pings worked from both sides. Ideally I'd like this to be automated using CORE's Python API later. 

Now only using a single RJ45 node in the CORE gui, I can ping the IP address (172.25.1.1) directly from the outside. The node's tcpdump shows that it receives the request and replies but the outside machine at 172.25.1.2 doesn't see it. This is why I'm wondering if there is a setting or permission blocking from traffic being sent outside.

![image](https://user-images.githubusercontent.com/33790468/118863521-ff2da800-b8ac-11eb-87ca-8e6adbec4de3.png)

Updated network for testing as suggested: 
![image](https://user-images.githubusercontent.com/33790468/118866078-a3185300-b8af-11eb-80c0-4fcab203e70b.png)

**Comment by bharnden** [comment]
Maybe try starting with a "PC" node and not a router, one that has default routing.

**Comment by bharnden** [comment]
Beyond that, if the packets are not leaving the VM, I can only leave that up to the setup of the environment and what is being used. I am only familiar with enabling promiscuous mode on the VM interfaces being used. I can ask others for any other thoughts, but that is all I know of for now.

**Comment by harrycha** [comment]
I tried with a PC node but didn't see any improvement. Yeah and like post #187 mentioned, I did enable promiscuous mode. In that same post you reference a now dead link (http://coreemu.github.io/core/usage.html#rj45-tool) would it still be beneficial?   Maybe its also worth mentioning that I have 3 network cards, one for managing the VM Host (172.25.200.101) and the other 2 that I am trying to bridge through CORE (172.25.1.1 and 172.25.1.5). 

Is there a smaller test with the RJ45 sending a simple ARP through CORE that I should look at? Are you able to reproduce this and have it work? Thanks a lot for all the help!

![image](https://user-images.githubusercontent.com/33790468/118880555-feead800-b8bf-11eb-8027-437879e01cd1.png)

**Comment by bharnden** [comment]
I don't have a setup to test with and I would really need your exact one to know any better, so there's not much I can do there.

This is the updated link, but likely not any different than what you know: https://coreemu.github.io/core/gui.html#rj45-tool

Just to be clear, you enabled promiscuous mode on the VM interfaces you are using in CORE? If you are failing to see any packets come out of a CORE RJ45 interface to your actual hosts, I can only assume it is related to the VM software being used and its settings.

**Comment by harrycha** [comment]
Right, for the interfaces that are being used in CORE I have enabled promiscuous mode. I'm going to try another set up on VirtualBox to confirm that it's not a CORE issue. If I can get the RJ45 simulation working in that environment then as you said, its the VM software.

**Comment by harrycha** [comment]
Hey @bharnden,

I got it working! You were right it was the virtualization software. In ESXi there is another security parameter along with promiscuous mode called forged transmits. Because CORE changes the mac addresses of these linked network interfaces it is considered a forged mac address. Turning that setting on allowed us to send traffic from CORE through an RJ45. Another solution would have been to change the mac addresses to comply with what ESXi originally set them to.

**Comment by bharnden** [comment]
Glad it worked out, CORE doesn't change the mac address that I can recall. I can only assume it is the mac address of whatever potential hosts you are replicating within CORE. So if any of their packets are routed out, sounds like the above configuration you noted would cause problems.
