### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PengfeiM** [coreemu/core#570]
**Describe the bug**
When I start core-daemon with root account and with emane installed by usual account with sudo, the start failed and print the error information as follow:
![image](https://user-images.githubusercontent.com/45191163/118786917-e03b1000-b8c4-11eb-8634-61200044f43d.png)

I tried to reinstall emane with root, but here is another error:

**To Reproduce**
1. su root
2. core-daemon

**Expected behavior**
no error report

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7
 - CORE Version: 7.5.1
 - EMANE Version: 1.2.7

**Additional context**

**Comment by bharnden** [comment]
That looks like a python2/3 issue. How did you install EMANE and the python bindings?

**Comment by PengfeiM** [comment]
I use th command line inv install-emane

**Comment by bharnden** [comment]
Taking a further look it seems to be related to `protoc` not being 3.0+ on CentOS 7. So you can either install and add to path a newer `protoc` that is compatible.

Or you can use the python build tool to generate the EMANE python proto files by modifying their Makefile.am.

First remove old version:
```shell
core-python -m pip uninstall emane
```

Then rebuild emane python bindings:
```shell
cd <EMANE REPO>/src/python
make clean
# below to update to use the installed python3 tool or skip this step if you get protoc 3.0+
vi Makefile.am
# replace all instances of protoc with the following: $(PYTHON) -m grpc_tools.protoc
make
core-python -m pip install <EMANE Repo>/src/python
```

**Comment by PengfeiM** [comment]
I upgraded the protoc to 3.0+(3.11.4&3.6.1), it's still not working.    
I can't even install emane
![image](https://user-images.githubusercontent.com/45191163/118942268-248de500-b985-11eb-8019-6a754a24cee7.png)

the second way I tried and failed, too.

**Comment by bharnden** [comment]
I am not sure what you are trying, but I did not say to run `inv install-emane` again, the modifications above are purely to re-install the emane python3 bindings.

It may be possible you have put things into some state of disarray at this point.

You only needed to uninstall the python bindings from the core environment, make clean and delete the existing generated protobuf files, then rebuild them with a python3 compatible protoc.

Then finally reinstalling them, with the last command I listed.

EMANE itself would still be installed and not impacted by any of the above.

In my case, I specifically modified their Makefile.am to use the python3 tools version `$(PYTHON) -m grpc_tools.protoc` for all lines that was previously using `protoc`. Poking around seems to indicate 3.0+ is also python3 compatible, so I assume that would work too.

But, based on your example, I don't know if you tried the right cases. If you installed a newer `protoc`, did you remove the old one? Does running `protoc --version` show the version you expect?

**Comment by bharnden** [comment]
If you get the bindings right, since this is purely an EMANE install related issue. You should be able to run the following command without issue. This is also assuming you installed CORE without using `-l` for the local install.

This is the specific import in your original example, triggering the python3 incompatibility from the emane python bindings.
```shell
core-python -c "from emane.events import LocationEvent"
```

**Comment by PengfeiM** [comment]
Thanks a lot, I have fixed the problem.  Sorry about the misunderstanding. 
I uninstalled the protoc 2.5.1 and installed the 3.0+ version, then reinstall the emane python bind, it worked!
Again, thanks for your patient answering.
