### ISSUE TITLE
node reset/re-initialization using grpc python api

### ISSUE THREAD

**Issue by mzy2240** [coreemu/core#571]
Is it possible to reset or reinitialize one single node and keep other nodes untouched? Let's say I am using the vcmd command to run a series of blocking execution in a single node, besides stop and rerun the whole core emulation (which might be time-consuming if other nodes are running heavy tasks), is there any efficient way to tackle it?

**Comment by bharnden** [comment]
I guess that depends on what you really want. You could use something like `vcmd` or python code to run commands. You can use those same semantics to kill those commands and restart them, if that is your desire.

**Comment by mzy2240** [comment]
Ok if the original vcmd command is a blocking command(let's say it is calling tshark to do an continuous probing), does that mean I have to wrap it into a multi-thread python script so that the node will be responsive to the later incoming tcmd command?

**Comment by bharnden** [comment]
No, you can kill the process without issue, but if you are trying to do it from the same program and it is blocking, then yes you would need to put the blocking one into a thread or some other case to not block yourself.

You could also use the grpc API to run node commands and background processes, etc, if desired.

**Comment by mzy2240** [comment]
Thank you for your answer! Is there any difference between using vcmd+nodechannel vs node command via grpc api?

**Comment by bharnden** [comment]
grpc can allow you to not block and is more specific for interacting with a core api, rather than directly using vcmd. At the end of the day it is all the same though. Up to you.

**Comment by mzy2240** [comment]
Thanks! It's clear now.
