### ISSUE TITLE
Can't run the gRCP examples

### ISSUE THREAD

**Issue by harrycha** [coreemu/core#572]
Hi all, 

I am very confused on how to run the gRCP. I open a gui and then hit =>"File" => "Execute Python Script..." . I then find the example scripts as seen in https://github.com/coreemu/core/tree/master/daemon/examples/grpc. They execute however nothing appears. It says on the docs https://coreemu.github.io/core/grpc.html that I have to switch to and attach to these sessions but how would I do that?

![image](https://user-images.githubusercontent.com/33790468/119206132-29b76680-ba4f-11eb-9311-bb139bc62c0b.png)

**Comment by bharnden** [comment]
"Execute Python Script..." serves an entirely different purpose than what you are trying and likely shouldn't exist.

To run the example gRPC scripts you would use `core-python` if you used the default installation. Or run it with `python3`, if installed locally.

Like so, assuming the core-daemon is running.
```shell
core-python example.py
```

**Comment by harrycha** [comment]
That clears it up so much. I thought the docs mean that core-daemon should be running in the background and we execute the scripts somehow. But I'll try executing the gRPC script with core-daemon (or python).

**Comment by bharnden** [comment]
No, you were right.

* The core-daemon must be running, this provides a gRPC server
* You then run an example script (which is a client) to interact with it

`core-python` is not the `core-daemon`, but it is a convenience to provide a `python` like command for core's python virtual environment.

**Comment by harrycha** [comment]
When I try running the script I get an exception calling /tmp/pycore.1 . For some context, I preformed a local install. This error doesn't happen on my other instance which has the virtual environment. I also noticed I can't `sudo` call the `core-python` command. Any thoughts on if the exception in calling pycore.1 and `sudo core-python` issues have something in common?

![image](https://user-images.githubusercontent.com/33790468/119551110-41e8f780-bd67-11eb-99fc-fd07d161dbca.png)
pycore.1

![image](https://user-images.githubusercontent.com/33790468/119551690-e8cd9380-bd67-11eb-9d21-b0efc33d1ea9.png)
`sudo core-python`

**Comment by bharnden** [comment]
`core-python` only exists to help support the virtual environment, it should not exist for a local install. With a local install you would just use `python3`.

If you have lingering left over directories or processes from failed runs, you can use `sudo core-cleanup` to help remove them.

**Comment by harrycha** [comment]
I made a mistake in explaining my context. Whenever I use just `python3` I had issues finding the core module. My workaround then was to perform a virtual install (maybe the reason why there are so many problems). `core-python` works as a user but not in root. Same with `core-cleanup` as shown in this picture:

![image](https://user-images.githubusercontent.com/33790468/119554976-516a3f80-bd6b-11eb-8afd-11e381444711.png)


Should I now just abandon this VM because the install was so messy or could fixing the exception of pycore.1 be enough for me to just work with the gRPC API?

**Comment by bharnden** [comment]
Might be easier to start over. If you don't have familiarity with python to understand that part and why things do what they do, I would start over.

**Comment by harrycha** [comment]
Hi @bharnden, I ended up calling `core-cleanup` using the full path like, `sudo /home/user/coredirectory/core-cleanup`. This deleted the /tmp/pycore.1 instance and allowed me to run the wlan.py example!
