### ISSUE TITLE
Issues with creating an RJ45 Node through the gRPC API

### ISSUE THREAD

**Issue by harrycha** [coreemu/core#574]
Hi all, 

I am trying to connect with one of my RJ45 nodes using the Python gRPC API. However I get an error similar to issue #461, with "RJ45Node3 does not exist". What is the equivalent to NodeOptions using the gRPC API? 

![image](https://user-images.githubusercontent.com/33790468/119907488-62a77d80-bf1e-11eb-98ee-3b1a922232c2.png)

**Comment by bharnden** [comment]
The issue you linked explained the problem. You must define an RJ45 node name to be the name of an interface on the host. When this node starts that interface will no longer be useable as well.

This documentation talks about the RJ45 node: https://coreemu.github.io/core/gui.html#rj45-tool

**Comment by bharnden** [comment]
I assume this has been resolved, let me know otherwise and I can try and help.

**Comment by harrycha** [comment]
Passing in the RJ45 names as arguments when creating those nodes fixed the issue. Thank you for all your help!
