### ISSUE TITLE
[help-wanted] Can't ping each other from MDR nodes using EMANE TDMA model

### ISSUE THREAD

**Issue by szl0144** [coreemu/core#576]
Hi，
I integrate CORE with EMANE package to have a TDMA simulation, I use 3 MDR nodes and one WLAN in the network. The daemon runs without any errors, but I can't ping other MDR nodes from each one. I check the routing table, I found the there are only 172.16.0.0/28 record in the routing table instead of nodes' IP 10.0.0.0/28. 

I change the nodes IP to 172.16.0.0/28 and try to start a traffic, but there is no mgen.log file in the tmp/pycore.session/n1.conf/var.log.  I used to use the same settings the last summer to have the same simulation, I remember I didn't face this kind of error..... Can you give me some suggestions on how to debug it? Thanks!

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - CORE Version [e.g. 7.5.1]
 - EMANE Version [e.g. 1.2.6]

Best,
Shaoyi

**Comment by bharnden** [comment]
EMANE uses a control network to help send traffic around. Which, usually would be the 172 address you described. You would not want to address your nodes actual IP addresses to be the same.

**Comment by bharnden** [comment]
If you leave the addresses as the default values, you can always evaluate if the emane process is running using `ps aux` and investigate any of the logs in the node directory if something is failing.

**Comment by bharnden** [comment]
I assume this was resolved, let me know otherwise
