### ISSUE TITLE
[FEATURE] core-cli query node should also contain position and geo

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#578]
**Is your feature request related to a problem? Please describe.**

We often use external (bash/python) scripts to interact with or visualize different aspects of the simulation. 
`coresendmsg` and `core-cli` can be used to update positions but for external tools to extract the position we always parse the `*.xy` files in the filesystem as `core-cli query node -i 39983 -n 1` only delivers the following output:
```
ID   | Name    | Type
1    | n1      | DEFAULT
Interfaces
Connected To | ID  | MAC Address       | IP4 Address        | IP6 Address
wlan3        | 0   | 00:00:00:aa:00:00 | 10.0.0.10/24       | 2001::10/128
```

**Describe the solution you'd like**

Either adding pos/geo to the default output or add a verbose flag that will contain these information would be really helpful - also for interactive debugging of headless simulations.
Similarly, having `query session` have all positions/geo locations in a tabular view for all nodes at once would be really nice!

**Describe alternatives you've considered**

`--json` does seem to contain these information but also much more. This behavior is kind of undocumented. It took me a while to find this. It's fine for automated parsing but pretty overwhelming for interactive analyses.

Thank you for the great work so far!

**Comment by bharnden** [comment]
Thanks for the input. The JSON flag may be going away, possibly. I can look into adding positions as well.

It is also always possible to leverage the gRPC API directly within code or a standalone script to mold data into any shape you like. It does require some extra work, but it is a possibility and can be more specific.

**Comment by gh0st42** [comment]
as the `-js` flag is now gone unfortunately and coordinate overview is not (yet) part of the `core-cli query session` output are there any plans or updates on this? 

writing gRPC client scripts for everything is much more work and error-prone (as python and dev environment must be kept in sync and gRPC interface is still changing) than using the existing CLI tools and just some bash scripts to parse the output.

**Comment by bharnden** [comment]
> and coordinate overview is not (yet) part of the core-cli query session output are there any plans or updates on this?

What do you mean by this? I am assuming you want a call to query a session for the entire complete picture as one call, vs all nodes individually?

**Comment by gh0st42** [comment]
Correct. I want to see all x/y and/or geo coordinates with one call - they are already pulled from the daemon through the session query gRPC call anyhow, just not passed to the user anymore.
We often use this for debugging headless sessions or periodically recording x/y to plot the movements later on. 

In the past the json output contained everything (also including currently active wireless links) which was very useful to automate integration tests or debug stuff. 

As a workaround, I quickly hacked together some [helper tools](https://github.com/gh0st42/coreemu-rs/tree/coreemu8/examples) using my rust gRPC client library but it is much more convenient if the standard tools that come with every coreemu installation already contained the most useful stuff to debug basic scenarios.

For me, an extra parameter such as `core-cli query positions` or `core-cli query geo` would also be fine. 
I understand that json output is probably unstable and will change over time as the gRPC API changes. 

If you say this bloats `core-cli` too much, the whole tool is to be made obsolete or you'd prefer a PR with the positions or json output added it would also be good to know :)

**Comment by bharnden** [comment]
I think your asks are reasonable, I would probably look to add the json support back in with the caveat you noted, that it could change if the related protobufs change. That might be reasonable to deal with though and ideally don't end up changing often/much.

**Comment by bharnden** [comment]
adding the json flag back, which will have similar values, some cases may not be directly protobuf translation, but the session dump will be.

also adding geo output to the session overview for the simple printed view, hopefully these are ok for now.

these are on develop for next release.
