### ISSUE TITLE
[Help-wanted] ModuleNotFoundError: No module named 'core.emane' 

### ISSUE THREAD

**Issue by szl0144** [coreemu/core#579]
OS Ubuntu 18.04
EMANE 1.2.6
CORE:7.1.0
Hi,

I run a standalone script emane80211.py integrated with EMANE. I use python3 filename to run the script, but I face a error No module named 'core.emane'. I reinstall CORE but still face it, can you please tell me how to solve it?

Best,
Shaoyi

**Comment by bharnden** [comment]
The current default install, places things into a python virtual environment. So the command line python3 interpreter would not work as you described. You could use `core-python` instead to function in the same way.

https://coreemu.github.io/core/install.html#automated-install

**Comment by szl0144** [comment]
Hi,

Thanks, I try to use the core-python, but I face a command not found error. Is it because of the env path? I didn't find the path of core-python using which core-python. Thanks!
Best,

**Comment by bharnden** [comment]
Possible, but for Ubuntu Desktop that is typically not a problem. The default path for executables is `/usr/local/bin` unless you used the option to change that during the install, or used the local install option.

**Comment by szl0144** [comment]
I check the env path and found /usr/local/bin is already in it

> Possible, but for Ubuntu Desktop that is typically not a problem. The default path for executables is `/usr/local/bin` unless you used the option to change that during the install, or used the local install option.

Hi,

I just checked my PATH and found `/usr/local/bin` is already in it. I can run core-daemon and core-gui without any errors. Can you please tell me whether there is any other potential problem? Thanks!

Best,

**Comment by bharnden** [comment]
I would also use the latest at least to start 7.5.1. But the default install, without any options is a virtual environment install. That also installs `core-python` as a convenience to leverage the virtual environment. It is described in the documentation above.

**Comment by szl0144** [comment]
> I would also use the latest at least to start 7.5.1. But the default install, without any options is a virtual environment install. That also installs `core-python` as a convenience to leverage the virtual environment. It is described in the documentation above.

Hi,

I upgraded my CORE 7.1.0 to 7.5.1 and found the core-python is installed at the default pathI will test the new version CORE to see if it can run normally with my emane. Thanks! 

Best,
