### ISSUE TITLE
EMANE python binding are not installed

### ISSUE THREAD

**Issue by Mark643** [coreemu/core#580]
When trying to use the ENAME plug in on Core 7.5.1 I get the CEL activate with the message "Python binding are not installed".

I have enquired on ENAME on GitHub but they think it maybe a Core problem, is there any advice you could give?

**Comment by bharnden** [comment]
There is an install task to try and help with using emane `inv install-emane`. You should be able to run this after the normal installation.

This is covered a bit here: https://coreemu.github.io/core/install.html#installing-emane

Basically the default installation for CORE goes into a python3 virtual environment. You need to have EMANE installed and then have the EMANE python3 bindings installed into that environmnet.

**Comment by bharnden** [comment]
I assume this was figured out, if not let me know.

**Comment by Lithimlin** [comment]
Hey, I'm haveing the same issue: When trying to start an emulation with an Emane node, I get the bind error.

I've installed both Core and Emane: First I installed Core, then ran the `inv install-emane` and continued to install it following Emane's installation guide.

I'm on Ubuntu 22.04 with Core 9.0.1 and Emane 1.4.1

**Comment by bharnden** [comment]
You can refer to the discussion here and the answer as well as refer to the Dockerfiles for specific commands used to account for EMANE bindings.

https://github.com/coreemu/core/discussions/721
