### ISSUE TITLE
[Help-Wanted] Generate traffic using MGEN with CORE Python API.

### ISSUE THREAD

**Issue by szl0144** [coreemu/core#581]
Hi，

I am going to generate a general MGEN traffic using CORE Python API, can you please tell me where I can find a template to do a simple practice? Thanks!

One more question is I am going to change the default broadcast routing table in the MDR node and run a demo using Python script, can you give me some hints about how to write a customized static routing table in an MDR node when it is initialized?

Thanks!

Best,
Shaoyi

**Comment by szl0144** [comment]
Hi, the second problem is done. I generate an EMANE TDMA session using GRCP and change the routing table using .node_command() function. The routing table comes to a unicast from n1 (10.0.0.2) to n3 (10.0.0.4) right now.

![image](https://user-images.githubusercontent.com/40918217/121822153-83383d00-cc6b-11eb-8238-b781f760d039.png)

**Comment by bharnden** [comment]
Seems like you found the answer for this, let me know otherwise.

**Comment by szl0144** [comment]
> Seems like you found the answer for this, let me know otherwise.
Hi, bharnden

Thanks for your follow-up. I still have one small question. I follow the instruction in Discord, and run the MGEN successfully. Because I am going to start a traffic generate in node1 and start a traffic listening in node3. I need to run two commands simultaneously in both two nodes, but when I run the first command in node1, it seems python stuck into this thread and didn't come out and run the second command. Do you have any suggestion about how to run multiple threads in one Python script?

Best,
Shaoyi

**Comment by bharnden** [comment]
If you are using node_cmd you set shell to True and background the command you are running.

Like so:
```shell
echo hello &
```

**Comment by szl0144** [comment]
Make sense, thank you for telling me that. No other questions.
