### ISSUE TITLE
[BUG] Unknown error within gRPC API   

### ISSUE THREAD

**Issue by harrycha** [coreemu/core#586]
**Describe the bug**
Hi all, I was playing around with the core-daemon file, reassigning IP addresses and port values. I reverted back the changes based on the core/daemon/scripts/core-daemon file. But there might have been more changes to other files. However, even after reverting back the changes I kept getting errors from the gRPC API. Specifically this `core_server` applicationwhich doesn't allow me to use the add_node function anymore. 

Here is my code:

```position = Position(x=350, y=300)
n1 = Node(type=NodeType.DEFAULT, position=position, model="router")
response = self.core.add_node(session_id, n1)
n1_id = response.node_id
self.n1_id = n1_id
```

Here is the error:

![image](https://user-images.githubusercontent.com/33790468/127072618-6ad9da83-e2a9-4a9f-a2d3-729125df515f.png)

The code has worked before but there might be configurations in core-daemon or python that are at the root of the problem. Either way the I've tried looking into the `core_server` with no luck, it doesn't help that the gRPC error code is also 'Unknown'. Any help here would be appreciated.

**Comment by bharnden** [comment]
I would assume it is related to your changing the files perhaps in some way, since you talk to it working before.

But looking at the error from the core-daemon side would probably provide you better specifics to solve the issue.
