### ISSUE TITLE
[BUG] installation error

### ISSUE THREAD

**Issue by wallace0x7d0** [coreemu/core#587]
installing core virtual environment ... |Encountered a bad command exit code!

Command: 'cd daemon && poetry install '

Exit code: 1

Stdout:

      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│ 
      1103│         return decode(output)
      1104│ 
      1105│     def execute(self, bin, *args, **kwargs):

Stderr:

**Comment by bharnden** [comment]
It is hard to tell what is going on from this alone. You could potentially try doing those commands manually to get the specific error.

```shell
cd daemon
poetry install
```

**Comment by wallace0x7d0** [comment]
even after the problem mentioned in the installation I managed to run the core with the command $ core-gui-legacy

**Comment by bharnden** [comment]
Based on your last example, seems you may be trying the `develop` branch. I assume that was your intent. But the legacy GUI is different than the python components, so that makes sense. I would run the commands as advised to see the issue.
