### ISSUE TITLE
[BUG] Zebra fails to start - Service(zebra) failed validation

### ISSUE THREAD

**Issue by JacobSweeten** [coreemu/core#588]
**Describe the bug**
When using a standard router with default services, zebra fails to start. I disabled validation so I could better investigate the cause. When I tried to manually run the startup command "bash quaggaboot.sh zebra", I get the error "ERROR: Quagga's 'vtysh' program not found in search path:" (https://github.com/coreemu/core/blob/master/daemon/core/services/quagga.py#L195)

**To Reproduce**
1. Create a router (In my case, one end is connected to an RJ45 adapter and the other to a switch)
2. Run the simulation

**Expected behavior**
Zebra starts with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/11415022/127200841-862f8eb7-4170-472a-9798-29bf7dfb6982.png)
![image](https://user-images.githubusercontent.com/11415022/127200851-4901e3c9-bf6a-4535-80f0-73cd3e56fe83.png)
![image](https://user-images.githubusercontent.com/11415022/127201120-7b41f86c-650a-4049-82ed-abcfdd31005e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - CORE Version: 7.5.1
 - EMANE Version: None

**Additional context**
Running inside VSphere hypervisor

**Comment by bharnden** [comment]
vtysh should be going into `/usr/local/bin`, so maybe it is an installation issue for OSPF MDR. You can check if `zebra` is on your `PATH` and see if there is a disconnect there at some level.

**Comment by JacobSweeten** [comment]
![image](https://user-images.githubusercontent.com/11415022/127213644-4c049bd8-480d-4198-b180-6cca57665ab6.png)
![image](https://user-images.githubusercontent.com/11415022/127213667-b107f160-5158-4cf8-8642-35421942d551.png)

The top image is the service list. The only configuration performed on these is the removal of any meaningful validation command.

The bottom image is the ls of /usr/local/bin and the attempt to use the zebra command.

**Comment by JacobSweeten** [comment]
Does the host machine need quagga-core installed, or is the CORE VM supposed to provide those binaries for the emulated machines?

**Comment by bharnden** [comment]
The software needs to be installed on the machine running the `core-daemon`. The core install script would automatically attempt to install OSPF MDR, if that was used.

**Comment by JacobSweeten** [comment]
I see. I was unaware of how each emulated machine acquired its binaries, so I assumed it was all packaged with CORE. This will be good to know in the future. Installing the following packages resolved the issue:

- quagga-core
- quagga-ospfd
- quagga-ospf6d

Now I am having trouble getting dhcpd to work (Same error, failed to validate). dhcpd is installed on the host machine, and I tried restarting core-daemon.

**Comment by bharnden** [comment]
The default CORE routing services may make some assumptions in configuration for the fork of quagga OSPF MDR, in particular MDR nodes, so installing the default quagga may have issue FYI.

https://github.com/USNavalResearchLaboratory/ospf-mdr

As far as the DHCP based services go, they may be older and their configurations could possibly be outdated to cause failure, but based on someone dive into what may be needed for some of these services, they noted the following.

https://coreemu.github.io/core/services/utility.html

Which may be a different DHCP package than you are using.

COREs current automated install attempts to cover basic software needed for default services used by nodes (ie OSPF MDR). But all other services require outside installation and are not all detailed on exactly what is needed, unfortunately. There is one current discrepancy, which is the `Host` node wants SSH and that is not installed by default, so  in the future that node will be removed to help avoid that type of issue/confusion.

But the bottom line is that all CORE "nodes" share the host file system, so they depend on anything they may need/want to use to be installed or available within it.

**Comment by JacobSweeten** [comment]
After installing the packages listed, all is working. Thank you for your assistance.
