### ISSUE TITLE
[BUG] Using Docker with CORE

### ISSUE THREAD

**Issue by Rafael-Ro** [coreemu/core#592]
Hi all,
I'm trying to simulate the network with docker images.
But after I have been installed "Docker.io" the communication inside the CORE stopped to work 

![Capture](https://user-images.githubusercontent.com/59362845/129869209-226dbc18-caf3-4b60-b33e-62abc2ecf5de.PNG)

Do you have any idea what I'm doing wrong?

 - OS: Ubuntu 20.04
 - CORE Version: 7.5.1

Thanks

**Comment by siliconja** [comment]
If you look at your iptables output (`iptables -vnL`), you'll see that Docker has inserted a default DROP policy on the FORWARD chain (which is used by CORE's Linux bridging to forward packets between namespaces.)  A quick fix is this:
`sudo iptables --policy FORWARD ACCEPT`
