### ISSUE TITLE
What is the best way to update the nodes locations from external source? 

### ISSUE THREAD

**Issue by martin20082018** [coreemu/core#602]
I have one question. From an external simulator items move to new locations (lat, long, alt) - in CORE I have the same items, but the location infos/changes come from the external simulator.

What is the best way to "feed in" this location updates into CORE?
See the image below.
![Geolocation_NEW-external location updates](https://user-images.githubusercontent.com/51402326/133264043-2005d317-0ca7-40dc-bbd2-7b57da1a62f2.png)
 
Is there any code example somewhere for instance?
thanks!

**Comment by bharnden** [comment]
The best way would be over the gRPC interface, which would have to be configured to serve the system externally.

`/etc/core/core.conf`

Update the line to use the address to listen on:
`grpcaddress = localhost`

Note that this does expose your system to have a service that can run arbitrary commands as root.

There is some documentation on using gRPC here; https://coreemu.github.io/core/grpc.html

And the call to move nodes in the current version, would be [here](https://coreemu.github.io/core/grpc.html) and [here](https://github.com/coreemu/core/blob/cbe1db1215f2a622042427c71cc027b210916c6d/daemon/core/api/grpc/client.py#L577).
