### ISSUE TITLE
[BUG] The terminal of the distrubuted node flash back

### ISSUE THREAD

**Issue by nameJa** [coreemu/core#605]
**Describe the bug**

When I try to open a terminal of a distrubuted node, it appears at first and disappears immediately (Using command 'xterm -e'). I try to keep the terminal open when command exit(Using command 'gnome-terminal --window') . At the same time, the corresponding process can be seen on the remote server. Corresponding results are shown in the figure below. I have checked that there is no problem with remote login through the command line, and the nodes deployed locally can also operate normally. 

**To Reproduce**
1. Deploy the node to the distributed server.
2. Run the simulation,  double-click the corresponding node icon to open it's terminal
3. Terminal flash back, and there is no error prompt

**Expected behavior**
The terminal of the node should be opened normally

**Screenshots**
![1631971262(1)](https://user-images.githubusercontent.com/69191226/133890363-0b5c6d2f-808e-49e4-bf36-eb6feabf30d4.png)

![1631971367(1)](https://user-images.githubusercontent.com/69191226/133890402-4879988d-fae1-4dab-8bc3-d8477c38ace3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version  7.5.1

**Comment by bharnden** [comment]
You have what's needed in place as noted here? https://coreemu.github.io/core/distributed.html#remote-gui-terminals

**Comment by nameJa** [comment]
Yes.
Strangely, the terminal can be opened normally when executing instructions directly in the terminal, but not in the simulation interface 
![CC8($}N)G8E{~JW2AU5F(65](https://user-images.githubusercontent.com/69191226/133917983-fa000d6d-9c0a-4a8a-8fff-9d324051e357.png)
![}YG%4NLP}}QT3J{LJ4{F0P4](https://user-images.githubusercontent.com/69191226/133917993-0fba59b5-c49f-4fbc-b88f-90b83673a035.png)

**Comment by bharnden** [comment]
Hard to say without having your environment, but there must be a difference between the 2 cases.
