### ISSUE TITLE
[BUG] Unable to complete core installation

### ISSUE THREAD

**Issue by antonymrtn** [coreemu/core#606]
**Describe the bug**
The installation of core stop at the **core virtual environment** part, which makes it impossible to start the `core-daemon` command.
Core is partially installed, since it is possible to start `core-gui`.

**To Reproduce**
1. Start the core installation, available [here](http://coreemu.github.io/core/install.html)

**Expected behavior**
The installation should complete without error, and I should be able to run the `core-daem` command.

**Screenshots**
<img width="759" alt="Capture d’écran 2021-09-19 à 16 20 02" src="https://user-images.githubusercontent.com/59775893/133931050-0ebe1fa0-48b8-434a-baef-04707b824d74.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2 hosting Ubuntu 20.04.3 (ARM)
 - CORE Version 7.5.1
 - EMANE Version N/A

**Comment by bharnden** [comment]
Fix as noted within #596 speaking to the same issue, will be in the next bug release shortly.
