### ISSUE TITLE
access point for wireless networks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coreemu/core#61]
```
Add the option to have the WLAN represent an access point instead of a MANET 
network.
```

Original issue reported on code.google.com by `ahrenh...@gmail.com` on 29 Apr 2011 at 7:41

**Comment by bharnden** [comment]
AP WLAN Node with links from nodes to the WLAN node, using range to determine connectivity.

**Comment by bharnden** [comment]
closing as this is more of a long term idea, when there is time, moving to internal TODO project
