### ISSUE TITLE
[FEATURE] Use Node Labels in Run Tool

### ISSUE THREAD

**Issue by TinCanTech** [coreemu/core#615]
The problem is that **Node Labels** are not the same as the **node list** which is presented by the **Run Tool**

It would be far more useful to have the **Node Label** listed in the **Run Tool**

That way a command can be easily run on selected nodes by label because label is shown on the GUI.

**Comment by TinCanTech** [comment]
OK, thanks.

**Comment by bharnden** [comment]
Open node terminals and start the program is one way. A long running or blocking process is not really the intent for the run tool.

You could also try backgrounding the process, but I forget offhand if that would work. Or you could also script and run these commands from a python API or shell script as well, there are lots of ways.

**Comment by TinCanTech** [comment]
You need a start command otherwise it cannot be started.

I mean more along the lines of an _enable at startup_ check box.

**Comment by b00ga** [comment]
@bharnden Little bit of a hack, but could you accomplish this by having a CORE service, say check for a file and "do nothing" in it's start script if the file is missing. Then have a hook script for the runtime hook create the file, so when you go to try and start the service through the GUI, now the "check file" exists, so the service actual starts up?

**Comment by TinCanTech** [comment]
What I tried was to edit my script with `exit 0` as the first command.  Once CORE is started, I edit the file and remove the `exit 0`.  It appears to work in the GUI but not so in the pygui.  This method also appears to stop my runtime hook script from running ..

As for there _being lots of ways_ .. possibly, if you know CORE and python inside-out but this is not easy to accomplish.  It would be far simpler if there was an "Enable at startup" checkbox.

**Comment by bharnden** [comment]
With things being so open ended on what can be done, it is really hard to say what is right for someone. But, my original advice seems to work fine, having an empty startup tuple. You can then manually run the script at a later time.

If you just want to run things at a later time, you can always orchestrate this from outside with some predefined script potentially, but that all depends on what you are doing and what it needs. Without knowing the details of that, I can only guess.
