### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by swy-1006-a** [coreemu/core#622]
1. Go to 'Build a distributed Environment'
2. Click on 'Allocate 10 nodes'
3. Scroll down to 'Run the scene'
ERROR - transport:_ log - Secsh channel 698 open FAILED: open failed:connect failed

**Expected behavior**
OSPF is not running, and nodes cannot ping each other. 

**Screenshots**
![4VGKO32~UHG6~)8XEKWXC`E](https://user-images.githubusercontent.com/76472845/137884606-9615c4d1-e9bb-4501-879f-33794135da64.png)

**Desktop**
 - OS: [Ubuntu 18.04]
 - CORE Version [7.5.2]
 - EMANE Version [1.2.5]

**Additional context**

Surprisingly, core-Daemon does not report errors when there are fewer distributed nodes.This error is also reported when setting up scenarios that do not use Emane

**Comment by bharnden** [comment]
Sending commands to distributed nodes would require an SSH connection to be made, odds are by the volume of nodes used and running iperf, you are saturating your connection, so SSH will not work.

I am not sure exactly how you have your setup, but I assume my comment above holds true. Also, basic WLAN is not a supported distributed node type, if that matters any.
