### ISSUE TITLE
[BUG] OVS value in XML

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#627]
**Describe the bug**

Importing legacy network config file, with OVS enabled, does not enable OVS in the latest CORE (say, v7.5.2).

**To Reproduce**

This issue can be quickly reproduced using the attached xml (gist file https://gist.github.com/esend7881/711d84e51384523581fb7258c0a92683) which was created using CORE v6.3, and with OVS enabled.

1. Begin with CORE 7.5.2 on RHEL/CentOS 8 (or RHEL/CentOS 7)
2. Start CORE DAEMON: core-daemon --ovs &
3. Start CORE PyGUI:  core-pygui &
4. In CORE PyGUI, open the network config file "local_port_test.xml" (attached)
5. Press "save" in CORE PyGUI
6. Note the following line in the SAVED file "local_port_test.xml"

`<configuration name="ovs" value="True"/>`

This line should be as shown below. Without it, OVS will not be enabled in CORE 7.5.2

`<configuration name="ovs" value="1"/>`

**Expected behavior**

`<configuration name="ovs" value="1"/>`

Note: "True" needs to be changed to "1" in the saved file. Without this change, OVS features remain disabled in CORE 7.5.2.
 
**XML File**

https://gist.github.com/esend7881/711d84e51384523581fb7258c0a92683

**Desktop (please complete the following information):**

- OS: RHEL/CentOS 8 (or RHEL/CentOS 7)
- CORE version: 7.5.2 (or 7.4.0)
- EMANE version: N/A

**Additional context**

 

N/A

**Comment by bharnden** [comment]
I believe this was a bad value being used in older versions, which happens to just be saved in your file.

Can you reproduce this without using an old (bad valued) save file? Otherwise it seems to be saving the correct value now.

**Comment by esend7881** [comment]
> I believe this was a bad value being used in older versions, which happens to just be saved in your file.
> 
> Can you reproduce this without using an old (bad valued) save file? Otherwise it seems to be saving the correct value now.
> 
> If you cannot reproduce, just edit your file and update to the proper value, as you noted `1` or `0`

It's true that if you create a network config (xml) file from scratch (say, using core-pygui), then the OVS attribute is created correctly: `<configuration name="ovs" value="1"/>`

However, the problem is with importing legacy network config files in CORE 7.5.2 (with OVS enabled). The legacy files require `<configuration name="ovs" value="True"/>` (Note "True")

Importing a legacy file in CORE 7.5.2 and saving it again keeps value="True" (does not change it to "1").  This keeps OVS disabled in CORE 7.5.2. (To enable OVS, "True" needs to changed to "1" by manually editing the xml file.)

This is the issue.

**Comment by bharnden** [comment]
I understand, I just wanted to make sure it was not an active issue.

Considering it was a mistaken value at the time and not a feature used by many people, you may be the only one to which this is an issue. Instead of adding one off logic, to try to account for this, it seems more reasonable for you to update the file in this case alone.

Thanks for pointing this out though, appreciated.
