### ISSUE TITLE
[BUG] EMANE Event Monitor

### ISSUE THREAD

**Issue by JiasenLee** [coreemu/core#636]
**Describe the bug**
Recently, I  I tried to reproduce the demo of [EMANE Emulation Event Log (EEL) Generator](https://coreemu.github.io/core/emane/eel.html). I prepared `eventservice.xml`, `eelgenerator.xml` and `scenario.eel`. When I ran `emaneeventservice eventservice.xml -l 3`, I can't see any movement of `n1` and `n2` in the core-pygui.

**To Reproduce**

1. Select `Open...` within the GUI
2. Load `emane-demo-eel.xml`
3. Click Start Button
4. After startup completes, double click n1 to bring up the nodes terminal

**Expected behavior**
`n1` and `n2` should move with `scenario.eel`.

**Screenshots**
![image](https://user-images.githubusercontent.com/24550544/145773533-adf3b55b-9031-4003-92f1-eec44d792c61.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version: v.7.5.0
 - EMANE Version: 1.2.5

**Additional context**
Part of the `core.conf` configuration file is as follows:

```python
# EMANE configuration
emane_platform_port = 8101
emane_transform_port = 8201
emane_event_monitor = True
#emane_models_dir = /home/username/.core/myemane
# EMANE log level range [0,4] default: 2
emane_log_level = 2
emane_realtime = True
# prefix used for emane installation
# emane_prefix = /usr
```

**Comment by bharnden** [comment]
Did you make sure the follow this note?

> WARNING: make sure to set the eventservicedevice to the proper control network value

Did you run the dump command and see anything? It would be nice to know more about the output you are seeing.

**Comment by JiasenLee** [comment]
> Did you make sure to follow this note?
> 
> > WARNING: make sure to set the eventservicedevice to the proper control network value

Yeah, `eventservice.xml` was set as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventservice SYSTEM "file:///usr/share/emane/dtd/eventservice.dtd">
<eventservice>
  <param name="eventservicegroup" value="224.1.2.8:45703"/>
  <param name="eventservicedevice" value="ctrl0.1"/>
  <generator definition="eelgenerator.xml"/>
</eventservice>
```

- `eelgenerator.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventgenerator SYSTEM "file:///usr/share/emane/dtd/eventgenerator.dtd">
<eventgenerator library="eelgenerator">
    <param name="inputfile" value="scenario.eel" />
    <paramlist name="loader">
      <item value="commeffect:eelloadercommeffect:delta"/>
      <item value="location,velocity,orientation:eelloaderlocation:delta"/>
      <item value="pathloss:eelloaderpathloss:delta"/>
      <item value="antennaprofile:eelloaderantennaprofile:delta"/>
    </paramlist>
</eventgenerator>
```

- `scenario.eel`:

```xml
0.0  nem:1 pathloss nem:2,90.0
0.0  nem:2 pathloss nem:1,90.0
0.0  nem:1 location gps 40.031075,-74.523518,3.000000
0.0  nem:2 location gps 40.031165,-74.523412,3.000000
1.0  nem:1 location gps 40.031075,-74.523518,3.000000
1.0  nem:2 location gps 40.031165,-74.523412,3.000000
2.0  nem:1 location gps 40.031227,-74.523247,3.000000
2.0  nem:2 location gps 40.031290,-74.523095,3.000000
```

> Did you run the dump command and see anything? It would be nice to know more about the output you are seeing.

Yes, I can see the output as shown in the picture.

![image](https://user-images.githubusercontent.com/24550544/145921833-6e722850-d716-458f-8593-184161fac404.png)

**Comment by bharnden** [comment]
Sorry it took a bit to get back, but looking at your output, things seem to be working.

There is the other aspect of COREs GUI not being factored in, there is a translation mapping for positions to X,Y and it has to be defined with valid values for it to potentially work. Your positions likely translate into values that are not valid for being placed on the canvas. This may show up in the core-daemon log, I forget offhand.

Trying to use CORE itself to show geospatial movements is really not the right tool. You would be better off using an external tool and feeding the positions to it, in my opinion.
