### ISSUE TITLE
[Question] Installation Issues

### ISSUE THREAD

**Issue by reza-ghazi** [coreemu/core#643]
**Describe the bug**
Installing the latest `core` in **Ubuntu 21.10** is not successful.

**To Reproduce**
I followed the standard setup has shown on https://github.com/coreemu/core.

After `setup.sh` has been successful in the last part I get an error and setup will exit with error:

```bash
reza@ubuntu:~/core$ inv install
installing core locally: False
installing core with prefix: /usr/local
checking for old installations ... done
installing system dependencies ... done
installing system grpcio-tools ... done
building core ... done
installing vcmd/gui ... done

installing core virtual environment ... -Encountered a bad command exit code!
Command: 'cd daemon && poetry install --no-dev'

Exit code: 1
Stdout:
       29│         self._path = path
       30│         self._base = base or Path.cwd()
       31│         self._full_path = path
       32│ 
    →  33│         if not self._path.is_absolute():
       34│             try:
       35│                 self._full_path = self._base.joinpath(self._path).resolve()
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))

Stderr:
```

**Expected behaviour**
Setup cannot be through during the error message shown above.

**Screenshots**

<img width="556" alt="core-network installation error1" src="https://user-images.githubusercontent.com/5891702/149563219-72bd152c-bb8f-431b-8678-e8464fa29eb1.png">
<img width="440" alt="core-network installation error2" src="https://user-images.githubusercontent.com/5891702/149563220-0de32cc2-e4d3-4745-9ba0-d0c2ac31c439.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.10]
 - CORE Version Latest
 - EMANE Version NA

**Additional context**
On the other hand, if I am going to install it locally. I will get another error. see below image:

<img width="556" alt="core-network installation error3" src="https://user-images.githubusercontent.com/5891702/149563236-0c1b9ac5-9b13-4348-9525-d5e5ce7d82c3.png">

**Comment by bharnden** [comment]
This doesn't look like a clean install attempt, I would try from such a case. Or be sure your prior installation is fully uninstalled.

A clean install works be simpler to verify.

**Comment by reza-ghazi** [comment]
I have had this error since the first installation (clean install). I tried to uninstall the previous installation, and it is not fully uninstalled. So, Is there any way to uninstall it thoroughly?

I am sure the `inv uninstall` is not the way.
