### ISSUE TITLE
[BUG] WLAN does not disconnect when out of range

### ISSUE THREAD

**Issue by adur1990** [coreemu/core#645]
**Describe the bug**
When two (or more) nodes are connected to each other using a WLAN network, they should disconnect as soon as they reach a distance threshold. In the GUI the green connection line disappears, but the connection actually does not. The nodes can still ping each other even when visually not connected anymore.
The problem apparently occurred in version 7, as our testing suggests that versions 5 and 6 are working as expected, whereas version 7 and 8 do not.

**To Reproduce**
1. Start the GUI
2. Create two (or more) PC or Host nodes (possible also others)
3. Create a WLAN network
4. Link all nodes to the WLAN network
5. Start the simulation
6. Open terminal on one of the nodes and start ping to other node
7. Drag one node away from the other to disconnect the nodes from each other

**Expected behavior**
As soon as the nodes are not connected any more, the pings should not be able to reach their destination.

**Screenshots**
I recorded two screen captures to visualize the problem.
[The first one](https://youtu.be/W4VIf5EapT0) shows Core version 8.0.0, where the problem can be seen.
[The second one](https://youtu.be/3W6seMSgzww) shows Core version 5.5.2, where the WLAN network is working as expected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 in a Docker Container; macOS Monterey in a Docker Container
 - CORE Version: all 7.x.y and 8.x.y.

**Comment by bharnden** [comment]
You do not have a 7.x.y example and there is no change I can think of for behavior there between 6 and 7. There was a big change for 8.x.y, switching from ebtables to nftables.

In your example and some quick testing, it does seem to work, but it is not an instant change (which I will investigate). If you try again, but wait a bit longer say 20 seconds for now, do you then see it fail to ping?

**Comment by bharnden** [comment]
Upon a bit further investigation there seems to be a relation with having default rules (inet) backed by nftables and priority of the CORE created one, which had the same priority.

You can view these with:
```shell
sudo nft list ruleset
```

After updating CORE to have a higher priority, the delay was gone and worked like expected.

This change is on develop, if you want to try.

**Comment by bharnden** [comment]
This is updated with both changes for priority and another small adjustment for handling updates on develop. If you want to try that, you can see if you still see issues.

**Comment by adur1990** [comment]
Hi,

thank you for your reply and your help.

Regarding versions 7.x.y, you are right.
I can not reproduce this error anymore locally for version 7.
I guess it was some kind of wrong configuration on my side.

Regarding the delay:
even after 30 seconds the connection is still persistent.
I can also restart the ping and it still works.

Finally, regarding the develop branch:
When CORE is running in Docker on Ubuntu the problem is gone when using the develop branch.
When running in Docker on macOS, however, the problem still exists...

I investigated this further.
What I found is that on the Linux host, `nft list tables` and `nft list ruleset` is empty for version 8.0.0.
Using the develop branch, both commands show one entry.
On macOS, however, there are not tables or rules in both version 8.0.0 and the develop branch.

I hope this helps.
If you need more information please let me know.

**Comment by bharnden** [comment]
Running things within Docker, while possible, is still a bit experimental. Doing so on Mac OS, probably even more so. I know sometimes the default docker iptable rules can cause issues. But, you would need to investigate.

I'll mark this as resolved for now, for the platforms we care about.
