### ISSUE TITLE
[BUG] DockerNode creates directories instead of files when calling create_file

### ISSUE THREAD

**Issue by wholderll** [coreemu/core#646]
**Description**
The issue is in DockerNode.create_file, when it creates the parent directories for the new file. On line 204 of docker.py it uses file_path.name where file_path.parent was probably intended, which is preventing the file from being copied to the container.

https://github.com/coreemu/core/blob/31e6839ac5a9a5e2b1d8840e32b9ad1f5b2606a1/daemon/core/nodes/docker.py#L204-L209

**Suggested Fix**
Line 204:
        directory = file_path.parent

**Source**

[PurePath.name](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name)

    A string representing the final path component, excluding the drive and root, if any

[PurePath.parent](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parent)

    The logical parent of the path

Not sure why pathlib doesn't use Path.filename and Path.directory; understandably not intuitive that a class named Path has a filename for its name and not the directory path.

**Environment**
 - OS: [e.g. Ubuntu 18.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.2.4]

**Comment by bharnden** [comment]
Thanks for pointing this out, I will eventually take a look at this.

**Comment by bharnden** [comment]
Good catch, it was right for LxcNode's but was updated wrong when some recent adjustments were made. Appreciate it.

Fix is on develop now.
