### ISSUE TITLE
[BUG] Missing Two-Node Tool button

### ISSUE THREAD

**Issue by JoeySo22** [coreemu/core#650]
Hello. I've just installed core into an Ubuntu 18 machine and I've gotten past the setup fine. Running the tool starts up fine and I can make my own topology. After clicking on the execute button, I can't find the two-node tool button on the left panel. I cloned only about a week ago.

**Comment by bharnden** [comment]
You would likely find that in core-gui-legacy, there are not current plans to have such a thing in the new GUI at the moment.

**Comment by JoeySo22** [comment]
> You would likely find that in `core-gui-legacy`, there are not current plans to have such a thing in the new GUI at the moment.

Thank you I was able to get it.
