### ISSUE TITLE
[FEATURE] Namespaces registered in ip netns

### ISSUE THREAD

**Issue by jmalcaraz** [coreemu/core#663]
**Is your feature request related to a problem? Please describe.**
The problem is the lack to have a common way to always the gathering of Linux namespaces in a computer (those created with CORE and those created without CORE). 

**Describe the solution you'd like**
When you instantiate each namespace you have the pid.  Example: the node "n11" has pid "67323". If you could just execute this command inmediately after each namespace creation:  "ip netns attach n11 67323".  Note that you already have as a installation requirement iproure2, thus it does not have significant implications. 
( You can try first the implication in the command line, just create an scenario, get the name and pid from /tmp/pycore.1/n11.pid and after executed the previous indicated command, try to execute then these 2 ones "ip netns" after that or "ip netn exec n11 bash") 

This registration may be enabled/disabled via configurable flag into the core-deamon .. "e.g. sudo core-deamon --register-ip-netns" and disabled by default, thus it will ensure any backward compatibility. 

Implications of added this small change?  
- A "standard" way to inventory CORE namespaces via "ip netns"
- A "standard" way to "enter into the namespace" via"ip netns exec" (rather than vcmd approach") 
This is key for make easier integration as only one approach need to be implementes and thus providing support for more use case. 

**Describe alternatives you've considered**
Not applicable

**Additional context**
The implications of this small change are very significant as any "inventoring tool" will start to "see" CORE containers straigh away allowing to do not differentate between "ip netns" namespaces and "CORE namespaces". 

P.S. Congratulation for the work done, it is really impressive.

**Comment by bharnden** [comment]
A decent idea, but unfortunately, it does not pan out.

* CORE uses more namespaces than just network, so using `ip netns` would not be ideal
* `ip netns attach` is not present on Ubuntu 18, likely CentOS releases as well, and not sure we would want to limit ourselves, just yet
* `vcmd` does use the desired namespaces for now and can use names (via a path /tmp/pycore.<session>/<node>) to have similar functionality to the desired case
* the `pid` could be added to node protobuf data, then it could be queried over gRPC, if desired

The alternative and more ideal case to consider would be `nsenter` for this case, it does not have inventory like functionality itself. But, CORE itself is the one maintaining inventory, so you could always get it there.
