### ISSUE TITLE
EMANE : node device failed to exist

### ISSUE THREAD

**Issue by vandit86** [coreemu/core#664]
**Describe the bug**

Running any example with **emane** wlan network is leading to _"Exception calling application: node device failed to exist"_
This type of error appears running in CORE locally **or** in docker.

![delete](https://user-images.githubusercontent.com/16361531/156019672-47c66b57-5593-4293-8f4b-8d273f5aa25d.png)

```
2022-02-28 16:19:00,614 - ERROR - app:show_grpc_exception - app grpc exception
Traceback (most recent call last):
  File "/home/vad/core/daemon/core/gui/coreclient.py", line 425, in start_session
    result, exceptions = self.client.start_session(self.session, definition)
  File "/home/vad/core/daemon/core/api/grpc/client.py", line 239, in start_session
    response = self.stub.StartSession(request)
  File "/home/vad/.cache/pypoetry/virtualenvs/core-mm-NMljy-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/vad/.cache/pypoetry/virtualenvs/core-mm-NMljy-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: node device failed to exist"
	debug_error_string = "{"created":"@1646065140.613823085","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Exception calling application: node device failed to exist","grpc_status":2}"
```

I will appreciate any suggestion.. 

**Desktop:**
 - OS: Mint 20.04
 - CORE Version 8.1.0
 - EMANE Version 1.3.3

**Comment by bharnden** [comment]
It appears as though you are not running the core-daemon for the GUI to connect.

I would not post issues to adjacentlink, unless it is an actual issue identified in EMANE.

**Comment by vandit86** [comment]
Thank you, @bharnden .
Actually, core-daemon is running, and all other CORE examples are working fine.  This error appears only with _EMANE wlan_ presented on topology..  
The same thing with older versions of EMANE..

**Comment by bharnden** [comment]
What output is in the core-daemon? That should speak to what is failing.

**Comment by vandit86** [comment]
> What output is in the core-daemon? That should speak to what is failing.

```
2022-03-01 17:14:49,263 - ERROR - _server:_call_behavior - Exception calling application: node device failed to exist
Traceback (most recent call last):
  File "/home/vad/.cache/pypoetry/virtualenvs/core-mm-NMljy-py3.8/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/vad/core/daemon/core/api/grpc/server.py", line 318, in StartSession
    boot_exceptions = session.instantiate()
  File "/home/vad/core/daemon/core/emulator/session.py", line 1188, in instantiate
    if self.emane.startup() == EmaneState.NOT_READY:
  File "/home/vad/core/daemon/core/emane/emanemanager.py", line 315, in startup
    self.startup_nodes()
  File "/home/vad/core/daemon/core/emane/emanemanager.py", line 324, in startup_nodes
    self.start_iface(emane_net, iface)
  File "/home/vad/core/daemon/core/emane/emanemanager.py", line 339, in start_iface
    self.install_iface(iface, config)
  File "/home/vad/core/daemon/core/emane/emanemanager.py", line 628, in install_iface
    iface.set_ips()
  File "/home/vad/core/daemon/core/nodes/interface.py", line 570, in set_ips
    self.waitfordevicenode()
  File "/home/vad/core/daemon/core/nodes/interface.py", line 546, in waitfordevicenode
    raise RuntimeError("node device failed to exist")
RuntimeError: node device failed to exist
```

**Comment by bharnden** [comment]
How did you install EMANE? How is CORE installed? There appears to be something off with getting EMANE to start correctly.

One way for now, you could look to see what is going on is the following.

* use `core-gui-legacy` and try to start a simple EMANE scenario
* I assume it will fail in the same way
* Open a terminal on a node and look to try and start the emane daemon directly, this would likely tell you the issue
* run `emane <platform.xml file>` and see what it says

**Comment by vandit86** [comment]
- EMANE was [installed](https://github.com/adjacentlink/emane/wiki/Install) from pre-build distribution packages.. 
- CORE was installed following [Automated Install](http://coreemu.github.io/core/install.html) instructions from repo.. 

I see that CORE and EMANE works fine separately, and the integration is failing in my case..  

> There appears to be something off with getting EMANE to start correctly.

yes, it looks like this.. 

>  I assume it will fail in the same way

yes, the emulation fail to start, so I can't open terminal on node.. 

**One thing noted**:  CORE can initiate emulation session without this exception  **if** I run some example  from _emane-tuttorial_ earlier. However, after reboot all goes the same.

**Comment by bharnden** [comment]
So you installed CORE without using any options? Did you install the EMANE python bindings into the CORE virtual environment?

If you use `core-gui-legacy` I believe you can still open a terminal, but I forget for sure in this case.

Did your machine/vm have prior CORE installs? You may want to start fresh if so, maybe you have some overlapping issues.

Also Mint is a non vetted OS, so I cannot speak to everything working there, same for the packages EMANE offers. Even is based on Ubuntu, it could be worth ruling that out.

**Comment by bharnden** [comment]
I just did a fresh Ubuntu 20.04, EMANE 1.3.3, CORE 8.1.0 install with no issues.

```shell
# install core
cd ~/Documents
git clone https://github.com/coreemu/core.git
cd core
./setup.sh
source ~/.bashrc
inv install

# install emane
cd ~/Documents
wget https://adjacentlink.com/downloads/emane/emane-1.3.3-release-1.ubuntu-20_04.amd64.tar.gz
tar xvf emane-1.3.3-release-1.ubuntu-20_04.amd64.tar.gz
cd emane-1.3.3-release-1/debs/ubuntu-20_04/amd64
sudo apt install ./emane* ./python3-emane_1.3.3-1_all.deb

# install emane python bindings
cd ~/Documents/core
inv install-emane v1.3.3

# now run core withe mane
```

**Comment by vandit86** [comment]
I appreciate your help @bharnden !

So what I have done so far:
- CORE removed complete (_inv uninstall_ ) from local machine, with all .conf files 
- All installed EMANE .deb packages removed 
- The docker image were installed following [instructions ](http://coreemu.github.io/core/install.html)
- Now only docker is used to run and launch CORE and EMANE in container 
- Same results so far ..  

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: node device failed to exist"
        debug_error_string = "{"created":"@1646318591.963740281","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Exception calling application: node device failed to exist","grpc_status":2}"
```

To be continue ..

**Comment by bharnden** [comment]
The only advice I can give you at this point is don't use Mint, use a fresh Ubuntu 20.04 install and follow my steps above.

Also don't use Docker or install it, to start anyway, and verify things work. If you think you still need it, if you have been using Docker in relation to all this, that could be your issue alone.

**Comment by vandit86** [comment]
Now I'm confusing.. _Ping_ should be interrupted when link between 2 MDR routers is broken.. However, that doesn't happen.
Please @bharnden  look at video..

https://user-images.githubusercontent.com/16361531/156782458-4e0b1b27-cf5c-4c35-b061-e5fa4a4fa2c5.mp4

**Comment by bharnden** [comment]
You need to provide all the specifics you can, without a complete picture, it is hard to say anything. Doesn't mean that will provide an answer, but it is needed as a basis.

I would start with an actual VirtualBox VM with Ubuntu 20 as I advised, anything else can bring other new elements and pitfalls into the problem.

* How are you running your Docker container? 
* Is this Docker from WIndows?
* When did you build the container (what CORE version)?

**Comment by bharnden** [comment]
I just reinstalled using the commands in the guide and the Dockerfile in the repo on an Ubuntu 18 VM and it works as expected. So there is likely some other variables in what you are trying. I would just say to stick with known cases.

**Comment by vandit86** [comment]
I'm actually using a remote VM, on which a CORE and Docker is running. The access to VM is made through _ssh_  with X11 forwarding to have an GUI.. 

`docker run -i -t -d --rm --name core -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v $HOME/.Xauthority:/root/.Xauthority:rw --net=host --privileged core`

` --net=host ` is needed to have an GUI on my Windows machine. It probably could be the reason of the problem.. I will check without this parameter by using _rdp_ to access remote host.. also, UBUNTU 20 VM should be tested..

**Comment by vandit86** [comment]
OK, so I create new UBUNTU 20 VM on remote host and install all necessary staff + CORE + EMANE. 
The initial error  _"node device failed to exist"_ does not appear, however the same behavior as on the video is preserved, i.e., with the default (**NOT** EMANE) wlan, one host can _ping_ another even when the link is broken.. Did I miss something in configuration? The ping should stop working when the node is out of the communication range..

**Comment by bharnden** [comment]
I just verified this too on a fresh Ubuntu 20, no issue, and have not heard anyone else with similar. You can verify if the nftables rules exist or are changing, but otherwise I followed the exact steps above.

**Comment by vandit86** [comment]
I created a new Ubuntu instance on oracle cloud..  Same results so far..    
but I will try to found solution anyway..  and for now, this topic can be closed.. 
Thanks a lot!
