### ISSUE TITLE
[BUG] core emane python bindings into the core virtual environment does not work

### ISSUE THREAD

**Issue by martin20082018** [coreemu/core#665]
install emane python bindings into the core virtual environment does not work.
After I installed core on a new machine as decribed [here](https://coreemu.github.io/core/install.html#installing-emane)
and tried to install the bindings with inv install-emane v1.3.3 (I had to use the version string, otherwise I got the error:
'install-emane' did not receive required positional arguments: 'emane_version')
```
t@Kampenwand:~/Downloads/core$ inv install-emane v1.3.3
installing system dependencies ... done
cloning emane ... -Encountered a bad command exit code!
Command: 'git clone https://github.com/adjacentlink/emane.git ../emane'
Exit code: 128
Stdout:
Stderr:
fatal: destination path '../emane' already exists and is not an empty directory.
mt@Kampenwand:~/Downloads/core$ 
```

 **- OS: [e.g. Ubuntu 20.04]**
 **- CORE Version 8.1.0**
 **- EMANE Version 1.3.3**

Please give me some advice how to get CORE and EMANE working together. See the green links etc. 
The installation instructions are not helpful, because if I do it step by step... I run into problems. Please give me some indication which version of CORE works with EMANE together and a procedure how to install them step by step.
In the end I want to use the Python API for my work and not the core-gui and use the sdt3d tooling for visualization.

Thank you so much for your help!

**Comment by bharnden** [comment]
The EMANE install task is more of a one off, you can just wipe the directory away to install it again. Assuming you are installing for a virtual environment.

Otherwise, maybe you had previous installations? The intent is that you always need to provide the version string, so that you align with whatever version of EMANE is installed on the system.
