### ISSUE TITLE
[Question] setting up EMANE network "right" for usage of  emane-spectrum-analyzer

### ISSUE THREAD

**Issue by martin20082018** [coreemu/core#667]
**Describe the bug**
There are 2 Emane Networks and 2 nodes (out of a example delivered in the code).
See following figure:
![scenario](https://user-images.githubusercontent.com/51402326/157530693-4b8f63d6-e468-457e-b1a7-2228de3e71a9.png)

It is a little test program to validate the node location updates and so on.
I can move nodes in order to increase their distance to the point where the link drops and decrease the position to see that the wireless recover. Works! :+1:  

I used the following code to build the test scenario:
```
    def test_two_emane_interfaces_02(self, session: Session):
        """
        Test nodes running multiple emane interfaces.

        :param core.emulator.coreemu.EmuSession session: session for test
        """
        # create emane node for networking the core nodes
        options = NodeOptions()
        
        options.set_location(53.651715, 7.678774, 20)
        options.emane = EmaneIeee80211abgModel.name
        emane_net1 = session.add_node(EmaneNet, options=options)
        
        options.set_location(53.751715, 7.778774, 20)
        options.emane = EmaneRfPipeModel.name
        emane_net2 = session.add_node(EmaneNet, options=options)

        config_key = "noisemode"
        config_value = "outofband"
        session.emane.set_model(
            emane_net1, EmaneIeee80211abgModel, {config_key: config_value}
        )
        session.emane.set_model(
            emane_net2, EmaneRfPipeModel, {config_key: config_value}
        )

        # create nodes
        options = NodeOptions(model="mdr")
        options.set_location(53.560087, 8.317760, 600)
        node1 = session.add_node(CoreNode, options=options)
        session.services.add_services(node1, node1.type, ["SSH"])

        options.set_location(53.370592, 7.772324, 250)
        node2 = session.add_node(CoreNode, options=options)
        session.services.add_services(node2, node2.type, ["SSH"])

        # create interfaces
        ip_prefix1 = IpPrefixes("10.0.0.0/24")
        ip_prefix2 = IpPrefixes("10.0.1.0/24")
        for i, node in enumerate([node1, node2]):
            iface_data = ip_prefix1.create_iface(node)
            session.add_link(node.id, emane_net1.id, iface1_data=iface_data)
            iface_data = ip_prefix2.create_iface(node)
            session.add_link(node.id, emane_net2.id, iface1_data=iface_data)

        # instantiate session
        session.instantiate()

        # ping node2 from node1 on both interfaces and check success
        status = ping(node1, node2, ip_prefix1, count=5)
        assert not status
        status = ping(node1, node2, ip_prefix2, count=5)
        assert not status
```

Then I start 2 **SSH connections on node3 and node4**:
perform pings. Works :+1: 

Then I try to run **spectrum-monitor** with:
```
 emane-spectrum-analyzer 10.0.0.4:8883 -100 --with-waveforms --hz-min 2320000000 --hz-max 2500000000
```
This gives the following window:
![spectrum-monitor](https://user-images.githubusercontent.com/51402326/157532770-2a7c489a-cc96-49ae-9c3b-9cf3b543ded5.png)

On my machine the spectrum monitor already works with the **letce2-tutorial-master** setup.
**Most probably I miss here some configuration in order to get it working...**

**Please assist me with the configuration of the emane setup used with CORE.
Thank you for your help!**

**Comment by bharnden** [comment]
I cannot help, sorry, I have no familiarity with using the spectrum analyzer or how it works.

**Comment by martin20082018** [comment]
I have posted the question to Steven Galgano from adjacentlink. 

I also re-validated the correct functionality with the **letce2-tutorial** (example 04) which uses the Spectrum Analyzer.
So the VM I use is configured right. but it seems that I do not have the right settings for the EMANE nodes. 

In particular I want to use the **emanesh** to  get the info of the MANET network configuration on a time-intervall of lets say 1-2 seconds.
I think that the **ota channel** is wrong configured in my example. Can you please advice me how I can change for example the default settings?
So far I'm not sure where these files are located or better - which one are used/loaded at session creation...from the python interface.

Thank you for your efforts!

**Comment by martin20082018** [comment]
In my little test program I can move the node-3 back and forth and the links breaks and get reestablished. I also see that the **2-ray RF-Channel model** is configured - and I thought, that I can see the respective "received" RX-level from the receiving node. 
**Noisemode must also be "on"**
and **otachannelenable** must also be **"on"**
Can you please help me with this?

**Comment by bharnden** [comment]
Assuming you have one emane nem per node, you can use the node id, the emane model name, and the desired configuration for the options you mentioned above. The config is a dict object with string keys and values, the keys are the names defined by emanes manifest files for every model etc as you will see noted in their wiki.

https://github.com/adjacentlink/emane/wiki

There is not in depth thorough python documentation or example, as most are not trying to write python directly. If you wish to understand how things happen, the best and easiest place to look is the gRPC server and utility functions. Everything there is used to run things from the GUI.

* https://github.com/coreemu/core/blob/master/daemon/core/api/grpc/server.py
* https://github.com/coreemu/core/blob/master/daemon/core/api/grpc/grpcutils.py

You can use the following line to configure EMANE options.
```python
session.emane.set_config(_id, emane_config.model, config)
```

The generated emane files used per node will be found within a nodes directory.

`/tmp/pycore.<session id>/<node name>.conf/`
