### ISSUE TITLE
Missing features in new release

### ISSUE THREAD

**Issue by xfn14** [coreemu/core#671]
**Description**
In the new release of CORE features like Wireshark have been removed.
Can someone confirm this or am I just not finding it.

**Comment by xfn14** [comment]
Thanks for the help but i think for ill stick to core-gui-legacy while this one is still in development.
Could you tell me the needed steps to uninstall core? i have a system running the older version and i wanted to upgrade it.

**Comment by bharnden** [comment]
Depends on the older version and how it was installed at that time. Ideally you would uninstall using that case.

If it's older, this should work:
```shell
cd <repo>
sudo make uninstall
```

If something more recent:
```shell
cd <repo>
inv uninstall <any options you used>
```

**Comment by xfn14** [comment]
Thank you very much.
Sorry to bother but I have one more question.
Does core have an arm version?

**Comment by bharnden** [comment]
Not that I am aware of, it is potentially possible to try and run the Docker based setup, if you have Docker on arm. I am unfamiliar offhand, so can't speak to it much.

**Comment by xfn14** [comment]
Thanks for the help keep up the good work!

**Comment by siliconja** [comment]
Hi @xfn14 - just commenting that the CORE backend does run on ARM. I've got 32-bit and 64-bit ARM cross-compilers building this. I'm referring to the `vnoded` and `vcmd` C programs that perform the underlying clone() syscall to instantiate the namespaces.  The rest of CORE is just Python and/or Tcl/Tk so if your OS supports those languages, I think you that it will run there.

**Comment by xfn14** [comment]
The thing is that when I try to install this happens
![image](https://user-images.githubusercontent.com/49213255/159053421-06279e20-e4b7-439f-8681-59a2093e9920.png)

**Comment by gh0st42** [comment]
I can confirm that it runs on aarch64/arm64, at least with ubuntu 20.04, which can be used on m1 macs either in docker or a virtual machine.
The shipped docker file needs some modification, an alternative `Dockerfile` that builds on arm64 can be found [here](https://github.com/gh0st42/coreemu8-docker/blob/main/Dockerfile)
