### ISSUE TITLE
[BUG] core-cli unable to load xml files

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#672]
**Describe the bug**
using `core-cli xml -f <filename>` does not work anymore - neither with the shipped examples nor with newly created ones with the most recent GUI.

**To Reproduce**
1. Go to '~/.coregui/xmls'
2. run `core-cli xml -f sample1.xml `

**Screenshots**
```
root@c4b24310db46:~/.coregui/xmls# core-cli xml -f sample1.xml 
Traceback (most recent call last):
  File "/usr/local/bin/core-cli", line 528, in <module>
    main()
  File "/usr/local/bin/core-cli", line 524, in main
    args.func(args)
  File "/usr/local/bin/core-cli", line 38, in wrapper
    return func(core, *args, **kwargs)
  File "/usr/local/bin/core-cli", line 171, in open_xml
    result, session_id = core.open_xml(args.file, args.start)
  File "/usr/local/lib/python3.8/dist-packages/core/api/grpc/client.py", line 927, in open_xml
    with file_path.open("r") as f:
AttributeError: 'str' object has no attribute 'open'
```

**Expected behavior**
In version <8.0 it was easily possible to load (and start using `-s`) an XML file using `core-cli`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CORE Version 8.1.0

**Additional context**

**Comment by bharnden** [comment]
Thanks, I will take a look at this.

**Comment by bharnden** [comment]
fixed for next release
