### ISSUE TITLE
Loopback interfaces in CORE ?

### ISSUE THREAD

**Issue by maaz06** [coreemu/core#683]
Hi, 
I am using CORE 8.0 (core-gui-legacy). I would like to ask if there is a way to create loopback interfaces (or similar) in CORE. 
I am trying to make an iBGP exercise with FRR service. It would be nice if it is possible.

**Comment by bharnden** [comment]
The nodes create have a `lo` loopback device already, not sure what you are looking for.

**Comment by maaz06** [comment]
Yes.  But I'm not able to configure (i.e. change/edit ip address of) the loopback "lo" interface created by nodes. And, they all have a same loopback interface address (127.0.0.1 i think). 

Moreover, it would be nice if i can add more loopback interfaces myself (say lo1, lo2 ... )

**Comment by bharnden** [comment]
You definitely can, it is not a direct option to carry out by using the GUI. You can however run commands to do so within the nodes once started.

```shell
# create dummy loopback interfaces
ip link add name loop1 type dummy
# add addresses
ip addr add 127.0.0.2 dev lo
```

**Comment by maaz06** [comment]
Thank you very much. I see it is possible. I can add these commands in frrboot  shell file (since I am using FRR) and it does the job perfectly.
