### ISSUE TITLE
[FEATURE]The use of Emane when the underlying node is an lxc or dockers container

### ISSUE THREAD

**Issue by nameJa** [coreemu/core#686]
Dear author, I noticed that coreNode nodes share the file system of the host, while lxc or docker containers have a higher degree of isolation. In this case, can I use emane to complete the link construction?

**Comment by bharnden** [comment]
You can potentially use EMANE in either case, EMANE is usually used with standard CORE nodes. Not sure I completely understand what you are asking.

**Comment by nameJa** [comment]
I mean, when the node is a docker container, the following error occurs when establishing a connection using emane
![1650944020(1)](https://user-images.githubusercontent.com/69191226/165215084-baa25583-3296-4da2-ab1f-3bd8c0a0c732.png)

**Comment by bharnden** [comment]
your container would have to have emane installed, along with routing software etc

**Comment by nameJa** [comment]
I'll try again, thank you for your reply
