### ISSUE TITLE
installation fails in fresh Ubuntu 22.04LTS install

### ISSUE THREAD

**Issue by PatrickTague** [coreemu/core#689]
i'm assuming that Ubuntu 22.04 isn't supported yet, but since it's an LTS, i'm hoping it will be very soon.  in any case, the standard installation method fails on a fresh install of 22.04 during the `inv install` step.  here is the console output:
```
mews@mews-p52s:~/core$ inv install
installing core locally: False
installing core with prefix: /usr/local
checking for old installations ... done
installing system dependencies ... done
installing system grpcio-tools ... /Encountered a bad command exit code!

Command: 'python3 -m pip install --user grpcio==1.27.2 grpcio-tools==1.27.2'

Exit code: 1

Stdout:

  Building wheel for grpcio-tools (setup.py): finished with status 'done'
  Created wheel for grpcio-tools: filename=grpcio_tools-1.27.2-cp310-cp310-linux_x86_64.whl size=32802178 sha256=4c32c1d309ed5baab52fea9f2b4aed84d03ce958d31b410a2b09643aa069bc39
  Stored in directory: /home/mews/.cache/pip/wheels/89/66/17/ef7eee103d55eacabe996286fbcb943e416d75add0bde6bfaf
Successfully built grpcio-tools
Failed to build grpcio
Installing collected packages: grpcio, grpcio-tools
  Running setup.py install for grpcio: started
  Running setup.py install for grpcio: still running...
  Running setup.py install for grpcio: still running...
  Running setup.py install for grpcio: finished with status 'error'

Stderr:

      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

any suggestions?

**Comment by bharnden** [comment]
With some of the recent development changes, this can be an easier path to go down. But the problems typically arise from some of the python based dependencies and them not having a pre-built binary. When this occurs it tries to build the dependency from source and sometimes that can require other system level dependencies, and when those don't exist an error will occur.

Some of the changes in development will bump versions up to help avoid this problem from occurring, but its not 100% as some proj based dependencies are needed (libproj-dev, proj-bin).

There is also the issue of building OSPF MDR, which is typically built and installed. This currently fails on Ubuntu 22.04 and it not something we maintain. OSPF MDR is not a requirement and you can go about without it, but that would be up to you and your needs.

For now it is probably much easier to just stick with 20.04, which still has roughly 3 years of life left.

**Comment by PatrickTague** [comment]
that seems entirely reasonable.  thanks for the reply!

**Comment by banool** [comment]
@bharnden Could you update the README to indicate this? I just tried the same thing and it indeed fails. The README says  Ubuntu 18+ right now, could you make it say Ubuntu 18.04 - 20.04?

**Comment by bharnden** [comment]
> @bharnden Could you update the README to indicate this? I just tried the same thing and it indeed fails. The README says Ubuntu 18+ right now, could you make it say Ubuntu 18.04 - 20.04?

The specific issue here has no relation to Ubuntu version, the note I mentioned on the OSPF MDR build has also been fixed recently, so all is well in that regard. Some dependencies with the current release likely need to be built from source and that is a python related issue.
