### ISSUE TITLE
[BUG] nft errors in docker on non-linux platforms

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#694]
**Describe the bug**
Since the switch to `nft` in coreemu 8, it cannot be used as a docker image on non-linux host systems.

**To Reproduce**
1. run the official coreemu docker image on, e.g., macOS (m1 or intel does not matter), probably also in Docker Desktop for windows
2. within the container, execute the python wireless example from the homepage or alternatively run the generated `nft` file with the following content:
```
add table bridge b.1.1
add chain bridge b.1.1 forward {type filter hook forward priority -1; policy drop;}
add rule bridge b.1.1 forward ibriport != b.1.1 accept
```
`nft  -f /tmp/pycore.nftables.atomic`
3. See error
```
Error: Could not process rule: Operation not supported
add rule bridge b.1.1 forward ibriport != b.1.1 accept
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The other rules execute just fine, so nftables itself are kinda working.

**Expected behavior**
It should just work :)

**Desktop (please complete the following information):**
 - Host OS: macOS on Intel as well as on M1
 - Guest OS: Ubuntu 20.04 and 22.04
 - CORE Version: 8.1.0, 8.2.0, master (all tested)
 
Kernel config from Docker:
```
$ zcat /proc/config.gz | grep NFT
# CONFIG_NFT_NUMGEN is not set
CONFIG_NFT_CT=y
CONFIG_NFT_COUNTER=y
CONFIG_NFT_CONNLIMIT=y
CONFIG_NFT_LOG=y
CONFIG_NFT_LIMIT=y
CONFIG_NFT_MASQ=y
CONFIG_NFT_REDIR=y
CONFIG_NFT_NAT=y
CONFIG_NFT_TUNNEL=y
# CONFIG_NFT_OBJREF is not set
CONFIG_NFT_QUEUE=y
# CONFIG_NFT_QUOTA is not set
CONFIG_NFT_REJECT=y
CONFIG_NFT_REJECT_INET=y
CONFIG_NFT_COMPAT=y
CONFIG_NFT_HASH=y
# CONFIG_NFT_XFRM is not set
# CONFIG_NFT_SOCKET is not set
CONFIG_NFT_OSF=y
CONFIG_NFT_TPROXY=y
# CONFIG_NFT_SYNPROXY is not set
CONFIG_NFT_DUP_NETDEV=y
CONFIG_NFT_FWD_NETDEV=y
CONFIG_NFT_REJECT_IPV4=y
CONFIG_NFT_DUP_IPV4=y
# CONFIG_NFT_FIB_IPV4 is not set
CONFIG_NFT_REJECT_IPV6=y
CONFIG_NFT_DUP_IPV6=y
# CONFIG_NFT_FIB_IPV6 is not set
# CONFIG_NFT_BRIDGE_META is not set
CONFIG_NFT_BRIDGE_REJECT=y
```

**Additional context**
With core version <= 7.5.2 network emulation works on all machines that have docker installed. 
Not sure if this is easily fixable, but losing the portability gained through docker is very unfortunate.

**Comment by gh0st42** [comment]
Sorry, I did not want to suggest going back to the old system. 

The question is more like why is the last command failing, the rest seems to work just fine, and can we find a future-proof way to make this work in docker to make it portable/runnable.
I'm not really experienced with nftables so finding workarounds or debugging this further is quite hard.

**Comment by bharnden** [comment]
You may want to lay out exactly what you are doing then for any type of reference. If it depends on having a mac host, I cannot really help in that regard.

How are you running CORE, what host and OS, what nodes, what docker images, etc.

But, the quick assumption seems to be related to that.

**Comment by gh0st42** [comment]
It seems to be related to the nft bridge meta information. 
As far as I can tell, `ibriport` (which is deprecated in favor of `ibrname`) is part of the nftables bridge meta information.
Docker Desktop runs all docker containers in its own little VM, that's how they make it available on Windows and macOS (and for whatever reason they also seem to do that on linux with kvm - so better avoid docker desktop and use the docker engine directly there).

The kernel output in all docker containers say:
```
# CONFIG_NFT_BRIDGE_META is not set
CONFIG_NFT_BRIDGE_REJECT=y
```

So I guess without this being set in the hardcoded docker VM it is not possible to use these features of nftables unless there is some other nftables syntax to achieve the same without the meta information.

The docker image is the one from the official coreemu repo, but I also tried with different tagged releases, other ubuntu versions to base the docker image on, my own docker images etc.

**Comment by bharnden** [comment]
I can only attribute what you have to the host you are stemming from. Running within Docker on a valid OS has no issue, I wouldn't chalk this up to a bug.

If you find a way to support your desired case as an improvement, you can let me know.
