### ISSUE TITLE
[BUG] EMANE manager doesn't start

### ISSUE THREAD

**Issue by gorgonaut04** [coreemu/core#703]
EMANE manager doesn't seem to launch when a CORE session is started. See change I made to code to get the thread to launch.
<img width="569" alt="Screen Shot 2022-09-21 at 12 49 13 PM" src="https://user-images.githubusercontent.com/10800071/191597198-96d5e075-0902-44d7-ba66-ab9780abe552.png">

1. Configure CORE to use EMANE according to these instructions: https://coreemu.github.io/core/emane.html#:~:text=profiles%20in%20EMANE-,EMANE,-Configuration
2. Create a session with one EMANE node and 2 MDR nodes
3. Connect each MDR node to the EMANE node
4. Start the session
5. Note that no EMANE-like behavior is available 

**Expected behavior**
Appropriate EMANE processes are launched

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CORE Version 8.2.0
 - EMANE Version 1.3.3

**Additional context**
Discussed this with Blake a couple months ago on Discord

**Comment by bharnden** [comment]
This is accounted for and fixed on "develop" branch, thanks for input
