### ISSUE TITLE
[FEATURE] CORE - CLI

### ISSUE THREAD

**Issue by Mohammad-ipv6** [coreemu/core#707]
**Is your feature request related to a problem? Please describe.**
When running CORE via python script, communication with nodes can be improved by providing CLI after the execution of code for real-time communication with multiple nodes via command line interface. 

**Describe the solution you'd like**
Upon running a core session via Python API, a new command line interface is shown to user to directly communicate with nodes. 

**Describe alternatives you've considered**
I think, at the moment, vcmd is used.

**Additional context**
The feature may be quite close to mininet CLI as depicted below:
![image](https://user-images.githubusercontent.com/114478757/192489154-b90fa6c3-be42-4459-a71f-1743bef79912.png)

**Comment by bharnden** [comment]
You can use the gRPC API, create one of your own in this case if desired, or use `-i` when running your python script to drop into an interactive shell similar to what you noted above.

There will be no plans for needing to implement anything more, given all that is already available. Appreciate the input.
