### ISSUE TITLE
[BUG] emane event listener

### ISSUE THREAD

**Issue by 1-Jone** [coreemu/core#729]
Recently, I I tried to reproduce the demo of [EMANE Emulation Event Log (EEL) Generator]. I prepared eventservice.xml, eelgenerator.xml and scenario.eel. When I ran emaneeventservice eventservice.xml -l 3, I can't see any movement of n1 and n2 in the core-pygui.

**Comment by bharnden** [comment]
You would need to go into `/etc/core/core.conf`

And set to the following values:
```
emane_event_generate = False
emane_event_monitor = True
```

**Comment by 1-Jone** [comment]
Thank you for your answer. I set it up as you said. Everything else is fine. The position change is displayed on the terminal, but the node on the core still does not move.

Is it possible that the nodes on the core can only be moved through the ns2 script? emane cannot move the nodes on the core canvas.

**Comment by bharnden** [comment]
Nope, not just through ns2. There is also a xy to geo translation that occurs, based on the settings in the GUI. If you move things too far or not within scope, then that translation can fail or be invalid values.

CORE itself is not a good viewer for seeing positions move geospatially, even though possible with the proper setup (which is also not trivial).
