### ISSUE TITLE
There is no checking for hostname validity when opening an imn file

### ISSUE THREAD

**Issue by rgbryant** [coreemu/core#73]
When one opens an imn file with invalid hostnames there is no error presented.  When the network is started there is no error shown either.  Then once one opens a terminal for a node with an invalid hostname it uses localhost.

Also If one manually tries to enter an invalid hostname it flashes the text in the hostname box and won't take it.  This could be improved by having a box pop up saying what the error actually is.

**Comment by bharnden** [comment]
Nodes now are highlighted red within the GUI and an error in the daemon log for an invalid hostname
