### ISSUE TITLE
How to tweak the frr.py to include the OpenFabric service

### ISSUE THREAD

**Issue by Rinzx** [coreemu/core#737]
I want to add the OpenFabric service 'FRRFabric' as part of the default services upon starting core-gui. Can you advise how I can tweak the frr.py file to achieve this or how else this could be possible. Thank you.

**Comment by bharnden** [comment]
Assuming you are using the latest release, you can follow this documentation related to adding [new services](https://coreemu.github.io/core/configservices.html#new-services).

Then you could base your Fabric variation on one of the other existing services associated with FRR:
https://github.com/coreemu/core/blob/master/daemon/core/configservices/frrservices/services.py

Replace the config content with what you need for fabric using FRR documentation and choose a new name to give it. You could even place it in the same group.
