### ISSUE TITLE
[FEATURE]about python api guide

### ISSUE THREAD

**Issue by hugo921** [coreemu/core#739]
i'm very interest in this emulator,when i try to write my own python scripts ,i dont have found a full manual guide or python api guide ,so 
may i ask whether  have a plan to make a full guide for python api or grpc api.

**Comment by bharnden** [comment]
There is no current plan, the best thing you can do is look through the [examples](https://github.com/coreemu/core/tree/master/package/examples) and read through the relevant source code.

Someday we may expand the guides and examples when there is time.

**Comment by hugo921** [comment]
thanks for your answers and your work.
