### ISSUE TITLE
execute scripts in core-gui

### ISSUE THREAD

**Issue by hugo921** [coreemu/core#740]
**Describe the bug**
I open core-gui ,and import my own script ,but return -1
I checked core-daemon print logs, which shows "ValueError: duplicate service being added: FRRBabel" like this belown
![无标题](https://user-images.githubusercontent.com/33097584/213440383-18b92578-9147-48b5-9781-e25ec47b1686.png)
my scripts very simple  and write it refering to example
the bug happened when CoreEmu() function init on this "coreemu = globals().get("coreemu", CoreEmu())"

**Desktop (please complete the following information):**
 - OS: [Centos stream]
 - CORE Version [9.0.1]

**Comment by bharnden** [comment]
Due to some of the more recent changes, I need to update that example. You can use this to avoid the duplicate service issue.

```python
coreemu = globals().get("coreemu") or CoreEmu()
```

**Comment by hugo921** [comment]
thanks for your answers.
 "coreemu = globals().get("coreemu")" passed ,but "CoreEmu()" still have the same phenomenon.

**Comment by hugo921** [comment]
but I have met new problem. options have no directory atrribute.but i write it still refering to the exampe.
![无标题](https://user-images.githubusercontent.com/33097584/213514831-2abe1f0e-287b-452c-9b09-4b8fa87e5aeb.png)

**Comment by bharnden** [comment]
The error you posted above shouldn't be happing, it looks like you are using the wrong options when you create nodes. It should be `CoreNodeOptions` and not `NodeOptions`.

**Comment by hugo921** [comment]
oh.I see. this script run well in the old version,it needs some change to adapt the new version.
![无标题](https://user-images.githubusercontent.com/33097584/213521583-f8243eb0-1569-4d4e-9646-0b9ac081748d.png)
the new problem: 'CoreInterface' object has no attribute 'getparam'. 
does have some changes about the  CoreInterface Class ?

**Comment by bharnden** [comment]
```python
iface1.options.delay
iface1.options.bandwidth
```

For anything further, just poke around the related code to make sense of. When you are writing scripts they way you are and touching the internals, you are most likely to run into changes.

**Comment by hugo921** [comment]
Thank you very much for your advice.I'm new to python and don't know much about the code of the Project.If i want to know more,How can i start,is there any documents about the architecture of the code.
