### ISSUE TITLE
[BUG] Broadcast Address not setting correctly

### ISSUE THREAD

**Issue by adur1990** [coreemu/core#744]
**Describe the bug**
The IPv4 broadcast addresses are not set correctly (always 0.0.0.0), regardless of node type and link type.

**To Reproduce**
1. Place two PC nodes
2. Connect the using the link tool
3. Start the emulation
4. Open a terminal on either of the nodes
5. `ifconfig eth0` is showing `broadcast 0.0.0.0`

**Expected behavior**
5. `ifconfig eth0` should show `inet 10.0.0.20 netmask 255.255.255.0 broadcast 10.0.0.255`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.1

**Additional context**
Core is running within docker.

**Comment by adur1990** [comment]
After some investigation and debugging it is like the following line: https://github.com/coreemu/core/blob/5ab71377cc9463e9bc64d381523640ff4dabce3a/daemon/core/nodes/base.py#L895

This check is only valid, if `ip` is a string. But in this case, it is an `netaddr.IPNetwork`, thus always false...

```python
if netaddr.valid_ipv4(str(ip)): 
```

fixes the issue...

**Comment by bharnden** [comment]
Thanks for catching this, fixed on develop for next update release.
