### ISSUE TITLE
[BUG] custom service issues

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#748]
**Describe
I tried to use custom service but failed. I put sample.py in ~/.coregui/myservices and restart core. But there is no new service in MDR node.

**Expected behavior**
There will be myservice1 and myservice2 when I click services (deprecated).
**Screenshots**
sample.py:
<img width="1115" alt="d7065beaa4ad60a1a559a4c0299b8a1" src="https://user-images.githubusercontent.com/101703577/216286376-1ac4f860-db50-4172-888a-f6791c8cd7cd.png">

core.conf:
<img width="612" alt="e57cbc6609e7addddf0c069e1520dd3" src="https://user-images.githubusercontent.com/101703577/216285641-2e5f1cf3-efdc-4104-ba38-7dbc0fb82515.png">

services (deprecated):
<img width="530" alt="ae6c906574434f0ac5324e3a809ebfe" src="https://user-images.githubusercontent.com/101703577/216286465-91bce900-5093-441e-84d4-34e6a091343e.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Comment by bharnden** [comment]
not sure your username is username, but maybe it is. Also need to restart the core-daemon, but they should be picked up after that.

**Comment by jxGui** [comment]
I tried it again and it showed Myservice option. However, when I tried to test it, it should show # test file in the n1 node terminal but it showe nothing ( I had removed the default service in service config option before I tested Myservice ) .This is the schreenshot about the question.
<img width="1110" alt="149409231cd09b9032a563058939d56" src="https://user-images.githubusercontent.com/101703577/216742283-3d529c76-f612-4497-8731-e08325324e77.png">

**Comment by bharnden** [comment]
Running a file that is only a comment does nothing and produces exactly what you saw, if you wanted to output the contents you could use `cat`.

```shell
cat myservice.sh
```

Appears everything is fine, based on what you are showing.
