### ISSUE TITLE
XML Export fails silently

### ISSUE THREAD

**Issue by daFritz84** [coreemu/core#76]
I see some troubles with the xml export feature. It fails silently for some network configurations, stating that the xml file was saved successfully, but in fact no file was created at all. However saving as a imn file works always flawlessly. See the attached immune file as a minimal example, and try to save it as an xml. 

uname: Linux 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
core packages used:
core-daemon_4.8-0ubuntu1_trusty_amd64.deb
core-gui_4.8-0ubuntu1_trusty_all.deb

[test.imn.zip](https://github.com/coreemu/core/files/51776/test.imn.zip)

**Comment by rodsantiago** [comment]
Can you also post your core.conf file?

**Comment by daFritz84** [comment]
Please find attached my core.conf.

This is the output from core-gui started from bash
```
Connecting to "core-daemon" (127.0.0.1:4038)...connected.
Connection to "core-daemon" (127.0.0.1:4038) closed.
Connecting to "core-daemon" (127.0.0.1:4038)...connected.
```

BTW, I've found that the xml-export works ok for another directory. In order to shed some light onto this: I always save my stuff into my home folder which is a nfs mount on our server. Whereas the other directory mentioned, is a pure local tmp folder inside opt. What still puzzles me, is the fact that the immune file format works fine and xml does not.

[core.conf.zip](https://github.com/coreemu/core/files/53598/core.conf.zip)

**Comment by rodsantiago** [comment]
I have not been able to reproduce this issue. However, one difference between how the xml and imn files are saved is that xml is created by the core daemon and chown'ed to the core gui user, while the imn file is created by the gui itself.

**Comment by daFritz84** [comment]
Thanks for looking into my issue.
Well, this makes perfect sense for me. Since the root user, has not access to my user's nfs share, and hence cannot create the file. So much to this mystery :). I guess this issue is solved then.

I still want to suggest, to add some kind of error message to notify the user in case the file cannot be written. It should be possible to test such a feature quite easily by creating an arbitrary folder and strip it from root access. Then try to save a xml file in that exact folder.
