### ISSUE TITLE
[BUG] Large Distributed EMANE

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#760]
**Describe the bug**
Description:
I want to build a wireless network of 128 MDR nodes. I tried two methods but all failed. I'll really appreciate your help, if  you can help me to build a  wireless network of 128 MDR nodes.
Method 1:
I use two virtue machines(one is host and the other is distributed server) to build 128 MDR nodes in total. I set 64 MDR nodes run on the distributed server. And I use 1 EMANE node whose model is tdma to link MDR nodes. The RAM of my virtual machine is 4G and I have used it to run 64 MDR nodes connected by one EMANE node successfully. I expect I can successfully run 128 MDR nodes using two virtual machines but it failed. The ERROR is it cannot open ssh channel after it starts.
The error:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/101703577/219864381-ed02c988-abe6-49ea-815c-a9cd0754a8b6.png">

Figure 1
<img width="337" alt="image" src="https://user-images.githubusercontent.com/101703577/219864389-74a09096-a95d-4c6f-977f-e0a89f9a5370.png">

Figure 2
<img width="337" alt="image" src="https://user-images.githubusercontent.com/101703577/219864398-7f1c600a-647f-41bd-a875-b1dff611b071.png">

Figure 3
<img width="337" alt="image" src="https://user-images.githubusercontent.com/101703577/219864407-86353c3b-ecaf-4e6a-8753-00d46f60f0bb.png">

Figure 4
<img width="336" alt="image" src="https://user-images.githubusercontent.com/101703577/219864416-bd7f10c6-ecee-4ad9-be2a-c61adfd81974.png">

Figure 5
The topology：
<img width="415" alt="image" src="https://user-images.githubusercontent.com/101703577/219864425-323ded46-552c-4969-bba2-fa476acbcfce.png">

Figure 6
Method 2:
I also try the wireless network of 128 MDR nodes on a better computer whose RAM is 31.1, but it also failed. I firstly try 128 MDR nodes and it run successfully but I cannot ping successfully like Figure 7.  Then when I try to decrease the number of linked MDR nodes to 96 and 64, the session cannot run successfully like Figure 8 and Figure 9.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/101703577/219864444-dae4e858-f195-48ab-80a1-f58a9f97326a.png">

Figure 7
<img width="415" alt="image" src="https://user-images.githubusercontent.com/101703577/219864456-d979c1d2-31ab-4089-bbb2-d65857daa6a7.png">

Figure 8
<img width="415" alt="image" src="https://user-images.githubusercontent.com/101703577/219864460-c1cfe2e2-ae4d-4d59-a019-3194b2a40a00.png">

Figure 9

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Comment by jxGui** [comment]
PS: I can run a wireless network of 8 MDR nodes on two virtual machines using the method of distributed emulation. However, I find if I place 32 or more MDR nodes on the distributed server, the distributed emulation fails.

**Comment by bharnden** [comment]
You would likely be hard pressed to run that many EMANE based nodes and do anything with it. Since the real impact happens upon running traffic.

Also you are trying too many different things to try and narrow down helping. I would put focus to one specific case. EMANE TDMA requires a schedule, which there is a default helper one, but it wouldn't cover your use case, so you would have to create one yourself and that requires EMANE knowledge specifically.

Some of the errors seem to indicate SSH/Key error issues for the distributed commands. Had to say the culprit, but would take better information and time to investigate.

**Comment by bharnden** [comment]
You also have to remember along with all the various EMANE settings, and TDMA schedule (if using that), position matters for these nodes. It may be the case, that your nodes are just not within reach of each other to function. You cannot just place nodes how you like and have it work out of the box, depending on all the settings at play.

**Comment by jxGui** [comment]
I just want to build a 128-node ad hoc network emulation and then enlarge it to 1000-node ad hoc network. In the beginning, I want to use one EMANE node ( the model can be any one) and MDR nodes to realize it by distributing CORE. However I failed. According to your comment, I need to try to change OSPFv3MDR protocol and SSH and find a suitable setting of EMANE node and then I can realize 1000-node ad hoc network. If I am wrong, can you tell me how to realize an 1000-node ad hoc network emulation on CORE.

**Comment by bharnden** [comment]
It is not just a measure of memory, I do not think that large of a scenario is realistic, you would need significant resources to even think about the possibility, especially with EMANE.
