### ISSUE TITLE
[BUG] Install CORE failed at command: inv install

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#761]
**Describe the bug**
I want to update CORE on Ubuntu20.04. I use the method of script installing but fail to run the command inv install. It shows me that I need to install python grpcio-tools but is shows installing system grpcio-tools ... done before.
**To Reproduce**
1. input inv install
2. See error:
abc@abc-virtual-machine:~/core/core$ inv install
installing core using python(python3) venv(/opt/core/venv) prefix(/usr/local)
checking for old installations ... done
installing system dependencies ... done
installing system grpcio-tools ... done
building core ... |Encountered a bad command exit code!

Command: './configure --prefix=/usr/local'

Exit code: 1

Stdout:

checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for a sed that does not truncate output... /usr/bin/sed
checking for a Python interpreter with version >= 3.9... python3.9
checking for python3.9... /usr/bin/python3.9
checking for python3.9 version... 3.9
checking for python3.9 platform... linux
checking for python3.9 script directory... ${prefix}/lib/python3.9/site-packages
checking for python3.9 extension module directory... ${exec_prefix}/lib/python3.9/site-packages

Stderr:

configure: error: please install python grpcio-tools

**Expected behavior**
install successfully

**Screenshots**
The error:
![image](https://user-images.githubusercontent.com/101703577/219921974-326c15ea-36ec-4567-a851-6eb2e43558ff.png)
![image](https://user-images.githubusercontent.com/101703577/219921987-43f15edd-dbdb-4cd0-bed1-7fe074b983aa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Comment by bharnden** [comment]
You need to run `setup.sh` first, but if you are trying to update from an older version, you really have to clear the old install first and then make sure everything gets up to date. Some of the libraries that help with the install from `setup.sh` have been updated, so they need to be updated as well.

This is the best I can say from the current info. It may be easier to start from scratch if you have tried a large variety of "fixes", but are now in a really bad place as well.

**Comment by jxGui** [comment]
But it shows intalling system grpcio-tools ... done and  why it also shows please install python grpcio-tools then building core?

**Comment by jxGui** [comment]
I have using inv uninstall to remove old CORE.
