### ISSUE TITLE
[BUG]ABOUT distributed emulation

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#762]
**Describe the bug**
I set one MDR on the host and 4 MDR on the server2 and use one EMANE(IEEE80211) to connect them and run successfully. But when I set one MDR on the host and 5 MDR on the server2, it fails and shows me invalid key or cannot connect to some MDR on the server2. 
By the way, can you tell me how to build large scale of nodes like MDR, PC and so on? Using mouse to click MDR nodes and put it on the canvas one by one is really tired. Maybe I need to install CORE 7.5.1. Where can I find how to install CORE 7.5.1?  Finally, I hope to build a MANET network including 1000 MDR nodes. Does this can be achieved?

**Expected behavior**
I hope it can run at least 64 MDR on server2.
**Screenshots**
<img width="1153" alt="09c4ceb7183f75279beea4b239a47f9" src="https://user-images.githubusercontent.com/101703577/219931015-73454c10-34bb-42bd-8751-7174f5fcfea3.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Additional context**

**Comment by bharnden** [comment]
For doing larger scenario, it can be easier to carry that out programmatically, then you can achieve whatever you like or even dynamically control scenario size etc.

I would only use the latest CORE for 9.0.1, as you may be run into issues from older versions and help point out any new ones if they exist for the future.

This seems to be close in line with your other issue #760 , so I will close this one
