### ISSUE TITLE
[BUG] Large WLAN Routing Issues

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#763]
**Describe the bug**
I use WLAN node to test 128 MDR. It successfully runs but when I use route -n to check route table of one MDR node. It only has a few routers and cannot ping to all MDR nodes successfully. Then I decrease the number of MDR to 64 and the simulation works well. The CPU usage of 128 MDR nodes is less than 70% and the CPU usage of 64 MDR nodes is less than 40%.

**Expected behavior**
Due to the CPU usage of 128 MDR nodes is less than 70%, I think the simulation of 128 MDR nodes should also work well.
**Screenshots**
The simulation of 128 MDR nodes:
![d3e66809c52a57ae701eed87890e60d](https://user-images.githubusercontent.com/101703577/219998463-244bca2e-82c3-47be-9e94-3f3b21d5d353.jpg)
The simulation of 64 MDR nodes:
![34b22f2eb858e91df353de00836afdd](https://user-images.githubusercontent.com/101703577/219998540-783548bb-268e-4729-9e7a-8ca2263d94ae.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CORE Version 9+

**Comment by bharnden** [comment]
It may take some time for the routing protocol to resolve itself, are you giving it enough time?

**Comment by jxGui** [comment]
I run it about some minutes. I will try run it longer
