### ISSUE TITLE
[BUG] About creating custom models

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#764]
**Describe the bug**
What I wanted to do was to create a new custom model modeled after rfpipe:, and although I succeeded as shown in Figure 1, which showed that the routing table had neighbor nodes in it and could be pinged through, it caused a series of new errors in the CORE GUI, as shown in Figure 2. When I used the IEEE model, The CORE GUI shows the Exception Calling Application. I can roughly tell that there was a problem with the remote rpc call, so I checked the protobuf that created the model and it didn't have an error. As shown in Figure 3, when I used the TDMA model, more alarms appeared. A more recent BUG is that when I double-click the terminal of the node and enter the emanesh localhost command, it shows that the emanesh command does not exist. So CORE doesn't have emane fully installed.
The specific steps are given below. Since the way CORE integrates EMANE is also based on gRPC, the direction I improved was to investigate the proto file of CORE GUI, but unfortunately no exception was found. So if you can help me troubleshoot my mistakes, I will provide a more complete custom model solution for the CORE community, so as to facilitate the use of more people.
**To Reproduce**
1. Derive creates a custom mac implementation，rewrite all APIs。
2. Transition method to override (override) all component states。
3. MACHeaderMessage Mac head data structure and member definition.
4. The necessary documents for the entire basic rfpipe model construction are roughly shown in Figure 4 and Figure 5:
5.Modify the Makefile files to compile ,There are these documents：emane/configure.ac，/emane/Make file.am，src/models/mac/Makefile.am，/emane/dtd/，/scripts/emanegenmanifests.sh，src/models/mac/myrfpipe/Makefile.am，/etc/core/core.conf。
6. Finally, run the following command to compile and install：
    ./autogen.sh
   `PYTHON=python3 ./configure --prefix=/usr `
    make check
    make -j$(nproc) 
    sudo make install
7.Restart the core-daemon process and Run a simple two-node with a different model。see errrs：
**Expected behavior**
All models and functions are working correctly
**Screenshots**
![image](https://user-images.githubusercontent.com/54539693/220230597-a0ec942b-9a63-4e55-b9b0-aa4fab272c95.png)
![de011c3227bbed8fa3753e74cba85d3](https://user-images.githubusercontent.com/54539693/220230639-dc6986d5-b600-4e8a-9b8d-cd281e72fd6a.png)
![4aa7612d57b00db4c2fbd089b7c04b4](https://user-images.githubusercontent.com/54539693/220230656-dd3159d3-f70e-4c49-b886-6acdea9dbf8f.png)
![image](https://user-images.githubusercontent.com/54539693/220230671-2008a3e3-1419-4d1b-ae40-7ed7cf1bcdda.png)
![image](https://user-images.githubusercontent.com/54539693/220230679-01fe5a1d-801a-44ac-b0c3-d6f574faa235.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [1.3.1]
**Additional context**
Or you can provide a new successful custom model solution for me to emulate, thank you for taking the time to understand my mistakes, all of which would be a great contribution to the CORE community.

**Comment by bharnden** [comment]
EMANE is specific to them, I believe I saw you ask them there as well, that is the right place.

Otherwise it needs to function properly in its own right and be similar to other EMANE models in nature, then this article supports the concept of bringing that in: https://coreemu.github.io/core/emane.html#custom-emane-models
