### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by olungwedc** [coreemu/core#769]
Experiencing issue with starting core-daemon. 
I have tried downgrading/upgrading protobuf and libprotoc and other things as well. One of the things I haven't tried is Solution 2, in fear of slowing system down. 

I have Ubuntu 22.04 and have the most recent core installed.

These are the errors:
dco@dco-VirtualBox:~$ sudop core-daemon
Traceback (most recent call last):
  File "/opt/core/venv/bin/core-daemon", line 3, in <module>
    from core.scripts.daemon import main
  File "/home/dco/core/daemon/core/scripts/daemon.py", line 15, in <module>
    from core.api.grpc.server import CoreGrpcServer
  File "/home/dco/core/daemon/core/api/grpc/server.py", line 16, in <module>
    from core.api.grpc import (
  File "/home/dco/core/daemon/core/api/grpc/grpcutils.py", line 19, in <module>
    from core.config import ConfigurableOptions
  File "/home/dco/core/daemon/core/config.py", line 10, in <module>
    from core.emane.nodes import EmaneNet
  File "/home/dco/core/daemon/core/emane/nodes.py", line 26, in <module>
    from emane.events import LocationEvent
  File "/opt/core/venv/lib/python3.10/site-packages/emane/events/__init__.py", line 36, in <module>
    from .eventservice import EventService
  File "/opt/core/venv/lib/python3.10/site-packages/emane/events/eventservice.py", line 34, in <module>
    from . import event_pb2
  File "/opt/core/venv/lib/python3.10/site-packages/emane/events/event_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/core/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by bharnden** [comment]
When you are installing EMANE python bindings in 9.0.0+, you need to build them using proco 3.19.0+ as indicated in the error. A more complete example is now provided in the updated docs on develop.

This section covers installing EMANE, and goes over rebuilding the python bindings appropriately.
https://github.com/coreemu/core/blob/785cf82ba3955d87e42353d27d5786394ba75f31/docs/install_ubuntu.md?plain=1#L28

**Comment by olungwedc** [comment]
Thank you. After installing EMANE, I went to ## setup PATH.
This is the result:

dco@dco-VirtualBox:~$ export PATH=$PATH:/opt/core/venv/bin
dco@dco-VirtualBox:~$ alias sudop='sudo env PATH=$PATH'
dco@dco-VirtualBox:~$ sudop core-daemon
2023-03-08 18:08:03,916 - INFO - daemon:banner - CORE daemon v.9.0.2 started Wed Mar  8 18:08:03 2023
2023-03-08 18:08:04,450 - INFO - coreemu:_load_emane - using emane: 1.3.3
2023-03-08 18:08:04,531 - INFO - server:listen - CORE gRPC API listening on: localhost:50051

Then I went into another terminal and typed:
core-gui

And this was the result:
core-gui: command not found

However, the coregui directory is located in home.
dco@dco-VirtualBox:~$ ~/.coregui
bash: /home/dco/.coregui: Is a directory
dco@dco-VirtualBox:~$ cd /home/dco/.coregui
dco@dco-VirtualBox:~/.coregui$ ls
backgrounds  custom_emane     gui.log  mobility  xmls
config.yaml  custom_services  icons    scripts
dco@dco-VirtualBox:~/.coregui$ cd gui.log
bash: cd: gui.log: Not a directory
dco@dco-VirtualBox:~/.coregui$

**Comment by bharnden** [comment]
If you run `export PATH` manually in one terminal, that does not carry over into a new one, so that would be why. Unless you add it to your `.bashrc`

**Comment by olungwedc** [comment]
Hi, I added it to the path and still could not open core-gui for some reason.

However, I did this:
dco@dco-VirtualBox:/opt/core/venv/bin$ source activate
(venv) dco@dco-VirtualBox:/opt/core/venv/bin$ cd
(venv) dco@dco-VirtualBox:~$ core-gui

And the CORE session opened.

**Comment by bharnden** [comment]
The PATH is what it is and works how it always does. So assuming you have no other "core-gui" executable in your PATH, it should be finding the one in /opt/core/venv/bin, assuming you updated the PATH properly in your terminal etc.

You can always check your PATH and validate these things to verify for certain.

```shell
echo $PATH
ls /opt/core/venv/bin/core-gui
```

You should see /opt/core/venv/bin be a part of the `echo` output, and you should find the file for the `ls` command. If not then, there is something else going on. Lingering old install files etc, possible.

**Comment by olungwedc** [comment]
That worked!
The path is now fixed, and was able to run core-gui alone.

Thank you for your time and patience.
