### ISSUE TITLE
XML read of projects with lanswitch fails

### ISSUE THREAD

**Issue by dlebling** [coreemu/core#77]
The result of creating a small network and saving it as XML, if it only has a host and a router, is fine. If I add a switch, it writes both .imn and .xml happily, but when I try to open the XML the result is a blank screen. The error in core-daemon.log is:

WARNING XML parsing '/home/sound/test7.xml': skipping node 'n3' interface 'e0': unknown network

where "e0" is the interface connecting the switch (n3) and router (n2).

There is (only occasionally) a note in the console output that says "lanswitch" is unknown. I have not been able to make this deterministic.

This is all done in version 4.8.

Full zip of excerpt from core-daemon.log, imn, and xml follows: 
[lanswitch.zip](https://github.com/coreemu/core/files/101259/lanswitch.zip)

**Comment by rodsantiago** [comment]
Fixed. Switches and hubs were being incorrectly designated in the exported XML file.
