### ISSUE TITLE
[BUG]About RJ45

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#771]
**Describe the bug**
I use RJ45 node to link  physical node and virtual node but when I connect the physical node to my computer and open the RJ45 configuration window , there is only eno1 which is not the interface to my physical node.  Can you tell me how do you connect a physical node and virtual node?

**Screenshots**
the physical node connected to the  computer
![f9eca3a898b37b9b540e5bde072552b](https://user-images.githubusercontent.com/101703577/225201075-fbaff38c-4bfa-4ce7-b0bc-10664a79ae0a.jpg)
the RJ45 configuration window:
![6b957f4d03e1bc3d142477976ddcdb1](https://user-images.githubusercontent.com/101703577/225201228-413f78a0-66c5-4538-b6c2-c2fba1a9154f.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 9.0.1]
 - EMANE Version [e.g. 1.3.3]

**Additional context**

**Comment by bharnden** [comment]
The RJ45 node will only show interfaces on the host running CORE. These interfaces are then disabled for normal use and function as a passthrough into the CORE emulation.

Your physical node would need to have its interface setup to communicate with the CORE node.

**Comment by jxGui** [comment]
I use eno1 interface to connect my physical node and successed in testing wired network including physical node. However,when I tried to test wireless network including physical node, it failed to ping between the physical node and virtual nodes no matter I use wlan node or emane node to provide wireless network. And then I tried to build a wireless network among virtual nodes and build a wired link between physical node (RJ45 node) and each node can successfully ping to each other. So does the RJ45 node cannnot connect to a network using a wireless link? There are some screenshot of  my test.
1. wireless network among virtual nodes and a wired link between physical node (RJ45 node) and a virtual node. And you can see each node can ping to other nodes.
![bca829ad45743869479b729a7e9d6c8](https://user-images.githubusercontent.com/101703577/225509966-db751c30-d961-4fa8-8343-d40505595ef2.jpg)

2. wireless network among virtual nodes and a physical nodes and a wlan node is used to provide a wireless network. And the physical node cannot ping to virtual node.
![3f2d6d675b678e9b1d7c2ffbee31c52](https://user-images.githubusercontent.com/101703577/225510039-1f00a772-715a-416b-b388-37d2a790aec0.jpg)

3.  wireless network among virtual nodes and a physical nodes and an EMANE node is used to provide a wireless network. And it cannot successfully start.
![Uploading 30a80d91d3998daa1fedcae72d04940.jpg…]()

**Comment by bharnden** [comment]
The wireless nodes, MDRs in your examples are running routing software, I assume your hardware is not, so of course it will not work the same directly.
