### ISSUE TITLE
[BUG]Start session for distributed emulation

### ISSUE THREAD

**Issue by ba1ab** [coreemu/core#773]
**Describe the bug**
I want to use two virtual machines to try distributed emulation, but I can't start session.

**To Reproduce**
1. follow the steps in http://coreemu.github.io/core/distributed.html to try distributed emulation
2. put 4 mdr and 1 emane on canvas 
3. start session and see error : Exception calling application: q must be exactly 160, 224, or 256 bits long

**Expected behavior**
The session will start and connect another server.

**Screenshots**

![7d9e818cee99840ea4a4dba1c6ec7a9](https://user-images.githubusercontent.com/127927664/226343011-35ac1368-4169-45c1-9d22-19d25db0af3a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 8.2.0]
 - EMANE Version [e.g. 1.3.3]

**Comment by ba1ab** [comment]
Yes, I also assigned 4 mdr and 1 emane on distributed server. The output of daemon like this :
![6326beff723ad47b48f3de8ed4adf44](https://user-images.githubusercontent.com/127927664/226495169-0dc0dabe-4deb-49a3-be16-8e26b378b740.png)

**Comment by bharnden** [comment]
It is not meant for ALL nodes to be on the distributed server, not the EMANE node itself, which is allowed should be changed.

That is also the GUI output, I would need the server side (daemon) output.

**Comment by bharnden** [comment]
You would have started the `core-daemon` in some way, so you would find it based how you did it.

Ideally you are running the `core-daemon` in a terminal and the output is right there.

**Comment by ba1ab** [comment]
I trid to start session on the root server, then run `core-daemon` in terminal. The output is :
![image](https://user-images.githubusercontent.com/127927664/226525890-3e658a8b-3291-4a8a-bb05-41f91db4aa6d.png)
And I run `core-daemon` on the distributed server, the output is :
![image](https://user-images.githubusercontent.com/127927664/226526432-10156bbe-bf54-47d4-b61e-821b891e267c.png)

**Comment by bharnden** [comment]
If you are already running the daemon, you cannot run it again. If you are not sure how you started CORE in the first place, it will be hard to help you.

**Comment by ba1ab** [comment]
I think that it's my gRPC API's error. When I run `core-daemon`, the output is :
 `2023-03-22 17:38:52,664 - INFO - core-daemon:banner - CORE daemon v.8.2.0 started Wed Mar 22 17:38:52 2023
2023-03-22 17:38:53,187 - INFO - coreemu:_load_emane - using emane: 1.3.3
2023-03-22 17:38:53,240 - ERROR - core-daemon:cored - error starting main server on:  localhost:4038
Traceback (most recent call last):
  File "/usr/local/bin/core-daemon", line 65, in cored
    server = CoreServer(address, CoreHandler, cfg)
  File "/home/abc/core/daemon/core/api/tlv/coreserver.py", line 30, in __init__
    socketserver.TCPServer.__init__(self, server_address, handler_class)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2023-03-22 17:38:53,240 - INFO - coreemu:shutdown - shutting down all sessions
`
Then it stop.
![image](https://user-images.githubusercontent.com/127927664/226870828-bc53751c-8a63-49dd-8a31-b6d75e75ed41.png)

IF service works correctly, it will output:
`2023-03-08 18:08:03,916 - INFO - daemon:banner - CORE daemon v.9.0.2 started Wed Mar 8 18:08:03 2023
2023-03-08 18:08:04,450 - INFO - coreemu:_load_emane - using emane: 1.3.3
2023-03-08 18:08:04,531 - INFO - server:listen - CORE gRPC API listening on: localhost:50051`
And it still work

**Comment by bharnden** [comment]
Yes, when something is already running on the same port, then anything else will be blocked with `Address already in use`.

**Comment by ba1ab** [comment]
This is my core-daemon's output when I start session on root server :
![image](https://user-images.githubusercontent.com/127927664/227081999-1e7bb01c-aa51-4aaa-b0c3-36a7c2a25b6b.png)
![image](https://user-images.githubusercontent.com/127927664/227082033-69067e4f-dc92-4e34-9736-46003d3dfaef.png)
But on distributed server there is no core-daemon's output.

**Comment by bharnden** [comment]
Looks to be something related with whatever distributed setup you are trying, also you have Python 3.8, so I assume you are using an older release. 

I would recommend updating anyways, even if not your specific problem here.  There isn't much I can help with here and not knowing exactly what you did for your setup.

**Comment by ba1ab** [comment]
Ok, thank you for your help. I'll try to update it.
