### ISSUE TITLE
[BUG]About Distributed simulation

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#775]
**Describe the bug**
After I completed the operation steps according to the distributed simulation page of the official website, the distributed simulation nodes could be fully run with less than 4 nodes. However, when the number of server nodes changed from 5, he reported an error of "connect failed". I found two possible solutions through consulting materials: the first is ssh connection saturation, but I don't know how to fix it, and the second is that the default thread number of coreservice.py is only 10. When I changed the thread number of utils.py file, it still couldn't be solved. If distributed functionality is possible, why can't the number of emulation nodes provide more? This is contrary to our intention to simulate large-scale node scenarios. We hope you can give us some inspiration.
**To Reproduce**
1. Follow the flow of this link：(https://coreemu.github.io/core/distributed.html)。
2. Assign nodes to slave servers。
3. Running network。
4. Viewing the routing table。
5. See error：the routing table is incomplete。
**Expected behavior**
More nodes can be emulated
**Screenshots**
![connect](https://user-images.githubusercontent.com/54539693/226566208-3cc54157-92a2-4fb7-9cda-39f5cd761ed8.png)
![node](https://user-images.githubusercontent.com/54539693/226566223-a64b8732-141f-40ea-a118-7cc82769d116.png)
![route](https://user-images.githubusercontent.com/54539693/226566228-cb8b2478-953b-4292-82ee-b2592670fb24.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.2.4]

**Additional context**

**Comment by bharnden** [comment]
If you could provide the actual `core-daemon` output for this case, it would help a lot to even try and look into what is going on.

**Comment by bharnden** [comment]
I was able to spend some time and validate, that there is not any 4 node limit. There was an issue with the GUI updating the session options with a bad value for `controlnet`, so if you set that in `/etc/core/core.conf` alone, that can be an issue. You would need to currently set that same value within the GUI session options dialog.

This is currently fixed on develop for the next release, but can be mitigated as I noted above.

Also remember that the location of nodes when using EMANE matter, as they end up mapping to geo locations and can impact communication.

**Comment by jhonzy0928** [comment]
I conducted debugging according to the steps you mentioned, but it still cannot be solved. If you do repeat successfully and there is no limit on the number of nodes, it may be that the information we communicated may not be accurate. I will try to provide you with more comprehensive information. Including CORE GUI and logger, as well as the configuration in my core.conf, as well as the linux network bridge, the mapping ratio of canvas size is only 100pix to 150m, so I'm pretty sure it's not the emane location. The reason may lie in the version or configuration. If possible, can I have a look at your configuration file? In addition, if you have no objection to my configuration, I wonder if it might be because of the version of CORE.
![bridge](https://user-images.githubusercontent.com/54539693/226784997-abccea3a-7789-471f-8e48-9a233c57deb9.png)
![core conf](https://user-images.githubusercontent.com/54539693/226785003-65955f45-7f60-41be-845a-0fd67dd561d1.png)
![GUI](https://user-images.githubusercontent.com/54539693/226785007-a04aeee4-43c8-4057-86df-8f1fc8a790b8.png)
![logger](https://user-images.githubusercontent.com/54539693/226785010-4f3dbe2e-d5cd-44bc-8e16-9683b37fb814.png)

**Comment by bharnden** [comment]
As far as the config goes, as I noted before, you just need to make sure that you set the controlnet within the GUI. Otherwise it may not be getting set correctly.

There are definitely limits from a CPU/Memory perspective etc, and EMANE with traffic is CPU intensive, so you generally will not get very large scale scenarios without powerful hardware, etc.

**Comment by jhonzy0928** [comment]
The hardware configuration of my machine is shown in the figure below. In terms of memory occupied by Core and cpu usage, my server is in a fully adequate state. And I used to have more than 200 nodes on a single server without using distributed master/slave servers. Therefore, I firmly believe that there may be some bugs in the Core distributed session startup code, such as the number of threads. I only changed the default number of threads in the utils.py file, but there seemed to be no significant effect, and the number of nodes that could be enabled only changed to 5.
The idea behind distribution is to increase server hardware resources so that node size grows linearly. In addition, looking at the official literature, I can see that on a 3.0GHz server, running Linux, about 300,000 packets per second can be pushed through the system, which is fully capable of supporting distributed simulation of at least 300 nodes. But the test results were disappointing.
So hopefully we'll be able to communicate a little bit more and make Core more functional.
![cpu](https://user-images.githubusercontent.com/54539693/226819699-e189c82f-1d39-4ca5-9b29-a940615f2ac0.png)
![top](https://user-images.githubusercontent.com/54539693/226819706-2cede820-bc26-4282-8f15-93a1d3e48aa5.png)
![内存](https://user-images.githubusercontent.com/54539693/226819710-49b9d9e3-b47e-4ca8-b38b-64b656d7a5de.png)

**Comment by jhonzy0928** [comment]
Image above: The cpu has 20 cores at @2.40GHz. When distributed emulation is enabled and the number of nodes is 10, the cpu usage is 0.3% and the memory usage is 0.1%. The total cpu memory was 93Gi and only 1.2Gi was used.

**Comment by bharnden** [comment]
The old documentation examples and notional ideas about what might be possible is not based on using EMANE. Also EMANE does not really have impact when creating the nodes alone, the impact will only be seen when sending traffic.

My VM for just testing 5 nodes as an issue you noted is rather poor, I am also not sending traffic, but did some minimal connectivity to verify. 

Not sure if you have set the value for `controlnet` proper in the GUI as I have stated at this point, beyond that there isn't much more I can say, for what you have shown.

**Comment by bharnden** [comment]
I also leave `controlnet[1-3]` and `controlnetif[1-3]` commented out, not sure if you are just doing that as a trial and error, but you shouldnt need to.

**Comment by jhonzy0928** [comment]
Thank you for your equal and patient communication and discussion with me. At least we have reached an agreement on hardware resources, that is, it has little to do with hardware resources when no traffic is sent. In the controlnet[1-3]controlnetif[1-3] perspective, controlnet[1-3]controlnetif[1-3] is a secondary control network and a network that communicates with the host bridge, and has little to do with the main control network. Even so, I was willing to take the time to try, so I commented it out and retested it, and it was still bad. I'm not sure exactly where and what value you mean by "set the value for proper in the GUI", at least in the original default, the number of distributed emulation nodes did not increase.

**Comment by jhonzy0928** [comment]
Thank you for your active guidance and communication. According to the GUI setting you said, the result is still disappointing. If you set the number of distributed nodes to be more than 10, there are no GUI errors. Then I will reflect on whether there are any other reasons why my steps are wrong. I know that this is not an out-of-the-box project and I need to check every step of my steps. But a basic logic error is that five distributed nodes can run and communicate, so why not ten if the hardware resources are sufficient? This requires more testing and development.So until I test and tune it, I still think it's a BUG.

**Comment by bharnden** [comment]
I was able to replicate the error. Turns out this is due to an sshd setting on the distributed server you are connecting to.

You can edit `/etc/ssh/sshd_config`

Then you need to uncomment and modify this line to have a valid value, I am sure there are limitations:
`MaxSessions 50`

Then restart the sshd service.

**Comment by jhonzy0928** [comment]
Thanks for your very constructive guidance. Inspired by you, I have just modified the file and retested it, and the results are very exciting. So far, our communication problems have been solved. Thank you again for your responsible help. As a student, I benefit a lot.
