### ISSUE TITLE
[BUG]About new service

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#776]
**Describe the bug**
I copy sample.py file(figure 1) to the folder ~/.coregui/custom_services to add new service. However, I cannot find my added service in the dialog window called Config service (figure 2)and when I start simulation, I cannot find the my added service in a node(figure 3). But I can find my added service in the dialog window called Services (Deprecated) (figure 4)and corresponding shell script in the node(figure 5).

**Expected behavior**
I hope my added service can be found and start after I start simulation. Or I hope I can find a way to start, validate or close my added service.

**Screenshots**
figure 1:
![0e51efdc6e323947613f229fd35a0fa](https://user-images.githubusercontent.com/101703577/226903610-4281216c-dac5-4df2-a1b7-66b3364d5386.jpg)

figure 2:
![f3d0869476f54b69e701505c5a62adc](https://user-images.githubusercontent.com/101703577/226903706-06848401-e543-4821-8fcd-020b2ac4e847.jpg)

figure 3:
![ae1d8084e597e8a803af59e3c929b41](https://user-images.githubusercontent.com/101703577/226903825-e6cb4a84-5413-4a5d-8454-461666c2abe6.jpg)

figure 4:
![db6aa6fcbcea9e23269652e4eb10533](https://user-images.githubusercontent.com/101703577/226903935-9b53dc17-9774-46b3-9113-1036750125f1.jpg)

figure 5:
![d9f5a75ff27f266f494d6017c241c72](https://user-images.githubusercontent.com/101703577/226904635-dbe5070a-b9bd-4c93-ac5f-a82b45b9dc30.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 8.2.0]
 - EMANE Version [e.g. 1.3.3]

**Comment by jxGui** [comment]
I follow your advice and it still doesn't work. This is the screenshot of my core.conf file and the dialog window called Config Services. I cannot find  my added service yet. If you need other information, please tell me and I will show you.
![196844faa09ead79ad1a21fce32a720](https://user-images.githubusercontent.com/101703577/227090866-82062598-387e-494d-9f92-09cedcdf3e31.jpg)

**Comment by bharnden** [comment]
It does work. I assume you updated the service code? Since what you had before would not work. Or you have done something else wrong.

**Comment by jxGui** [comment]
I just copy sample.py file to the folder ~/.coregui/custom_services. I do not change sample.py that the core offered.

**Comment by jxGui** [comment]
I copy sample.py file from ~/core/daemon/tests/myservices

**Comment by jxGui** [comment]
I also tried copy exampleservice.py file offered by your link and it still doesn't work after I restarted core-daemon.
![image](https://user-images.githubusercontent.com/101703577/227197568-d2181225-b061-46bb-9985-1a235147a357.png)
My core-daemon version is 8.2.0. Maybe it is caused by the version of my CORE?
![image](https://user-images.githubusercontent.com/101703577/227197992-a4466b0c-1e07-466f-80b2-eb65418fee10.png)

**Comment by bharnden** [comment]
You didnt restart the daemon above, as the error is telling you its already running. You would also need to run as `sudo` and not just your user.

You definitely have something wrong, but I would actually try to restart the daemon first, however you started it in the first place, try stopping it.

Yes, I would also recommended updating to the latest, any errors encountered will not be corrected in the old version.

**Comment by jxGui** [comment]
This is my operation: 1.restart 2.core-gui 3.open config service window. And I cannot find my added service.
![image](https://user-images.githubusercontent.com/101703577/227276401-05b1e6aa-bb50-47b2-af7d-17f761dc2a26.png)
And this is my /etc/core/core.conf.
![image](https://user-images.githubusercontent.com/101703577/227276792-0de8b439-d98b-4e87-804b-a811ae1cb51a.png)
And this is my added service python file: exampleservice.py copied from core/daemon/examples/myservices/exampleservice.py.
![image](https://user-images.githubusercontent.com/101703577/227278351-9c52f229-4d73-4612-b563-12fc3c9dc79b.png)
I put exampleservice.py into ~/.coregui/custom_services.
![image](https://user-images.githubusercontent.com/101703577/227278498-bca3555d-fd17-4d24-b971-590fcbcb34b1.png)
And the exampleservice.py file:
![image](https://user-images.githubusercontent.com/101703577/227278776-c7853d7c-dedf-4d9b-8401-6294bafd1a78.png)

This is all my operations. And it doesn't work.

**Comment by bharnden** [comment]
Yes, your example service code is wrong, as I noted before. That is an old style service, so of course it does not show up.

See here for a better example:
https://coreemu.github.io/core/configservices.html#example-custom-service

**Comment by jxGui** [comment]
According to your advice, I successfully import the exampleservice. But there is a new question that there is no startup and kill down command in gui.
<img width="839" alt="7c65ccd54fca5043cd7d27ba001c0b2" src="https://user-images.githubusercontent.com/101703577/227418771-0121027a-ac77-48ff-8ef8-326ec4f01104.png">
 Then I modify the exampleservice.py file to add startup, validate and shutdown command and restart core-daemon. But there is still no startup and kill down command in gui. My exampleservice.py file is:
<img width="678" alt="6eeab62935582841f835a32a8f7d132" src="https://user-images.githubusercontent.com/101703577/227419433-e0ede965-1f2c-4053-967d-bdf3901df99f.png">
And I try to start the exampleservice after I start the simulation but there is nothing appears in the Xterm of mdr node. I should show Hello in the Xterm of mdr node.
<img width="970" alt="70f19f9c0fabcc9b1e158133cc59671" src="https://user-images.githubusercontent.com/101703577/227419789-e8e40b01-3f0d-4d5e-8363-3eca590f36b5.png">
I think there is something wrong in my exampleservice.py file but I don't know where it is.

**Comment by bharnden** [comment]
The service would not output or do anything to your terminal, that is not how it works. Hard to say without knowing your entire setup, but you should see the commands listed.

If you are not on the latest yet, I would still recommend doing that as a priority.

**Comment by jxGui** [comment]
So you mean I should update CORE first and then try again?

**Comment by bharnden** [comment]
yes

**Comment by jxGui** [comment]
I have fix it, but when I input "/opt/core/venv/bin/python -m pip install ." command, new problem appears.
<img width="1123" alt="2db2b1632ad37fdf91e9914b273a52d" src="https://user-images.githubusercontent.com/101703577/227541016-2b1211a4-1f4c-4e84-b085-359fa1971948.png">
How can I fix it?

**Comment by jxGui** [comment]
This is setup.py file
<img width="683" alt="92e047612ef27bf6ca7433165cb83bb" src="https://user-images.githubusercontent.com/101703577/227547219-55cf5d25-6a02-4ebf-a5fc-93b20093732b.png">

**Comment by bharnden** [comment]
See these instruction here: https://github.com/coreemu/core/blob/d52e0c4547ba4528b9233f9035fad5a53ef5d863/docs/install_ubuntu.md?plain=1#L74

You have to build the EMANE python bindings with protoc 3.19+ for compatibility, which is the error you see in the `core-daemon`.

**Comment by jxGui** [comment]
After following your advice, I still cannot open core.  It shows me remote server connection refused.
My step after successful installation and binding of emane:
1.export PATH=$PATH:/opt/core/venv/bin
2.sudo env PATH=$PATH core-daemon
3.alias sudop='sudo env PATH=$PATH'
4.sudop core-daemon
5.press ctrl C on keyboard
6.core-gui

Screenshots of my steps:
<img width="1118" alt="c2d28f9e26605ab22bcbcae75324971" src="https://user-images.githubusercontent.com/101703577/227721305-a5cd05fd-37fc-46f9-ab03-a0a973f637a4.png">
<img width="509" alt="33e8c3cc0d8a8590286364f86ba2f08" src="https://user-images.githubusercontent.com/101703577/227721311-6ae12c42-9a80-4b7b-a862-22bf4642e26e.png">
 
Is the reason that network is bad? How can I fix it? Change this?
<img width="420" alt="4460ee34e5c9c28f70dbf8c8e41c647" src="https://user-images.githubusercontent.com/101703577/227721535-8bb27575-3485-41cb-a7d5-58ea02a008fc.png">

**Comment by jxGui** [comment]
I find the sulotion:
1. sudo vim ~/.bashrc
2. add sudo env PATH=$PATH core-daemon
3. add alias sudop='sudo env PATH=$PATH'
4. save and quit vim
5. run command: source ~/.bashrc
Then the problem is solved. And the core can be started successfully. Next, I will try the function of new service in the latest CORE.

**Comment by jxGui** [comment]
I test the new service and I can see my startup, validate and shotdown command. And I have another question: How can I test my new service? I press start button but there is nothing appears in the terminal of the PC node. I remember you say it isnot way to test my service and it doesn't work in this way. So I hope you can offer me some ways to show my new service is working.
1. my new service code:
<img width="700" alt="2266727760360431b17d637e1e7420d" src="https://user-images.githubusercontent.com/101703577/227725624-34b834ed-eb37-44ff-a7fe-19223b7184de.png">
2.the config window of my new service: 
<img width="788" alt="50ca3b8671b01e07cf546957c8fcaf3" src="https://user-images.githubusercontent.com/101703577/227725711-45f60e43-35e9-40ac-ac85-36f3b6402dfe.png">
3. the terminal of PC node after I start my new service:
<img width="949" alt="2579bf0187e7b27e28901ef426849a7" src="https://user-images.githubusercontent.com/101703577/227726002-88e5fafb-f44e-4c82-b94b-87f9220a5bf2.png">
4.my service content:
<img width="803" alt="16f8b337d5deb29712de217da0f0aaf" src="https://user-images.githubusercontent.com/101703577/227726046-c1ba39b7-e695-454b-b308-2fff040abb08.png">

**Comment by jxGui** [comment]
And there is another question: I have a protocol written in C language and I want to import my protocol into CORE. But I find the CORE uses python and shell script to add new service. And I don't hope to rewrite my protocol using python and shell script. Is there a way to just call my protocol in C language to realize my protocol in CORE.

**Comment by bharnden** [comment]
CORE does not run things, it being written in python has nothing to do with how you could run your protocol. CORE only sets up and orchestrates a network, the software that runs in it is real. You would just run you C program as you normally would anywhere else that you would really use it.

Services are just a convenience for running shell commands, just as you would type in a normal terminal. That's all there is to it. Imagine the nodes in CORE are real physical machines that you have connected together.

If this all doesn't make sense, there is not much more I can do for you, sorry.
