### ISSUE TITLE
[BUG]About installation

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#777]
**Describe the bug**
When I install CORE, I cannot run the command "inv install" and it show me: ModuleNotFoundError: No module named "invoke"

**Screenshots**
![IMG_20230327_194234](https://user-images.githubusercontent.com/101703577/227931803-555a3fe1-6f1a-47a4-9ffd-b85f1d53e6f4.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.2.4]

**Additional context**

**Comment by bharnden** [comment]
You did not include everything you ran to get to this point, so its hard to say, but its a PATH error of some sort, depending on what you did.

**Comment by jxGui** [comment]
I just follow these steps:
<img width="569" alt="0cd05f0a20f83368a670402a920820a" src="https://user-images.githubusercontent.com/101703577/228107869-c8a31e00-f095-42b4-939a-92e6684faa5d.png">
The error didn't appear when I install CORE on my virtual machine before. How can I solve the problem? How to install the module "invoke"

**Comment by bharnden** [comment]
This was a brand new clean OS install? Not much I can really say based on this, sorry.
