### ISSUE TITLE
[BUG] Python API

### ISSUE THREAD

**Issue by 1-Jone** [coreemu/core#778]
When I run the sample file peertopeer.py, I get the error below.

![asd](https://user-images.githubusercontent.com/109195146/228471888-839e3561-a2e3-41fe-879e-ca9ebad13f40.JPG)

**Comment by bharnden** [comment]
You must run as `sudo`, this is why you see `Operation not permitted`.

**Comment by bharnden** [comment]
You would have to be more specific on what file you are running, as not all files would be compatible to work with this usage. I would also say, you likely shouldn't be going this route to start out anyway.
