### ISSUE TITLE
[BUG]A bug about the number of nodes

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#779]
**Describe the bug**
The background to my testing was that I needed to test large-scale node communication. When I increased the number of nodes to 200, CORE worked fine, but when I reached 300 nodes, CORE reported a BUG. First of all, I excluded a question I often think about, which should be irrelevant to emane because I'm not sending traffic or other events, just treating them as WLAN. Secondly, about the computer performance, when I ran 300 nodes, I used the Top command to check the cpu usage, and found that it was only about 30%~40%, which was not fully occupied. I also tried to use distributed, adding 10 distributed nodes to the slave server instead of 200. The bug still appears. According to the error message, the address range is more like ip address information, but I only allocate 10 nodes to a network segment, it is unlikely that the problem is ip. So I'm wondering if this is a CORE GUI problem, the GUI call is unable to address out of range bug.
**To Reproduce**
1. Use 20 emane, each emane connected to 10 nodes。
2. Each emane uses a different frequency to ensure that the network does not have too complicated connectivity.
3. Run
**Expected behavior**
According to the performance index of the literature, it can run at least 10,000 nodes under the condition of 3Ghz and 16GB memory.
**Screenshots**
![230error](https://user-images.githubusercontent.com/54539693/228707229-35cc5282-2141-43a3-b17a-e968bbe7ca8c.png)
![300error](https://user-images.githubusercontent.com/54539693/228707231-aa1656d3-2256-4d7b-bb92-5571cdef6a63.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.4.1]

**Additional context**
Thank you very much for taking the time to duplicate and try to fix the bug.

**Comment by jxGui** [comment]
I also meet this bug. And my background is 1000 mdr nodes and I just use 20 emane to link 200 mdr nodes. Each emane is linked to 10 mdr nodes. There are no operations on other mdr nodes. I just creat them.

**Comment by jhonzy0928** [comment]
Thank you very much for your patient guidance. According to your idea, I tried and solved this bug. As you said, hardware limitations are a big problem for emane nodes, and I will try to use distributed to solve the problem of insufficient performance on a single machine in the future. Do you have any doubts about the idea of using distributed networks to increase the number of nodes?

**Comment by bharnden** [comment]
Traffic between nodes will/can potentially saturate your physical links depending on how you distribute things. So it can help yes, but there are other factors that come in to play.
