### ISSUE TITLE
Bad references in the CORE manual

### ISSUE THREAD

**Issue by rodsantiago** [coreemu/core#78]
In section 2.2.2 "Installing from Packages on Fedora/Centos", there are references to http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/tkimg.html and http://dl.fedoraproject.org/pub/epel/6/x86_64/tkimg-1.4-1.el6.x86_64.rpm, which are no longer active pages.

**Comment by xiaoxiaopingzi** [comment]
You have to manually download tkImg in this page [https://sourceforge.net/projects/tkimg/](tkImg)
