### ISSUE TITLE
[BUG]About distributed emulation on CORE 9.0.2

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#782]
**Describe the bug**
First, I uncomment controlnet = core1:172.16.1.0/24... and run simulation but fails.
<img width="408" alt="66fe1ae13c4313645c482d50e632e42" src="https://user-images.githubusercontent.com/101703577/230961965-49764e6a-a0e5-4e20-a014-17646fe2fb45.png">
<img width="508" alt="b71de69ac5f1df344efe3d636acd914" src="https://user-images.githubusercontent.com/101703577/230961984-b0318350-f37b-41a3-843b-becfe7bf4b81.png">
<img width="635" alt="3532fcc32ad1ad7066839b2aa050d94" src="https://user-images.githubusercontent.com/101703577/230962017-1a6b78c9-e035-462e-9ae5-123a829aa707.png">

Then I change the controlnet to my network: 192.168.30.0/24 and run it again. However, it run a lot of time but cannot get into Executing state.
<img width="551" alt="88e8b6272e1f460d6086b6e68943824" src="https://user-images.githubusercontent.com/101703577/230962694-e078f104-91ad-46e8-ae1f-a6b7ebf2a7ab.png">

How can I successfully run distributed emulation.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.2]
 - EMANE Version [e.g. 1.4.1]

**Additional context**

**Comment by bharnden** [comment]
The `controlnet` should not be your current actual network. That is an error connecting to the EMANE process on the remote node. Is that address pingable? Is EMANE installed and running on that remote node at this point? There is a lot to confirm about your situation, I can't say much otherwise.

**Comment by jxGui** [comment]
master server:
ip: 192.168.30.140/24
contronlnet = 192.168.30.0/24
I uncomment controlnet =core1...
the core.conf:
<img width="403" alt="7372c437657486727e78d7eebeae241" src="https://user-images.githubusercontent.com/101703577/231036575-f6bf8b80-baa7-4250-b43a-7adb058e9aed.png">

slave server:
ip:192.168.30.142/24 
controlnet =192.168.30.0/24
I uncomment controlnet =core1...
the core.conf:
<img width="410" alt="c10ed7ea2216aca58c86d1ce2ec5d7b" src="https://user-images.githubusercontent.com/101703577/231036562-0819f1d1-bfdd-4cab-a779-ffee6cec41bf.png">


the result:
<img width="480" alt="c1b936fadbd220505d83db17a3a0f35" src="https://user-images.githubusercontent.com/101703577/231037329-d4d22815-dd52-4eb8-9672-d15aebdd92ce.png">
it run a long time and cannot get to executing mode.

Master server and slave server are both virtual machine created by vmware.And Master server can link to slave master by ssh root@192.168.30.142 in terminal.

**Comment by jxGui** [comment]
Then I change the core.conf on both virtual machine
<img width="409" alt="44058ff30764e03a985867b5ff0bbf7" src="https://user-images.githubusercontent.com/101703577/231040573-49bb1f4e-af00-4137-bc0b-fc84d78cbf18.png">
And the result is the same.

**Comment by jxGui** [comment]
After a long time, it shows me:
<img width="473" alt="8243f0af46c322170437e6c090d9253" src="https://user-images.githubusercontent.com/101703577/231042775-d7ea9e13-ed2e-42fa-b9f1-13f876bc3058.png">
And after I run core-gui, I can not link to my slave server by ssh like this:
<img width="408" alt="c989a9559ee8a9b69124263be6e9aa4" src="https://user-images.githubusercontent.com/101703577/231043244-2a5ef5ef-be5d-484d-a76f-1e2721cd4dfb.png">
And I cannot even ping to it
But when I restart both virtual machines, I can link to my slave machine again.
<img width="408" alt="5ef565decd9dadd8d527071cd183db4" src="https://user-images.githubusercontent.com/101703577/231044615-f5ea1414-8349-46db-b7ce-537af021f79f.png">

**Comment by jxGui** [comment]
I restart sshd and run CORE again and this time it shows me : 
<img width="683" alt="bfd8355569f879b756ee07a01534e5a" src="https://user-images.githubusercontent.com/101703577/231047847-c5e8b61f-c59c-427c-89d4-6353dbd358a1.png">
The I input sudo ip link delete ctrl0.1 to delete it and run again. And the CORE always runs but can not get inot executing mode.
<img width="577" alt="659e8a93f1b76aabaae84bea84b93bc" src="https://user-images.githubusercontent.com/101703577/231048115-1b210a54-76a6-4696-a199-0224fe2556f3.png">
This picture is the screenshot of CORE running 5 minutes

**Comment by jxGui** [comment]
Yes, it is the problem of EMNAE on slave server. At first, slave server is cloned from master server.I think there is no problem in slave server because master server is work well with emane. Then I test EMANE on slave server ,however, it cannot run.

**Comment by flykong** [comment]
I meet the same problem, have you solved? how?
