### ISSUE TITLE
[question]About visual interface design

### ISSUE THREAD

**Issue by ba1ab** [coreemu/core#784]
I want to develop a Python  program for interactive simulation, which visualizes node communication and movement when using CORE for large-scale mobile ad hoc network simulation.
What way is there for me to obtain real-time information about node communication and movement after the simulation starts？

**Comment by bharnden** [comment]
CORE only sets up a network, everything after the fact is not managed by CORE. For traffic you could use any tool you would normally use, like `tcpdump`, etc.

For movement, you can use the gRPC API to listen for movement events. Depending on how you are "moving" things, you may be the one driving the movement and this would not really be needed.

**Comment by ba1ab** [comment]
I want to open the terminal of the node n1 through Python file. I checked some files like `/core/daemon/core/emulator/session.py`, `/core/daemon/core/nodes/network.py`, etc. And I couldn't find any related functions. Are there any related functions ?
