### ISSUE TITLE
[BUG] EMANE distribution emualtion

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#785]
**Describe the bug**
My error is:
<img width="1083" alt="5f6330247a0a66ddc2ab2930ab5aee6" src="https://user-images.githubusercontent.com/101703577/232291191-e5dc73d8-c513-4b9d-94dc-a68d990b407d.png">
The core-daemon shows:
<img width="645" alt="161f950ecd4422f11859dc44cae9518" src="https://user-images.githubusercontent.com/101703577/232291340-f68559f1-4ae8-4c7a-810e-6b17ec36185a.png">
 I have tried wired network simulation by distribution emulation and it emulated successfully. And I am sure that emane can be used in both local and remote servers. So what is the reason of this error and how can I fix it?
my core.conf file on both servers are:
<img width="644" alt="e34dfb251c64d5461f022b8859b9f14" src="https://user-images.githubusercontent.com/101703577/232291898-2ad1f667-0bb7-4c20-b551-c9f77f7fd450.png">
If you need more information, please tell me and I will show it to you. I am really grateful if you can give me some help.
Both servers environment:
Ubuntu:22.04.2
CORE 9.0.2
EMANE: 1.4.1

**Comment by bharnden** [comment]
As the error notes, there is no route to the host, so something is going on there and you would need to investigate why that is.

You also mentioned using the same addressing as your real host before, you do not want to do that.

**Comment by jxGui** [comment]
The slave server is cloned from the master server and then I configure both servers following the instruction of the CORE Document. Both server are on VMware. I search the reason of the error on the internet and they all tell me that the error is caused by firewall and I need close it. But after I close the firewall, it does not work and the same error still appears. Now I don't know how to fix it. Besides, you mean the error is not related to the CORE or EMANE but my two virtual machine setting, do you?

**Comment by bharnden** [comment]
Yes, cloning a machine and using it straight up would be unideal for sure. Something with your settings. Not much I can really do to help debug that, sorry.
