### ISSUE TITLE
[BUG] Too many open files！

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#788]
**Describe the bug**
Hello, my tutor! After many attempts, I come to you again with my question. One of the things I've been working on lately is increasing the size of nodes, which may not make sense, but I'm very interested in, because in massively multithreaded scenarios, system stability is very important. So I may have been playing the role of testing CORE performance.
To be specific, when the number of nodes reached 128, he often reported errors as shown in Figure 1. I think the possible reason is that the process resources of the system are insufficient, so I adopted distributed communication and allocated half of the nodes to the slave server, but it still could not be solved. But I could have run 64 nodes on the main server. So 1 plus 1 doesn't equal 2. In the case of insufficient system process resources, I think there are some quantitative limitations in some places. I would appreciate it if you could repeat my error in Figure 1 or help me explain the meaning of this error.
**To Reproduce**
1. A total of 200 nodes are placed
2. The TDMA model of Emane is selected
3. 200 slots are allocated to 200 nodes
4. Run and see error

**Expected behavior**
Normal communication。
**Screenshots**
![微信图片_20230420122212](https://user-images.githubusercontent.com/54539693/233257537-cf34c938-01f0-48bb-bb53-d7a242f0b1d7.png)
![微信图片_2023042012222](https://user-images.githubusercontent.com/54539693/233257542-e547a408-f75c-48ac-990a-ff9453a7bc5d.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.4.1]

**Additional context**

**Comment by bharnden** [comment]
You would be better off showing the error from the `core-daemon` side, there is not much context from the GUI. That would at least point to where the error is originating from.

**Comment by jhonzy0928** [comment]
Thank you very much for your warning, but I have solved the problem for the time being by community member @jxGui. The problem was that linux had reached its maximum number of file handles, and then I solved his limit.
