### ISSUE TITLE
[BUG] Version 9.0.2 - Wireless nets can't be configured for non-/32 subnets

### ISSUE THREAD

**Issue by apwiggins** [coreemu/core#789]
**Describe the bug**
GUI restricts all wireless and WLAN nets to support /32 addresses on interfaces.  There is no reasonable workaround.

The configuration of a wireless subnet extends to other engineering use cases.  A wireless net can simulate a network make/break through a simple in/out range.  This is an extremely useful short-hand for engineering studies to test software behaviour when the network is present or not present.  In larger configurations, this can extend to testing single or multiple points of failure.

The more cumbersome workaround is to use a switch and manually set / unset loss per link.  It requires a more complex setup and a more complex set of steps to reproduce the expected behaviour.  With a wireless link, it's a simple drag and drop to make or break a connection.

Last point, we have some wireless subnets that are not MANETs and use non-/32 address spaces.  Simulation of these non-/32 address spaces due to this bug will require significant rewriting of scenarios. 

**To Reproduce**
![Screenshot from 2023-04-26 09-48-49](https://user-images.githubusercontent.com/7106951/235195838-ad83461f-1826-405b-a081-192ed354bca9.png)

**Expected behavior**
Provide a GUI option to configure a non-/32 subnet.  Each subsequent node that is added to the non-32/subnet is allocated an IP address within the subnet.  A /24 subnet example is shown below.
![Screenshot from 2023-04-26 09-46-22](https://user-images.githubusercontent.com/7106951/235195943-d36dc238-4830-4b0e-951f-560ff10045d8.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - CORE Version [9.0.2]
 - EMANE Version [N/A]

**Additional context**

This is a blocker item for our group in adopting any version post 7.5.2.

**Comment by bharnden** [comment]
Thanks for bringing this up as a need to have, I will definitely take a look at adding support. Is being able to change just the /32 part good enough?

Albeit painful, you could edit each node at the moment.

**Comment by apwiggins** [comment]
It works for a simple net like a chain.  Thanks for the tip.  It's a bit more cumbersome to adjust each interface's ip address.
![Screenshot from 2023-04-28 14-31-37](https://user-images.githubusercontent.com/7106951/235214931-7c813ef5-3b4a-48c4-91db-9e75a7768c10.png)

In versions <7.5, we could always create a wireless net, modify the subnet to /24, and then start adding links to the wireless subnet which would auto-populate with increments starting .1, .2 and so on.  Some of our guys only use wireless nets to get rid of the visual clutter at scale.

**Comment by bharnden** [comment]
Yes, I get that. I am just saying before it seemed to implicate the entire subnet to use, but would focusing on the prefix alone be good enough(ie just the 32 changing to 24, etc)?

**Comment by apwiggins** [comment]
The full subnet (network address and subnet mask) is what we normally use (wireless model) and then allocate the interfaces from the subnet.  We often use multiple wireless interfaces per router from Class A/B/C depending on what is being simulated.

**Comment by bharnden** [comment]
initial implementation within the new GUI to support this concept is now available on the develop branch, but only for the original WLAN node. 

I will likely extract out this network configuration to its own unique dialog, so that is can be reused across all the wireless network types.

**Comment by bharnden** [comment]
Update, if you try, this network configuration now lives within the general node configuration option, which can be brought up with a double click. This allows it to be provided for all wireless types.
