### ISSUE TITLE
[BUG] Custom EMANE Model documentation and example don't load platform config

### ISSUE THREAD

**Issue by santos-j** [coreemu/core#790]
**Describe the bug**

I am working on developing my own custom EMANE models and after a few days stuck in the process, I found out that the current 'Custom EMANE Model' [documentation](http://coreemu.github.io/core/emane.html#custom-emane-models) and [example](https://github.com/coreemu/core/blob/master/package/examples/myemane/examplemodel.py) are missing a crucial step to correctly instantiate a custom EMANE model, i.e., loading the platform configuration manifest. 

As you can see in the snippet below, extracted from the example and documentation links above:

<pre>
    @classmethod
    def load(cls, emane_prefix: Path) -> None:
        """
        Called after being loaded within the EmaneManager. Provides configured
        emane_prefix for parsing xml files.

        :param emane_prefix: configured emane prefix path
        :return: nothing
        """
        manifest_path = "share/emane/manifest"
        # load mac configuration
        mac_xml_path = emane_prefix / manifest_path / cls.mac_xml
        <b>cls.mac_config = emanemanifest.parse(mac_xml_path, cls.mac_defaults)</b>
        # load phy configuration
        phy_xml_path = emane_prefix / manifest_path / cls.phy_xml
        <b>cls.phy_config = emanemanifest.parse(phy_xml_path, cls.phy_defaults)</b>
</pre>

We are loading the PHY and MAC configurations, but are missing the platform configuration, as per the [_EmaneModel_ base class](https://github.com/coreemu/core/blob/c44dc521fb11f9308da46e0b4657ed5bc68d58fe/daemon/core/emane/emanemodel.py):

<pre>
    @classmethod
    def load(cls, emane_prefix: Path) -> None:
        """
        Called after being loaded within the EmaneManager. Provides configured
        emane_prefix for parsing xml files.

        :param emane_prefix: configured emane prefix path
        :return: nothing
        """
        <b>cls._load_platform_config(emane_prefix)</b>
        # load mac configuration
        mac_xml_path = emane_prefix / MANIFEST_PATH / cls.mac_xml
        cls.mac_config = emanemanifest.parse(mac_xml_path, cls.mac_defaults)
        # load phy configuration
        phy_xml_path = emane_prefix / MANIFEST_PATH / cls.phy_xml
        cls.phy_config = emanemanifest.parse(phy_xml_path, cls.phy_defaults)
</pre>

From my understanding, the lack of the platform configuration makes the session unable to locate the EMANE service and well, work. Adding that single line above in the example/tutorial was able to fix the issue for me. 

**To Reproduce**
1. Follow the 'Custom EMANE Model' [tutorial](http://coreemu.github.io/core/emane.html#custom-emane-models).
2. Save the custom EMANE model from the tutorial in your custom EMANE model directory.
3. Run a session with any number of nodes and an EMANE wireless network using your custom model. 
4. See errors :(

**Expected behavior**
Be able to run the tutorials and follow the example out of the box. 

**Screenshots**
The error thrown from the CORE GUI:

![screenshot_20230429_220001](https://user-images.githubusercontent.com/8865676/235332732-672fcd31-4095-48c0-9136-93ead37d4c2d.png)

The error thrown from the terminal calling the CORE GUI:

![screenshot_20230429_220105](https://user-images.githubusercontent.com/8865676/235332739-c3bc4055-c2d2-4dcb-a4f1-b67f461346d7.png)

**Desktop (please complete the following information):**
OS: Ubuntu Server 20.04.5 LTS (cloud image)
CORE Version 9.0.2
EMANE Version 1.3.3

**Comment by bharnden** [comment]
Ya, with some adjustments a bit ago the examples were not updated to correlate. I will update the examples, thanks.
