### ISSUE TITLE
[BUG]Encountered a bad command exit code!

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#791]
**Describe the bug**
There was one other issue with installing the new version of CORE that I couldn't fix, unlike others in the community. From the point of error message, it seems to be associated with the virtual environment of python, but my installation steps based entirely on https://coreemu.github.io/core/install.html, the specific configuration as shown below, also I don't know how to solve this problem now, because when I repeated installation, The error is the same. Can you help me solve this problem?
**To Reproduce**
1. Go to https://coreemu.github.io/core/install.html。
2. Script Based Install。
3. When inv install is used, core cannot be installed。

**Expected behavior**
core can be installed properly
**Screenshots**
![微信图片_20230505174342](https://user-images.githubusercontent.com/54539693/236426221-26c094d4-e937-4b0a-a0d3-2dff9b3af68b.png)
![微信图片_20230505174326](https://user-images.githubusercontent.com/54539693/236426278-83e72ef7-ef02-458b-9a26-ddd61f1d8450.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.2]
 - EMANE Version [e.g. 1.4.1]

**Additional context**

**Comment by bharnden** [comment]
According to the first error it seems to be related to your internet connection, not sure I can help much with that. You can add `-v` to the install to get the actual output.

**Comment by jhonzy0928** [comment]
I think I've got over the core installation problem but with emane I tried a lot of things and didn't get it installed and I didn't get any problems with the whole process so what else should I be aware of from an integration perspective?
![22b06a52be1964dbc3480d46364071a](https://github.com/coreemu/core/assets/54539693/a5f16eeb-15b7-4b21-9ebe-250ec1f5ba50)
![1a430bb56a46321cd41ae50040bd017](https://github.com/coreemu/core/assets/54539693/a5ffc161-a81f-4f53-abc5-2ecdffe79d6c)
