### ISSUE TITLE
[FEATURE]core-python examples

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#795]
**Is your feature request related to a problem? Please describe.**
https://coreemu.github.io/core/python.html
From this example, I can use some of the functions in the core-gui, such as creating nodes and setting node parameters. But in this example I don't know how to enter the node terminal to execute external commands, for example: I can't use the MGEN tool for delay testing and so on. Which means I don't know the output of the network simulation. And I can't use mobility scripts to move nodes and so on.
**Describe the solution you'd like**
This is because core-python allows the simulation to modify certain parameters as it goes along, such as when the communication parameters of some nodes are of poor quality. It is not supported in core-gui. So I wanted to do a more powerful simulation with core-python, which meant that I could orchestrate the resources I wanted, for example, some nodes were not powerful enough, throughput was poor, so I could increase the power and bandwidth and so on in real time.
**Describe alternatives you've considered**
![微信图片_20230525154206](https://github.com/coreemu/core/assets/54539693/a1193f75-7fc5-4ad6-a965-ac25dac63ecf)
In the simulation, I have changed the parameters, but more is not implemented.
**Additional context**
Or if there are more powerful features, I can follow the tutorial guide.

**Comment by jhonzy0928** [comment]
I understand what you said about node.cmd being a line of code used in python? Or can I connect to a node in a virtual environment using the command line node.cmd after I run Core-python XXX.py?

**Comment by jhonzy0928** [comment]
I learned from core's emulation architecture that virtual command terminal vcmd is a command line utility used to send shell commands to nodes. I wondered if I could run vcmd while Core-Python was running, but based on core-Python I needed to close the session after running. Or can I use interrupts to test nodes? Or when core-python is running, what specific behavior can I use as input and output to test the network simulation topology I'm building? I don't know if you can understand what I'm trying to say.

**Comment by bharnden** [comment]
`node.cmd()` is a function you can use on a node, when created to run arbitrary commands. So you programmatically can run any command within a node after session startup. That is about as much as I can explain, there are plenty of ways to test this out with some python knowledge.

https://github.com/coreemu/core/blob/c44dc521fb11f9308da46e0b4657ed5bc68d58fe/daemon/core/nodes/base.py#L710
