### ISSUE TITLE
After installation core-gui not found

### ISSUE THREAD

**Issue by AnitaSaH** [coreemu/core#798]
After installing , can not start the core-gui. 
Installed with these commands
git clone https://github.com/coreemu/core.git
cd core
# install dependencies to run installation task
./setup.sh
# run the following or open a new terminal
source ~/.bashrc
# Ubuntu
inv install
Then inside core directory. If I execute core-gui. It says command not found.

virtual-machine:~/core# core-gui
core-gui: command not [found]

Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-52-generic
    Architecture: x86-64

**Comment by bharnden** [comment]
The default installation, is into a virtual environment, so this is expected. Updating the PATH to make it available is covered here (https://coreemu.github.io/core/install.html#resolving-path-issues).

**Comment by AnitaSaH** [comment]
Thank you. Its working now.
