### ISSUE TITLE
[BUG]CORE could not be started correctly！

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#799]
**Describe the bug**
When I installed the CORE according to the instructions of the official website and executed `sudop`, `core-dameon`, `core-gui`, the core could start, but when I created the node to start the communication, I could not create the node, because I did not have the permission, but in this virtual environment, How can I add permissions so that the node can be successfully created and run?
**To Reproduce**
1. Put the command line in the`.bashrc` file as shown in the following image
2. `sudop`
3. `core-daemon &`
4. `enter`,`core-gui`
5. Create a simple topology node and run it
**Expected behavior**
The node is successfully created and can communicate with each other
**Screenshots**
![1688464506859](https://github.com/coreemu/core/assets/54539693/5c32fc28-fcd3-490f-a315-e042cb85c152)
![1688464148583](https://github.com/coreemu/core/assets/54539693/77031e57-46ab-4472-a754-749fd8b2842f)
**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.2]
 - EMANE Version [e.g. 1.4.1]

**Additional context**
![1688464148583](https://github.com/coreemu/core/assets/54539693/5445d287-1d73-42bd-a424-408f197b104f)

**Comment by bharnden** [comment]
Use the example for `sudop` not your own:
`alias sudop='sudo env PATH=$PATH'`
