### ISSUE TITLE
Saving as XML locks up with grid network

### ISSUE THREAD

**Issue by rgbryant** [coreemu/core#80]
Whenever I try to save a network as an XML with a grid of switches it locks up my machine. This network saves ok as an IMN file.  I've pasted an imn file of a network that does this (this is a very simplified version of a network we are using).  It does save as an XML file for this imn, but the core-gui won't load the XML file it just created.  On the larger network that I'm trying to save as XML it won't even create a file.  I can work around it by removing the ladder and just hooking everything to a central switch, but I'd prefer to be able to have everything 1:1 with the network we are using in real life.

`
node n1 {
    type lanswitch
    network-config {
    hostname n1
    !
    }
    canvas c1
    iconcoords {503.0 294.0}
    labelcoords {503.0 318.0}
    interface-peer {e0 n7}
    interface-peer {e1 n2}
    interface-peer {e2 n6}
}

node n2 {
    type lanswitch
    network-config {
    hostname n2
    !
    }
    canvas c1
    iconcoords {969.0 297.0}
    labelcoords {969.0 321.0}
    interface-peer {e0 n8}
    interface-peer {e1 n1}
    interface-peer {e2 n3}
    interface-peer {e3 n5}
}

node n3 {
    type lanswitch
    network-config {
    hostname n3
    !
    }
    canvas c1
    iconcoords {1278.0 289.0}
    labelcoords {1278.0 313.0}
    interface-peer {e0 n9}
    interface-peer {e1 n2}
    interface-peer {e2 n4}
}

node n4 {
    type lanswitch
    network-config {
    hostname n4
    !
    }
    canvas c1
    iconcoords {1304.0 512.0}
    labelcoords {1304.0 536.0}
    interface-peer {e0 n10}
    interface-peer {e1 n3}
    interface-peer {e2 n5}
}

node n5 {
    type lanswitch
    network-config {
    hostname n5
    !
    }
    canvas c1
    iconcoords {996.0 492.0}
    labelcoords {996.0 516.0}
    interface-peer {e0 n11}
    interface-peer {e1 n4}
    interface-peer {e2 n6}
    interface-peer {e3 n2}
}

node n6 {
    type lanswitch
    network-config {
    hostname n6
    !
    }
    canvas c1
    iconcoords {492.0 486.0}
    labelcoords {492.0 510.0}
    interface-peer {e0 n12}
    interface-peer {e1 n5}
    interface-peer {e2 n1}
}

node n7 {
    type router
    model router
    network-config {
    hostname n7
    !
    interface eth1
     ip address 10.0.11.1/24
     ipv6 address 2001:11::1/64
    !
    interface eth0
     ip address 10.0.10.1/24
     ipv6 address 2001:10::1/64
    !
    }
    canvas c1
    iconcoords {496.0 169.0}
    labelcoords {496.0 201.0}
    interface-peer {eth0 n13}
    interface-peer {eth1 n1}
}

node n8 {
    type router
    model router
    network-config {
    hostname n8
    !
    interface eth1
     ip address 10.0.9.1/24
     ipv6 address 2001:9::1/64
    !
    interface eth0
     ip address 10.0.8.1/24
     ipv6 address 2001:8::1/64
    !
    }
    canvas c1
    iconcoords {950.0 178.0}
    labelcoords {950.0 210.0}
    interface-peer {eth0 n16}
    interface-peer {eth1 n2}
}

node n9 {
    type router
    model router
    network-config {
    hostname n9
    !
    interface eth1
     ip address 10.0.7.1/24
     ipv6 address 2001:7::1/64
    !
    interface eth0
     ip address 10.0.6.1/24
     ipv6 address 2001:6::1/64
    !
    }
    canvas c1
    iconcoords {1273.0 184.0}
    labelcoords {1273.0 216.0}
    interface-peer {eth0 n17}
    interface-peer {eth1 n3}
}

node n10 {
    type router
    model router
    network-config {
    hostname n10
    !
    interface eth1
     ip address 10.0.5.1/24
     ipv6 address 2001:5::1/64
    !
    interface eth0
     ip address 10.0.4.1/24
     ipv6 address 2001:4::1/64
    !
    }
    canvas c1
    iconcoords {1350.0 682.0}
    labelcoords {1350.0 714.0}
    interface-peer {eth0 n18}
    interface-peer {eth1 n4}
}

node n11 {
    type router
    model router
    network-config {
    hostname n11
    !
    interface eth1
     ip address 10.0.3.1/24
     ipv6 address 2001:3::1/64
    !
    interface eth0
     ip address 10.0.2.1/24
     ipv6 address 2001:2::1/64
    !
    }
    canvas c1
    iconcoords {983.0 661.0}
    labelcoords {983.0 693.0}
    interface-peer {eth0 n15}
    interface-peer {eth1 n5}
}

node n12 {
    type router
    model router
    network-config {
    hostname n12
    !
    interface eth1
     ip address 10.0.1.1/24
     ipv6 address 2001:1::1/64
    !
    interface eth0
     ip address 10.0.0.1/24
     ipv6 address 2001:0::1/64
    !
    }
    canvas c1
    iconcoords {472.0 647.0}
    labelcoords {472.0 679.0}
    interface-peer {eth0 n14}
    interface-peer {eth1 n6}
}

node n13 {
    type router
    model PC
    network-config {
    hostname n13
    !
    interface eth0
     ip address 10.0.10.20/24
     ipv6 address 2001:10::20/64
    !
    }
    canvas c1
    iconcoords {494.0 49.0}
    labelcoords {494.0 81.0}
    interface-peer {eth0 n7}
}

node n14 {
    type router
    model PC
    network-config {
    hostname n14
    !
    interface eth0
     ip address 10.0.0.20/24
     ipv6 address 2001:0::20/64
    !
    }
    canvas c1
    iconcoords {449.0 790.0}
    labelcoords {449.0 822.0}
    interface-peer {eth0 n12}
}

node n15 {
    type router
    model PC
    network-config {
    hostname n15
    !
    interface eth0
     ip address 10.0.2.20/24
     ipv6 address 2001:2::20/64
    !
    }
    canvas c1
    iconcoords {999.0 834.0}
    labelcoords {999.0 866.0}
    interface-peer {eth0 n11}
}

node n16 {
    type router
    model PC
    network-config {
    hostname n16
    !
    interface eth0
     ip address 10.0.8.20/24
     ipv6 address 2001:8::20/64
    !
    }
    canvas c1
    iconcoords {930.0 73.0}
    labelcoords {930.0 105.0}
    interface-peer {eth0 n8}
}

node n17 {
    type router
    model PC
    network-config {
    hostname n17
    !
    interface eth0
     ip address 10.0.6.20/24
     ipv6 address 2001:6::20/64
    !
    }
    canvas c1
    iconcoords {1266.0 69.0}
    labelcoords {1266.0 101.0}
    interface-peer {eth0 n9}
}

node n18 {
    type router
    model PC
    network-config {
    hostname n18
    !
    interface eth0
     ip address 10.0.4.20/24
     ipv6 address 2001:4::20/64
    !
    }
    canvas c1
    iconcoords {1379.0 855.0}
    labelcoords {1379.0 887.0}
    interface-peer {eth0 n10}
}

link l1 {
    nodes {n14 n12}
    bandwidth 0
}

link l2 {
    nodes {n12 n6}
    bandwidth 0
}

link l3 {
    nodes {n15 n11}
    bandwidth 0
}

link l4 {
    nodes {n11 n5}
    bandwidth 0
}

link l5 {
    nodes {n18 n10}
    bandwidth 0
}

link l6 {
    nodes {n10 n4}
    bandwidth 0
}

link l7 {
    nodes {n17 n9}
    bandwidth 0
}

link l8 {
    nodes {n9 n3}
    bandwidth 0
}

link l9 {
    nodes {n16 n8}
    bandwidth 0
}

link l10 {
    nodes {n8 n2}
    bandwidth 0
}

link l11 {
    nodes {n13 n7}
    bandwidth 0
}

link l12 {
    nodes {n7 n1}
    bandwidth 0
}

link l13 {
    nodes {n1 n2}
    bandwidth 0
}

link l14 {
    nodes {n2 n3}
    bandwidth 0
}

link l15 {
    nodes {n3 n4}
    bandwidth 0
}

link l16 {
    nodes {n4 n5}
    bandwidth 0
}

link l17 {
    nodes {n5 n6}
    bandwidth 0
}

link l18 {
    nodes {n6 n1}
    bandwidth 0
}

link l19 {
    nodes {n2 n5}
    bandwidth 0
}

canvas c1 {
    name {Canvas1}
}

option global {
    interface_names no
    ip_addresses yes
    ipv6_addresses no
    node_labels yes
    link_labels no
    show_api yes
    background_images no
    annotations yes
    grid yes
    traffic_start 0
    mac_address_start 32
}

option session {
}

`

**Comment by rodsantiago** [comment]
One thing I noticed about the scenario you included is that it contained loops. (Note: the switches and hubs in CORE do not employ STP). Are you able to run the scenario?
Unfortunately, unlike saving IMN files which is performed in the GUI component, saving XML files is performed in the daemon by walking through the scenario. A loop like what you have in your scenario will prevent it from completing the XML file. I'll keep this issue open as this may be something we want to remedy, but it might take a while.

**Comment by bharnden** [comment]
noted as being fixed in v4.4

**Comment by bharnden** [comment]
Latest release has a newer way for generating xml files, please reopen if this still stands.
