### ISSUE TITLE
[BUG] Running docker nodes with emane

### ISSUE THREAD

**Issue by BitEmu23** [coreemu/core#801]
I tried to make an emane based network on dockers and the emane is properly installed in the containers - tested without core.

Steps to reproduce the behaviour:
1. add 2 docker nodes with docker image that emane is properly installed in and the required apt packages duo to the CORE documentation.
2. add emane network even a 'bypass' model and connect to the docker nodes.
3. run the scenario.

Expected behaviour:
Just connects the nodes using emane and can ping between the nodes.

Screenshot of the error after hitting the run button:
![Screenshot from 2023-07-06 11-00-55](https://github.com/coreemu/core/assets/130286633/5a040cbc-2f70-4edc-b5a4-48d1f86c5b3a)

Desktop:
 - OS: Ubuntu 20.04
 - CORE Version 8.2.0
 - EMANE Version 1.4.1

**Comment by bharnden** [comment]
You would need to retry this case in the current release, if still an issue, you can update it here with your findings. There was some larger changes in 9.x and this may not be an issue currently.

**Comment by BitEmu23** [comment]
Hi, 
I tried the same scenario with the following changes:
OS: Ubuntu 20.04 -> 22.04
CORE Version 8.2.0 -> 9.2.0
EMANE Version 1.4.1

Still not working but lead to different problem:
![remmina_Quick Connect - vm ubu22 04 96_10 10 32 96_2023718-103944 287731](https://github.com/coreemu/core/assets/130286633/e8049d6c-0e37-4601-a4b3-85862bae3ae1)

Seems that the generated emane input files neither copied into the container nor their location is mounted into the container.

**Comment by bharnden** [comment]
this should work on `develop` now

**Comment by BitEmu23** [comment]
Works great, thanks a lot!
