### ISSUE TITLE
[BUG]installation error

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#813]
**Describe the bug**
After I input inv install, it failed at intalling core. My ubuntu is 22,04. It shows:
<img width="370" alt="92b9e2f6ac0ddd50fec881c68762028" src="https://github.com/coreemu/core/assets/101703577/825ef41c-28ef-4fc6-80d6-2dfa38db89dd">
How can I fix it?

**Comment by bharnden** [comment]
You can run `inv install -v` to get better output during install, which should help

**Comment by jxGui** [comment]
It still shows that there is no "poetry" file or directorary. Do I need install it manually? if I need , where should I install?
<img width="372" alt="0614abd463a5c9b2b256da9da850038" src="https://github.com/coreemu/core/assets/101703577/d021ddd3-e150-44c4-960a-a18e874048cd">

**Comment by bharnden** [comment]
This provides a more complete example of how to go about it from a clean install, if it helps.

https://coreemu.github.io/core/install_ubuntu.html

I assume you did not run `./setup.sh`

**Comment by jxGui** [comment]
Yes. I forgot run ./setup.sh and now I have installed it.  I'm so sorry for this question.
