### ISSUE TITLE
[FEATURE]Cluster the nodes in the EMANE network and control the links between them

### ISSUE THREAD

**Issue by LongGieGie** [coreemu/core#814]
**Is your feature request related to a problem? Please describe.**
I need to cluster the nodes in the EMANE network and each cluster  has a head node and other member nodes in each cluster. The head nodes of each cluster need to establish links with each other and the member nodes can only establish links with the head node.

I have achieved this effect using EEL controlled path loss under precomputed propagation model. It is shown in the figure below.
![shot](https://github.com/coreemu/core/assets/57282447/8f13984e-ed35-4b58-ab6a-3ea3a07ce7e5)

I want to realize this under 2ray model because I want to adjust the link state in real time according to the distance between nodes and I don't know how to achieve it.

**Comment by bharnden** [comment]
This would be a better question for the EMANE developers, CORE just helps run EMANE, based on provided configurations.

https://github.com/adjacentlink/emane
