### ISSUE TITLE
Can not save the configuration if configure both upstream and downstream for a link

### ISSUE THREAD

**Issue by ctalluri** [coreemu/core#816]
**Describe the bug**
From Core-gui can not save the configuration if configure both upstream and downstream for a link
using core 9.0.2

**To Reproduce**
1. Right click on a link
2. Click on >> to open Downstream/Upstream configuration
3. Add values to both Downstream/Upstream 
5 click File/save
6. It gives following error

Failed to define session
command(vcmd -c /tmp/pycore.1/ground -- tc qdisc replace dev eth1 root handle 10: netem  rate 10000.0kbit limit 167 delay 100000us 0us 25%), status(1):
stdout: 
stderr: vcmd[1932467]: 17:01:44.586510 vnode_connect[vnode_chnl.c:56]: connect() failed for '/tmp/pycore.1/ground': No such file or directory
vcmd[1932467]: 17:01:44.586629 vnode_client[vnode_client.c:308]: vnode_connect() failed for '/tmp/pycore.1/ground': No such file or directory
vcmd[1932467]: 17:01:44.586645 main[vcmd_main.c:428]: vnode_client() failed: No such file or directory

![Screenshot 2023-09-07 at 4 57 02 PM](https://github.com/coreemu/core/assets/9088827/7877c86b-07ab-449b-be2b-716a3800cbbb)

![Screenshot 2023-09-07 at 5 01 56 PM](https://github.com/coreemu/core/assets/9088827/3ed5b2ea-76d4-4e80-9f5b-1d7d68d8635d)

**Expected behavior**
Should be able to save in an xml file to load later

**Desktop (please complete the following information):**
 - OS: Mac OS using XQuartz on RHEL 8.8 
 - CORE Version 9.0.2

**Comment by bharnden** [comment]
Thanks for the information, I will take a look at this.

**Comment by bharnden** [comment]
fixed on develop branch, thanks
