### ISSUE TITLE
Auto-assigned MAC Address Causing Network Problems

### ISSUE THREAD

**Issue by lchigami** [coreemu/core#82]
Dear CORE authors,

I've been using CORE to teach basic concepts about computer networks for graduation students, and i faced a big problem using 32 distributed topologies between 8 computers using CORE emulator.
The MAC Address formation caused an ARP flood inside my network because I've identified several nodes with the same MAC between the nodes. Is this the expected behaviour? I'm assuming this feature is intended mainly to prevent this kind of scenario.

**Comment by siliconja** [comment]
Try using Tools > Mac Addresses to change the starting MAC address number.

Usually if there is an ARP flood it is due to some type of bridging loop. Note that STP is not turned on by the bridges built by CORE.

**Comment by bharnden** [comment]
Noted as being fixed in 4.3

**Comment by bharnden** [comment]
Please reopen if jeffs instructions above didn't resolve your issue.
