### ISSUE TITLE
Problem while running the network (Beginner)

### ISSUE THREAD

**Issue by Urwah92** [coreemu/core#824]
I am attempting to open a terminal by double clicking on the node, but it does not seem to appear, nor does it show any console option by right clicking the node?
When I start the run it gives me an exception error stating "Exception calling application: No authentication methods available"
Regards,

**Comment by bharnden** [comment]
You need to add more context. What OS are you using? How exactly are you running everything? What node are you trying to run when you double click?

`Edit->Preferences` has terminal options or you can enter a custom one that works as well. But, if you are using Ubuntu/Cent OS desktop releases, you should not be running into this case.

Without all the details, there is not much I can say.

**Comment by Urwah92** [comment]
I am using Ubuntu, I have directly installed it on Ubuntu. I am using a simple wlan tutorial topology. What should I select in the Edit->Preferences ?

**Comment by bharnden** [comment]
Ubuntu Desktop? You are still not answer all the questions above and with specifics.

**Comment by Urwah92** [comment]
Yes Ubuntu desktop, Ubuntu 22.04.1 LTS

**Comment by bharnden** [comment]
Sorry if I missed this before, if you have not corrected this. You can copy/run the command noted within the GUI output or daemon output with debug enabled. Then you could manually verify why things are failing in your case.
