### ISSUE TITLE
Trouble Running Tutorial 3

### ISSUE THREAD

**Issue by KorelU** [coreemu/core#826]
**Describe the bug**
I’ve been looking at Tutorials 3 from the Documentation which address mobility.  Unfortunately, I am having trouble running the examples from Tutorial 3. The Running with XML file using NS2 Movement seems to throw an error when I follow the Documentations examples.

**To Reproduce**
1. Launch Oracle VM Virtual Box with Ubuntu 22.04.3LTS installed
2. Run sudop core-daemon on a new terminal
3. Run core-gui on a new terminal
4. Given a new interface go to file open and find directory "home/vboxuser/Documents/core/package/examples/turorials/tutorial3/scenario.xml"
5. Click Start Session on the upper left corner
6. Click Run on wLan3 Mobility Player
7. New window opens saying GRPC Exception: Mobility Error "exception calling applicaiton: int() argument must be a string, a bytes-like obj ect or a real, number not a 'NoneType"

**Expected behavior**
Observe movement of the nodes

**Screenshots**
![Screenshot 2023-10-10 140402](https://github.com/coreemu/core/assets/140857681/ba993ef0-81a3-48c4-ba17-36ba40eb6630)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - CORE Version 9.0.3
 - EMANE Version 1.4.1

**Additional context**

**Comment by bharnden** [comment]
Thanks for helping point this out, paths for referenced files in the scenario are corrected on the develop branch for a develop install. Ready for the next release.

You could manually adjust the scenario.xml file to point to the right path to correct your issue.
