### ISSUE TITLE
[BUG]The interface information of the router cannot be correctly configured！

### ISSUE THREAD

**Issue by jhonzy0928** [coreemu/core#827]
**Describe the bug**
I haven't seen my mentor for a long time, I have been working on core development, and recently I have made new progress.
As shown in the following figure, I run two router nodes using the ospf routing protocol. When I use the vtysh command line to configure the ospf interface, for example, configure hello-interval. Strangely, when I used the packet capture tool to parse the packets, I found that the configuration information did not take effect. I wonder if there is some problem with the CORE call?
**To Reproduce**
1. Run two router nodes, connect with a wire, and double-click on one node.
2. Run the vtysh command to configure the interface information.
3. Use the packet capture tool to parse packets.

**Expected behavior**
The parsed fields should be consistent with the configuration information.

**Screenshots**
![ospf-interval](https://github.com/coreemu/core/assets/54539693/e0837fcf-810d-45b5-98fd-7ba1007b867a)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.2.1]
 - EMANE Version [e.g. 1.4.1]

**Additional context**

**Comment by bharnden** [comment]
this is not a CORE issue, but a question for the software. You do not need the change, since the hellos are ipv6 and you are configuring ipv4.

`ipv6 ospf6 hello-interval 4`

**Comment by jhonzy0928** [comment]
I am very happy that this problem has been solved through your guidance, thank you very much!
