### ISSUE TITLE
[BUG]Connection between physical node and virtual MDR node

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#828]
**Describe the bug**
The issue is related to the connectivity problem between physical nodes and virtual nodes in the CORE emulator using the virtual Ethernet connection. Specifically, the problem arises when, after the initial simulation launch, the communication between the physical nodes and virtual nodes is established, but upon the first reboot, the communication fails. However, upon the second reboot, the communication between the physical and virtual nodes is restored. The ip of two

**To Reproduce**
The topology is following and the IP addressed of two physical nodes are 10.0.0.130/24 (connecting to 10.0.0.1/24 on node n1) and 10.0.1.130/24(connecting to 10.0.1.130/24 on node10.0.1.1/24 on node n4)
<img width="502" alt="ae2087f2f65e63fd353af3d95052a57" src="https://github.com/coreemu/core/assets/101703577/4a00c169-627f-42ae-8b20-d1a1dc1e0545">
1. start simulation 
<img width="364" alt="2c33f6202e0f2ff7d42dde04f945343" src="https://github.com/coreemu/core/assets/101703577/e46758e2-b569-4a03-83db-078a333dbf4e">

2. restart and fail
<img width="357" alt="d36f91c2177206a17450eb91c8d6a9c" src="https://github.com/coreemu/core/assets/101703577/7d3a1a7f-6c65-4462-a45b-07055aaed1da">

3. restart and success
![image](https://github.com/coreemu/core/assets/101703577/7df77438-88a8-4ce2-88d7-2d18d9a1c785)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2LTS
 - CORE Version 9.0.2
 - EMANE Version 1.4.1

**Comment by bharnden** [comment]
There was an issue joining RJ45 sessions fixed in 9.0.3. Possibly related, so I would update first.

Not sure what you mean by restart?

**Comment by jxGui** [comment]
restart means I stop the emulation by clicking stop button and then start it by clicking start button
