### ISSUE TITLE
[BUG] install CORE9.0.3

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#829]
**Describe the bug**
I cannot run inv install command successfully

**To Reproduce**
I create a new account in Ubuntu and install CORE9.0.3 in this account. However, there has been CORE9.0.2 in another account in the same computer.
1. run command: ./setup.sh and it shows:
<img width="781" alt="43ec03f37ebfc435a2899f19c31a64a" src="https://github.com/coreemu/core/assets/101703577/5976b660-6151-46c6-bf60-cdc597d91370">

2.  run command: inv install and it shows:
<img width="770" alt="6ddc82a312b63c62ab024663af8f1d1" src="https://github.com/coreemu/core/assets/101703577/cbb429bf-06d1-44b5-9f50-145c31337643">

3. run command: inv install -v and it shows:
<img width="794" alt="e68d61e4b3897b3bbb6e7c4fffcc36b" src="https://github.com/coreemu/core/assets/101703577/d162a708-f610-4038-b45a-699e3e77834d">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]

**Comment by bharnden** [comment]
you need to completely uninstall/remove the prior install, since the installs are going to the same location, you are likely going on top of each other.

**Comment by bharnden** [comment]
it also looks like you need to update the install tools as well `poetry` and `invoke` provided by `setup.sh` you may need to uninstall them first.

```shell
pipx uninstall invoke
pipx uninstall poetry
./setup.sh
```
