### ISSUE TITLE
Systemd service fails

### ISSUE THREAD

**Issue by b00ga** [coreemu/core#830]
Systemd service is failing to start (tried on Ubuntu 20.04 from DEB install and AlmaLinux 8 by copying unit file from repo). In debugging, I found the following in the *Command Lines* section of the [systemd.service manpage](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html):

> Note that the first argument (i.e. the program to execute) may not be a variable.

But this is what is being used in the *core-daemon.service* file:
https://github.com/coreemu/core/blob/20071eed2e73a2287aa385698dd604f4933ae7ff/package/core-daemon.service#L8

I see that in *after-install.sh*, the **/opt/core/service** file referenced by the systemd unit is conditionally setting the path, otherwise I would have just submitted a PR to hard-code this to the venv-path.

Since the Github-published DEB file _does_ install the venv (at least by default), it would nice to tweak this in such a way as the install systemd unit is startable after package install.

**Comment by bharnden** [comment]
adjustments on develop to replace the variable with the hard coded absolute path for either case, depending on install
