### ISSUE TITLE
"connect: Network is unreachable" on nodes

### ISSUE THREAD

**Issue by jtremback** [coreemu/core#84]
This just started happening after I had to change some network settings to get my VM (the core 4.7 premade image) to connect to the internet (I added some nameservers to the VM's /etc/resolv.conf, however when I removed them, the problem persists).

When I run a simulation, then open the terminal on one of the nodes and ping another node, I get the error: "connect: Network is unreachable".

Having the node ping one of its own interfaces works, also the VM itself continues to have internet access.

**Comment by siliconja** [comment]
This means the node doesn't have a route to the other node. Check the routing table with `ip ro`. Depending on your emulation topology, you may be using routers in between? The default router setup uses Quagga.

**Comment by jtremback** [comment]
Thanks, my mistake. I was using the router node type. I switched to the MDR node type and it works now.

**Comment by omrfrkmrk** [comment]
I got same problem and i couldn't figure it out. I create MDR router that has 10 computer and connected them with WLAN. When i send ping between computer it says "Network is unreachable". Should i configure something in MDR router? ıf so,how?
