### ISSUE TITLE
[QUESTION] How to import a customzied routing protocol for ad hoc network?

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#845]
**Describe the bug**
I tried to remove ospfmdr service and change routing information by shell command "ip route add/delete x.x.x.x via x.x.x.x". For example, I use "ip route add 10.0.0.2 dev eth0" to add routing information for node1 (ip is 10.0.0.1) and do the same for node2(ip is 10.0.0.2). Then node1 and node2 can communicate with each other. Does this method can be used to import a customzied routing protocol in core? The nodes I use are mdr node and emane(model:ieee108.2.11). 

**To Reproduce**
1. create two mdr nodes(node1 and node2) and an emane node(node3) and remove ospfmdr service before emulation
2. Start emulation and click node1 and node 2 to open their terminal
3.input "ip route add 10.0.0.2 dev eth0" in node1 terminal and input "ip route add 10.0.0.1 dev eth0" in node2 terminal 
4. in node1 terminal, ping 10.0.0.2 and it success.

**Screenshots**
<img width="584" alt="bc9c5b858ca05f5da2feb4130e1b892" src="https://github.com/coreemu/core/assets/101703577/cc4f0971-46df-47b1-8215-9c1c654bd7b7">
<img width="794" alt="b117a1b800975f28b009b5181082db5" src="https://github.com/coreemu/core/assets/101703577/8dbdbb7a-7c24-4303-8bb3-63de0164c646">
<img width="788" alt="0ace050877c5d6d4b4d2deb84fa3921" src="https://github.com/coreemu/core/assets/101703577/da883bb3-ff61-4700-955d-ca9eaccd24f5">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.3]
 - EMANE Version [e.g. 1.5.1]

**Comment by bharnden** [comment]
Whatever software you can run and commands you can use to support your case, you can do. I am not sure your exact question here.
