### ISSUE TITLE
[BUG] exact error message from #829 but in fresh ubuntu 22.04 VM

### ISSUE THREAD

**Issue by PatrickTague** [coreemu/core#847]
**Describe the bug**
the exact error message that is screenshot in issue #829 is occurring in a freshly spun ubuntu 22.04 VM at the step of running `inv install`.  there should be no previous install, since it's a fresh vm image.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04.03 on vmware workstation, windows 11 host w/ intel i5
 - CORE 9.0.3

**Comment by bharnden** [comment]
You can try with `-v` to make it more verbose, without more info its hard to say. You could also potentially be trying whats on the develop branch with a fresh install, to see if that has already corrected the issue.

**Comment by PatrickTague** [comment]
the issue was interesting.  poetry kept installing version 1.1.12 even when 1.2.1 was requested.  had to manually purge the old version before it would upgrade, regardless of `--force-reinstall` or anything else.  i didn't see anything different related to poetry in the develop branch, but didn't try that.
