### ISSUE TITLE
[BUG] Unable to mix Docker/LXC Nodes with EMANE

### ISSUE THREAD

**Issue by jack-ullery** [coreemu/core#850]
**Describe the bug**
I haven't been able to connect Docker nodes with EMANE. I think this is because CORE always generates the EMANE configuration files in `/tmp/pycore` directory, without copying them to the container. I believe this issue also affects LXC.

**To Reproduce**
1. Install CORE (20071eed2e73a2287aa385698dd604f4933ae7ff), EMANE  (adjacentlink/emane@687b8d08ccc196d8cc61ea10572d0f9a5d42cda7), and follow the [Docker Node](https://coreemu.github.io/core/docker.html) instructions
3. Create and build the following Dockerfile
```
FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /root
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y iproute2 ethtool wget

RUN wget https://adjacentlink.com/downloads/emane/emane-1.5.1-release-1.ubuntu-22_04.amd64.tar.gz
RUN tar zxvf emane-1.5.1-release-1.ubuntu-22_04.amd64.tar.gz
WORKDIR emane-1.5.1-release-1/debs/ubuntu-22_04/amd64
RUN dpkg -i *.deb; apt-get install -fy

WORKDIR /
```
3. Create a new scenario in `core-gui` with two Docker nodes (using your image) that are connected by EMANE. 
4. Run the scenario
5. Observe the following error: **Exception calling application: command(nsenter -t 120114 -m -u -i -p -n -- emane -d -l 2 -r -f /tmp/pycore.1/n1.conf/eth0-emane.log /tmp/pycore.1/n1.conf/eth0-platform.xml), status(1):
stdout: 18:58:28.290129 ABORT ParseException: Failed to parse document in /tmp/pycore.1/n1.conf/eth0-platform.xml.**
6. Also note that `/tmp/pycore.1/n1.conf/eth0-platform.xml` exists on the host, but not anywhere in the Docker container

**Expected behavior**
EMANE should work with Docker/LXC Nodes, as it does with the standard node type

Poking around the source code a little, maybe the offending function could be `create_file()` in [emanexml.py](https://github.com/coreemu/core/blob/master/daemon/core/xml/emanexml.py). This function should probably either write the file directly into the container, or copy the file from the pycore directory using `docker copy` or `lxc file push`

**Screenshots**
![image](https://github.com/coreemu/core/assets/46848683/365648b6-be28-4744-9606-99765a900421)

**Comment by bharnden** [comment]
LXC nodes are being removed in the next release. There is a current fix for this issue on the develop branch.
