### ISSUE TITLE
[BUG] Tutorial 3 missing files and not working

### ISSUE THREAD

**Issue by James-Sloop** [coreemu/core#851]
**Describe the bug**
Tutorial 3 crashes and throws an error when I click the play button on the mobility player.

**To Reproduce**
1. Make sure the core-daemon is running a terminal - ```$ sudop core-daemon```
2. In another terminal run the GUI - ```$ core-gui```
3. In the GUI menu bar select File->Open..., and select this tutorials scenario.xml file
4. Hit play to start the session
5. Select the play button on the Mobility Player to start mobility
6. See error: GRPC Exception: Mobility Error: Exception calling application: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Error Output**
```
2024-02-01 15:23:10,915 - ERROR - app:show_grpc_exception - app grpc exception
Traceback (most recent call last):
  File "/home/hume-users/jcsloop/Documents/core/daemon/core/gui/dialogs/mobilityplayer.py", line 136, in click_play
    self.app.core.client.mobility_action(
  File "/home/hume-users/jcsloop/Documents/core/daemon/core/api/grpc/client.py", line 697, in mobility_action
    response = self.stub.MobilityAction(request)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: int() argument must be a string, a bytes-like object or a real number, not \'NoneType\'", grpc_status:2, created_time:"2024-02-01T15:23:10.914705738-05:00"}"
```

**Expected Behavior**
I expect the one of the nodes to start moving.

**Screenshots**
Screenshot of the screen after the error:
![image](https://github.com/coreemu/core/assets/100043766/7ea13c96-000a-40f3-b669-859609fe6fc4)

Screenshot of the Core Documentation specifying files that are not included:
![image](https://github.com/coreemu/core/assets/100043766/f7333ce0-5486-4626-b30a-d26fa028b524)

Screenshot of the output of ```ls``` in ```/tutorial3``` with different files than the documentation specifies:
![image](https://github.com/coreemu/core/assets/100043766/9b873c5b-5a87-4cce-a953-fb43c2a4a842)

Screenshot of the files included in "tutorial3" in the file explorer:
![image](https://github.com/coreemu/core/assets/100043766/dacd9ae2-8b04-4b59-91f7-8cb6a661f993)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.3

**Additional context**
I think the problem could be related to the fact that the files specified in the "Core Documentation" do not match the files included in the tutorial. Specifically, ```printout.py``` is missing and ```move-node2.py``` is included instead.

**Comment by bharnden** [comment]
I believe this is also one corrected on `develop`, the movement file path is likely not correct and has been updated on `develop` for a new location.

You could show me the `core-daemon` side error or check the `scenario.xml` file to see where the location of the `movements1.txt` is being referenced and fix that.

**Comment by James-Sloop** [comment]
Thank you for the help. I was able to fix the problem by changing the reference to ```movements1.txt``` in ```scenario.xml```. However, upon trying to complete the next step, running the ```scenario.py``` script, there is no movement after I hit enter and I don't get an error. I have 3 terminals open, one for the daemon, one running ```scenario.py```, and one running the ```core-gui```. I am able to open the scenario but when I go back to the terminal running ```scenario.py``` and hit enter, or any other key, nothing happens. Do you know what could be causing this? I checked the ```develop``` branch and ```/tutorial3/scenario.py``` is the same as it is on ```master```. I am also curious if I would be better to ask questions relating to the tutorials in your discord or should I continue to use github issues? Thank you.
