### ISSUE TITLE
Get throughputs in EMANE network

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#854]
**Describe the bug**
ThroughputEvent in emanenet only gives me the throughputs marked by mdr node id and iface_id=99. And the throughput is not equal to the  throughput showed on link between two mdr nodes. So how can I use python file to get the throughput between two mdr nodes?

Here is my python script to get throughput:

def handle_throughputs_event(event):
    global throughputs_data, times, average_throughputs_data, start_time
    current_time = time.time()
    if start_time is None:
        start_time = current_time  # 设置基准时间点

    relative_time = current_time - start_time  # 计算相对时间
    
    throughputs_data.clear()  # 清除旧数据
    throughputs_data.extend(event.iface_throughputs + event.bridge_throughputs)
    
    if throughputs_data:  # 确保有数据再进行处理
        average_throughput = 0.001 * sum(throughput.throughput for throughput in throughputs_data) / len(throughputs_data)
        print(throughputs_data)
        print(len(throughputs_data))
        print(f"{average_throughput}")
        average_throughputs_data.append(average_throughput)  # 更新平均吞吐量数据
        times.append(relative_time)  # 使用相对时间

def listen_throughputs(core, session_id):
    """
    在独立线程中监听吞吐量事件。
    """
    def listen():
        core.throughputs(session_id, handle_throughputs_event)
    thread = threading.Thread(target=listen)
    thread.daemon = True
    thread.start() 

**Screenshots**
Here is the content of event.iface_throughputs + event.bridge_throughputs:
 
<img width="1051" alt="4ecdc5cc21921ebf4965f3c6f7e815e" src="https://github.com/coreemu/core/assets/101703577/00483907-d540-403b-b48b-8c8e349dddd9">

The iface_id = 99, and the throughput is not equels to the throughput on link in Gui.
Here is throughput on link in Gui:
<img width="502" alt="5e0e8b66cc53c7ea9dd34e10dfb262c" src="https://github.com/coreemu/core/assets/101703577/b5d26db8-571a-45b2-9390-1e64ec73e135">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.3]
 - EMANE Version [e.g. 1.5.1]

**Additional context**

**Comment by bharnden** [comment]
The throughputs events do no apply for EMANE networks.
