### ISSUE TITLE
[BUG]Custom Node Error

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#855]
**Describe the bug**
First I use core-gui ->Edit -> Custom Nodes to create a custom node named "drone"(The drone node only has IPForward and zerba services.).  Then I try to use grpc api (the code is : drone_node = session.add_node(drone_id, model="drone", position=drone_pos)) to creat a custom node named "drone". However , after I save xml, the <device> parts in xml file don't have <configservices> part shown as figure 1. But if I use core-gui to create drone node (click drone node and put it on the canva) and save xml, the  the <device> parts in xml file have <configservices> part shown as figure 2. 
 
Figure1:
![dba6a5c45db89e5be8c08cb68b72e2a](https://github.com/coreemu/core/assets/101703577/7e452898-e77e-4389-b14d-0f8e0a2b4ccd)

Figure2:
![a79678eeacdfa4e321fd66d427dec5a](https://github.com/coreemu/core/assets/101703577/74c7cf88-77df-4d50-b23d-00a6543916ff)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.3]
 - EMANE Version [e.g. 1.5.1]

**Comment by bharnden** [comment]
The CORE GUI is a separate gRPC client. The GUI does not persist these custom nodes for use by other scripts.
