### ISSUE TITLE
[BUG]FRR Zebra is not running on node

### ISSUE THREAD

**Issue by sei-gseroka** [coreemu/core#857]
**Describe the bug**
A router node with only FRRzebra enabled in config services is not running Zebra after a session is started.  When starting a session no errors are raised.  Opening a terminal and running `vtysh` returns "Exiting: failed to connect to any daemons".

**To Reproduce**
1. Create a new session
2. Add to router nodes and link them
3. On node 2 remove all selected services in Config Services, select FRRzebra, save
4. Start session
5. Open terminal on node 2 and run vtysh

**Expected behavior**
vtysh should connect to a running zebra daemon

**Desktop**
 - OS: Ubuntu 22.04.4
 - CORE Version 9.0.3
 - EMANE Version 1.5.1
 - FRR Version 9.1

**Additional context**
- Manually running `bash frrboot.sh zebra` on the node terminal also returns "Exiting: failed to connect to any daemons".
- Manually running `pidof zebra` on the terminal returns nothing.
- Comparing /tmp/pycore.1/n1.log to n2.log the only thing that looks different on n2 is this message at the end: "node_child_cb[vnode_server.c:161]: pid 35 not found in client command list: completed normally with status 1"

**Comment by bharnden** [comment]
The zebra service has been designed from past use cases of having a dependence on the other services to run one of the protocols. Zebra alone is not sufficient.

**Comment by sei-gseroka** [comment]
Is there any documentation on what FRR services need to be running? The FRR service including the zebra daemon is running on the host OS.

**Comment by bharnden** [comment]
Not in depth specifically for that service. You basically would need the FRRzebra service, along with the other FRR<protocol> service to help try to run one example configuration case for that protocol. You may also need the IPForward service as well, depending on what you are doing.

You can see an example of similar usage, since FRR is a fork of Quagga on the baked in "router"/"mdr" nodes, which use zebra, OSPF, and IP Forward by default to achieve the desired effect.

**Comment by sei-gseroka** [comment]
I changed the logging level for the core daemon to debug and dropped the session down to a single node only running FRRzebra with a template generated config.
I got the attached traceback:
<img width="1139" alt="Screenshot 2024-03-22 at 16 46 37" src="https://github.com/coreemu/core/assets/98774321/4c20d5c8-691d-401b-affc-fe567ea6073c">

The same node with only zebra enabled starts with no errors.

**Comment by bharnden** [comment]
If I am understanding correctly you are just using zebra alone. I was saying that you cannot do that. It needs to be ran with another FRR protocol, in the current setup.

**Comment by sei-gseroka** [comment]
Sorry @bharnden, I was trying to scope the problem down as small as possible.  Attached is the traceback for a single node with FRRBGP, FRRzebra, and IPForward enabled.
![Screenshot 2024-03-25 at 10 33 34](https://github.com/coreemu/core/assets/98774321/b8d230ae-38d2-4577-b27c-92b13746dff4)

**Comment by bharnden** [comment]
Possibly related to the FRR install, you could try to manually run the file in the failed state. The node will be left up and running. This allows you to investigate why its failing, potentially not finding the executables in PATH would be my first guess. Hard to say without knowing the whole setup.

**Comment by sei-gseroka** [comment]
Zebra executable seems fine.  
![Screenshot 2024-03-25 at 11 50 19](https://github.com/coreemu/core/assets/98774321/534bb3ad-de7a-4dde-b5f7-0d4f0f6f0dd1)
If I remove the router bgp 2 line from the config and try again I get the failed to connect to any daemons message.  If I add a second node and link for an interface/IP, zebra gets stuck on the interface lines in the config.
![Screenshot 2024-03-25 at 12 16 59](https://github.com/coreemu/core/assets/98774321/a6a80f1e-8eb0-4e60-a86b-5af231923661)
I also reinstalled frr from the Debian repository just in case.

**Comment by bharnden** [comment]
Possibly FRR configuration has changed from the example we use, which is from some time ago. This would be a case to figure out what FRR is complaining about, to determine how to resolve.

**Comment by bharnden** [comment]
BGP may also be a bad example to try, looking at the example configuration, it has notes expecting you to update it for use, as the default is likely not correct.

That may likely be your issue here.

**Comment by sei-gseroka** [comment]
No change after configuring BGP.  

Do you know if there is a way to get logs out of the CORE node?  For logs I checked:
- os /tmp/pycore.1/n2.log and it is not updating based on commands inside the node
- Systemctl is unavailable inside the node
- var.log/frr is empty inside the node
- journalctl can't find any journal files

**Comment by bharnden** [comment]
I am guessing the logging would be a byproduct of how you run FRR and ya, I would not expect systemd services to work in this case. frrboot.sh runs the commands to start things directly, passing in parameters as needed. But, you could run them yourself differently, if need be.

**Comment by sei-gseroka** [comment]
I added `log file /var/log/frr/frr.log debugging` to the top of my FRRzebra config.  Looking at frr.log after boot the frrboot.sh script appears to be trying to store the zebra pid in /var/run/quagga.
![Screenshot 2024-03-26 at 10 38 13](https://github.com/coreemu/core/assets/98774321/1087fa08-9122-471a-bd0c-366f32344435)

**Comment by bharnden** [comment]
Do you have both FRR and Quagga? Or did you install CORE in such a way that installed OSPF MDR as well? I bet that you have an issue with picking up the alternative version of zebra. As it should be logged to `/var/run/frr` not `/var/run/quagga`.

You cannot have the other installed or at least not resolve first on PATH when trying to run FRR, since they are all a fork of Quagga, you will have issues.

**Comment by sei-gseroka** [comment]
You are right, I did install OSPF MDR.  I don't think I need it, so I guess I will remove it and try again.

**Comment by sei-gseroka** [comment]
The core install script installs OSPF MDR by default and the package install doesn't work for reasons I haven't been able to figure out. 
<img width="1371" alt="Screenshot 2024-03-26 at 23 18 01" src="https://github.com/coreemu/core/assets/98774321/07f93a8a-c350-42c2-91a9-e9d1cce7dd83">

**Comment by sei-gseroka** [comment]
@bharnden I rolled out a clean Ubuntu 22.04.4 host and installed core using the scripted install method but added the --no-ospf flag. After installing FRR on the ubuntu host FRRZebra does not show up as an option in core config services.  For FRR I tried both 8.1 from ubuntu packages and 9.1 from deb.frrouting.org.

**Comment by bharnden** [comment]
It's an aspect of the service looking to validate existence of expected executables to be on PATH. I believe FRR installs into a non typical PATH. In particular this needs to be the PATH of the running `core-daemon`.

You could modify the run directly or update PATH in other ways.

```shell
sudo PATH=$PATH:/path/to/frr/bin core-daemon
```

**Comment by jaredt17** [comment]
@bharnden I also am experiencing FRRZebra not showing up in the available node services, and when I do pass the updated path while running the daemon it does show up... However, I am unable to actually launch the node, the startup just spins forever in the GUI.

**Comment by sei-gseroka** [comment]
@bharnden I am seeing the same issues as @jaredt17.  I'm able to manually run vcmd and pull up a shell on the node and everything looks fine.  Comparing the vcmd output of `bash frrboot.sh zebra` to `bash quaggaboot.sh zebra`, on two different hosts with the correct zebra binary installed, frr is very chatty and quagga is silent.

**Comment by bharnden** [comment]
Does one exit and the other does not? FRR services were contributed some times ago and not used at all by myself, so I don't have any experience with running them.

**Comment by sei-gseroka** [comment]
I have two defunct vcmd processes for I'm assuming the two nodes in my session.  So I think vcmd is exiting successfully, but CORE is for some reason not aware of the successful exit.

**Comment by sei-gseroka** [comment]
@bharnden can this issue be reopened?

**Comment by bharnden** [comment]
Looking into this a bit more, seems that FRR has shifted their execution a lot in recent versions. I am guessing what was contributed was for a much older version of FRR. Likely 7.X.

You would likely need a whole new set of services for FRR, for now the current set may want to be removed. There isn't a current plan to update things at the moment.

**Comment by sei-gseroka** [comment]
FRR version appears to be working

**Comment by jaredt17** [comment]
I am using version 8 and do not see the frr zebra service listed… can you @sei-gseroka?

**Comment by sei-gseroka** [comment]
Yes, after I followed the instructions [here](https://github.com/coreemu/core/issues/857#issuecomment-2023245443).  For me the actual command is `sudo PATH=$PATH:/usr/lib/frr/ core-daemon`

**Comment by jaredt17** [comment]
@sei-gseroka just tested that for myself and when pressing play It just hangs even though the service shows as available. I am running FRR v9.1

**Comment by jaredt17** [comment]
How did you install FRR?

**Comment by sei-gseroka** [comment]
I am running 8.5.4 installed directly from https://deb.frrouting.org on ubuntu 22.04.

**Comment by sei-gseroka** [comment]
FRR version 9 was causing session start to hang for me as well.
