### ISSUE TITLE
[BUG] nodes don't work after I install 4 64G-RAM sticks

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#863]
**Describe the bug**
After I install 4 64G-RAM sticks in my computer to enlarge the scale of simulated network, I find the both mdr node and router node cannot work under emane(802.11abg) or WLAN node. They cannot ping to one another. And there is no ip of mdr or route node in their route tables.  

**To Reproduce**
1. Creat mdr router emane wlan node 
2. Click on 'start'
3. open one node terminal and ping to another node

**Expected behavior**
It can ping successfully

**Screenshots**

![20240408p1](https://github.com/coreemu/core/assets/101703577/180c5bd9-b3a4-425e-8d42-bb4003f0b282)

![20240408-p2](https://github.com/coreemu/core/assets/101703577/3f46a426-6ce0-46bc-97b9-564cb95fad8a)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.3]
 - EMANE Version [e.g. 1.5.1]

**Additional context**

**Comment by bharnden** [comment]
turn off your configuration for controlnet, you have 2 networks with the same name.

**Comment by jxGui** [comment]
which controlnet should I turn off and how can I do it? Thank you very much.

**Comment by jxGui** [comment]
Besides, I compare it with another core in virtual machine and find that there is no vitrual bridge like b.145.1 when I use emane node to support wireless network. And when I use emane node in core of another virtual machine, there are two ctrl0 in route table shows 172.16.0.0 and 224.1.2.8.
![image](https://github.com/coreemu/core/assets/101703577/30099731-23b6-4139-ad9c-83c14be02327)
