### ISSUE TITLE
Daemon not starting

### ISSUE THREAD

**Issue by grahamj1978** [coreemu/core#867]
I'm new to CORE and am currently just trying to get it installed and running so I can make my way through the tutorials.  I've currently gotten it properly install (or so I believe) on an Ubuntu 22.04 VM. 

I followed the Script Install instructions for Ubuntu as provided on the coreemu.github.io site.
However, when I run the aliased 'sudop core-daemon' command, I get the following:

> 2024-05-10 10:51:05,165 - INFO - daemon:banner - CORE daemon v.9.0.3 started Fri May 10 10:51:05 2024
> usage: core-daemon [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: core-daemon --help [cmd1 cmd2 ...]
>    or: core-daemon --help-commands
>    or: core-daemon cmd --help

Additionally, if I try to start it as a service, it failed.  The associated status information is as follows:

> × core-daemon.service - Common Open Research Emulator Service
>      Loaded: loaded (/lib/systemd/system/core-daemon.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Fri 2024-05-10 10:46:56 EDT; 12min ago
>     Process: 87838 ExecStart=/usr/local/bin/core-daemon (code=exited, status=203/EXEC)
>    Main PID: 87838 (code=exited, status=203/EXEC)
>         CPU: 1ms
> 
> May 10 10:46:56 jgraham-virtual-machine systemd[87838]: core-daemon.service: Failed at step EXEC spawning /usr/local/bin/co>
> May 10 10:46:56 jgraham-virtual-machine systemd[1]: Started Common Open Research Emulator Service.
> May 10 10:46:56 jgraham-virtual-machine systemd[1]: core-daemon.service: Main process exited, code=exited, status=203/EXEC
> May 10 10:46:56 jgraham-virtual-machine systemd[1]: core-daemon.service: Failed with result 'exit-code'.

Finally core-gui also fails, presumably because the daemon is not actually starting, with a 'failed to connect to all addresses" error.

Any help that could be provided would be appreciated, because I am not sure what the problem could be, since as far as I can tell everything is installed and configured correctly.

**Comment by bharnden** [comment]
I am guessing these are connected for the same reason, whatever it is. I am not clear on exactly what your error is, in the first case.
You could try running the daemon directly.

```python
sudo /opt/core/venv/bin/core-daemon
```

I assume this is a clean environment with no existing versions etc?

**Comment by grahamj1978** [comment]
Correct.  This was done in a fresh VM.

And running the daemon directly as you suggested give the same message.

To me it looks like it's acting as if it suspects additional command line parameters, but what I've read in the documentation seems to imply that it should be unnecessary.  Unless there's something wrong with the default core.conf file? (I've left it unmodified outside of uncommenting and modifying the custom_config_serviecs_dir line as prompted in the Setup Tutorial with respect to 'chatapp'.

**Comment by bharnden** [comment]
I would inspect the file being ran and the script and see what it is, because yes, it does not require any options. So something is very off or different in your environment.

**Comment by grahamj1978** [comment]
Well, here is a listing of my core.conf file: 

> [core-daemon]

> #distributed_address = 127.0.0.1
> grpcaddress = localhost
> grpcport = 50051
> quagga_bin_search = "/usr/local/bin /usr/bin /usr/lib/quagga"
> quagga_sbin_search = "/usr/local/sbin /usr/sbin /usr/lib/quagga"
> frr_bin_search = "/usr/local/bin /usr/bin /usr/lib/frr"
> frr_sbin_search = "/usr/local/sbin /usr/sbin /usr/lib/frr /usr/libexec/frr"
> 
> # uncomment the following line to load custom services from the specified dir
> # this may be a comma-separated list, and directory names should be unique
> # and not named 'services'
> #custom_services_dir = /home/<user>/.coregui/custom_services
> custom_config_services_dir = /home/jgraham/.coregui/custom_services
> 
> # uncomment to  establish a standalone control backchannel for accessing nodes
> # (overriden by the session option of the same name)
> #controlnet = 172.16.0.0/24
> 
> # uncomment and edit to establish a distributed control backchannel
> #controlnet = core1:172.16.1.0/24 core2:172.16.2.0/24 core3:172.16.3.0/24 core4:172.16.4.0/24 core5:172.16.5.0/24
> 
> # uncomment and edit to establish distributed auxiliary control channels.
> #controlnet1 = core1:172.17.1.0/24 core2:172.17.2.0/24 core3:172.17.3.0/24 core4:172.17.4.0/24 core5:172.17.5.0/24
> #controlnet2 = core1:172.18.1.0/24 core2:172.18.2.0/24 core3:172.18.3.0/24 core4:172.18.4.0/24 core5:172.18.5.0/24
> #controlnet3 = core1:172.19.1.0/24 core2:172.19.2.0/24 core3:172.19.3.0/24 core4:172.19.4.0/24 core5:172.19.5.0/24
> 
> # uncomment and edit to assign host interfaces to auxilary control channels
> # for use in connecting with other servers in a distributed environments.
> # Note: This is valid for auxiliary control channels only. The primary control
> # channel, specified by 'controlnet', is tunneled across servers.
> #controlnetif1 = eth2
> #controlnetif2 = eth3
> #controlnetif3 = eth4
> 
> # optional controlnet configuration script for controlnet, uncomment to
> # activate, and likely edit the script.
> # Note: the controlnet_updown_script is not used by the auxiliary control
> # channels.
> # controlnet_updown_script = /usr/local/share/core/examples/controlnet_updown
> # publish nodes' control IP addresses to /etc/hosts
> #update_etc_hosts = True
> 
> # EMANE configuration
> emane_platform_port = 8101
> emane_transform_port = 8201
> emane_event_generate = True
> emane_event_monitor = False
> #emane_models_dir = /home/<user>/.coregui/custom_emane
> # EMANE log level range [0,4] default: 2
> #emane_log_level = 2
> emane_realtime = True
> # prefix used for emane installation
> # emane_prefix = /usr

As you can tell, most lines are commented out, and as mentioned earlier I have only modified the one line.  

And I'm not sure where else in my setup I might be able to check to validate things.

**Comment by bharnden** [comment]
The `core.conf` file should have nothing to do with the `core-daemon` being inherently different for some reason.

**Comment by grahamj1978** [comment]
I see.  I guess then the question is what "commands" is the daemon looking for with respect to the "no commands supplied" error?
I'll keep poking at it, but my lack of knowledge of the underlying software and its installation process probably means I won't have much success.  I'll probably have to try another clean install, maybe using the pkg based install method as an alternative. I'll also try to log the install output to see if there's some kind of warning or error that I missed during the installation. Although, I would think that if there were an error that it would be obvious.





















    On Friday, May 10, 2024 at 01:46:30 PM EDT, bharnden ***@***.***> wrote:  
 
 


The core.conf file should have nothing to do with the core-daemon being inherently different for some reason.

**Comment by grahamj1978** [comment]
Well, I'm not sure what exactly I did to fix the issue, but today, I redid the installation of core from scratch using the script install method, and the core-daemon is now working correctly. There are two possibilities that I can think of: 1) I had been using a 'Developer' folder rather than 'Documents for my install attempts, and 2) There may have been an issue somewhere else in the install process that I just missed, but I am not sure what it may have been.

**Comment by bharnden** [comment]
Ya, whatever happened, that `core-daemon` you had, was not the one we provide. But, glad to hear.
