### ISSUE TITLE
[BUG] cannot communicating over 10km using emane

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#869]
Emane model :IEEE80211abg
model: freesapce
systemnosie: 0.0
txpower: 50.0
fixedAntennagain: 10.0
I found that when pathlloss is 120, the communication is failed. No matter how I change txpower ，fixedAntennagain， systemnoise, the pathloss in receivepowertable is 120 when the distanse is 10km in core and emane. So how can I change code of emane to break the limitation of communication distanse. I will apprecate it that you can help me. If you need more information please tell me

**Comment by bharnden** [comment]
Sounds like something EMANE specific in this case, you would need to ask their developers.
