### ISSUE TITLE
Multiple Validation Commands Produce 'list index out of range' error

### ISSUE THREAD

**Issue by stash-global** [coreemu/core#888]
**Describe the bug**
When running a custom service that has 3 (or more) validation commands in the list, it results in a "Start Exception" with an error message 'list index out of range'. When looking at the run_validation() function in services/base.py, the cmds are iterated over with a while loop, but in the loop, the cmds list is modified with 'del cmds[index]', so when the index is incremented, it effectively skips the second command, and then results in an index out of bounds when index = 2.

Changing the 'while cmds:' loop to a 'for cmd in cmds:' loop, removing the 'del cmds[index]'  command, and replacing the cmds in the validation_timer check with a flag, seemed to work around the issue - while possibly not affecting the validation_timer check.
e.g.
```
        failedCommands = False;
        # while cmds:
        for cmd in cmds:
            logger.warning("cmds: %s", json.dumps(cmds))
            logger.warning("index: %s", index)
            # cmd = cmds[index]
            logger.warning("cmd: %s", cmd)
            try:
                self.node.cmd(cmd, shell=True)
                # del cmds[0]
                index += 1
            except CoreCommandError:
                failedCommands = True
                logger.debug(
                    f"node({self.node.name}) service({self.name}) "
                    f"validate command failed: {cmd}"
                )
                time.sleep(self.validation_period)

            if failedCommands and time.monotonic() - start > self.validation_timer:
                raise ServiceBootError(
                    f"node({self.node.name}) service({self.name}) failed to validate"
                )
```

Here are the initial validation commands, and the values of cmds, cmd, and index at each iteration through the loop when the index error occurred, as produced by the logger.warning() calls in the code above:
```
Initial Validation commands: ["ps aux | grep \"nc -lk 135\"", "ps aux | grep \"nc -lk 139\"", "ps aux | grep \"nc -lk 445\""]

run_validation() variables:
cmds: ["ps aux | grep \"nc -lk 135\"", "ps aux | grep \"nc -lk 139\"", "ps aux | grep \"nc -lk 445\""]
index: 0
cmd: ps aux | grep "nc -lk 135"
cmds: ["ps aux | grep \"nc -lk 139\"", "ps aux | grep \"nc -lk 445\""]
index: 1
cmd: ps aux | grep "nc -lk 445"
cmds: ["ps aux | grep \"nc -lk 139\""]
index: 2
**** index out of bounds ***
```

**To Reproduce**
1. Create an example service with 3 validation commands (see attached)
2. Configure the example service to run on a node
3. start the session

[ExampleService.py.txt](https://github.com/user-attachments/files/16532802/ExampleService.py.txt)

**Expected behavior**
The validation commands run as configured and do not produce an error message

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.1.0
 - EMANE Version 1.5.1

**Additional context**
The shutdown property, with 3 commands in the list, works fine as-is.

**Comment by bharnden** [comment]
Good catch on the issue. I just need to remove the indexing. The intent is to keep retrying a command for success within the validation time frame. It should just keep using index 0 while cmds exist to try from the copied list that is being depleted on success.

Thanks!

**Comment by cbevans** [comment]
Issue was added with the wrong user context - apologies. Not sure if there's a way to delete it so I can re-create it under the right user context so I get updates on it - but whatever is easiest.

**Comment by bharnden** [comment]
if there's more to explain, feel free to put it here. But what I said above would correct the aspect notes as desired.

**Comment by bharnden** [comment]
this specific issue is fixed on develop for next release
