### ISSUE TITLE
[Documentation] DocBlock Typo in grpc/client.py::open_xml()

### ISSUE THREAD

**Issue by cbevans** [coreemu/core#889]
**Describe the bug**
The doc block description for the open_xml(), start parameter is incorrect - it give the return value description, not what the start parameter is.

File: daemon/core/api/grpc/clien.py
Function: open_xml()

![Screenshot 2024-08-07 165026](https://github.com/user-attachments/assets/0a671b22-6d89-4f88-880c-e240ea32930d)

**Comment by bharnden** [comment]
thanks will clean up for the future

**Comment by bharnden** [comment]
fixed on develop for next release
