### ISSUE TITLE
Throughput widget non-functional on RJ-45<->Switch/Hub links

### ISSUE THREAD

**Issue by rodsantiago** [coreemu/core#89]
RJ-45<->switch/hub links throughput widget remain fixed at 0 bps.

**Comment by Wdraaijer** [comment]
I'm having this issue with links between two switches
![VirtualBox_Test-vm_core_30_04_2021_16_52_16](https://user-images.githubusercontent.com/45690844/116712776-7e2d7000-a9d4-11eb-92e4-dc8a75b274d0.png)

**Comment by siliconja** [comment]
I think we only supported layer 3 nodes with the Throughput Widget, so routers, servers, PCs, etc. but not hubs/switches.

In the Tcl/Tk code, `getstats_link_ifname()` looks for "NETWORK" nodes on either side of a link. If the node is a "LINK" type (the hub/switch node) it is skipped.  This function would need to be fixed to get the proper interface name mapping. The widget periodically reads `/proc/net/dev` for stats.

GUI development is now focused on the Python/Tk GUI. So I wouldn't expect a fix to the old GUI, unless you are willing to update the code and submit a PR.

**Comment by Wdraaijer** [comment]
I just checked the Python GUI and it has the same issue. The Python GUI doesn't even display a throughput label
![VirtualBox_Test-vm_core_04_05_2021_11_25_30](https://user-images.githubusercontent.com/45690844/116984419-83880480-accb-11eb-971f-24444ab23ae7.png)
