### ISSUE TITLE
No route to host After adding a link to emane

### ISSUE THREAD

**Issue by jxGui** [coreemu/core#891]
**Describe the bug**
Hello,

I'm encountering a peculiar issue while running a session in our simulation environment. Here's a brief rundown of the situation:

During runtime, I've successfully created an interface on Node 1.
I then utilized the core.add_link() method to establish a connection between this interface and the EMANE module.
However, I've noticed that Node 1 is unable to ping Node 2, which is also linked to the same EMANE module.
Interestingly, the situation changes when I interact with Node 2 through the core-gui interface:

Upon clicking on Node 2, Node 1 suddenly gains the ability to ping Node 2.
The daemon logs display the following messages:
<img width="494" alt="1be03454e55c88a23f5bea70b7b206a" src="https://github.com/user-attachments/assets/36256193-3a0a-4b53-92ba-882a0f854dfe">
And my python code is :
<img width="425" alt="edc6239ade45f0e6a830115778e174c" src="https://github.com/user-attachments/assets/cab01273-4f3a-43b6-a971-46d65eaf7bdf">

I'm curious if anyone has come across a similar issue or has any insights into what might be causing this behavior. Any guidance or suggestions would be greatly appreciated.

Thank you in advance for your help.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.3]
 - EMANE Version [e.g. 1.5.1]

**Additional context**

**Comment by bharnden** [comment]
Some aspects of CORE were not originally written to handle runtime changes well. Or at least result in impacting things in a way you might not realize.

Nodes running EMANE often depend upon running a routing protocol. If you add an EMANE connection at runtime, the `service` that ran to facilitate routing already ran and does not know about this new interface. So you would have to full restart the service and routing software with the new configuration or manually update that yourself in some other way.
