### ISSUE TITLE
[BUG]gRPC API client.InterfaceHelper.create_iface small subnet issue

### ISSUE THREAD

**Issue by sei-gseroka** [coreemu/core#896]
**Describe the bug**
A small subnet with a large node_id will throw an IndexError.

**To Reproduce**
```
from core.api.grpc import client
from core.api.grpc.wrappers import LinkOptions, Position

iface_helper = client.InterfaceHelper(ip4_prefix="10.0.0.0/30")

core = client.CoreGrpcClient()
core.connect()

session = core.create_session()

position = Position(x=100, y=100)
node1 = session.add_node(3, position=position)
position = Position(x=300, y=100)
node2 = session.add_node(4, position=position)

iface1 = iface_helper.create_iface(node1.id, 0)
iface2 = iface_helper.create_iface(node2.id, 0)
link = session.add_link(node1=node1, node2=node2, iface1=iface1, iface2=iface2)
```

**Expected behavior**
Interfaces should be assigned an IP in a subnet when one is available.

**Screenshots**
<img width="883" alt="Screenshot 2024-11-11 at 13 26 04" src="https://github.com/user-attachments/assets/7033c638-aac3-4891-b972-d0e5cc76a9ba">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.1

**Comment by bharnden** [comment]
The interface helper is just that and used as a convenience in some cases, it is not a requirement to use. You can freely define the interface information however you like. The helper will try to utilize the subnet and IDs of the nodes to automatically define an address.

If you have other needs, avoid using the helper and you can define it all, however you like.

**Comment by sei-gseroka** [comment]
If this is a won't fix then maybe the python documentation could specify ip address assignment is based on node ids.

**Comment by bharnden** [comment]
Can definitely look to help make the documentation clear for it's current expected usage.
