### ISSUE TITLE
[BUG]Core-GUI stop running session popup bug

### ISSUE THREAD

**Issue by sei-gseroka** [coreemu/core#897]
**Describe the bug**
Closing a core-gui window with a running session results in a "Stop the running session" popup.  Clicking on cancel still closes the window.

**To Reproduce**
1. Open core-gui
2. Start a session
3. Close the window
4. Click Cancel on the popup
5. The core-gui window still closes

**Expected behavior**
Clicking cancel should result in no change except the stop the running session popup being dismissed.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CORE Version [e.g. 5.2.1]
 - EMANE Version [e.g. 1.2.4]

**Comment by bharnden** [comment]
Will look into correcting this, thanks.

**Comment by bharnden** [comment]
fixed on develop, thank you for pointing this out
