### ISSUE TITLE
[BUG]wlan default subnet doesn't work

### ISSUE THREAD

**Issue by sei-gseroka** [coreemu/core#898]
**Describe the bug**
When creating a wlan node in core-gui the subnet is set to 10.0.0.0/32. Connecting two nodes to the same wlan without changing the defaults results in nodes being connected on the GUI but unable to reach other as they are on different subnets.  Changing the mask to /24 on the wlan node causes all connections to fail.

**Desktop (please complete the following information):**
OS: Ubuntu 22.04
CORE Version 9.1

**Comment by bharnden** [comment]
`/32` is intentional by default, as it is assumed you would connect a node running routing software. Adjusting the prefix to something else would be one way to adjust around that.

Not sure what you meant by all connections to fail. I do not observe that myself.

**Comment by sei-gseroka** [comment]
What do you mean connect a node running routing software? It was my understanding that wlan nodes don't do any routing on their own just traffic shaping. In tutorial 2 all the mdr nodes are in a /24 together.

1.  create a wlan node
2. open the wlan configuration and change the ipv4 mask to /24 and apply
3. create a container node router
4. use the link tool between the wlan and container node
5. no link is actually created

**Comment by bharnden** [comment]
MDR nodes run routing software by default. They do not, need to be `/24`. WLAN nodes also determine connectivity as an on/off by pixel distance. So potentially your nodes are too far and out of range, so no connection.

**Comment by bharnden** [comment]
The nodes being `/24` in the example is bad and not what it should be, thanks for pointing it out, the example will need to be adjusted.

**Comment by sei-gseroka** [comment]
two routers on independent /32s are unable to ping each other.

**Comment by sei-gseroka** [comment]
just plain routers, my instance of CORE doesn't have MDR installed.

**Comment by bharnden** [comment]
That would likely be related the example is specifically using MDR nodes for a reason. Plain router nodes also would want to run outing software by default as well, so you would still need something installed. So there is definitely things not aligned in your environment, compared to what is expected.

I will likely update the documentation to make it very clear of what is expected to be installed, in the context of these examples.

**Comment by bharnden** [comment]
Updated examples on develop to create the interfaces more explicitly with addressing with prefixes the same as the GUI defaults to. These are always just examples of things that can work, but never a definitive answer, depending on setup etc.
