### ISSUE TITLE
Pep8 and documentation

### ISSUE THREAD

**Issue by Shatnerz** [coreemu/core#94]
If I run all the python code through pep8 to get the code to a common standard, will the pull request be accepted?

Similarly, I was thinking about adding some documentation for pycore which is currently lacking. If I do this (or at least start) using sphinx-napolean and Google style doc strings, will the pull request be accepted.

I would find both immensely useful, but I'd rather not waste my time if it goes against some current convention that I am not aware of.

**Comment by Shatnerz** [comment]
It would be nice if we could remove all these import all statements (`from x import *`). There are so many strung together it is impossible to determine where some things are originating. I'm trying to to remove all unused imports, but then some of those imports are used in these import all statements (I'm assuming). One example is in `daemon/core/phys/pnodes.py`.

    except CalledProcessError as e:  # Where the hell is this coming from?
        self.warn("cmd exited with status %s: %s" % (e, str(args)))

I feel that its much better to explicitly state these imports. Once the code is cleaned up, it makes it much easier for users to contribute.

**Comment by siliconja** [comment]
Thanks for being willing to contribute. I would be up for such an exercise.

@tomgoff what do you think?

**Comment by Shatnerz** [comment]
I made a pull request last night that reduces the violations significantly. I should probably make sure everything builds and runs correctly though (I didn't change any logic, but I did change quite a few import statements).

Some things I've noticed digging through the code

    * Styles are inconsistent. For example
        * There is something like `mutecall` and then `check_call`. Be consistent with the underscores
        * Doc strings are all over the place. Most use " ''' " but some might use " """ ". Sometimes the ending triple quotes are on a separate line, sometimes not. Indentation sometimes matches up with the first quote and sometimes matches up the first character of the string.

    * There are a lot of Notes and TODOs throughout the code. It would be nice from someone to pull these out into a manageable list. That way contributors can go through and check things off.

Sorry of this sounds like a lot. I just feel that we can manage to get everything up to a easier to manage standard, maintenance and contributing would be easier.

Where is the best place to discuss these things? Would it be worth setting up a slack group (with dev and user channels) or irc? There is the mailing list, but that is mostly users and typically only Jeff responds.

**Comment by justas-** [comment]
+1 for improving the documentation of the source code. Trying to find something and tracing what imports what takes so much time.

**Comment by Shatnerz** [comment]
@justas- I did make a pull request where I make all the imports explicit.

**Comment by Shatnerz** [comment]
Nice, I haven't checked the commit log yet, but the code looks like its in a substantially better place now.
