### ISSUE TITLE
coresendmsg crashes core-daemon if interacting with a node not in the active canvas

### ISSUE THREAD

**Issue by dwiden** [coreemu/core#99]
If you are running a session with two or more canvases, and you try to issue a command to a node in the non-active canvas, core-daemon will crash.

To test, make a new simulation, put a single host onto canvas 1, make a new canvas (canvas 2). Start the simulation, and on the CLI, run the following command:

`coresendmsg node=17 xpos=100 ypos=100`

This command will work. Now, click on canvas 2. Run the following command:

`coresendmsg node=17 xpos=200 ypos=200`

This will cause a popup error from Core-GUI, and will cause the core-daemon to crash

**Comment by bharnden** [comment]
the issue would be tied to not providing the canvas option, assuming this is how the script worked then:
coresendmsg node=17 xpos=100 ypos=100 canvas=0
